### ISSUE TITLE
[UX] Ambiguous paper wallet UI

### ISSUE THREAD

**Issue by jonathancross** [input-output-hk/daedalus#1025]
The current UI and description for creating a "paper wallet certificate" is unclear.  Users may (rightfully) believe that the paper wallet is a representation of the _currently selected hot wallet_, rather than a completely independent seed.

**Suggestion:** Improve the description and link to more explicit documentation on the paper wallets certificates explaining how they work and why they are different than the 12 word seed phrase.

@DominikGuzei - Thoughts?

**Comment by DominikGuzei** [comment]
Thanks for the feedback @jonathancross, i will forward this question to @darko-mijic @nikolaglumac

**Comment by nikolaglumac** [comment]
You got the point there @jonathancross. We should improve the instructions shown on the 1st of the Paper wallet generator dialogs to make things more clear as for some users this may not be obvious.
cc @darko-mijic

**Comment by nikolaglumac** [comment]
This issue has been addressed in https://github.com/input-output-hk/daedalus/pull/1309 and is to be released in the upcoming Daedalus `0.13.0` version.

**Comment by gorgos** [comment]
I'm still thinking that this is not sufficient. In fact, I actually only realized that this is not for the hot wallet creating a second paper wallet.

Maybe a solution would be to either

a) allow as second option to create a paper wallet for the current hot wallet (my preference)

or

b) at least have a confirmation screen with only that warning and nothing else
