### ISSUE TITLE
Where and how can I run and use Cardano CLI options?

### ISSUE THREAD

**Issue by Coding-Jewelry** [input-output-hk/daedalus#1028]
Dear.

Now I am trying to install Cardano wallet.
I have successfully ran ./connect-to-mainnet.
What I am not sure is where and how can I run Cardano CLI options like cardano-node?

Please give me a hint if you have any idea.
Thank you.

**Comment by nikolaglumac** [comment]
Please post this question to https://github.com/input-output-hk/cardano-sl
