### ISSUE TITLE
Latest ui issues and feature requests

### ISSUE THREAD

**Issue by greggdourgarian** [input-output-hk/daedalus#1048]
1.  Transactions list needs to show date and time of transaction.  Currently only shows time.  
2. Addresses are STILL hard to read/use/identify as they all begin w the same long string of characters.  
3. Password should not have to be reentered every single time you do a send.   Currently it is quite a pain to send multiple transactions as each time you copy in the send address and amount you then have to enter the password.  

Perhaps I am wrong or don't appreciate the development environment you are in, but these seem like simple changes that could be done in an hour or less.   Is there no room in the project planning to do simple fixes?

**Comment by nikolaglumac** [comment]
Thanks for the feedback @greggdourgarian!

> 1. Transactions list needs to show date and time of transaction. Currently only shows time.
Transaction list shows transactions grouped by date which means you can find the exact date of the transaction above the each block of transactions.

> 2. Addresses are STILL hard to read/use/identify as they all begin w the same long string of characters.
Addresses format is not easy to change. The addresses are long and I'm afraid you will have to focus on their last part to distinguish them. There are plans to make the addresses shorter in the future.

> 3. Password should not have to be reentered every single time you do a send. Currently it is quite a pain to send multiple transactions as each time you copy in the send address and amount you then have to enter the password.
This is a security feature. We can not and should not store spending password in any way. Therefore the user is required to enter it each time he/she want's to create a new transaction.
