### ISSUE TITLE
Strange result for Account Index in the api

### ISSUE THREAD

**Issue by bazooka70** [input-output-hk/daedalus#1074]
After creating a new wallet via API, or creating it via the daedalus UI, I have noticed that when calling:

`/api/v1/wallets/{walletId}/accounts`

I get strange `index` in the response  - a very large number such as 16723090.
I don't have access to the machine right now so I can't tell the exact `Index` I see in all wallets.
I was expecting it to be 1 for each wallet I created.

Our server is Windows based, and we have the latest cardano/daedalus version.

Did I miss anything or is this a bug?
BTW, Can someone reproduce this please?

**Comment by bazooka70** [comment]
It would be nice to mentioning this fact in the docs. Thanks

**Comment by nikolaglumac** [comment]
@bazooka70 that is what HD wallets are all about: https://cardanodocs.com/technical/hd-wallets/

**Comment by bazooka70** [comment]
@nikolaglumac I'm far from being an expert, but using **random** account indexes makes no sense to me.
From what I know account indexes are usually sequential and start from 0. e.g. '44/`0/`0 (for Bitcoin), then '44/'0'/'1 etc...

If you restore your wallet later and your account index is *random*, how will you know your derived keys/addresses later? 

My guess (after a bit of thinking) is that the number I see in the api resperest a 0 base index of `i & ~0x80000000u` for a hardened path. I can verify this on sunday since I don't have access to the cardano server now.
But, maybe i'm way off.  dunno :)

**Comment by nikolaglumac** [comment]
@bazooka70 this is more of a question for https://github.com/input-output-hk/cardano-sl repo
I believe you will get more answers about how Cardano works there :)

**Comment by bazooka70** [comment]
@nikolaglumac I'm not sure which part of your api responsible for returning the api responses? is that the  daedalus or cardano-sl or what? maybe this question should be re-opened if you are not sure about the randomness part.

**Comment by nikolaglumac** [comment]
@bazooka70 I am sure about the randomness part but if you want to get more details you should open the ticket on the Cardano-SL repo.
