### ISSUE TITLE
Which algorithm is used by Daedalus to hash the spendingPassword?

### ISSUE THREAD

**Issue by bazooka70** [input-output-hk/daedalus#1077]
I have created a wallet using the **API** and used SHA256 on the password, which I encoded to hex. 
When I try to spend funds from this wallet which was created via API, all is good.

However if I create the wallet in Daedalus UI, and later try to send the password I used to create the wallet (after hashing with SHA256), vi the API, I get an error that the password does not match.

`{"status":"error","diagnostic":{"msg":"Request error (Passphrase doesn't match)"},"message":"UnknownError"}`

How to resolve this issue? How can I match the hash algorithm in my app with the one in Daedalus ?

P.S: I'm using the latest Cradano/Daedalus package.

**Comment by MarcusHurney** [comment]
`
// @flow
import blakejs from 'blakejs';

const bytesToB16 = (bytes) => Buffer.from(bytes).toString('hex');
const blake2b = (data) => blakejs.blake2b(data, null, 32);

export const encryptPassphrase = (passphrase: string) => (
  bytesToB16(blake2b(passphrase))
);
`

**Comment by bazooka70** [comment]
@MarcusHurney , Thanks a million!

**Comment by MarcusHurney** [comment]
@bazooka70
No problem, happy to have you using the ecosystem!
