### ISSUE TITLE
Daedalus dist (macOS)

### ISSUE THREAD

**Issue by hellc** [input-output-hk/daedalus#1085]
Any way to hide/encode dist folder?

Right now I could easily edit index.js file. That could be potential vulnerability.

Ex: I could easily emulate an update:
<img width="978" alt="screenshot 2018-09-06 at 09 56 34" src="https://user-images.githubusercontent.com/750178/45140361-3a4e2280-b1bb-11e8-9a91-3966fc4fd45c.png">

then...

**Comment by SebastienGllmt** [comment]
To do this you would need to be able to write arbitrary files to somebody's computer (to overrride the existing files)
If you can already do this, then your computer is already doomed beyond any hope

If you were already able to write arbitrary bytes to a user's machine, why not just replace the EXE in the first place

**Comment by hellc** [comment]
@SebastienGllmt yeah, you are right.

So if there are no other reasons to hide the code, seem like its useless to do encoding...
