### ISSUE TITLE
How to get notifications/events about new wallet transactions?

### ISSUE THREAD

**Issue by bazooka70** [input-output-hk/daedalus#1087]
Is there a way to get notifications/events about wallet transactions via websockets?
The new API does not seem to mention anything about this.
P.S: I’m using the  version 0.11.0

Thanks in advanced.

**Comment by nikolaglumac** [comment]
There is currently no `websockets` support.
The only way to detect a new transaction is to create a `poller` which checks if there is a new transaction by fetching results from the transactions endpoint: https://cardanodocs.com/technical/wallet/api/v1/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions%2Fget
