### ISSUE TITLE
Disable Check for improperly start of Daedalus 0.11.1

### ISSUE THREAD

**Issue by TheDevKnight** [input-output-hk/daedalus#1134]
Hi,

is it possible to disable (startargument for exe?) the check for the improperly start of Daedalus 0.11.1 on windows?
Background: I run my node on a different machine in a docker container + portmapping and only started the Daedalus.exe with 0.11.0 on the clients.

This is with 0.11.1 not possible, because of that new check. 
Must i wait until the new IPC Feature is available and use the old version 0.11.0 to run my setup?

Regards

**Comment by cleverca22** [comment]
what is the host os?
what is the base image for the docker image?
what are your main uses for running cardano in docker like this?

**Comment by TheDevKnight** [comment]
hi, 

the host of the docker is synology DSM (i believe it is based on debian). 
base Image is ubuntu:18.04
my main use is that my wallet is always up to date = 100% sync with the blockchain. I also plan to solo stake by myself. 

BUT the problem is not the node in the container. I run this since 1.1.0. My problem is the new feature of deadalus that will check that the node is running local on the same machine like deadalus.  

Is it possible to disable the check?

Regards

**Comment by nikolaglumac** [comment]
Since the 0.12.0 release Daedalus manages the Cardano node process itself.
In order to switch back to the old setup you will have to build Daedalus from source and use the `frontendOnlyMode`: https://github.com/input-output-hk/daedalus#frontend-only-mode

**Comment by TheDevKnight** [comment]
Hi Nikola,

thx for the hint. I will not build deadalus from sources by myself. Can you tell me if the frontend only flag/mode

https://github.com/input-output-hk/daedalus/pull/1260

Is available in daedalus release 0.13.0 for the end-user or must I always build daedalus from sources after the release to use the mode?

Regards
Henry
________________________________

**Comment by nikolaglumac** [comment]
Hi Henry,

This flag is not available to the end user - official Daedalus installers are shipped with the Cardano node packaged along with Daedalus. In order to use this flag you must build Daedalus from source.

Cheers!

**Comment by TheDevKnight** [comment]
Hi Nikola, when this the only solution for my problem. Thank you. I will look at the how to build daedalus.

Regards
Henry
________________________________
