### ISSUE TITLE
Fake copy/paste throughout the app

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/daedalus#1237]
DAEDALUS0.12.0
Windows build 10727, with Cardano 2.0.0

No matter where I right-click on the app, I get a "copy / paste" dialog that opens (even if I have nothing selected). Both options do nothing (as nothing is selected)

**Comment by nikolaglumac** [comment]
Thanks for the report @SebastienGllmt.
This small UX issue will be fixed for the next release.

**Comment by nikolaglumac** [comment]
Thanks for the report @SebastienGllmt.
This issue is fixed in: https://github.com/input-output-hk/daedalus/pull/1281 and will be released with Daedalus 0.13.0.
