### ISSUE TITLE
Can't install daedalus for Linux

### ISSUE THREAD

**Issue by ralampay** [input-output-hk/daedalus#1239]
I downloaded the installer file but I can't run it. After making it an executable file and/or run it with bash, it keeps giving me this message:

`../run: line 1: ./nix/store/somelonghash-startup: No such file or directory`

**Comment by darko-mijic** [comment]
Please check installation instructions here:
https://daedaluswallet.io/#download

![image](https://user-images.githubusercontent.com/4280521/50536846-20b15c00-0b59-11e9-8a06-223fd6dc9709.png)

**Comment by ralampay** [comment]
I think I figured it out. For those with the same issue, you have to clear the cache in `~/.cache` directory. Was caused by a previous interrupted install.

**Comment by laplasz** [comment]
I had the same issue - but I had to remove the folder under /tmp/ which was mentioned in the error message:
`/tmp/tmpx-2008332ed8ba8a3d/dat/../run: line 1: ./nix/store/gkcxc38f7zyx35i317jh94pivybihhmr-startup: No such file or directory`
