### ISSUE TITLE
The Summary and Transaction buttons in the Daedalus interface are redundant

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/daedalus#1355]
Hi,
  The Summary and Transaction buttons on the Daedalus interface do the exact same thing. I suggest consolidating the two buttons into one. Or at least put them next to each other.

<img width="1069" alt="Summary" src="https://user-images.githubusercontent.com/25856278/54730810-456a0e00-4b61-11e9-8dcc-f16086456761.png">

**Comment by nikolaglumac** [comment]
Hi @rickymac68,

This is actually not true. The summary screen shows the wallet balance, number of pending transactions and the 5 of the latest transactions. On the other hand, the transactions screen shows all your transactions.

Cheers!

**Comment by rickymac68** [comment]
Nikola, 
     I need to fix my wording here. The summary and transaction tabs display the same information. They are redundant to the point where Yoroi only Transactions tab and not a Summary tab for example. Here are some screen caps to show what I mean.
<img width="1147" alt="Summary" src="https://user-images.githubusercontent.com/25856278/54744134-87647580-4b9c-11e9-93a0-893ddc63d6e2.png">

<img width="1151" alt="Transactions" src="https://user-images.githubusercontent.com/25856278/54744147-90eddd80-4b9c-11e9-94c3-caf329d0708c.png">

<img width="1147" alt="Redundant" src="https://user-images.githubusercontent.com/25856278/54744165-9814eb80-4b9c-11e9-91d6-f2a817f5fa3a.png">

<img width="1797" alt="Yoroi" src="https://user-images.githubusercontent.com/25856278/54744212-b4b12380-4b9c-11e9-9ab1-4d0f09a4da40.png">

**Comment by nikolaglumac** [comment]
HI @rickymac68,

Well, Yoroi and Daedalus are not the same and there is no reason to make them look alike.
On the summary screen, we also show the number of pending transactions (while there are some).
Transaction screen will be updated in the future as we will be adding filtering options so that you can browse transactions by date and direction (outgoing/incoming).
Also, there are some performance challenges - we need the summary screen to be rendered fast which would be a challenge if you have a large number of transactions.

Cheers!

**Comment by rickymac68** [comment]
So maybe the Summary and Transaction button should at least be right next to each other instead of having the send/receive buttons in between them. These are two different icons/menu selections that present the same data.

**Comment by nikolaglumac** [comment]
We will leave them as is for now.
I agree with you that the screens are very similar but this will change in the future as we add more functionalities to the "Transactions" screen.

Thank you for your feedback!

**Comment by rickymac68** [comment]
I made a YouTube video that might better explain what I am trying to say about how the menu and navigation works. I'm not all that GitHub savvy, but maybe I can get some user feedback on the video and see how that goes. Here's the link

https://www.youtube.com/watch?v=e9jiCB8bAXU

**Comment by nikolaglumac** [comment]
Thank you for the video @rickymac68 !
Your comments are welcome and we will for sure make some changes in the future Daedalus versions!

**Comment by nikolaglumac** [comment]
Hi @rickymac68!
Daedalus Mainnet 1.0.0 introduces transaction filtering option which is only present on the "Transactions" screen which makes this screen which resolves the issue you reported.
Thank you!
