### ISSUE TITLE
GPU Safe Mode UX

### ISSUE THREAD

**Issue by nikolaglumac** [input-output-hk/daedalus#1360]
There was a question @rickymac68 posted as a part of his video (https://www.youtube.com/watch?v=e9jiCB8bAXU) about the UX of the Daedalus *GPU Safe Mode* option which is available from the application menu: `Daedalus > GPU Safe Mode`.

![Screen Shot 2019-03-21 at 17 21 54](https://user-images.githubusercontent.com/376611/54767664-ec03ec80-4bfd-11e9-8908-47f5ab668fbb.png)

@rickymac68 suggested this item needs a confirmation dialog which would explain what this option actually does. Even though this is a valid point, this feature is to be used by users facing the "Blank Daedalus Window" issues which occur due to problems with the GPU drivers and/or GPU hardware on their machine which prevent Daedlus window contents to be rendered. In the described circumstances there is no way to render this additional confirmation dialog and thus the only viable solution is to trigger Daedalus to restart into the GPU Safe Mode upon clicking on this menu item.

Once Daedalus is restarted users can see if the GPU Safe Mode is active by checking the application menu item and the application window title:

![gpu-safe-mode](https://user-images.githubusercontent.com/376611/54767882-65034400-4bfe-11e9-818c-35e946028748.png)

**Comment by ebeloded** [comment]
Is Daedalus using some unique rendering method? I haven't seen this kind of mode in other Electron apps (VS Code, Slack, Github Desktop).

**Comment by nikolaglumac** [comment]
@ebeloded Daedalus uses default Electron rendering method. However, on some systems and specific setups, the GPU accelerated rendering (https://electronjs.org/docs/all#gpu-accelerated) can fail and thus cause the contents of the Daedalus window not to be displayed at all (white or black screen is shown instead). The purpose of the "GPU Safe Mode" is to allow the users to manually disable "GPU accelerated rendering" in case such an issue occurs.

**Comment by nikolaglumac** [comment]
This issue has been resolved in Daedalus `0.14.0`: https://github.com/input-output-hk/daedalus/releases/tag/0.14.0 (release notes: https://iohk.zendesk.com/hc/en-us/articles/360033778753).

> **Blank Screen Fix**
> The option to disable graphics acceleration when a blank screen is displayed instead of the Daedalus user interface has been renamed from ‘GPU Safe Mode’ to ‘Blank Screen Fix’ to make it more easily understandable. The setting now also has expanded confirmation dialogs which explain how and when it should be used.
