### ISSUE TITLE
Please get signing key into PGP WOT

### ISSUE THREAD

**Issue by jonathancross** [input-output-hk/daedalus#1380]
#### Motivation:

Users need to be able to verify if the release signing key is **authentic**.  Right now that is nearly impossible.

#### Issue:

The current signing key (`D325 87D4 090F E461 CAEE  0FF4 966E 5CB9 CBFA A9BA`) is [not reachable using the PGP Web Of Trust](https://pgp.cs.uu.nl/mk_path.cgi?FROM=c0c076132ffa7695&TO=CBFAA9BA&PATHS=trust+paths).  It has many signatures, but most keys (17) are not available and the others are isolated (have not been signed by anyone else and could be sock puppets).

#### Suggested fix:

Exchange key signatures (certifications) with devs who have well connected keys -- especially those working on Cardano / Daedalus.

As an interim solution, please post the key fingerprint to various locations to help users gain some vague certainty about the authenticity.  Eg: add it to all public presentations, footer of IOHK website, Twitter account, etc.  Add it to your [README](https://github.com/input-output-hk/daedalus/blob/develop/README.md), use it to sign important messages and post those signatures publicly, confirm on this bug that the fingerprint above is correct.

**Comment by goetzc** [comment]
Providing the GPG signing key ID on other official sites would be great, aside from the Web of Trust. 

Daedalus [used to provide](https://github.com/input-output-hk/daedalus/issues/556#issuecomment-459231975) the key ID on the GitHub releases page:
https://github.com/input-output-hk/daedalus/releases/tag/0.11.0

**Comment by jonathancross** [comment]
It has been a year and we still don't have someone even confirming this fingerprint is correct here on GitHub :-/

There are 52 keys that have signed this key now, but **zero** that are part of the WOT Strong Set.  They could all have been created by a malicious party, etc. Sad.

**Comment by nikolaglumac** [comment]
@disassembler please take charge of this one 🙏

**Comment by jonathancross** [comment]
I saw that @CodiePP is not far from me (Zürich area) and he has a published OpenPGP key.  We have a shared connection in LinkedIn.  Is he capable of verifying + cross-signing the IOHK key definitively?  If so, I can meet him and cross-sign adding a WOT path.

**Comment by danielmain** [comment]
We provide instructions for this here: https://daedaluswallet.io/en/download/#modal=download_pgp_instructions_darwin
