### ISSUE TITLE
restoring wallet hangs on 23% for 4 days now

### ISSUE THREAD

**Issue by Mickroz** [input-output-hk/daedalus#1411]
I've been trying to restore my wallet for the last 4 days now, it keeps hanging on 23% and says its gonna take 3 weeks....
I haven't seen a shitty program like this in my life, i tried all solutions posted by others, and it still hangs on 23%.
Im just guessing i can say bye to my money now, and take my loss then trying to spend more time on this garbage piece of software.

**Comment by nikolaglumac** [comment]
Hello @Mickroz,
Sorry to hear you are having issues :(
The problem you have described sounds like an issue with blockchain data being corrupted on your machine and thus the restoration can not progress.
I suggest you follow this article - it should resolve the issue you are having: https://iohk.zendesk.com/hc/en-us/articles/360009484874-Delete-and-re-sync-blockchain-data

**Comment by Mickroz** [comment]
Ok, so doing it like this actually worked, and fast.
So not so shitty program after all, sorry for my rage, but was kinda done with it after 5 days.

**Comment by nikolaglumac** [comment]
I'm glad to hear the issue has been resolved @Mickroz 🎉 
Once again, I apologize for the problems. We are constantly working on improving Daedalus.
Still, if you run in any sort of issues do not hesitate to check for solutions on our Support Portal: https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-wallet or submit a support request (https://iohk.zendesk.com/hc/en-us/requests/new) or a GitHub issue like you did now.
We will do our best to help you!
Have a nice day!
