### ISSUE TITLE
Installing a wallet on a CentOS

### ISSUE THREAD

**Issue by kotora-cat-jp** [input-output-hk/daedalus#1432]
Hello.
I want to install the daedalus wallet on CentOS, but it does not work. Please let me know how to install.(daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin)

**Comment by daniloprates** [comment]
Hi @kotora-cat-jp,

Could you please try following the instructions on the following links:

* https://iohk.zendesk.com/hc/en-us/articles/360010496553-System-Requirements
* https://iohk.zendesk.com/hc/en-us/articles/360020253274

Alternatively, please, could you send more information about what is not working? Is there any error message?

Thank you,
Danilo

**Comment by kotora-cat-jp** [comment]
Hi.
Thank you for your response. 
When I run the following command on CentOS on Azure with SELinux disabled, I get an error.

$bash daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin
daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin: line 56: cd: /tmp/tmpx-404114d595d5e0d: Permission denied

Thank you

**Comment by kotora-cat-jp** [comment]
Hi.
In addition I tried the following command.

$sudo sysctl -w kernel.unprivileged_userns_clone=1
sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
$sudo sh -c "echo kernel.unprivileged_userns_clone=1 > /etc/sysctl.d/nix-user-chroot.conf"
$bash daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin
daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin: line 56: cd: /tmp/tmpx-404114d595d5e0d: Permission denied

I appreciate your cooperation.
Thank you.

**Comment by kotora-cat-jp** [comment]
Hi.
This is additional information. I tried the following command and the error message changed.

$ sudo chmod 777 tmpx-404114d595d5e0d
$ bash daedalus-0.13.1-cardano-sl-3.0.1-mainnet-x86_64-linux-5130.bin
chmod: changing permissions of ‘./run’: Operation not permitted

But I do not know what to do.
I do not know where ./run is on CentOS.
Please teach me.
Thank you.

**Comment by disassembler** [comment]
Can you share to output of `mount`? Seems like /tmp has some weird permissions set on the systmem. Also `ls -hal /tmp`.

**Comment by kotora-cat-jp** [comment]
Thank you for answering. This is the result of executing the ls -hal / tmp command.

[user@host:~]$ ls -hal /tmp
total 92K
drwxrwxrwt.  8 root root 4.0K Jun 25 15:07 .
dr-xr-xr-x. 18 root root  257 Apr 23 05:34 ..
drwxrwxrwt.  2 root root    6 Dec 19  2018 .font-unix
drwxrwxrwt.  2 root root    6 Dec 19  2018 .ICE-unix
drwx------.  3 root root   17 Jun  2 08:00 systemd-private-d9ea1005f3ef43728178d4f278c39df3-ntpd.service-PjiDbi
drwxrwxrwt.  2 root root    6 Dec 19  2018 .Test-unix
-rw-------.  1 root root 1.7K Jun 19 15:08 tmp16IfOk
-rw-------.  1 root root 1.7K Jun 15 15:13 tmp2vJqJ9
-rw-------.  1 root root 1.6K Jun 24 15:15 tmp3DiCNJ
-rw-------.  1 root root 1.7K Jun 20 15:09 tmpabPyQl
-rw-------.  1 root root 1.7K Jun 25 15:07 tmpbyBbhc
-rw-------.  1 root root 1.7K Jun 17 15:12 tmpcUl1aJ
-rw-------.  1 root root 1.7K Jun 21 15:05 tmpcxYD6j
-rw-------.  1 root root 1.7K Jun 15 15:13 tmpd4DKDp
-rw-------.  1 root root 1.7K Jun 17 15:12 tmpdZjVl3
-rw-------.  1 root root 1.6K Jun 22 15:14 tmpgap9Xf
-rw-------.  1 root root 1.7K Jun 19 15:08 tmpHYQfqH
-rw-------.  1 root root 1.7K Jun 23 15:10 tmpP66WaL
-rw-------.  1 root root 1.7K Jun 18 15:10 tmppbrxRY
-rw-------.  1 root root 1.7K Jun 25 15:07 tmpRdMJ_6
-rw-------.  1 root root 1.6K Jun 16 15:15 tmpsmhxOo
-rw-------.  1 root root 1.7K Jun 21 15:05 tmpttlJa6
-rw-------.  1 root root 1.7K Jun 23 15:10 tmpuivgWN
-rw-------.  1 root root 1.7K Jun 20 15:09 tmpUN_QyJ
-rw-------.  1 root root 1.6K Jun 22 15:14 tmpWXHKNz
-rw-------.  1 root root 1.6K Jun 16 15:15 tmpXvJ5m2
-rw-------.  1 root root 1.6K Jun 24 15:15 tmpzkx1Ue
-rw-------.  1 root root 1.7K Jun 18 15:10 tmpzxSjnT
drwxrwxrwt.  2 root root    6 Dec 19  2018 .X11-unix
drwxrwxrwt.  2 root root    6 Dec 19  2018 .XIM-unix
[user@host:~]$

I can ask the IT administrator about settings, but please tell me how I should ask him.
Thank you.

**Comment by kotora-cat-jp** [comment]
Thank you for answering. This is the result of executing the ls -hal / tmp command.

```
[user@host:]$ ls -hal /tmp
total 92K
drwxrwxrwt. 8 root root 4.0K Jun 25 15:07 .
dr-xr-xr-x. 18 root root 257 Apr 23 05:34 ..
drwxrwxrwt. 2 root root 6 Dec 19 2018 .font-unix
drwxrwxrwt. 2 root root 6 Dec 19 2018 .ICE-unix
drwx------. 3 root root 17 Jun 2 08:00 systemd-private-d9ea1005f3ef43728178d4f278c39df3-ntpd.service-PjiDbi
drwxrwxrwt. 2 root root 6 Dec 19 2018 .Test-unix
-rw-------. 1 root root 1.7K Jun 19 15:08 tmp16IfOk
-rw-------. 1 root root 1.7K Jun 15 15:13 tmp2vJqJ9
-rw-------. 1 root root 1.6K Jun 24 15:15 tmp3DiCNJ
-rw-------. 1 root root 1.7K Jun 20 15:09 tmpabPyQl
-rw-------. 1 root root 1.7K Jun 25 15:07 tmpbyBbhc
-rw-------. 1 root root 1.7K Jun 17 15:12 tmpcUl1aJ
-rw-------. 1 root root 1.7K Jun 21 15:05 tmpcxYD6j
-rw-------. 1 root root 1.7K Jun 15 15:13 tmpd4DKDp
-rw-------. 1 root root 1.7K Jun 17 15:12 tmpdZjVl3
-rw-------. 1 root root 1.6K Jun 22 15:14 tmpgap9Xf
-rw-------. 1 root root 1.7K Jun 19 15:08 tmpHYQfqH
-rw-------. 1 root root 1.7K Jun 23 15:10 tmpP66WaL
-rw-------. 1 root root 1.7K Jun 18 15:10 tmppbrxRY
-rw-------. 1 root root 1.7K Jun 25 15:07 tmpRdMJ_6
-rw-------. 1 root root 1.6K Jun 16 15:15 tmpsmhxOo
-rw-------. 1 root root 1.7K Jun 21 15:05 tmpttlJa6
-rw-------. 1 root root 1.7K Jun 23 15:10 tmpuivgWN
-rw-------. 1 root root 1.7K Jun 20 15:09 tmpUN_QyJ
-rw-------. 1 root root 1.6K Jun 22 15:14 tmpWXHKNz
-rw-------. 1 root root 1.6K Jun 16 15:15 tmpXvJ5m2
-rw-------. 1 root root 1.6K Jun 24 15:15 tmpzkx1Ue
-rw-------. 1 root root 1.7K Jun 18 15:10 tmpzxSjnT
drwxrwxrwt. 2 root root 6 Dec 19 2018 .X11-unix
drwxrwxrwt. 2 root root 6 Dec 19 2018 .XIM-unix
[user@host:]$
```

I can ask the IT administrator about settings, but please tell me how I should ask him.
Thank you.

**Comment by nikolaglumac** [comment]
@disassembler can you please follow up on this one?

**Comment by nikolaglumac** [comment]
CentOs is not an operating system we officially support. Please see the following for more details:

- https://iohk.zendesk.com/hc/en-us/articles/360010496553-System-Requirements
- https://iohk.zendesk.com/hc/en-us/articles/360020253274
