### ISSUE TITLE
Network status hides Block Consolidation status

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/daedalus#1470]
a little issue.
The "network status" is made as a semitransparent popup, covering all other GUI elements. 
When clicking (switching) in the menu to any other content it looks like it doesn't work (appear) 
The user first must click the X on top-right of the network-status overlay.

I would suggest the overlay can remain the same, but any other menu click should automatically close the overlay.

**Comment by daniloprates** [comment]
Hi @gufmar,

Thank you for your report. Could you describe the exact steps for this issue to occur?

We will investigate it.

Regards,
Danilo

**Comment by daniloprates** [comment]
@gufmar could you also, please, let us know which Daedalus version you are using?

**Comment by gufmar** [comment]
it is version 0.13.1#3.0.1.12940

Steps to reproduce
Start Daedalus 
Menu Daedalus > Block Consolidation Status (the page appears by replacing the wallet page = OK)
Menu Daedalus > Network Status (the page appears by poping up above the Block Consolidation status = OK)
Now when the user didn't note it is a full window size (popup) overlay that must be clicked away on top-right X and he clicks again in menu Daedalus > Block Consolidation status, the Network status overlay will remain on top, and it looks like the app is not reacting anymore (beside the status values updating)

**Comment by daniloprates** [comment]
Hi @gufmar. We have a new Daedalus finishing baking which will address this issue and also unify the layout for all overlays.

Many thanks for the information,
Danilo
