### ISSUE TITLE
Daedalus npm install failed

### ISSUE THREAD

**Issue by Alteryy** [input-output-hk/daedalus#1542]
~/[daedalus# npm install
                                  ^
/root/.cache/node-gyp/8.2.1/include/node/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
       regfunc,                                                        \
       ^
../src/validation.c:87:1: note: in expansion of macro ‘NAPI_MODULE’
 NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
 ^
validation.target.mk:101: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/root/daedalus/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-154-generic
gyp ERR! command "/root/.nvm/versions/node/v8.2.1/bin/node" "/root/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/daedalus/node_modules/utf-8-validate
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN @emotion/provider@0.11.2 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/styled-base@0.10.6 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/styled-base@0.10.6 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-router@3.1.2 requires a peer of mobx@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-treebeard@3.1.0 requires a peer of @emotion/styled@^0.10.6 but none is installed. You must install peer dependencies yourself.
npm WARN daedalus@0.14.0 No repository field.
npm WARN daedalus@0.14.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utf-8-validate@5.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    

 /root/.npm/_logs/2019-08-19T17_52_14_591Z-debug.log
----log----
715 silly saveTree │     └── camelcase@5.3.1
715 silly saveTree ├─┬ webpack-stream@5.2.1
715 silly saveTree │ ├── lodash.clone@4.5.0
715 silly saveTree │ ├── lodash.some@4.6.0
715 silly saveTree │ └── plugin-error@1.0.1
715 silly saveTree ├── webpack@4.27.1
715 silly saveTree └── yamljs@0.3.0
716 warn @emotion/provider@0.11.2 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
717 warn @emotion/styled-base@0.10.6 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
718 warn @emotion/styled-base@0.10.6 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
719 warn mobx-react-router@3.1.2 requires a peer of mobx@^3.0.0 but none is installed. You must install peer dependencies yourself.
720 warn react-treebeard@3.1.0 requires a peer of @emotion/styled@^0.10.6 but none is installed. You must install peer dependencies yourself.
721 warn daedalus@0.14.0 No repository field.
722 warn daedalus@0.14.0 No license field.
723 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
724 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
725 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
726 verbose stack Error: utf-8-validate@5.0.1 install: `node-gyp-build`
726 verbose stack Exit status 1
726 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
726 verbose stack     at emitTwo (events.js:125:13)
726 verbose stack     at EventEmitter.emit (events.js:213:7)
726 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
726 verbose stack     at emitTwo (events.js:125:13)
726 verbose stack     at ChildProcess.emit (events.js:213:7)
726 verbose stack     at maybeClose (internal/child_process.js:921:16)
726 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
727 verbose pkgid utf-8-validate@5.0.1
728 verbose cwd /root/daedalus
729 verbose Linux 4.4.0-154-generic
730 verbose argv "/root/.nvm/versions/node/v8.2.1/bin/node" "/root/.nvm/versions/node/v8.2.1/bin/npm" "install"
731 verbose node v8.2.1
732 verbose npm  v6.10.3
733 error code ELIFECYCLE
734 error errno 1
735 error utf-8-validate@5.0.1 install: `node-gyp-build`
735 error Exit status 1
736 error Failed at the utf-8-validate@5.0.1 install script.
736 error This is probably not a problem with npm. There is likely additional logging output above.
737 verbose exit [ 1, true ]
----log----

**Comment by nikolaglumac** [comment]
@Alteryy you need to start Daedalus through the nix-shell. Please refer to this part of the README: https://github.com/input-output-hk/daedalus#connect-to-local-demo-cluster
There are options which allow you to connect to the Staging and Testnet networks too.

**Comment by nikolaglumac** [comment]
@Alteryy any news?

**Comment by nikolaglumac** [comment]
@Alteryy please follow the installation steps provided in the README: https://github.com/input-output-hk/daedalus#installation

**Comment by nikolaglumac** [comment]
@Alteryy please use yarn and nix as described in Daedalus README: https://github.com/input-output-hk/daedalus/blob/develop/README.md#yarn
