### ISSUE TITLE
Synchronize took over 48 hours to complete 

### ISSUE THREAD

**Issue by carlwhiston** [input-output-hk/daedalus#1582]
Hi.

Recently installed Daedalus on Windows 10. Install run ok. When I ran the Wallet for the first time it took over 48 hours to do the synchronize section. My computer was flat out and I couldn't run anything else for that period.  I can provide logs etc if you specify where they are and which ones you need.

Many thanks
Carl

**Comment by nikolaglumac** [comment]
Hi @carlwhiston,

Syncing time depends on many factors such as:
- Internet connection speed
- hard drive speed
- CPU and memory

Usually, syncing should be complete within 3-4 hours. Having spent 48 hours is definitely unexpected. This process involves downloading and processing large number of files which results in a lot of I/O operations and could be impacted by Windows Defender or antivirus software.

Regards,
N.

**Comment by nikolaglumac** [comment]
@carlwhiston please download the latest Daedalus Mainnet 1.0.0 which introduces huge improvements in terms of connecting and syncing performance: https://daedaluswallet.io/en/download/
