### ISSUE TITLE
Any plan porting to BSDs?

### ISSUE THREAD

**Issue by matm** [input-output-hk/daedalus#1667]
Just wondering if there is ongoing work porting Daedalus to other UNIX systems like OpenBSD?

If not, I'd like to give it a try. Do you see any technical showstopper (maybe Electron, Nix ...)?

Thanks and keep up the good work!

**Comment by nikolaglumac** [comment]
There are no such plans at the moment.
System requirements: https://iohk.zendesk.com/hc/en-us/articles/360010496553-System-Requirements
