### ISSUE TITLE
starting on Linux - update file not found

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/daedalus#1747]
First start on Linux after installation - package is daedalus-0.15.1-cardano-sl-3.1.0-mainnet-x86_64-linux-8695.bin
command was used:
`:~$ ~/.local/bin/daedalus-mainnet`
Error during execution:
```
[cardano-sl.launcher:Notice:ThreadId 4] [2019-12-09 16:40:46.50 UTC]     /bin/update-runner "/home/user/.local/share/Daedalus/mainnet/installer.sh"
[u[updater] update file not found
pdater] + '[' '!' -e /home/user/.local/share/Daedalus/mainnet/installer.sh ']'
[updater] + echo 'update file not found'
[updater] + exit -1
```

**Comment by nikolaglumac** [comment]
@laplasz please use the latest Daedalus Mainnet 1.0.0 release available on https://daedaluswallet.io/en/download/
