### ISSUE TITLE
Latest build of INT wallet in hydra wrongly calculates required fee, forcing users to leave 1 lovelace dust

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/daedalus#1776]
I installed the build of INT wallet from IOHK Hydra, build id 1498778 in Cardano:daedalus-bors-staging, when I recovered my paper wallet and moved my balance to the rewards wallet, I tried to move the funds to my pledge address. When I entered the balance amount - tx fee, the UI would not let me execute the transaction, when I reduced the amount by 1 lovelace, the UI let me execute the TX and it executed successfully, leaving 1 lovelace in the rewards wallet I created.

![Capture](https://user-images.githubusercontent.com/18139116/70855753-55383800-1ed0-11ea-8f56-d091c1e408b1.JPG)

![Capture_xxx](https://user-images.githubusercontent.com/18139116/70855755-6a14cb80-1ed0-11ea-8720-2571786ded43.JPG)

I don't know if any of the pending PRs or those merged into master fix this issue, I haven't checked. Link to mentioned hydra build left-out intentionally not to get people too excited prior to official release.

**Comment by nikolaglumac** [comment]
Closing this one as Daedalus ITN is no longer in use.
