### ISSUE TITLE
Daedalus from staging branch (7e78b7f) for INT shows entire balance sent to a pledge address as rewards

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/daedalus#1777]
This will most probably concern only pool operators / owners, but (freshly created for INT) Daedalus wallet restored using 15 words mnemonic to which I've sent my pledge does not show the funds that I've sent there as a balance, it considers it to be rewards.

I would anticipate that Daedalus would be able to differentiate between funds that were sent by someone to the rewards address and the rewards itself, that have been paid automatically by the protocol.
![pledge-address-bug](https://user-images.githubusercontent.com/18139116/70855967-9716ad80-1ed3-11ea-80ca-3f40ee553117.JPG)
![pledge-address-bug-2](https://user-images.githubusercontent.com/18139116/70856009-87e42f80-1ed4-11ea-83d0-2785d7997a6c.JPG)

**Comment by nikolaglumac** [comment]
@mark-stopka Daedalus only presents your the sum of all your wallet's UTXO's as the balance which explains why your pledge amount (which is stored on your wallet's rewards account) is not detected by Daedalus.
