### ISSUE TITLE
Daedalus doesn't notify the end user about not enough disk space

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/daedalus#1787]
When launching ```Daedalus 2.0.0-ITN1#3.1.0.10012``` with low disk space, it doesn't alert the user in GUI, just keeps try to _Connect to the network_.

The background logs however hold this message.

```
{"at":"2019-12-17T13:28:13.271Z","env":"itn_rewards_v1:Linux:4.19.74","ns":["daedalus","v2.0.0-ITN1","*itn_rewards_v1*"],"data":{"response":{"isNotEnoughDiskSpace":true,"diskSpaceRequired":"2 GB","diskSpaceMissing":"640.1 MB","diskSpaceRecommended":"32.6 GB","diskSpaceAvailable":"1.4 GB"}},"app":["daedalus"],"msg":"Not enough disk space","pid":"","sev":"info","thread":""}
```

**Comment by nikolaglumac** [comment]
Fixed in: https://github.com/input-output-hk/daedalus/releases/tag/2.2.0-ITN1

Please upgrade your Daedalus by downloading the latest version from: https://staking.cardano.org/delegation/
