### ISSUE TITLE
Daedalus not loading stake pool list

### ISSUE THREAD

**Issue by PapaCryptoIO** [input-output-hk/daedalus#1789]
I delegated one wallet to a pool with no issue.  After a few hours, I tried to delegate a second wallet but the stake pool list was empty.  I tried to restart Daedalus multiple times but it did not resolve this issue.
<img width="1262" alt="Screenshot 2019-12-18 at 09 27 40" src="https://user-images.githubusercontent.com/55553493/71069493-24c6f700-2179-11ea-902d-401712a5c846.png">

**Comment by darko-mijic** [comment]
Can you attach your logs @PapaCryptoIO?

Logs do not contain any sensitive information. 
Logs can be downloaded from the Help menu, Download logs.

![image](https://user-images.githubusercontent.com/4280521/71070175-8340a500-217a-11ea-9c4c-5606820336d4.png)

**Comment by darko-mijic** [comment]
Also, @PapaCryptoIO, it would be best if you create a support request. Our support team can handle this issue. Let me know when you created a support request there so I can close this issue here.

**Comment by PapaCryptoIO** [comment]
Hi Darko,

Support ticket opened.  Thank you!

Jay
