### ISSUE TITLE
Lost my funds

### ISSUE THREAD

**Issue by wstrik** [input-output-hk/daedalus#1792]
Hi, I'm trying to setup a stake pool and have send the pledge amount to my stakepool account. But it seems like the rest of my funds disappeared with it.
[https://shelleyexplorer.cardano.org/en/address/addr1s38t9jn0ek9e37xem9mk4y3czswemlkgq4dff52xjhd04zvdeah2x0uj2e0pxu0y3tych3g58qal0asmnqwfgu2443xcdkfv7q7qxdca9mqh2a/](https://shelleyexplorer.cardano.org/en/address/addr1s38t9jn0ek9e37xem9mk4y3czswemlkgq4dff52xjhd04zvdeah2x0uj2e0pxu0y3tych3g58qal0asmnqwfgu2443xcdkfv7q7qxdca9mqh2a/)

![71175294-7fd71780-2267-11ea-966d-216c27ecdad3](https://user-images.githubusercontent.com/767227/71236239-c035a480-22fe-11ea-9c89-afced7a528aa.png)

**Comment by darko-mijic** [comment]
@wstrik, please create a support ticket:
https://iohk.zendesk.com/hc/en-us/requests/new

**Comment by nikolaglumac** [comment]
@wstrik Daedalus does not display the "account" balance. Only UTXO are detected and summed up to be presented as your wallet's balance. Thus, your funds are not lost - they are just not a part of your wallet's UTXO anymore since you have moved all your funds to the stakepool account.
