### ISSUE TITLE
Stake pool popup description is being cut

### ISSUE THREAD

**Issue by Gwearon** [input-output-hk/daedalus#1796]
[Minor] Stake pool description is being violently cut even though it adheres to [json schema](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry). [See original text](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/blob/master/registry/ed25519_pk1zpht6k7dmcw2xrnql2qnsx3s0aa03t8820x2a8gdmvlywgytxj7qssx2rq.json#L7).

Solution 1: Provide full 255 characters.
Solution 2: Add text ellipsis.

![Bug_text_cut](https://user-images.githubusercontent.com/58776553/71257130-3227e100-2333-11ea-8a87-81225747346d.png)

**Comment by nikolaglumac** [comment]
Fixed in: https://github.com/input-output-hk/daedalus/releases/tag/2.2.0-ITN1

Please upgrade your Daedalus by downloading the latest version from: https://staking.cardano.org/delegation/
