### ISSUE TITLE
how to build createDelegationTx   And  signDelegationTx

### ISSUE THREAD

**Issue by lvshaoping** [input-output-hk/daedalus#1800]
i want to build a delegation function . but i cannot find the params of these two function .Can you tell me how to createDelegationTx or offer an opened api about delegation?

**Comment by SebastienGllmt** [comment]
Perhaps what you're looking for is JCLI? You can find information about JCLI at https://github.com/input-output-hk/jormungandr

**Comment by nikolaglumac** [comment]
@lvshaoping please refer to the following repo: https://github.com/input-output-hk/cardano-wallet
