### ISSUE TITLE
Wallet Balances don't reflect current state

### ISSUE THREAD

**Issue by kakerley** [input-output-hk/daedalus#1807]
After upgrading to new version of daedalus my rewards wallet balances are back to displaying a 0 balance but I cannot retransfer my Balance Wallet funds to my Rewards Wallet (if I try the transaction sits in pending forever). Also my stakepool wallet address shows an incorrect balance (At least it seems incorrect to me). After transferring 550 ADA to addr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj the balance is showing as 49.6 ADA. I can't send any more funds to this address from Daedalus as it won't let me move ADA from my Balance Wallet or my Rewards Wallet.

https://shelleyexplorer.cardano.org/en/address/addr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj/

Hash8add28f78040df608456f86f0d6a2632e96fb661ebce406b87b6ee6473844366
--
Fromaddr1sszlcal499grt5w8txsq0vjya534pn4vg84tmaqzdtrnw4qghwyr0awht3f4wmcarmn7xg6e9jtrc6d0zsdahzc2cxaqt0u0srpkv75kedrup580837.783043 ADA | Toaddr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj50.000000 ADAaddr1sju77j2ja4tz45t6vrkuw4p0zrtz0ewxwwnsnreu9xsmd3vm8y4rtawht3f4wmcarmn7xg6e9jtrc6d0zsdahzc2cxaqt0u0srpkv75k983m2w80787.283043 ADA
Fee0.500000 ADA

Hash524dac8e90f0fd9a3c023f49033a6d590ab9f29f626db360dfd22191cbb67486
Fromaddr1sju77j2ja4tz45t6vrkuw4p0zrtz0ewxwwnsnreu9xsmd3vm8y4rtawht3f4wmcarmn7xg6e9jtrc6d0zsdahzc2cxaqt0u0srpkv75k983m2w80787.283043 ADA | Toaddr1sjhed3ffgxvkpctt85ck89s7ftqhdepax59arm2c0zntuke5w55g3awht3f4wmcarmn7xg6e9jtrc6d0zsdahzc2cxaqt0u0srpkv75k0ddw2r80286.783043 ADAaddr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj500.000000 ADA
Fee0.500000 ADA

Hash462eb3ef5b4dbb6f73dccd5c760a2d5f91aa463c60c9ca4d2e9795762afa2bb0
Fromaddr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj500.700000 ADA | Toaddr1sh8mdx9zn3fhzqpd0uy4a2qdzy5hes32v2cxle7t8n00vz2x4l6nu43hnrj0.300000 ADA
Fee500.400000 ADA (I'm not too sure how this transaction was initiated or how the fees on this transaction hit 500.4 ADA but this seems to be the issue with my balance being 49 ADA)

**Comment by diegueins680** [comment]
Same here. Tried several times but the transaction shows as pending indefinitely.

**Comment by nikolaglumac** [comment]
Closing this one as Daedalus ITN is no longer in use.
