### ISSUE TITLE
Pool performance ranking inconsistencies

### ISSUE THREAD

**Issue by hex-pool** [input-output-hk/daedalus#1809]
Version: Daedalus Incentivized Testnet v1- Rewards (2.0.1-INT1#3.1.0.10152)

I’ve noticed that a fresh installation shows a different pool order than an older installation.

Some reverse engineering revealed the following:

“AppData\Roaming\Daedalus - Rewards v1\wallets\stake-pools.sqlite” contains, among others,  the tables “pool_production” and “stake_distribution”.

Pool_production has a lot of records and it looks like it contains all the blocks created since the ITN started and the pool that created the block.

On a fresh installation, stake_distribution only contains data starting with the epoch in which Daedalus was installed. (I installed Daedalus during epoch 20; stake_distribution contains data from epoch 20 and epoch 21)

Stake pool ranking looks completely different on an older vs a newer Daedalus installation. I assume this happens because ranking is calculated starting with the installation onward.

Because pool ranking is updated after each block creation, this inconsistency is confusing to delegators. On fresh installations it displays higher ranking for pools with more stake, disregarding overall pool performance.

**Comment by consuman** [comment]
Thx for digging into it. I noticed too, that its not really obvious how the ranking is done. Compared a lot of pools manually and found little correlation.

Maybe the time of registration is also relevant?

**Comment by hex-pool** [comment]
See https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Pool/Metrics.hs

Pool ranking is basically blocks_minted / blocks_allocated * constant.

Daedalus does something wrong and it computes that - see original description for details

**Comment by nikolaglumac** [comment]
This is a known issue, which is why we have implemented the "Experimental data" notification: https://github.com/input-output-hk/daedalus/pull/1845
