### ISSUE TITLE
ITN - Daedalus showing wrong balance and wrong info about delegation

### ISSUE THREAD

**Issue by uipavec** [input-output-hk/daedalus#1813]
At times Daedalus reports awkward sums (not real balance) in my wallets. All my wallets are delegated to different staking pools and the UI says they are not delegated at all (not a single one). So I can pick any  wallet to delegate it, but after entering the spending password and clicking Confirm the UI displays: An error occurred.

It's the first time I get the error above, but the next error I get occurs quite often. For all my wallets 0 ADA sum is displayed which is incorrect. In case I want to re-delegate a wallet, I cannot do it because the UI reports that I don't have enough ADA.

**Comment by cliffc2** [comment]
my ITN wallet showed 0 balance. and the mainnet wallet looked like i never moved the ada to ITN.  i had to move it again. waiting for it to connect now.

**Comment by nikolaglumac** [comment]
These issues were due to ITN network instability. They should be resolved now.
