### ISSUE TITLE
Feature request: use local files to generate a wallet address

### ISSUE THREAD

**Issue by jbax** [input-output-hk/daedalus#1836]
Just throwing a suggestion here. Keeping track of seed words - especially when you deal with multiple wallets - is a pain and not user friendly at all. Also keeping the seed phrase in physical form is as safe as writing your credit card password in a piece of paper and hoping no one will ever find it.

**So here is the suggestion**

Would it be possible to generate wallet addresses using the entropy generated from any combination of random files a user sends to daedalus (offline?). For example, I'd rather have my wallet generated from the picture I took from my first newborn coupled with the image from a frame of the video of my wedding at 15 minutes and 2 seconds. Add my favorite snippet from a book or part of a song that I like. A seed phrase could still be generated from that and securely stored as usual (and that might be a very long seed), but then that's not a single point of failure anymore.

The benefits of this approach are: you can still use a seed phrase, but you are not forced to. No one knows what images/videos/files you used. You can save everything online in multiple places with a lot of other stuff alongside it (google drive for example), you have a great chance of being able to recover the funds if you forget or lose the seed phrase. It's pretty much impossible for someone to find out what images/video frames/files were used, and in which order. I'm not an expert but this should make the wallet quantum resistant as well as it doesn't depend on random combinations of words that can be guessed.

**Comment by SebastienGllmt** [comment]
You can always just run your files through a hashing algorithm to generate the entropy yourself. Generating a recovery phrase from entropy can be done through https://iancoleman.io/bip39/ so it's not impossible to do right now -- just requires a bit more knowledge of how these things work. Daedalus could introduce a feature to make this flow a bit more accessible but you have to be really careful about it because for example somebody might change their picture to a different file format or change the metadata in the image and it would generate a different recovery phrase.

**Comment by jbax** [comment]
Thanks @SebastienGllmt , there doesn't seem to be an "ADA" or "Cardano" coin option in the page you linked (https://iancoleman.io/bip39/). I'm wondering what would be compatible with a daedalus wallet seed and also a paper wallet seed. 

If we could give daedalus multiple random files to generate the entropy and make it ensure it's random enough, that would help a lot.

**Comment by SebastienGllmt** [comment]
The coin is only for the `BIP32 Root Key` section which you don't need. You just need the `BIP39 Mnemonic` of the right length (12 for Byron-era reward, 15 for Byron-era Yoroi, 15 for any Shelley wallet)
