### ISSUE TITLE
"Wallet you are trying to restore already exists." Shown After Upgrading to 2.1.0-ITN1

### ISSUE THREAD

**Issue by JamesRobertKelley** [input-output-hk/daedalus#1853]
No wallets were shown after upgrading Daedalus to v2.1.0.

Attempting to restore the wallet gives the following error:

> Wallet you are trying to restore already exists.

![image](https://user-images.githubusercontent.com/21016477/74581920-4e3aae00-4f83-11ea-8065-c40d266f4e3e.png)

This is running on Windows 10.

**Comment by JiraiyaTheSage** [comment]
You would need to delete the contents in the Daedalus state directory. Follow the instruction provided [here.](https://iohk.zendesk.com/hc/en-us/articles/360039511853-Delete-the-contents-of-the-state-directory)

**Comment by JamesRobertKelley** [comment]
Deleting the contents and restoring the wallet allowed me to use Daedalus.

It would be better for the end-user experience if deleting the folder was not required, so please let me know if you need anything from me to assist with a permanent fix. I made a backup of the folder before removing the contents. If not, then I am satisfied.

**Comment by rdlrt** [comment]
How to resolve this using workaround is not a big issue, but having this issue mapped to QA/testing process to verify this is not missed in future is important.

**Comment by nikolaglumac** [comment]
Fixed in: https://github.com/input-output-hk/daedalus/releases/tag/2.2.0-ITN1

Please upgrade your Daedalus by downloading the latest version from: https://staking.cardano.org/delegation/
