### ISSUE TITLE
ITN - Reflect correct state of node

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/daedalus#1858]
Daedalus ITN currently waits cardano-wallet-jormungandr process to start responding and report sync status, which in turn - is waiting for jormungandr bootstrap process to finish.

All this while what is presented to an end user is "Connecting to Network.." message - which not only gives a very bad UX, but also makes them restart nodes often, making it worse.

The status on the screen needs to be presented better. I understand this issue may need a feature to be enabled on cardano-wallet end, but given the issue classification (bug, failure of test, task with predefined decisions), I am opening the issue here instead from end user's point of view.

**Comment by nikolaglumac** [comment]
Thank you for opening this ticket. We are aware of this issue and the negative impact it has on the UX. However, Daedalus is helpless in this case as without the changes on the `cardano-wallet` side there is no way for us to know if we are in the initial boostrap phase or not.

**Comment by nikolaglumac** [comment]
Closing this one as Daedalus ITN is no longer in use.
