### ISSUE TITLE
Please inform the enduser whats going on

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/daedalus#1876]
Hi,

so, a new version 2.3.0 is out, but it just works the same way (or not) as the previous version.
We as stakepool operators can track it down, jormungandr is having troubles connecting to other
peers. But the enduser is sitting there and seeing just a "Connecting to Network..." message. Thats not enough in my oppinion.

First, please show a message that the Node is reading the database from the harddisk. This can be fast or slow depending on the enduser machine. After that, show messages about the Bootstrap process and Trusted Peers. "Connecting to trusted peer xxx ..." , "failed!" "Connecting to trusted peer yyy ...", "failed!" etc.

Just give the enduser more information, especially in this Testnet environment!

We all would like that people holding some tADA to join the Testnet and test out this "COOL NEW STAKING THING WITH CARDANO". But leaving them behind with a non working Wallet couldn't be the solution.

I know i know, all testing, rust code, etc. BUT, if it is possible, please show more Status Informations to the user. And when jormungandr doesn't get back anything from a trusted peer for a few seconds, dump it, go to the next. 

Thank you!

Best regards,
 Martin

**Comment by nikolaglumac** [comment]
Closing this one as Daedalus ITN is no longer in use.
