### ISSUE TITLE
Daedalus repeatedly fails to run in a QubesOS Linux virtual machine

### ISSUE THREAD

**Issue by clayt0nk** [input-output-hk/daedalus#1878]
![Screenshot_2020-03-04_14-50-49](https://user-images.githubusercontent.com/3198617/76032441-e02b4a80-5f74-11ea-94a7-7604611c9a7f.png)

What has happened repeatedly now, is after an install or an update, it will run for a while, typically until it is almost synced, when there will be an error message that the daemon has "failed". After that, any attempt to restart it fails immediately until the next update.

In the attached screenshot, Daedalus is installed in the /rw partition, is already mostly synced (within a few %) and there is 17G free in that partition, yet it still throws an error about needing "at least 2G" of disk space.

**Comment by nikolaglumac** [comment]
Hello @clayt0nk!
Regardless of the partition/drive on which you install Daedalus, it downloads the blockchain data (which requires a lot of space) on your main partition/drive. So, in this case, it doesn't matter that the drive on which you have installed Daedalus has 17G of free space. Please free up some space on your main partition/drive and that will fix the issue.
Thanks!

**Comment by clayt0nk** [comment]
![Screenshot_2020-03-07_19-13-43](https://user-images.githubusercontent.com/3198617/76142360-f259d580-60a7-11ea-95fa-a15636af2af8.png)

The partition I have installed to is /rw, and this *is* my main partition. It is also the only partition a non-root user can write to on this Linux box (without invoking sudo, and let's hope Daedalus is not caught doing that....) so all of Daedalus activity should be confined to /rw/, as confirmed by above screen shot. There is no shortage of space where the blockchain is being written, and in fact most of it is already there.

**Comment by nikolaglumac** [comment]
This issue was fixed in the recent Daedalus Mainnet releases. Please update to the latest Daedalus Mainnet version.
