### ISSUE TITLE
Daedalus ITN error message uncaughtException::gpu-process-crashed: not-killed

### ISSUE THREAD

**Issue by josephj11** [input-output-hk/daedalus#1879]
I  slightly modified a copy of namespaceHelper so I can pipe its console  output into a filter to make it more human-readable. When an entry has a  "msg" field, I just print the local time and the message content. (I'm  filing another related report asking for you to make it so I don't have  to change namespaceHelper to get this output.)

This is part of what I get every time I start it. Why does the GPU thing always crash? Is some part of my hardware not being used correctly? Daedalus, itself, seems not to mind this and still syncs - usually after being killed and restarted four or five times.

I just installed the new Daedalus update. This issue is slightly improved. I only get one crash message instead of two in a row.

The new version almost scared me when it synced so fast! Syncing was always quite difficult before this. This is dramatically better!

17:56:15 Detected system locale
17:56:15 Daedalus is starting at 2020-03-05T22:56:15.434Z
17:56:15 Updating System-info.json file
(node:13378) ExperimentalWarning: The fs.promises API is experimental
17:56:15 Detected system locale
17:56:15 Main Error Handler started
17:56:15 CardanoNode: get itn_rewards_v1-PREVIOUS-CARDANO-PID success
17:56:15 CardanoNode: checking if previous cardano-node process is still running
17:56:15 CardanoNode: checking if cardano-wallet-jormungandr process (PID: 11128) is still running
17:56:15 uncaughtException::gpu-process-crashed: not-killed
17:56:15 No cardano-wallet-jormungandr process (PID: 11128) is running
17:56:15 CardanoNode: transitions to <starting>
17:56:15 CardanoNode#start: trying to start cardano-node for the 1 time
17:56:15 CardanoNode path with args

[logs-2020-03-05T230522.0208Z.zip](https://github.com/input-output-hk/daedalus/files/4295564/logs-2020-03-05T230522.0208Z.zip)

**Comment by nikolaglumac** [comment]
Hi @josephj11,
This is no reason for alarm - this uncaught exception is thrown from Electron (https://www.electronjs.org/docs/api/app#event-gpu-process-crashed) and in your case it actually does not mean the process crashed as it says it was not-killed and your Daedalus window wasn't closed.
Thanks!

**Comment by josephj11** [comment]
No problem. I just thought you might want to know it was occurring.
 
I have no idea what Daedalus does internally, but since it was was having such great difficulty syncing (especially before the latest version), I thought there was a chance that it might have wanted to use my GPU for extra processing power and was failing to do so.

If it's no big deal or something that can't or won't be fixed, you can just close this issue.

**Comment by nikolaglumac** [comment]
Hi @josephj11! This issue has been resolved.
