### ISSUE TITLE
Retired Stake Pool appears in Daedalus Pool List

### ISSUE THREAD

**Issue by DarkPaladin56** [input-output-hk/daedalus#1898]
Running 2.3.0-ITN1

Retired stake pool still appears in Daedalus stake pool list. The retired node does not appear in the jcli stake-pools get list.

The retired node was 6c0051b05359460dc2af61bd0f5b4b6c57fd1e9a7b7269f9c717bcafae0fbc55

**Comment by nikolaglumac** [comment]
Closing this one as Daedalus ITN is no longer in use.
