### ISSUE TITLE
Creating Paper Wallet with network connections turned off

### ISSUE THREAD

**Issue by gilleswittenberg** [input-output-hk/daedalus#1973]
Daedalus 0.15.1

When creating a new Paper Wallet while all network connections are turned off, Daedalus pops up the "Network connection lost - reconnecting..." view. 

In addition I would expect to be able to create a paper wallet without having to sync the entire blockchain first.

**Comment by nikolaglumac** [comment]
Hi @gilleswittenberg!

Daedalus does not support offline mode at the moment. You need to be connected to the network and fully synced to access the main UI and use the "Create paper wallet" feature.
But yes, it is perfectly reasonable to expect creating paper wallet should work even in offline mode.
Thank you for your suggestion - we will put it on our todo list.

Thanks!

**Comment by nikolaglumac** [comment]
Paper wallet feature has been discontinued. Closing this issue...
