### ISSUE TITLE
Paper wallet PDF text

### ISSUE THREAD

**Issue by gilleswittenberg** [input-output-hk/daedalus#1974]
Daedalus 0.15.1

The address in the paper wallet PDF file is displayed on two lines. When copy + pasting this, there is a space and / or newline character placed between the characters of the two lines. Also double clicking on a line only selects that specific line. Would be nice to select the entire address in that case.

Minor other issue: the numbering in front of the 18 seed words is also selected when selecting all 18 words.

**Comment by nikolaglumac** [comment]
Paper wallet feature has been discontinued. Closing this issue...
