### ISSUE TITLE
cardano-node doesn't stop rescanning on wallet restore

### ISSUE THREAD

**Issue by rex4539** [input-output-hk/daedalus#1975]
Latest `develop` (flight) on macOS 10.15.5

Reproducibility: always

Steps:
Restore a wallet from a 12-word seed and wait till 100% rescanning is complete.

What happened:
The `cardano-node` process keeps using 200% CPU although rescanning has actually completed.

Expected result:
The `cardano-node` process uses minimal CPU as soon as rescanning is completed.

Notes:
When quitting the wallet and restarting it, all is good and `cardano-node` uses minimal CPU.

**Comment by nikolaglumac** [comment]
Hi @rex4539!
Thank you for the report. This is a known issue and the team is working on a fix.
Thank you for your patience!

**Comment by nikolaglumac** [comment]
This issue has been fixed a while back. Closing this issue...
