### ISSUE TITLE
Build Issue - Unable to Download Specific NixOS Cache

### ISSUE THREAD

**Issue by breadsax** [input-output-hk/daedalus#2000]
I'm building on Mac OS and get the following error when running the build script for unix:

trace: [hscolour-plan-to-nix-pkgs] cabal new-configure --with-ghc=ghc --with-ghc-pkg=ghc-pkg
warning: unable to download 'https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo': SSL peer certificate or SSH remote key was not OK (60); retrying in 282 ms
warning: unable to download 'https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo': SSL peer certificate or SSH remote key was not OK (60); retrying in 571 ms
warning: unable to download 'https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo': SSL peer certificate or SSH remote key was not OK (60); retrying in 1337 ms
warning: unable to download 'https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo': SSL peer certificate or SSH remote key was not OK (60); retrying in 2026 ms
error: unable to download 'https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo': SSL peer certificate or SSH remote key was not OK (60)

Any help is appreciated. Thank you.

**Comment by breadsax** [comment]
I also tried to run 

sudo curl --insecure https://cache.nixos.org/1h3ziqmll0vpg82431arai1ji6da9g5a.narinfo

but I receive a 404 error.

Is the URL broken?

**Comment by nikolaglumac** [comment]
@disassembler @cleverca22 can you please help us out here?

**Comment by nikolaglumac** [comment]
@breadsax please follow instructions listed in Daedalus README: https://github.com/input-output-hk/daedalus/blob/develop/README.md
You need to set up [Nix](https://github.com/input-output-hk/daedalus/blob/develop/README.md#nix) and then use yarn commands to start Daedalus for desired network: https://github.com/input-output-hk/daedalus/blob/develop/README.md#development
