### ISSUE TITLE
Node is not syncing

### ISSUE THREAD

**Issue by rex4539** [input-output-hk/daedalus#2007]
See attached logs below.

**Comment by nikolaglumac** [comment]
@rex4539 can you please provide full logs?

**Comment by rex4539** [comment]
[Logs.zip](https://github.com/input-output-hk/daedalus/files/4582140/Logs.zip)

**Comment by rex4539** [comment]
Logs attached.

**Comment by disassembler** [comment]
You're unable to resolve our DNS name. This is usually related to one of the following:

1. a misconfigured DNS server on your machine
2. a misconfigured VPN
3. a misconfigured router
4. an ISP filtering traffic

There is nothing we can do from the perspective of the application or the network we maintain that can help you resolve this. I recommend checking DNS on your local machine and your router to try resolving `relays-new.cardano-mainnet.iohk.io`. You can use tools like `nslookup` and `dig` to troubleshoot further.
