### ISSUE TITLE
high cpu load mac os 10.13.6.

### ISSUE THREAD

**Issue by bahamasbahamas** [input-output-hk/daedalus#2013]
Hi,
I'm really happy that you support mac os 10.13.6. (mac 2011 :D,  8gb ram).
I've noticed that the wallet (daedalus 1.0.0) had an high cpu load on my machine. It synced but still %cpu was like 199%.  I closed the wallet and started again. After the restart the cpu load reads 3% and the machines runs smooth again. 
Cheers

**Comment by mertenvg** [comment]
+1
<img width="975" alt="Screenshot 2020-06-17 at 22 56 47" src="https://user-images.githubusercontent.com/2158243/84951574-e9d65980-b0f0-11ea-8d43-64104025bfc0.png">

**Comment by rhyslbw** [comment]
Resolved in https://github.com/input-output-hk/cardano-node/pull/986
