### ISSUE TITLE
[BUG] Inconsistencies in Daedalus (1.2.0-STN1) stake pool display on different Linux flavors

### ISSUE THREAD

**Issue by onyxstakepool** [input-output-hk/daedalus#2055]
The number of stake pools shown in Daedalus (1.2.0-STN1) is inconsistent on different Linux platforms.

See screenshot of Daedalus running on Ubuntu 20.04 with 105 stake pools shown.

![Daedalus-1 2 0-STN1](https://user-images.githubusercontent.com/58674131/86540290-567c9100-bf04-11ea-8082-1b398e0132be.png)
![Daedalus-1 2 0-STN1-Debug](https://user-images.githubusercontent.com/58674131/86540298-5f6d6280-bf04-11ea-8dce-82e136576f39.png)

**Comment by gitmachtl** [comment]
This was shown here for that exact same timeslot:
