### ISSUE TITLE
[FR] Show pool id in daedalus

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/daedalus#2059]
Due to scammers being able to register the same or similar tickers to legitimate pools, the end user needs to be able to see a pool id so they can verify that it is legitimate by comparing to other sources.

They need to be able to match the pool id to the pool id listed on a pool's website or telegram channels. Otherwise, we will just have scammers registering the same or similar ticker symbols to successful legitimate pools.

**Comment by AndrewWestberg** [comment]
Also, adding search by pool id would be helpful.

**Comment by bergr01** [comment]
I second the above requests, also I'm pretty sure Yoroi supported search by pool id (which is currently the only true unique identifier) already... 👍

**Comment by AndrewWestberg** [comment]
I'm pretty sure the pool id view has been implemented already. Not sure about the search capabilities.

**Comment by nikolaglumac** [comment]
This feature has been released in Daedalus Mainnet 3.1.0.
