### ISSUE TITLE
Cardano Explorer is not called with the correct URL

### ISSUE THREAD

**Issue by aticomismana** [input-output-hk/daedalus#2075]
The link to see the address or transaction ID on the Cardano Explorer website does not work; Cardano Explorer is called and displayed, but the address or transaction ID is not moved to it.

It is possible that the Cardano Explorer website has modified the embedding URL and Daedalus Mainnet 1.1.0#12849 has an older embedding URL format.

**Comment by nikolaglumac** [comment]
This has been fixed a while ago.
Thanks for reporting!
