### ISSUE TITLE
Invalid wallet password after recovery

### ISSUE THREAD

**Issue by cyberbudy** [input-output-hk/daedalus#2076]
After successful restoring wallet from secret.key file I cannot send any transaction because Daedalus Flight shows that wallet password is incorrect.
I'm sure that password is correct because it was used just before the released update when my cardano-sl node stopped working. I have logs that used spending password to send transactions right before.
Is there anything I can do to find out the problem?

**Comment by clovehitch** [comment]
How did you restore from the secret.key file?

**Comment by nikolaglumac** [comment]
Please wait for the import feature to be enabled again and then try importing from secret.key once more.
There is no clear ETA but, as soon as there is one, it will be posted here: https://github.com/input-output-hk/daedalus/issues/1234
