### ISSUE TITLE
[enhancement/ui/ux issue] Clicking on current pool, shows 'delegate to this pool'

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/daedalus#2088]
when i go to > Stake Pools > click on the pool i am currently delegating to - in the popup the button says 'delegate to this pool'. this seems a bit confusing, as I already am delegating to it.

**Comment by darko-mijic** [comment]
You could have multiple wallets delegated to different pools. This button launches the delegation wizard where you can select a wallet and a different pool. I agree it is not ideal in all cases. We will see how we can improve this. Thanks for the report.
