### ISSUE TITLE
Stops syncing if you turn wifi off and back on

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/daedalus#2089]
My Daeadalus on OSX stops syncing if i turn off my wifi and then back on again.
It will onyl restart syncing if i shut it down and restart
v 1.5.1 STN 4

**Comment by nikolaglumac** [comment]
@willcbanks is this still the case?

**Comment by nikolaglumac** [comment]
@gnpf @ManusMcCole @mioriohk can you confirm this behavior?

**Comment by gnpf** [comment]
@nikolaglumac I couldn't reproduce this on macOS Catalina, Daedalus 3.2.0. The syncing restarts after the wifi is connected again.

**Comment by nikolaglumac** [comment]
Thanks @gnpf - I guess this issue has been fixed in the recent releases. 
Closing this issue now...
