### ISSUE TITLE
DAEDALUS1.6.0-STN5 - not possible transfer/delegate ITN rewards

### ISSUE THREAD

**Issue by drastys** [input-output-hk/daedalus#2092]
Hello,
I recovered ITN staking addr created on Yoroi and balance is correct.
I tried delegate this amount and it looks that it is not able to calculate TX Fee and if you want to send funds from this wallet so it is not possible at all, if you put Receiver addr to correct field and put correct password so not possible to click to any button.

Bye, DOLCA

**Comment by lunarpool** [comment]
Same for ITN pool rewards

![image](https://user-images.githubusercontent.com/58665645/88488584-70067b00-cf8e-11ea-86e9-24d9bbc2f517.png)

**Comment by darko-mijic** [comment]
This is listed in the known issues. This only affects wallets which have only rewards. It will not be an issue on the mainnet since we will have a dedicated ITN rewards redemption feature. Which pays the fees for transferring rewards from the destination wallet.

**Comment by darko-mijic** [comment]
Add some UTXO funds to this wallet and try again.

**Comment by darko-mijic** [comment]
![image](https://user-images.githubusercontent.com/4280521/88488639-dc817a00-cf8e-11ea-81b3-4271c35311fa.png)
