### ISSUE TITLE
Pools destined for imminent retirement should be shown further down the Stake Pool list in Daedalus

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/daedalus#2102]
Using Daedalus 1.6.0-STN5#13825

The other day I saw a pool that was 'Retirement in 5 hours' shown in the top 20 list of rankings. If someone were to delegate to that pool at that point in time, they're essentially guaranteeing no rewards (because by the time their delegation comes into effect, the pool will no longer be there, so they'll be left with a dangling delegation).

IMHO it would be worthwhile to move all the due-for-retirement pools to the bottom of the list, perhaps the ones with most imminent retirement being absolute last?

**Comment by glitch40** [comment]
Additionally, The option to delegate to a retiring pool should not be allowed in the wallet, after a pool has been set to retire to avoid complication / confusion.

**Comment by darko-mijic** [comment]
Thanks for the feedback.

Retirement is not part of the ranking calculation. But we discourage users to delegate to retiring pools.
We will probably have a filter which will hide retiring pools and will be on by default soon.

We should also disable delegating to pools which will retire before they can get you any rewards.

![image](https://user-images.githubusercontent.com/4280521/88626687-5149d680-d0ab-11ea-998f-0c427651b791.png)

**Comment by hodlonaut** [comment]
Still waiting for 'We will probably have a filter which will hide retiring pools and will be on by default soon.', @darko-mijic
