### ISSUE TITLE
Delegation center references Shelley Testnet

### ISSUE THREAD

**Issue by bbhart** [input-output-hk/daedalus#2112]
![image](https://user-images.githubusercontent.com/474498/88870645-e51ebe00-d1e3-11ea-998f-990fcae26881.png)

Can be confusing since user is on mainnet.

**Comment by nikolaglumac** [comment]
Hello @bbhart!
Thank you for this bug report. This issue will be fixed with the next Daedalus release.

**Comment by nikolaglumac** [comment]
@bbhart fixed in https://github.com/input-output-hk/daedalus/pull/2125 and is to be released with the next Daedalus version.
