### ISSUE TITLE
error: cannot figure out user name

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/daedalus#2115]
Ubutnu 18.04.03
Daedalus 2.0.0

started with: ./daedalus-2.0.0-mainnet-13980.bin
during installation at 99% I got the following error:
error: cannot figure out user name

**Comment by nikolaglumac** [comment]
@alan-mcnicholas can you please assist us here?

**Comment by laplasz** [comment]
Yes, what should I provide?

**Comment by nikolaglumac** [comment]
Nothing further for now @laplasz.

@disassembler @cleverca22 perhaps you could help us out here too?

**Comment by cleverca22** [comment]
what user did you run the command as?
can you paste more logs from the command?

**Comment by laplasz** [comment]
the problem is that now it is working... how can I do a fresh install? what should I remove /tmp/tmpxXXX folder and what else?

**Comment by cleverca22** [comment]
you would also have to `rm -rf ~/.daedalus/` to remove all of the binaries

**Comment by nikolaglumac** [comment]
@laplasz can we close this issue?

**Comment by laplasz** [comment]
@nikolaglumac - yes

**Comment by jcortes** [comment]
Hello everyone. I did follow de instructions here:
1. https://daedaluswallet.io/en/download/#modal=download_pgp_instructions_linux 
2. https://iohk.zendesk.com/hc/en-us/articles/900000776446

But I'm getting the same error using Ubutnu 20.04.2 LTS:
```
$ ./daedalus-3.3.0-mainnet-16556.bin 
SSE4 check pass
inside installer
source /nix/store/hck9pm5f5arp4sqyq13vpnp1k7bl40sl-tarball/tarball/tarball.tar.xz
mkdir: created directory '/home/<username>/.daedalus'
 344MiB 0:01:24 [4.10MiB/s] [===================================================================================================================================================>  ] 99%            
error: cannot figure out user name
```
Any clue on what can I do to solve the issue in this case?
Thanks in advance!

**Comment by nikolaglumac** [comment]
Did you follow all these steps? https://iohk.zendesk.com/hc/en-us/articles/900000776446-Installing-Daedalus-Mainnet-on-Linux-

**Comment by jcortes** [comment]
Yes I even ran the commands in the **note** section but nothing!

**Comment by laplasz** [comment]
i tired again and still failing:
can we re-open this?
```
$ ./daedalus-3.3.1-mainnet-16693.bin 
SSE4 check pass
inside installer
source /nix/store/23pg4v95x22878h4vr25ibdk1k418b3c-tarball/tarball/tarball.tar.xz
 345MiB 0:00:25 [13.7MiB/s] [=============================================================================================================================================>  ] 99%            
error: cannot figure out user name
```
