### ISSUE TITLE
Daedalus charges higher fee than advertised for delegation

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/daedalus#2116]
I restored a Byron wallet in mainnet Daedalus, it did not consolidated the UTxOs during migration  and when I delegated my stake to stake-pool, it charged me higher than advertised fee... 

You can see [the transaction in the explorer](https://explorer.cardano.org/en/transaction?id=e92c3c19fbdf64fc402ffdcf62383d1862b448d8301bcd8528e7c4e0cbfeca0e), the advertised fee was less than 0.2 ADA while the actually "deducted fee" is over 2 ADA... 2 ADA just disappeared... 

The total amount input != output + fees...

**Daedalus version**: 2.0.0
**Daedalus build number**: 13980
**Cardano node version**: 1.18.0
**Cardano wallet version**: 2020.7.28

.

**Comment by mark-stopka** [comment]
Also I noticed the fees changing when I try to consolidate by sending the coins... I have no UTxO < 1 ADA that could imply change of fees by simply changing the amount by 0.2 ADA...

![image](https://user-images.githubusercontent.com/18139116/88960443-ca138300-d2a3-11ea-9983-0a4385b4dcd1.png)
![image](https://user-images.githubusercontent.com/18139116/88960460-ced83700-d2a3-11ea-9553-41c073c6312f.png)

**Comment by mark-stopka** [comment]
See https://github.com/input-output-hk/cardano-node/issues/1601

**Comment by Zizaerion** [comment]
That extra 2 ada is the cost to register that wallet as a staking wallet.  It's set by the protocol.

**Comment by mark-stopka** [comment]
@Zizaerion then it should be part of the UI / UX design, not a "after the fact surprise" in both the wallet UI and exploerer UI...

**Comment by nikolaglumac** [comment]
Thanks for the report @mark-stopka!
As @Zizaerion pointed out this is expected - the extra 2 ADA is actually a deposit taken out of your wallet when registering your wallet's delegation key on-chain which happens only the first time you delegate.

**Comment by mark-stopka** [comment]
> Thanks for the report @mark-stopka!
> As @Zizaerion pointed out this is expected - the extra 2 ADA is actually a deposit taken out of your wallet when registering your wallet's delegation key on-chain which happens only the first time you delegate.

It certainly not expected to not be informed about in in both Daedalus and Explorer. Is the UI / UX going to be addressed? People are asking about that a lot.

**Comment by nikolaglumac** [comment]
No ADA is lost. First delegation includes 2 ADA deposit (the cost of storing your delgation certificate on the blockchain) that you get back once you undelegate.
The deposit amount will soon be displayed within the "Delegation Wizard" and within transaction details.

**Comment by nikolaglumac** [comment]
@mark-stopka this issue has been resolved in: https://github.com/input-output-hk/daedalus/pull/2339
We will have it released in the next Daedalus version.
Thank you for the patience!

**Comment by nikolaglumac** [comment]
The fix for this issue is now available in Daedalus Mainnet 3.3.0.
Please update your version of Daedalus either through the automatic update or manually by downloading the installer from: https://daedaluswallet.io/en/download/
Thank you for your patience!
