### ISSUE TITLE
Arch Linux Install Error | "error: creating directory '/nix/store': Permission denied"

### ISSUE THREAD

**Issue by wi-ski** [input-output-hk/daedalus#2118]
Hi there.

Encountered the following error:
```
$ yarn nix:mainnet    
yarn run v1.22.4
$ NETWORK=mainnet nix-shell --argstr nodeImplementation cardano --argstr cluster mainnet
error: creating directory '/nix/store': Permission denied
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When installing via: `yarn nix:mainnet`

This is a quasi-known issue for Arch: https://github.com/NixOS/nix/issues/879

:point_up: I haven't dug in very far. It appears I'm able to sidestep the _initial_ permission issue by a simple: `sudo chown $USER:$USER /nix`

I'm assuming this will hurt me sooner-rather-than-later.

Is this a known issue? Is there a recommended way for achieving the build in Arch?

Thank you for the time <3

**Comment by wi-ski** [comment]
Build failed - I'm closing this issue for now :broken_heart:

**Comment by nareto** [comment]
@wi-ski did you ever solve this? Stumbling in the same issue with the official `nix` archlinux package

**Comment by SmolPatches** [comment]
@nareto 
by changing the folder permissions to a non root user i was able to use nix from the official arch package.
```bash
sudo chown ${USER} /nix -R
```

**Comment by michalrus** [comment]
Hey, I think this is more an issue for ArchLinux, not Daedalus. Once you have your Nix setup working, you'll be able to enter the devshell.

Otherwise, the official builds don’t require Nix, it's only used for development.

**Comment by michalrus** [comment]
You could also maybe try the DeterminateSystems installer, it's good, though I haven't tried it on Arch:

https://github.com/DeterminateSystems/nix-installer
