### ISSUE TITLE
Shelley wallet restore feature is disabled on Daedalus2.0.0

### ISSUE THREAD

**Issue by namanChaturvedi** [input-output-hk/daedalus#2120]
Please refer screen shot. Daedalus wallet disabled the option to restore shelley wallet.
![daedalus error at restore](https://user-images.githubusercontent.com/19547444/89106667-a95d4180-d3f9-11ea-9e96-d92a42f3943a.PNG)

**Comment by MarcelKlammer** [comment]
That's hidden for as long as your Daedalus is not beyond the hard fork, I guess. So let it sync completely?

**Comment by nikolaglumac** [comment]
Hi @namanChaturvedi!
@MarcelKlammer is right - Daedalus needs to be synced beyond the point of the Shelley hard fork in order to display/enable Shelley features.
