### ISSUE TITLE
Lost Passwords to my Wallet (PLEASE HELP)

### ISSUE THREAD

**Issue by Dragovioon** [input-output-hk/daedalus#2123]
Can someone please help me. I recently moved and lost the codes for my Wallet (spending and seed) I found my old laptop and saw that the wallet is still running with all my Ada in display. I read about the secret files and import features in Daedalus also. Is there a way to use those files (secret.key or secret.key.code) to restore the wallet and change the spending password or to decode those files and find the password? Or will there be a feature for people in my situation in the future?

Please I really need help with this I am desperate.

If anyone can help I will pay them!

**Comment by nikolaglumac** [comment]
Sorry to hear that @Dragovioon :(

The import feature has been temporarily disabled in Daedalus 2.0.0 and will be re-enabled once the import tool is updated.
I don't have any ETA for that but I suggest you safely store the complete old Daedalus state directory (including the secret.key file) so that you can use it once the feature is made available again.

Thanks!

**Comment by Dragovioon** [comment]
> Sorry to hear that @Dragovioon :(
> 
> The import feature has been temporarily disabled in Daedalus 2.0.0 and will be re-enabled once the import tool is updated.
> I don't have any ETA for that but I suggest you safely store the complete old Daedalus state directory (including the secret.key file) so that you can use it once the feature is made available again.
> 
> Thanks!

But will in the future I be able to get my spending password back just to change my Ada to another wallet. I dont mind not being able to stake just want to get my investment back please

**Comment by nikolaglumac** [comment]
> But will in the future I be able to get my spending password back just to change my Ada to another wallet. I dont mind not being able to stake just want to get my investment back please

No. You still need to remember your spending password.

**Comment by Dragovioon** [comment]
> > But will in the future I be able to get my spending password back just to change my Ada to another wallet. I dont mind not being able to stake just want to get my investment back please
> 
> No. You still need to remember your spending password.

So I will never get my Ada back? Not even with the pc files? Not even in 20 years? That is sad. Should be a way to get back the codes even in crypto there should be a way. Sadly I lost everything I had because of this

**Comment by nikolaglumac** [comment]
@Dragovioon your secret key is encrypted on the hard drive using your spending password. You will not need the spending password to import the wallet into Daedalus but you will need it in order to move the funds. It is all described here: https://github.com/input-output-hk/daedalus/issues/1234#issuecomment-615855129
Please understand that there is no way for us to know what your password is - that is the purpose of it.
You will need to try to remember it / try different passwords you used in the past.

**Comment by Dragovioon** [comment]
Is there no program to decrypt the secret file? There should be a way. I
saw you mention in a post a program to let you open the file. Sorry but I
am just scared I will never get my Ada back

A segunda, 3 de ago de 2020, 11:37, Nikola Glumac <notifications@github.com>
escreveu:

**Comment by nikolaglumac** [comment]
> Is there no program to decrypt the secret file? There should be a way. I
saw you mention in a post a program to let you open the file. Sorry but I
am just scared I will never get my Ada back

@KtorZ @cleverca22 @disassembler do you know if this would be possible?

**Comment by Dragovioon** [comment]
Please if anyone knows of a way please help me I will pay for your help. I
just need my Ada back I tried every password I could remember and nothing.

A segunda, 3 de ago de 2020, 11:58, Nikola Glumac <notifications@github.com>
escreveu:

**Comment by KtorZ** [comment]
> Is there no program to decrypt the secret file

Not that we know of. That's the point of encryption. If it were possible we (and the entire Internet) would have serious issues. 
The only way to recover an encrypted private key is to find the passphrase. 

If you used a rather short / weak passphrase, you can always try brute-forcing it, it may takes a while yet if it was created through Daedalus which enforce already some level of security in passphrases, it may takes a lot longer.

**Comment by KtorZ** [comment]
side-note: I saw no mention of the recovery-phrase on this thread but, if you do remember your recovery phrase, then you can always restore from it and choose a new encryption passphrase.

**Comment by nikolaglumac** [comment]
Thank you @KtorZ!
Closing this issue while hoping @Dragovioon will remember either his recovery phrase or his spending password 🙏
