### ISSUE TITLE
Not possible to restore Shelley wallet in Linux Wallet

### ISSUE THREAD

**Issue by PeaStew** [input-output-hk/daedalus#2127]
This may have been addressed but I didn't see it anywhere ;listed as a known issue. The option to restore a Shelley wallet in Linux (Ubuntu 20.04) is greyed out, in windows version this is possible.

Windows:
![image](https://user-images.githubusercontent.com/34198053/89229110-20a0fa00-d5e1-11ea-8e5c-1e928f5b76eb.png)

Linux:
![image](https://user-images.githubusercontent.com/34198053/89229159-36aeba80-d5e1-11ea-924f-a9e540f863a9.png)

Any ideas?

**Comment by darko-mijic** [comment]
@PeaStew, I suppose you are not fully synced? You need to be synced to the epoch when Shelley was activated.

**Comment by PeaStew** [comment]
Ah, yes, that'll do it 👍
