### ISSUE TITLE
[2.0.1] Stake pool search box

### ISSUE THREAD

**Issue by willcbanks** [input-output-hk/daedalus#2129]
On OSX, there is a very annoying delay/freeze when typing into the search box.
I have experienced this on other dynamic searches on certain websites before too.
The problem, is that the program is updating it's search every time you press a key, so it starts as soon as you type a letter, then when you type the next letter it searches again etc etc. I'm not sure why this would cause it to go so slow and freeze, but it does.
I would imagine that using some sort of cache to store all the pool names in would fix it.
i.e. instead of querying the whole database, it could use either some kind of index on the names.
I am using it a very high spec mac, but when i search it feels like i am using a machine with no ram.
Also wht happens, is - if i just type at a constant speed - s h i v a for example - only the first 2 letters will appear in thebox and it will just freeze up searching for only 'sh' and the last letters i typed wont even appear.!
this should be an easy fix.

**Comment by MarcelKlammer** [comment]
Same here. A 700 entry list is too much to be filtered and animated all the time.

Starting to update/animate the list after the third key stroke or with a delay of 0.3 seconds after a key stroke might help here.

**Comment by matiwinnetou** [comment]
IMHO: searching on such a field should be debounced, time based debounced.

**Comment by willcbanks** [comment]
now it just freezes completely every time i search !

**Comment by willcbanks** [comment]
i type in a phrase - it finds the result and then nothing is clickable. everything frozen

**Comment by nikolaglumac** [comment]
Hi all! These performance issues have been fixed couple versions back. Please update to the latest version of Daedalus Mainnet.
Thanks!
