### ISSUE TITLE
[2.0.1] Concurrent processing of wallets

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/daedalus#2130]
I restored 25+ wallets in Daedalus when setting up our pools 5 days ago. Since then that Daedalus instance was closed.
Now it tries to get all wallets on tip at the same time, which 200% cardano-node CPU along with 50% cardano-wallet-shelley CPU.

Please limit actual the processing of wallets to 1 or 2 in parallel. For 25 wallets it takes 5 minutes to increase by 0.02% sync percent.

**Comment by MarcelKlammer** [comment]
It managed to sync. Now cardano-node takes 125% CPU to stay on tip for all wallets.

**Comment by nikolaglumac** [comment]
The cardano-node performance has been significantly improved since this issue was raised.
In case you are still seeing issues, please open a ticket on the cardano-node GitHub repo: http://github.com/input-output-hk/cardano-node
Thanks!
