### ISSUE TITLE
[2.0.1] Add indicator, that cardano-node socket is not available for fee calculation and transactions

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/daedalus#2132]
When you start up Daedalus, even when you only have 14 wallets restored, and even when the chain is almost on tip, the cardano-node needs some time to load/verify the DB and to update the wallets. The cardano-node socket is not available during that time and thus UI actions like trying to send ADA (calculating fee), will not work.

There is currently no indication, that Daedalus is still updating the wallets or that the socket is not available for any node actions.

Please add an indicator, that the user has to wait until the node (socket) is ready.

**Comment by nikolaglumac** [comment]
@MarcelKlammer are you still seeing this issue in the latest Daedalus Mainnet version?

**Comment by MarcelKlammer** [comment]
The wallet progress bar indicator is fine. People can now see, that the wallets are not ready yet. The cardano-node speed improved considerably in the past months, so it doesn't take too long. All good now.
