### ISSUE TITLE
Is it will provide the function to migrate 12-mnemonic 

### ISSUE THREAD

**Issue by bulingTang** [input-output-hk/daedalus#2134]
hi , will you provide the function to let 12-mnemonic  can transfer or a function migrate to shelley-net ? 
i canot found a method that can do it . and my ada can not move out , 
thank you

**Comment by darko-mijic** [comment]
You can restore your Byron wallet with 12-word recovery phrase:

![image](https://user-images.githubusercontent.com/4280521/89410137-78477e80-d723-11ea-8c51-fd4952ce7c09.png)

And Daedalus will guide you to transfer the funds to a Shelley wallet:

![image](https://user-images.githubusercontent.com/4280521/89410185-8c8b7b80-d723-11ea-88e5-990e36c19fda.png)

**Comment by bulingTang** [comment]
is there a mobile wallet to migrate it ?  and i must use daedalus to do it ?

**Comment by darko-mijic** [comment]
Only Daedalus supports legacy Byron wallets (with random key derivation) and there is no mobile client yet.
