### ISSUE TITLE
Stake shows "undelegated" label next to the wallet, after upgrade to version 2.0.1 (build 14017)

### ISSUE THREAD

**Issue by hedgehog34** [input-output-hk/daedalus#2137]
After upgrading Daedalus,  previously delegated stake shows as "undelegated" in delegation centre, and any attempt to redelegate to same pool, fails, since Continue button in step 2 stays disabled after reselecting same stake pool from list.

Expected behaviour - label to show state of staking as "delegated" or "delegated starting at epoch 210".

OS - Windows 10, (10.0.18363)
Daedalus is Connected and Synced

**Comment by nikolaglumac** [comment]
Delegation center has been significantly improved in the last Daedalus Mainnet release 3.2.0.
This issue should no longer be happening...
