### ISSUE TITLE
Daedalus does not run on non-SSE4 CPUs

### ISSUE THREAD

**Issue by eyelash** [input-output-hk/daedalus#2156]
When trying to run Daedalus on Ubuntu 20.04 I get the following error message
```
ERROR: your cpu lacks SSE4 support, cardano will not work
```
and Daedalus does not start. Please consider supporting Daedalus on non-SSE4 CPUs.

**Comment by mark-stopka** [comment]
If it's even possible to build `cardano-node` without SSE4 support, it would require at least attaching both SSE4 and non-SSE4 compatible bineries as I would expect the performance impact of non-SSE4 node would be significant.

**Comment by nikolaglumac** [comment]
Closing this ticket as there are no plans to add support for non-SSE4 CPUs.
