### ISSUE TITLE
Font issue: The number "1" and the letter "l" look too similar. 

### ISSUE THREAD

**Issue by cchansenn** [input-output-hk/daedalus#2159]
In Daedalus 2.1.0 the font used for wallet addresses makes the number "1" and the letter "l" look very similar. 

Here is a screenshot. The only difference is that the top of the number 1 bends down to the left, whereas the L is horizontal. 

<img width="423" alt="Screen Shot 2020-08-18 at 12 07 15 PM" src="https://user-images.githubusercontent.com/69870219/90555175-cf9a1580-e14b-11ea-8e08-2809fcbf79eb.png">

**Comment by nikolaglumac** [comment]
Even though these characters look similar, I doubt that anyone will be typing the addresses directly.
You should use copy&paste options for that.
