### ISSUE TITLE
Daedalus restore -> ADA Coins

### ISSUE THREAD

**Issue by arturtessaro** [input-output-hk/daedalus#2161]
Hi, I used to have daedalus 0.15 version, and when the 2.0 version was launched my daedalus 0.15 stopped working and when i try to access in the new version, don't work, shows that i have 0 Ada. I want to know if there is any way I can restore my wallet using a backup file from the old version. Thanks

**Comment by srdjan** [comment]
same here (although my version migration was 0.14 -> 0.2.1) 

I think you want to follow this issue:
https://github.com/input-output-hk/daedalus/issues/1234

**Comment by arturtessaro** [comment]
it worked for you? I tried here but didn't work

**Comment by srdjan** [comment]
no, we have to wait for the 'Import' feature (right now disabled)

**Comment by nikolaglumac** [comment]
Closing this issue as it is a duplicate of https://github.com/input-output-hk/daedalus/issues/1234
