### ISSUE TITLE
Copy Daedalus Mainnet chain history to Daedalus Flight

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/daedalus#2163]
When user has already Daedalus Mainnet installed, it would be nice if Daedalus Flight would be able to detect it and had an ability to copy Daedalus Mainnet `chain` directory to Daedalus Flight so that the Daedalus Flighs does not initially have to download the entire chain history from network nodes again.

Perhaps article in a knowledge base (with a link to in on the initial sync screen) article would suffice...

**Comment by matiwinnetou** [comment]
-1

**Comment by nikolaglumac** [comment]
@mark-stopka thanks for bringing this up!
Here's the support portal article which contains the requested info: https://iohk.zendesk.com/hc/en-us/articles/900004403866
