### ISSUE TITLE
After restoring the 12-size byron legacy wallet, the ada cannot be move to the shelley wallet, it is bug? Vesion:Daedalus Mainnet (2.1.0#14079)

### ISSUE THREAD

**Issue by Jack-Jhon** [input-output-hk/daedalus#2164]
![ip](https://user-images.githubusercontent.com/14866109/90859536-fca02f80-e3ba-11ea-8b4e-dc0103305531.png)

view log ：
Recv MsgRejectTx (HardForkApplyTxErrFromEra S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash "6cda5f3841e0926fbd7b2008e56890b76dba49855ff7bed3e5b15f2b",KeyHash "849a4dd754f308d5edf3ffdfcb11a6e5c88fbd42bb7ef614035d47a6"]))))]})))

complete log==>

Send MsgSubmitTx (HardForkGenTx {getHardForkGenTx = S (Z Tx' {_body' = TxBody' {_inputs' = fromList [TxInCompact (TxId {_unTxId = "74c3e72ddc2c377761c0312c248056237577c4f27619d0de6cc57fb2db837a6f"}) 0,TxInCompact (TxId {_unTxId = "d4c27bc8c82983826814f87de7c67c7d73f2fa5b584611fdc1cba21a7d672542"}) 0,TxInCompact (TxId {_unTxId = "f0e8b6f7b208f1f13c1481ab0a3a7469e2a764d83d0b5b9667357307fec686c3"}) 0], _outputs' = StrictSeq {getSeq = fromList [TxOutCompact "\SOH\236\249\169p{\186wj\NAK\STXn\211\bAHd^\US\244\"a\231{\156\ENQ]BW\152\159\128sVO\233 \159O\242'\216\242\201;\165\140\ETX\145\148\ETB\179b)\148\SYN\198" 1575996]}, _certs' = StrictSeq {getSeq = fromList []}, _wdrls' = Wdrl {unWdrl = fromList []}, _txfee' = Coin 187105, _ttl' = SlotNo {unSlotNo = 6431300}, _txUpdate' = SNothing, _mdHash' = SNothing, bodyBytes = "\164\NUL\131\130X t\195\231-\220,7wa\192\&1,$\128V#uw\196\242v\EM\208\222l\197\DEL\178\219\131zo\NUL\130X \212\194{\200\200)\131\130h\DC4\248}\231\198|}s\242\250[XF\DC1\253\193\203\162\SUB}g%B\NUL\130X \240\232\182\247\178\b\241\241<\DC4\129\171\n:ti\226\167d\216=\v[\150g5s\a\254\198\134\195\NUL\SOH\129\130X9\SOH\236\249\169p{\186wj\NAK\STXn\211\bAHd^\US\244\"a\231{\156\ENQ]BW\152\159\128sVO\233 \159O\242'\216\242\201;\165\140\ETX\145\148\ETB\179b)\148\SYN\198\SUB\NUL\CAN\f<\STX\SUB\NUL\STX\218\225\ETX\SUB\NULb\"D", extraSize = 180}, _witnessSet' = WitnessSet' {addrWits' = fromList [], msigWits' = fromList [], bootWits' = fromList [BootstrapWitness' {bwKey' = VKey (VerKeyEd25519DSIGN (PublicKey "\132\164\231*\DEL\155\161d\249\191\177\181>U \179\156yM\DEL,\224\172W\186\230]\157\236\209u\158")), bwSig' = SignedDSIGN (SigEd25519DSIGN (Signature "(\133\&8\ENQ\158@1\178\150\vB\EMh\NAK\240\NAK\210\227\180\146\DC4\200\184\170.K&\132t\140\180\246\208\ENQo\141\239\231\149\237p{\DLE61NaTg\209m!%_\NAK\138z\r\203\192\187\229\&0\NUL")), bwChainCode' = ChainCode "Z.\170\187n6f\249Q\198S\EM\178\213\246l\229\252e\n|\195\FS,u<9\171\216\&9T\214", bwAttributes' = "\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\177\184\&4!\191E\248\136\&7\149\154]\ACK\236/\167\DLE\129", bwBytes = "\132X \132\164\231*\DEL\155\161d\249\191\177\181>U \179\156yM\DEL,\224\172W\186\230]\157\236\209u\158X@(\133\&8\ENQ\158@1\178\150\vB\EMh\NAK\240\NAK\210\227\180\146\DC4\200\184\170.K&\132t\140\180\246\208\ENQo\141\239\231\149\237p{\DLE61NaTg\209m!%_\NAK\138z\r\203\192\187\229\&0\NULX Z.\170\187n6f\249Q\198S\EM\178\213\246l\229\252e\n|\195\FS,u<9\171\216\&9T\214X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\177\184\&4!\191E\248\136\&7\149\154]\ACK\236/\167\DLE\129"},BootstrapWitness' {bwKey' = VKey (VerKeyEd25519DSIGN (PublicKey "\130C\252\136h\250\ETB,(\166cM\168\&9\SO\SUB-S\158\209\DC3D 2DA\168\173\US\\\157\159")), bwSig' = SignedDSIGN (SigEd25519DSIGN (Signature "\GS\ESC\149K\175s\140\DC3\ESC\199n\SUBz\220cEj\v\246\219\188\164\208\165Z\252\FSx\134\202\218\STXc\131\158\224\CAN<\217\DEL\ENQ\247\&87\f bA\248\198\153<\229\ENQ\242 x\248\ESC\248\245e#\b")), bwChainCode' = ChainCode "\188\247 \139\252\166\250\243\160\ACK}\r\180\240\177.\206(\223\ETX8\150\169\185B\GS\143\225\227\249W\203", bwAttributes' = "\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\179\184]\229O\200\213\153\210-+\"!|\GS.3\234", bwBytes = "\132X \130C\252\136h\250\ETB,(\166cM\168\&9\SO\SUB-S\158\209\DC3D 2DA\168\173\US\\\157\159X@\GS\ESC\149K\175s\140\DC3\ESC\199n\SUBz\220cEj\v\246\219\188\164\208\165Z\252\FSx\134\202\218\STXc\131\158\224\CAN<\217\DEL\ENQ\247\&87\f bA\248\198\153<\229\ENQ\242 x\248\ESC\248\245e#\bX \188\247 \139\252\166\250\243\160\ACK}\r\180\240\177.\206(\223\ETX8\150\169\185B\GS\143\225\227\249W\203X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\179\184]\229O\200\213\153\210-+\"!|\GS.3\234"}], txWitsBytes = "\161\STX\130\132X \132\164\231*\DEL\155\161d\249\191\177\181>U \179\156yM\DEL,\224\172W\186\230]\157\236\209u\158X@(\133\&8\ENQ\158@1\178\150\vB\EMh\NAK\240\NAK\210\227\180\146\DC4\200\184\170.K&\132t\140\180\246\208\ENQo\141\239\231\149\237p{\DLE61NaTg\209m!%_\NAK\138z\r\203\192\187\229\&0\NULX Z.\170\187n6f\249Q\198S\EM\178\213\246l\229\252e\n|\195\FS,u<9\171\216\&9T\214X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\177\184\&4!\191E\248\136\&7\149\154]\ACK\236/\167\DLE\129\132X \130C\252\136h\250\ETB,(\166cM\168\&9\SO\SUB-S\158\209\DC3D 2DA\168\173\US\\\157\159X@\GS\ESC\149K\175s\140\DC3\ESC\199n\SUBz\220cEj\v\246\219\188\164\208\165Z\252\FSx\134\202\218\STXc\131\158\224\CAN<\217\DEL\ENQ\247\&87\f bA\248\198\153<\229\ENQ\242 x\248\ESC\248\245e#\bX \188\247 \139\252\166\250\243\160\ACK}\r\180\240\177.\206(\223\ETX8\150\169\185B\GS\143\225\227\249W\203X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\179\184]\229O\200\213\153\210-+\"!|\GS.3\234"}, _metadata' = SNothing, txFullBytes = "\131\164\NUL\131\130X t\195\231-\220,7wa\192\&1,$\128V#uw\196\242v\EM\208\222l\197\DEL\178\219\131zo\NUL\130X \212\194{\200\200)\131\130h\DC4\248}\231\198|}s\242\250[XF\DC1\253\193\203\162\SUB}g%B\NUL\130X \240\232\182\247\178\b\241\241<\DC4\129\171\n:ti\226\167d\216=\v[\150g5s\a\254\198\134\195\NUL\SOH\129\130X9\SOH\236\249\169p{\186wj\NAK\STXn\211\bAHd^\US\244\"a\231{\156\ENQ]BW\152\159\128sVO\233 \159O\242'\216\242\201;\165\140\ETX\145\148\ETB\179b)\148\SYN\198\SUB\NUL\CAN\f<\STX\SUB\NUL\STX\218\225\ETX\SUB\NULb\"D\161\STX\130\132X \132\164\231*\DEL\155\161d\249\191\177\181>U \179\156yM\DEL,\224\172W\186\230]\157\236\209u\158X@(\133\&8\ENQ\158@1\178\150\vB\EMh\NAK\240\NAK\210\227\180\146\DC4\200\184\170.K&\132t\140\180\246\208\ENQo\141\239\231\149\237p{\DLE61NaTg\209m!%_\NAK\138z\r\203\192\187\229\&0\NULX Z.\170\187n6f\249Q\198S\EM\178\213\246l\229\252e\n|\195\FS,u<9\171\216\&9T\214X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\177\184\&4!\191E\248\136\&7\149\154]\ACK\236/\167\DLE\129\132X \130C\252\136h\250\ETB,(\166cM\168\&9\SO\SUB-S\158\209\DC3D 2DA\168\173\US\\\157\159X@\GS\ESC\149K\175s\140\DC3\ESC\199n\SUBz\220cEj\v\246\219\188\164\208\165Z\252\FSx\134\202\218\STXc\131\158\224\CAN<\217\DEL\ENQ\247\&87\f bA\248\198\153<\229\ENQ\242 x\248\ESC\248\245e#\bX \188\247 \139\252\166\250\243\160\ACK}\r\180\240\177.\206(\223\ETX8\150\169\185B\GS\143\225\227\249W\203X\"\161\SOHX\RSX\FS\159\235C\231\164a\255\240\GS\223\179\184]\229O\200\213\153\210-+\"!|\GS.3\234\246"})})
Recv MsgRejectTx (HardForkApplyTxErrFromEra S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash "6cda5f3841e0926fbd7b2008e56890b76dba49855ff7bed3e5b15f2b",KeyHash "849a4dd754f308d5edf3ffdfcb11a6e5c88fbd42bb7ef614035d47a6"]))))]})))

**Comment by melmccann** [comment]
Please also note the following when looking into this issue. 
https://github.com/input-output-hk/cardano-wallet/issues/2058

**Comment by nikolaglumac** [comment]
This is a cardano-wallet limitation. Please follow this thread: https://github.com/input-output-hk/cardano-wallet/issues/2058#issuecomment-753331796

**Comment by simonmichael** [comment]
I too had byron wallets. I transferred most of them last year with an older Daedalus. In current Daedalus 3.2.0, I can't transfer the last one - the UI for it is there, but after selecting the destination account it just shows the spinner for ever (?). If this is the same issue reported here, I don't think it should be closed.

**Comment by nikolaglumac** [comment]
I doubt this is the same issue but in order to help you, we need more info.
Please provide a screenshot of the error alongside a screenshot of the "UTXO distribution" screen of that Byron wallet. 
This one:
![Screenshot 2021-02-15 at 08 50 28](https://user-images.githubusercontent.com/376611/107919042-fe623e80-6f6a-11eb-98f4-b1dd2c303e52.png)
Having Daedalus logs (collected straight after you withness the error) would be very nice...

**Comment by simonmichael** [comment]
Well, as I prepared screenshots, today it just worked: after clicking Transfer funds button, instead of an unending spinner it immediately showed the spending password field, and the transfer worked normally. Not a very satisfactory report, but oh well. Thanks for your attention!

**Comment by nikolaglumac** [comment]
Glad that it worked! Cheers!
