### ISSUE TITLE
Separate currency from quantity in the csv export of rewards

### ISSUE THREAD

**Issue by iasinDev** [input-output-hk/daedalus#2170]
When opening csv in excel and converting it to columns, the column Reward contains quantity + currency symbol (ADA) which makes it difficult apply a direct autosum.

Also I think that if in the future we could have rewards in different coins it's better having them separated in different columns, also good for coin tracking softwares that could look directly for the currency in the currency column instead of parsing the content of a field.

**Comment by iasinDev** [comment]
I would try to make the fix but I've not found where it's created the export in the code

**Comment by nikolaglumac** [comment]
Hi @iasinDev!
The changes you requested have been implemented in https://github.com/input-output-hk/daedalus/pull/2451 and will be released in the next Daedalus version.
Thanks for the patience 🙏

**Comment by iasinDev** [comment]
wow, awesome! thank you!!

**Comment by nikolaglumac** [comment]
This has been implemented and released in scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience 🙏
