### ISSUE TITLE
Pool rankings do not factor in saturation and diminished rewards for oversaturation

### ISSUE THREAD

**Issue by safestak-keith** [input-output-hk/daedalus#2174]
**Current behaviour**

![image](https://user-images.githubusercontent.com/67933144/91857930-7e684680-ec60-11ea-8630-b06ae23cf020.png)

IOG1's oversaturated pool with 270,671,048 ₳ is showing as number 1 in the rankings list even though it will cause delegators to lose 22% of their rewards. The same applies to SWIM at number 3 resulting in a 4% loss in rewards to delegators. 

Seeing oversaturated pools at the top of the list with no additional UI warnings, the average delegator will generally always pick the top pools assuming that the system knows best. Even worse, the saturation can and will likely grow further in its current state.

**Expected behaviour** 

- Saturation is factored into the ranking of the pools with oversaturated pools appearing lower in the list
- UI indicator highlighting the negative effects of delegating to oversaturated pools.

**Comment by rdlrt** [comment]
Duplicate, perhaps consider closing and continuing [here](https://github.com/input-output-hk/cardano-wallet/issues/1980#issuecomment-683632938)

**Comment by Anviking** [comment]
> Duplicate, perhaps consider closing and continuing

Although the discussion is relevant, the issue https://github.com/input-output-hk/cardano-wallet/issues/1980 itself is completely unrelated. 

I suspect IOG1 will drop in ranking when its _active stake_ becomes more oversaturated. (I believe it is only slightly at the moment)

**Comment by MarcelKlammer** [comment]
IOG1 is 12% oversaturated in active stake. It should be listed way down. Instead it keeps filling up.

**Comment by safestak-keith** [comment]
> Duplicate, perhaps consider closing and continuing [here](https://github.com/input-output-hk/cardano-wallet/issues/1980#issuecomment-683632938)

Although [this](https://github.com/input-output-hk/cardano-ledger-specs/issues/1823) is a more relevant piece, IMHO a separate issue should be raised and tracked against Daedalus as a frontend component because it provides traceability up to the end-user experience, especially when it follows a different release cadence. 

> I suspect IOG1 will drop in ranking when its _active stake_ becomes more oversaturated. (I believe it is only slightly at the moment)

@Anviking Correct me if I am wrong but my understanding is that IOG's number 1 in ranking on Daedalus right now is taken from [cardano-wallet](https://github.com/input-output-hk/cardano-wallet/blob/406c35fdcbb53195517279cbcae3eb1c21aa2609/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L190) which is in turn based on desirability from the cardano-ledger-specs, with its calculation factoring in the **active** stake of 236.84m, the value retrieved as a snapshot from the previous epoch as opposed to a **live** value. With this in mind it wouldn't that mean potential delegators will keep flocking to highly ranked oversaturated pools until the end of this epoch? I can see that the number is still growing.

**Comment by cybershaman73** [comment]
I see it now, Section 5.6.1 of the Delegation Design Spec: "To determine a pool’s rank, we order pools by decreasing desirability. The most desirable pool gets rank 1, the second most desirable pool gets rank 2 and so on. We predict that pools with rank ≤ k will eventually be saturated, whereas pools with rank > k will lose all members and only consist of the owner(s)"

The design spec is predicting saturation of pools <= k. This is the problem with the wallet ranking, it's derived from a design spec that is failing to account for saturation so early in the Shelley genesis. If k is not increased soon, this prediction made by the algorithm being used by the wallet will come to pass and many pools needed for a larger value of k will have perished. That is unless of course existing SPOs in the top 150 pools just spin up new pools to offset outflow.

In addition, section 5.6.6 Apparent Performance of New Pools, is deriving its factor from what appears to be a moving average over too short a time frame to allow the smaller pools to be fairly ranked. Apparent performance = 1 was only set for two epochs. This may not be enough time to allow smaller pools to reach a rank of desirability that favorably influences a rising change in k parameter. The health of the network is at stake here. If the project believes that k = 150 will serve its goals then no changes are necessary. If project needs k = 1000, then we're in trouble with the way ranking is currently calculated.

**Comment by hodlonaut** [comment]
Daedalus (and other layers, wallet, node etc potentially) need live data about current stake as well as high level totals for the network (e.g. total circulating supply) in order to show useful information to end users... currently this is retrievable via ledger-state dump parsing and is done by sites like pooltool.io. Until that is addressed, it might as well show a 'Enter pool ID' field and have a link to pooltool.io in its UI...

**Comment by cybershaman73** [comment]
I see the problem now more clearly. Presently ranking is per design spec section 5.6.1. However, there's also an assumption made in section 5.9 that delegators will always have "ALL" of the information they need to make the best choice about their delegations. This is where Daedalus is failing delegators by allowing saturated pools to rank, in this case, #1. The Daedalus interface needs to have a way to provide the delegator information about the risks of diminishing rewards that come with delegation to saturated pools. In this way Daedalus is failing to follow design spec per 5.9. This needs to be corrected asap.

**Comment by cybershaman73** [comment]
Further more, per Section 4.3 of Design Specification for Delegation doc, it clearly states:

"Since this ordering depends not only on the costs and margin set by the stake pool operator, but also on the performance of the pool and on the amount of stake that it already has accumulated, this will promote pools that are reliable, have not yet reached saturation, and have a low cost and margin."

Daedalus Wallet Version 2.2.0#14276 is indeed failing to follow design spec by allowing pools that have reached saturation to be ranked highest in their Delegation Center.

**Comment by Klobbinger** [comment]
From what I can tell Daedalus uses the pool desirability from 5.6.1 in the design spec while it should be using the non-myopic member rewards from 5.6.4 Formula (3) to sort pools. Depending on the slider, which sets the amount a user intends to stake, Daedalus should calculate the excpected non-myopic member rewards for each pool and rank them from highest to lowest.

https://hydra.iohk.io/build/3744897/download/1/delegation_design_spec.pdf

**Comment by darko-mijic** [comment]
This is no longer the case. 

Stake pool rankings do take into account oversaturation and the intended amount of stake selected using the stake slider or the wallet dropdown next to the stake slider.
