### ISSUE TITLE
Notification from Wallet for Pool changes

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/daedalus#2179]
Throughout the delegation specifications, we have various citations of **wallet notifying users** for things like when a pool is deregistered or when pool parameters are changed (ofcourse, when they're next online). Daedalus is yet to see this feature.

**Comment by rdlrt** [comment]
@nikolaglumac - might be a typo in changelog referring to this issue? 🙂

**Comment by nikolaglumac** [comment]
You are right @rdlrt - the link should be pointing to https://github.com/input-output-hk/daedalus/pull/2177
Sorry for the false alarm!

**Comment by rdlrt** [comment]
Any updates on this one?
With nOpt about to increase, this feature being absent might come more into visibility (for folks who do rely on Daedalus and not use community tools for notification).

At the very least, until this feature is built by Daedalus, maybe you'd want to direct users to existing notifications systems (pooltool, ADAStat, cardanoscan, adapools all offer notifications via social media) - perhaps help adoption of good work further while doing so.

**Comment by nikolaglumac** [comment]
Hi @rdlrt,
We will have this feature ready before the k-parameter is increased.
Thank you for your patience!

**Comment by rdlrt** [comment]
Thanks @nikolaglumac , pleasantly surprised to know notification for pool changes will get in before 6th of December (date when k is to be increased), looking forward to it 🙂

**Comment by nikolaglumac** [comment]
This is an important feature and we can not allow our users to face 6th of December update without it :)
Thank you for your support!

**Comment by hodlonaut** [comment]
So, it's December 15th now - did this feature get implemented and rolled out, @nikolaglumac ?

**Comment by nikolaglumac** [comment]
Hi @hodlonaut,
We had a newsfeed announcement before the 6th of December but that was it...
We are still planning on how to deal with the tracking of stake pool saturation and ranking changes.
However, this is not a simple challenge since Daedalus is not constantly running.
Fear not, we will get there - we do understand the importance of this feature.
Thank you for your patience!

**Comment by hodlonaut** [comment]
This issue has nothing to do with saturation or ranking changes - it's about changes to the pool definition (e.g. fee raised, pledge lowered) and status (active -> retirement pending)...

**Comment by nikolaglumac** [comment]
Ranking and saturation changes are part of the issue alongside the other data you mentioned.

**Comment by rdlrt** [comment]
What is implemented (news feed) is absolutely not what we were hoping with `notification` mentioned in specs and the issue description. I was quite surprised to see that it was mentioned as viable for 6th December, apparently not without a reason 😢

Also, I see that this is _now_ being labelled as a `feature request`. Daedalus is a wallet that adheres to the delegation specs (giving it more importance than human sense). I just feel its a bit dishonest to label this as a feature request, when it is something that we should have expected from get go, even more so when changing `nOpt`

I am absolutely fine with this being a backlog item that you didn't have time to get to yet (as dependency or otherwise), but labelling this as feature request is really worrying if this becomes something like #605 which is now open for over 3 years

**Comment by nikolaglumac** [comment]
> What is implemented (news feed) is absolutely not what we were hoping with notification mentioned in specs and the issue description. 

Yes, I share the same view - this is why this ticket has not been closed. The feature is still to be implemented.

> Also, I see that this is now being labelled as a feature request. Daedalus is a wallet that adheres to the delegation specs (giving it more importance than human sense). I just feel its a bit dishonest to label this as a feature request, when it is something that we should have expected from get go, even more so when changing nOpt

The label plays no role in prioritization of this issue. We only have 3 labels for the user tickets: `bug`, `feature-request`, and `question`. Out of these 3, I find the `feature-request` to be the best match.

> I am absolutely fine with this being a backlog item that you didn't have time to get to yet (as dependency or otherwise), but labelling this as feature request is really worrying if this becomes something like #605 which is now open for over 3 years

I am sorry for the delays with #605. Please understand that we have limited resources and a lot of things to implement. We are doing the best we can to make everyone happy.

Thank you for your patience!

**Comment by hodlonaut** [comment]
Where are we at with regards to notifications in Daedalus front? Any progress made since the start of the year that is coming to mainnet?

**Comment by nikolaglumac** [comment]
Sorry to disappoint, but there is still no way for Daedalus to actively track pool changes. We can not collect historical data as we depend on the data we get while Daedalus is running. We might explore the idea of tracking those changes (AKA. between now and last time you ran Daedalus) but that's about it for now :-(
cc @daniloprates @alexander-rukin @mariusb

**Comment by rdlrt** [comment]
> This is an important feature and we can not allow our users to face 6th of December update without it :)

I feel horribly wrong to comment on how big a gap conceptually could be from above statement to where we are now (which got turned into generic vague news feed).

Regardless, as far as I am concerned, this issue can be closed, I didn't expect things to go any different when I commented last. It seems yhe issue is apparently not big enough as UI frontend glitter, besides - from tg support point of view, I am not attending any Ddz queries myself.
