### ISSUE TITLE
Full blockchain verification happens every time I open 2.3.0 RC

### ISSUE THREAD

**Issue by MagicMiikka** [input-output-hk/daedalus#2199]
OS affected: Mac and Windows

There seems to be a regression when upgrading 2.3.0-FC2 -> 2.3.0-RC
2.3.0-FC never had this issue for me and it only did the one time verification as documented.
When I updated flight and mainnet version to 2.3.0-RC it started happening on both versions.

**Comment by nikolaglumac** [comment]
@MagicMiikka how long does the verification last? What percentage does it start from?

**Comment by darko-mijic** [comment]
So it was completed but it is happening again every time? We have not seen this issue during the QA. Can you provide logs via a support portal ticket?

**Comment by nikolaglumac** [comment]
Quick verification is expected at every Daedalus start.

**Comment by MagicMiikka** [comment]
> @MagicMiikka how long does the verification last? What percentage does it start from?
it starts from 0% and takes about 15 minutes

> So it was completed but it is happening again every time? We have not seen this issue during the QA. Can you provide logs via a support portal ticket?
Yes, it was 100% completed. I'll drop the logs upon this current re-verification completing.

**Comment by darko-mijic** [comment]
>  I'll drop the logs upon this current re-verification completing.
Great. The Node team will take a look at logs right away.

**Comment by MagicMiikka** [comment]
Sent the logs. req #104318

On a more focused repro, I noted that the first restart the node was not syncing and I ended up restarting daedalus twice.
I added the same info on the ticket as well

1. Full validation
2. Restart Daedalus, node not responding
3. Restart Daedalus, full revalidation

**Comment by nikolaglumac** [comment]
Thanks @MagicMiikka! As @darko-mijic mentioned, we will have someone from the node team checking this out shortly.

**Comment by darko-mijic** [comment]
@MagicMiikka, looks like data corruption may be an issue:

> It’s most likely that the state is incorrect in some way (eg because some state has been written incorrectly to disk).  This could be a node issue or a hardware/OS issue. Deleting state and restarting would probably solve the problem for the user if so.  I would also advise the user to check the health of their disk using the OS facilities  (it may have a bad block, for example).  We will investigate to see whether there is a node issue, of course.

**Comment by MagicMiikka** [comment]
I ran a disk error check and deleted all but Flight and Mainnet states and then it magically started working. No longer facing this issue.
