### ISSUE TITLE
Wallets not removed when Daedalus is uninstalled on Windows

### ISSUE THREAD

**Issue by bbhart** [input-output-hk/daedalus#2226]
I uninstalled Daedalus last month so that my wallet wouldn't be sitting around on the file system. When I installed 2.4.0 today, it didn't prompt me for my recovery phrase. Instead, it found my wallet from before sitting on disk and used that. 

My expectation is that wallet and chain data would be removed when Daedalus is removed. I'll be mindful to delete my wallet next time, but you should be very clear with the user that the wallet will stay on disk.

**Before uninstall:**

![daedalus-before](https://user-images.githubusercontent.com/474498/97824945-4ba3f400-1c8b-11eb-80fa-3c0e6c4b5e9a.png)

**After uninstall:**

![daedalus-after](https://user-images.githubusercontent.com/474498/97824957-53639880-1c8b-11eb-940a-8da7b983011a.png)

**Comment by nikolaglumac** [comment]
@bbhart this is expected behavior. Please refer to: https://iohk.zendesk.com/hc/en-us/articles/900005345103
