### ISSUE TITLE
'Daedalus Mainnet' folder not removed from Start Menu when uninstalling Daedalus on Windows

### ISSUE THREAD

**Issue by bbhart** [input-output-hk/daedalus#2228]
Uninstall should remove: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Daedalus Mainnet

To reproduce:
1. Install Daedalus.
2. Note the Daedalus Mainnet folder in the Start Menu.
3. Uninstall Daedalus.
4. Folder still exists.

Microsoft Windows [Version 10.0.19041.572]

**Comment by nikolaglumac** [comment]
@gnpf @ManusMcCole @mioriohk please try to reproduce this issue. Thanks 🙏

**Comment by ManusMcCole** [comment]
I couldnt reproduce on Windows 10 version 10.0.18363. I will upgrade and try again

**Comment by nikolaglumac** [comment]
@bbhart are you still experiencing it?

**Comment by gnpf** [comment]
I can't reproduce this issue on Windows version 10.0.19041.488.
Check screenshots: [Before](https://drive.google.com/file/d/1buKZGXUeSUgJKWzarvUwci99sJTknbaG/view?usp=sharing) and [after](https://drive.google.com/file/d/15GlJUez9raFTW_usElQe4bOKIGOXAbDL/view?usp=sharing).

**Comment by mejia-b** [comment]
This issue still exists. I was able to reproduce it on Windows 11 with the latest Daedalus
