### ISSUE TITLE
Retiring pool issues

### ISSUE THREAD

**Issue by bergr01** [input-output-hk/daedalus#2229]
In Daedalus 2.4.0 the retirement indicator (red) seems to have been removed from the main pool listing, which is a bit odd - it should definitely be brought back instead of being moved to just the pop-up with pool details. 

Also pools that are scheduled for retirement should be moved towards the bottom of the pool list (probably on par with pools that aren't honouring pledge) since delegating to them would be non-sensical.

**Comment by darko-mijic** [comment]
@bergr01, thanks for your suggestions. We have taken them on board. 
Alos, we are implementing some filtering features which will not show retiring pools by default.
