### ISSUE TITLE
[Question] Is it safe to upgrade from 0.9.0 to 2.4.1?

### ISSUE THREAD

**Issue by dangfan** [input-output-hk/daedalus#2240]
I was using Daedalus 0.9.0 on Mac, but when I tried to launch it recently, it got stuck saying "connecting to network". So is it safe to upgrade to the latest version?

**Comment by nikolaglumac** [comment]
Hi @dangfan!
Daedalus Mainnet 2.4.1 is a different application and you can have both Daedalus 0.9.0 and the Daedalus Mainnet 2.4.1 installed in parallel. Once you install this newer version you will need to restore your Byron wallets using your 12-word recovery phrases for each of them.
Cheers!
