### ISSUE TITLE
copy / paste context menu 

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/daedalus#2248]
the right mouse context menu in the transaction history offers **copy** and **paste** options

Copy seems not working
Paste seems not useful on this position

![2020-11-24_12h33_07](https://user-images.githubusercontent.com/13198220/100088949-3a48a480-2e51-11eb-928c-0e6930a9bf83.png)

**Comment by nikolaglumac** [comment]
Thanks for the bug-report @gufmar - we will look into it next week.

**Comment by ManusMcCole** [comment]
Hi @nikolaglumac. I tested this against the 2.5.0 Release Branch build 15326 Testnet and I can confirm that what @gufmar reported is true. Copy does not work for To addresses and paste has no function in this context

**Comment by nikolaglumac** [comment]
@ManusMcCole what about other places? Can you copy and paste other selectable text?

**Comment by ManusMcCole** [comment]
@nikolaglumac.The Copy and Paste functionality is not working for From Addresses and also not for Transaction id

**Comment by nikolaglumac** [comment]
@ManusMcCole what about wallet balance?

**Comment by gnpf** [comment]
@nikolaglumac @gufmar @ManusMcCole I could reproduce this on edge cases (the text is not selected, or right click over the external link icon). Check the videos for: [balance screen](https://drive.google.com/file/d/1RRKZW0mt3jjwbeuU-Q1tij8c6ymDJH0B/view?usp=sharing), [balance screen unselected](https://drive.google.com/file/d/1e8osDQgKQOXlf79MXgP2WE6QcVvfgGGh/view?usp=sharing), [transaction screen](https://drive.google.com/file/d/1e1jOXb-dv0T2GU03QsArU6YqTwTvRK_f/view?usp=sharing), [settings screen](https://drive.google.com/file/d/1tfB2atT6eCRfJ6Zci6GLx9F22s5uL0nm/view?usp=sharing).

I think the "Copy" option should be disabled unless some text is clearly selected, as it's working for those scenarios. "Paste" option only seems relevant for **Settings - Name** and **Send-Receiver/Amount** inputs.

**Comment by nikolaglumac** [comment]
Thanks @gnpf!

We will work on this in our next sprint 🚀

**Comment by nikolaglumac** [comment]
Hi @gufmar!
This issue has been fixed in https://github.com/input-output-hk/daedalus/pull/2300 and will be released in next Daedalus version.
Thanks once again for reporting the issue and thank you for your patience!
Best,
N.

**Comment by nikolaglumac** [comment]
Hi @gufmar!
The fix for this issue has been released in Daedalus Mainnet 3.2.0.
Cheers!
