### ISSUE TITLE
[BUG]Unable to search WIRA Pool in newly installed version of Daedalus(2.4.1#15062)

### ISSUE THREAD

**Issue by projectwira** [input-output-hk/daedalus#2252]
**What version are we using?**

Daedalus:
    • Version: 2.4.1
    • Build Number: 15062
 
Cardano Node:
    • Version: 1.21.1

Cardano Wallet:
    • Version: 2020.10.13

**Does this issue reproduce with the latest release?**

Yes, it does

**What Operating System and Processor Architecture are we using?**

OS:			Microsoft Windows 10 Pro 
Platform Version:	10.0.91041
CPU: 			Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
RAM:			14.0 GB

OS:			Linux
Platform Version:	5.3.0-64-generic
CPU:			Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
RAM:			16.0GB

**What did we expect to see?**

When we search for “WIRA”, our pool name in the newly installed version of Daedalus(2.4.1#15062), we expect it to return all 10 pools of ours as shown below: 

![image](https://user-images.githubusercontent.com/75071168/100436078-d08efb80-30d9-11eb-894a-08691fd52b80.png)

**What did we see instead?**

But when we search for “WIRA” in the newly installed version of the Daedalus(2.4.1#15062), it returns 0 in the search result. All of our pools listed below is missing

WIRA, WIRA💎,WIRA🏆,WIRA🌏,  WIRA🌟, WIRA🌠,WIRA🌍, WIRA🌎, WIRA🔥, WIRA👑
![image](https://user-images.githubusercontent.com/75071168/100435738-5199c300-30d9-11eb-86c5-dcaa21fc069a.png)

**What did we do?**

Since we could not search for our pools in a newly installed version of the Daedalus(2.4.1#15062) wallet, we tried debugging the issue to narrow down the cause of the bug. 

(1) ANALYZED WIRA🔥 (F1) POOL METADATA HASH IN STAKE-POOLS.SQLITE

We searched for one of our pools WIRA🔥 (F1) at wallets/stake-pools.sqlite. In the "pool_registration" table's data. There are 4 records as shown in the screenshot taken below, indicating this pool's metadata was updated 4 times in the past. The record with the latest slot is pointing to the correct metadata hash. But as we can see the 3rd record in the table is pointing to an older metadata-hash. 

![image](https://user-images.githubusercontent.com/75071168/100436132-e7355280-30d9-11eb-866c-87ddcf26d8db.png)

(2) REPLACE WIRA🔥 (F1) POOL METADATA HASH IN STAKE-POOLS.SQLITE

However, when we replaced the 4th row METADATA HASH with the 3rd row data which consist of the OLD METADATA HASH  into the table, now the WIRA🔥 (F1) pool appears in the search bar.
![image](https://user-images.githubusercontent.com/75071168/100436144-ee5c6080-30d9-11eb-9952-662a3850e012.png)
![image](https://user-images.githubusercontent.com/75071168/100436153-f1575100-30d9-11eb-8e89-99d6bf02d289.png)

(3) RUN SMASH URL QUERY FOR BOTH OF THE METADATA HASH VALUE

We proceeded to run SMASH URL query with an OLD METADATA HASH value, smash replies with data.
URL QUERY: "https://smash.cardano-mainnet.iohk.io/api/v1/metadata/bee1c394dc9670ccaf70d1d73566e9d83c40311fd1a09f1742ab0bcb/4a731a82b5af6a1d47a454caf48dbbade5cb489349b7a1fd9e0e68fdef9cc05c" 

![image](https://user-images.githubusercontent.com/75071168/100436182-fae0b900-30d9-11eb-8c4b-b69aa3ad6f23.png)

But when we run SMASH URL query with the NEW METADATA HASH value, page can’t be found, shows up.
URL QUERY: "https://smash.cardano-mainnet.iohk.io/api/v1/metadata/bee1c394dc9670ccaf70d1d73566e9d83c40311fd1a09f1742ab0bcb/8e8216c920cee3ce0451145a5b80518cde4c50d628ff3ad46296b86930ccb141" 

![image](https://user-images.githubusercontent.com/75071168/100436199-ffa56d00-30d9-11eb-9b28-2e14c1dbb37d.png)

This could indicate an issue with SMASH.

**Summary**

    • All WIRA pools appear when searched on Daedalus(2.4.1#15062) installed before the 10th of November 2020, 
    • All WIRA pools do not appear when searched on newly installed Daedalus(2.4.1#15062)
    • Our pool can be searched on Yoroi, adapools.org and pooltool.io but not on a newly installed Daedalus(2.4.1#15062) client.
    • We were told it takes 2 epoch’s for SMASH to update the correct metadata when contacted IOHK support.
    • Our pool’s metadata was updated in epoch 229, however we are still not able to search for WIRA pools at Daedalus in epoch 232
      

**Conclusion**

We suspect that there may be an issue with SMASH.

**Comment by nikolaglumac** [comment]
@projectwira can you please check again? 
I get quite a few WIRA stake pools in the latest Daedalus Flight (and Daedalus Mainnet too):
<img width="1150" alt="Screenshot 2020-11-29 at 18 12 41" src="https://user-images.githubusercontent.com/376611/100548716-91de7a00-326e-11eb-86a7-c2233d8831e2.png">

**Comment by projectwira** [comment]
@nikolaglumac 

[Update on issue]

We've managed to get our WIRA pools to show up again in Daedalus.

Here's how we got our pools to show up:
-Reissued new pool certificate
-Changed pool description to generate new metadata hash
-Changed metadata hash URL

There seems to be a problem with SMASH when a pool submits pool metadata with the same metadata hash URL.

**Comment by nikolaglumac** [comment]
@projectwira this is not a Daedalus issue. Please raise all SMASH related issues on https://github.com/input-output-hk/smash
Closing this this ticket now...
