### ISSUE TITLE
Exporting rewards CSV causes Daedalus to crash

### ISSUE THREAD

**Issue by dustinf1989** [input-output-hk/daedalus#2255]
Everytime I tried to download the CSV file for my rewards statement, Daedalus crashes and the program closes. Anyone else have this problem? It has been happening forever for me, and I'm using the newest Daedalus version now on Ubuntu 18.04 LTS.

**Comment by NinjaPerson24119** [comment]
Same, also on Ubuntu 18.04 LTS.

Error from terminal:
```
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>

(electron:28086): GLib-GIO-ERROR **: 17:36:09.505: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
[launcher:Notice:11] [2020-11-28 01:36:09.53 UTC] Wallet exited with exitcode: ExitFailure (-5)
[launcher:Notice:11] [2020-11-28 01:36:09.53 UTC] Daedalus exited with ExitFailure -5, will shutdown cardano-launcher
```

**Comment by nikolaglumac** [comment]
Hi!
Unfortunately, this is a known issue on Ubuntu... We are working on a fix.
Will let you know once we have a fix ready.
Thank you for your patience!

**Comment by nikolaglumac** [comment]
This issue has been fixed and the fix will be released in the upcoming Daedalus Mainnet 3.3.0 release.
Thank you for the patience!

**Comment by nikolaglumac** [comment]
The fix for this issue is now available in Daedalus Mainnet 3.3.0.
Please update your version of Daedalus either through the automatic update or manually by downloading the installer from: https://daedaluswallet.io/en/download/
Thank you for your patience!

**Comment by dustinf1989** [comment]
Thanks, now a csv file actually comes out, but it only has one row with my
current rewards value.  Isn't it possible to get the entire rewards history
by epoch into csv format?

**Comment by nikolaglumac** [comment]
We do not get more than that from the cardano-wallet API and thus we can only show total ever earned rewards for every single wallet.
As soon as we get the data from the API we will enable our already built UI which will enable you to browse all your rewards historically and also to export all of them in the CSV.
This is the issue you can track for this feature request https://github.com/input-output-hk/daedalus/issues/2347
