### ISSUE TITLE
Ancient Daedalus 0.8.2 restoration

### ISSUE THREAD

**Issue by nitowa** [input-output-hk/daedalus#2256]
Hello!

So I've found myself in a bit of a pickle regarding my Cardano wallet. Long story short, I got some coins in 2017 and transfered them to my wallet. At the time this was Daedalus 0.8.2 (in Daedalus > About) which is of course very out of date. The version.txt in `Program Files/Daedalus` reports 1.0.3769.0, and file `version` says `v1.4.3`

Unfortunately the backup phrase was not preserved, and the old installation does no longer connect to the network due to what I can only assume to be several network upgrades. The program is stuck on connecting 

![image](https://user-images.githubusercontent.com/12898594/100519112-2a54fb80-3196-11eb-8669-91de69f7487f.png)

While googling around for possible solutions I ran into this thread https://github.com/input-output-hk/daedalus/issues/1234 which opened up the `daedalus.api` command line interface to me. Obviously I tried to give that a shot, and found the `daedalus.api.getWallets` function which sounded just like the miracle I had been looking for. Unfortunately the localhost server does not seem to work anymore as pretty much all calls respond with `connect ECONNREFUSED 127.0.0.1:8090`.

So my question is if it is possible to somehow start this service (I assume that's the node) in dummy mode to access the data stored within? There are no local key or database files that I could find (ie secrets-1.0 or similar), although I am 100% certain this is the installation that used to work.

Thank you!

**Comment by matiwinnetou** [comment]
Do you have a 12 world byron addres? If yes then download latest version 2.5.0 from the official IOHK website (make sure to verify pgp checksum) and then restore your wallet. If you don't have 12 words stored somewhere from your Byron era wallet then IOHK staff may still help you provided you don't tinker too much. There should be a wallet.dat somewhere file or similar which could be used to restore funds. This is a bit more tricky then.

Official http://daedaluswallet.io/ website.

**Comment by nitowa** [comment]
As already outlined in the OP the mnemonic is no longer available. I am very apt with javascript and not scared of the electron debugger. I also have an up-to-date version of daedalus running in tandem with the old installation.

`Program Files/Daedalus` which contains files last modified 2017 (so that should be where it is?) contails only one `.dat` file, called `icudtl.dat`. Would this be the file in question?

**Comment by matiwinnetou** [comment]
I don't know exactly which file that was. I think it is possible to restore somehow but please talk to official IOHK staff or find it online

**Comment by nitowa** [comment]
After playing around with the program a bit more, it turns out the node wouldn't start because it couldn't find the `Secrets-1.0`  folder.  After creating the folder manually, the program started normally, although obviously without any known wallets, as I just created an empty folder for them. I assume this can only mean whichever private keys the wallet once held were deleted *somehow*. I surely didn't go in there and delete my keys, but I guess any chance of recovering the wallet is gone.
