### ISSUE TITLE
Pop-Up Window Message for Rewards-Only Wallet Needs Improved

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/daedalus#2286]
Daedalus wallets that contain only rewards Ada do not allow users to send the Ada. The user alert that pops up when this situation arises is insufficient, and I have seen multiple users report the same issue. In general the alerts in Daedalus need to tell users "What to do" or "How to fix the issue" in addition to "What you cannot do".

Request changing the pop-up when sending Ada that is in a Rewards only wallet, where there is a pop-up window that says "Cannot send from a wallet that contains only rewards balances". The pop-up alert needs to say "This wallet contains rewards-only Ada. Send 10 Ada to this wallet to move rewards-only Ada." or however much Ada is needed in order to send the rewards-only Ada.

The screen shot sent by the user is attached.
![photo_2020-12-22_17-38-20](https://user-images.githubusercontent.com/25856278/103000082-4d09d400-44f8-11eb-8079-05ca38b41283.jpg)

**Comment by nikolaglumac** [comment]
Thanks for raising this with us @rickymac68!
We will look into this and make sure to improve the error message as soon as possible!
cc @darko-mijic

**Comment by HSleurink** [comment]
@nikolaglumac I have the same error (daedalus 3.1.0). How much ADA is needed in a wallet to make the transfer of the rewards possible?

**Comment by nikolaglumac** [comment]
You need to have at least one UTXO entry @HSleurink.
This means at least 1 ADA.

**Comment by nikolaglumac** [comment]
This one has been fixed in https://github.com/input-output-hk/daedalus/pull/2450 and the fix is to be released on Daedalus Flight today. You can expect it on Daedalus Mainnet a bit later this week.
Thank you for the patience! 🙏

**Comment by nikolaglumac** [comment]
This has been implemented and released in the scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience! 🙏
