### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by imrecsoka** [input-output-hk/daedalus#2288]
Hi, i have a general question regarding staking , and that is how on earth do you stop staking on the wallet so that a transfer can be made to an external address

In the Delegation Center section i can only redelegate but there is no undelegate option as youtube videos are pointing out.

Really confused here

**Comment by nikolaglumac** [comment]
Hi @imrecsoka!

There is no way to stop staking at the moment.
We will add this feature in one of the upcoming Daedalus releases.

**Please note that you can freely move your funds regardless of if you are staking or not.**

The only difference once the "undelegate" option becomes available is that, once you undelegate, you will get your 2 ADA deposit back.

Best,
N.

**Comment by imrecsoka** [comment]
HI, that's great news about the upcoming release which would incorporate that feature, so many people are looking forward to this project as there is a lot of noise on twitter and YouTube especially which i can observe.
So, silly question, how do you move the funds or transfer the funds? 
I am more used to the QT wallets , so  apologies.

Kind Regards
Imre

**Comment by nikolaglumac** [comment]
@imrecsoka staking itself is not locking your funds in any way. You can simply go to the wallet "Send" screen and send ada normally. Sending funds out of a staking wallet will only reduce the amount you are staking and thus reduce your rewards. An opposite thing happens when you receive funds to a wallet which is already staking - in this case you will get more rewards...

**Comment by imrecsoka** [comment]
Okay great thank you , not sure why I thought I can't send.
If I may ask, what is a decent amount to stake in the wallet - if i wanted to accumulate long term and earn more or less 10 coins a week, granted there are network factors, but I really wish to know this type of information.
Hope you can give me something
Regards


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nikolaglumac** [comment]
To earn ~10 ADA per epoch (which is 5 days long), you would need to stake around 14.000 ADA.
You can always check the "Potential rewards" in the stake pool tooltip or in the "list view":
![rewards](https://user-images.githubusercontent.com/376611/104185884-e4868680-5415-11eb-99d7-e9a15fbe807e.png)
