### ISSUE TITLE
Issue With Deadalus Sync

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/daedalus#2293]
Hello,

I have a recurrent issue with multiple version of Daedalus  Last one I tried is : 3.1.0 (Mainnet).

One I open the wallet the blockchain start syncing fats and it drops overt  time until it stops syncing and I retart the node again ,and after the restart ,it restart syncing fats and drops again after about (2-3 Min),
 I am facing this issue since along time, I tried  to remover(Stop  ) my Antivirus firewall and  it didn't help 

Please find attached the logs and PCAP maybe you can help me  identifying the issue.

**Comment by djalillounis** [comment]
[logs-2021-01-06T175814.0497Z.zip](https://github.com/input-output-hk/daedalus/files/5777480/logs-2021-01-06T175814.0497Z.zip)
![Win01](https://user-images.githubusercontent.com/13331817/103805401-d28e9780-5053-11eb-9abb-2754dead3926.png)

**Comment by nikolaglumac** [comment]
Hi @djalillounis!

Sorry to hear about your trouble...
This issue sounds like a networking/configuration problem on your side.
@disassembler @cleverca22 can you guys help us out here and check the logs? 🙏 

Thanks!

**Comment by djalillounis** [comment]
I am based in Poland, maybe if I manipulate my hosts file to point to a relay located in Germany will help, I will test it and let you know

**Comment by nikolaglumac** [comment]
@djalillounis any luck with this? Did the hosts file change work?

**Comment by djalillounis** [comment]
I didnt test it yet. I will do it during this week

**Comment by nikolaglumac** [comment]
Hi @djalillounis!
Any news?
Thanks!

**Comment by nikolaglumac** [comment]
@djalillounis I will close this ticket now. Please let us know if you experience this issue again.
