### ISSUE TITLE
Trouble with Uninstalling Daedalus Ubuntu 20.04

### ISSUE THREAD

**Issue by aquaductape** [input-output-hk/daedalus#2296]
I had issues [installing Daedalus](https://iohk.zendesk.com/hc/en-us/articles/900000776446-Installing-Daedalus-Mainnet-on-Linux-), the icon wasn't generated, a bunch of logs were spitting out, I couldn't tell if they were errors or not, I wish I copied them to post here for clarity but oops. Later I switched a different wallet, so I no longer needed Daedalus.

I tried to follow [this guide](https://iohk.zendesk.com/hc/en-us/articles/360013170694-Uninstall-Daedalus), but the paths where daedalus was suppose to live don't exist.

I used the `find` in the terminal and this is the result
```
 ❯ sudo find  / -type f -iname "daedalus*"
[sudo] password for caleb: 
/home/caleb/Downloads/daedalus-3.0.0-mainnet-15592.bin
find: ‘/proc/354514/task/354514/net’: Invalid argument
find: ‘/proc/354514/net’: Invalid argument
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
/tmp/nixlw1LxV/root/.local/bin/daedalus-mainnet
/tmp/nixlw1LxV/root/.local/share/applications/Daedalus-mainnet.desktop
/tmp/nixlw1LxV/root/.daedalus/nix/store/wbva047n3d247sb3nwlv4vh2c16ww212-Daedalus-mainnet.desktop/share/applications/Daedalus-mainnet.desktop
/tmp/nixlw1LxV/root/.daedalus/nix/store/ra418jr58hx8iw7zdzgxlsyr1hwnkz36-daedalus-frontend/bin/daedalus-frontend
/tmp/nixlw1LxV/root/.daedalus/nix/store/938hfhnyn4xn1qi1cvxc4qh8l2qw4db7-daedalus/bin/daedalus
```

Is okay to remove the found paths starting with `nixlw1LxV`?

```
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-58-generic 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI 04:00.0 Picasso 
```

**Comment by nikolaglumac** [comment]
Hi!
Please follow these steps:

1. Remove the installation of Linux Daedalus from your home directory:
```
chmod -R +w ~/.daedalus-mainnet
rm -rf ~/.local/bin/daedalus* ~/.daedalus-mainnet
```
2. Remove Desktop Icons:
```
rm -f ~/.local/share/applications/Daedalus-mainnet.desktop
```
3. Remove Daedalus configuration
```
rm -rf ~/.config/Daedalus\ Mainnet
```

**Important: Running the following commands will remove all Daedalus wallet data. Please make sure you have a copy of your Daedalus wallet pass phrase(s).**

4. (Optional) Remove the Daedalus blockchain, DB, and wallets.
```
rm -rf ~/.local/share/Daedalus/mainnet
```

**Comment by aquaductape** [comment]
I can't follow those steps because all of those paths that you listed, daedalus doesn't exist. When I installed the daedalus bin file, it installed them in different paths, I don't know exactly and I wish I copied the logs, so that's why I provided the results from the `find` command in my post, to see if its safe to remove them.

**Comment by nikolaglumac** [comment]
If you don’t have any of these paths then Daedalus is surely no longer installed. I am not sure what these other paths are - perhaps @disassembler can help us here 🙏

**Comment by nikolaglumac** [comment]
@aquaductape can this ticket be closed?
