### ISSUE TITLE
build-installer-win64.bat missing

### ISSUE THREAD

**Issue by claudiudc** [input-output-hk/daedalus#2297]
I would like to do a full build on windows platform, however build-installer-win64.bat is missing from sources.
Can you please check?

Thank you.

**Comment by nikolaglumac** [comment]
@cleverca22 @disassembler can you help us here?

**Comment by nikolaglumac** [comment]
@claudiudc unfortunately, there is no support for building on Windows platform and adding this is not in our plans.
