### ISSUE TITLE
Trezor T hidden wallet hidden passphrase public key export fail

### ISSUE THREAD

**Issue by europound** [input-output-hk/daedalus#2306]
cannot export private keys from trezor t to daedalus wallet directly
trezor t device asks to enter hidden password on connected host
but computer is not asking for anything

daedalus is waiting on public keys indefinitely

ubuntu 20.04

**Comment by nikolaglumac** [comment]
@europound this is a known issue already reported in https://github.com/input-output-hk/daedalus/issues/2238
Please follow the linked issue for more details. I am closing this one as it is a duplicate.
