### ISSUE TITLE
Sorting By Rewards In Daedalus

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/daedalus#2309]
When you sort by "rewards" in daedalus it sorts as follows (example) - "1,10,100,0,0" assuming five wallets. i would expect it to sort "0,0,1,10,100"; where there are two numbers that are the same i would sort alpahbetically by wallet name

**Comment by nikolaglumac** [comment]
We are on it @gmanroney 🚀

**Comment by nikolaglumac** [comment]
This has been fixed in https://github.com/input-output-hk/daedalus/pull/2333 and is to be released in the next Daedalus version.

**Comment by nikolaglumac** [comment]
The fix for this issue is now available in Daedalus Mainnet 3.3.0.
Please update your version of Daedalus either through the automatic update or manually by downloading the installer from: https://daedaluswallet.io/en/download/
Thank you for your patience!
