### ISSUE TITLE
Delegation wizard needs over-saturation warnings implemented

### ISSUE THREAD

**Issue by stakelovelace** [input-output-hk/daedalus#2316]
E.g. if I'm a 25m whale delegating to a pool that has 50m stake (and saturation level is 64m), the delegation wizard in Daedalus should present a prompt with information similar to the following:

⚠️ Warning: continuing with delegation to pool X will result in pool becoming oversaturated (saturation level of % percent). This will in turn result in reduction of future rewards (by x percent), to both you and existing delegators to that pool. Are you sure you want to proceed?  If you want to avoid over-saturation, please select a pool with a saturation percentage below <insert value here> ⚠️

Current implementation relies on the person delegating to go back to the pool listing after the delegation wizard and check the saturation level - plus for people that don't actually know what saturation is, this sort of prompt is a must-have.

**Comment by nikolaglumac** [comment]
Thanks for the feedback @stakelovelace!
We will look into this.
cc @darko-mijic

**Comment by darko-mijic** [comment]
Thanks for the feedback @stakelovelace. We have filed this in our backlog and it will be implemented.

**Comment by hodlonaut** [comment]
@nikolaglumac Any idea whether this improvement (that has been implemented by Yoroi wallet already since this github issue was originally raised in Daedalus repo) has progressed in the backlog?

**Comment by nikolaglumac** [comment]
@daniloprates is this included in https://github.com/input-output-hk/daedalus/pull/2649 ?

**Comment by daniloprates** [comment]
@stakelovelace thank you for your suggestion. It was implemented on #2733 and released in the [4.5.1](https://iohk.zendesk.com/hc/en-us/articles/4409944350489-Daedalus-4-5-1-release-notes) version.
