### ISSUE TITLE
[Bug] Tx Error: Candidate contains blocks from future exceeding clock skew limit

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/daedalus#2319]
Send with Ledger X fails with

```
[31m[MacBook3:cardano.node.ChainDB:Error:26][0m [2021-01-26 09:10:11.79 UTC] Candidate contains blocks from future exceeding clock skew limit: 85674e88d957a8b27562be3372d90c968a592aad7654febaf785f43276c2bc2a at slot 20085927, slots 85674e88d957a8b27562be3372d90c968a592aad7654febaf785f43276c2bc2a@20085927
```

I resynched from an empty block store, but still ^^^

On my Ledger I noticed an epoch very far into the future (i.e. 544) we are currently on 244, perhaps that has something to do with it.

**Comment by nikolaglumac** [comment]
The TTL is hardcoded far in the future at the moment.
We will be changing this to a dynamic calculated TTL soon, but I don't think this is a root cause of the issue you are seeing.

@KtorZ can you please look into this?

**Comment by KtorZ** [comment]
@nikolaglumac I don't think this has anything to do with the transaction's TTL. This is an error from the ledger database which is probably due to a wrong offset on the local clock. 

I don't recall seeing this error every to be frank. We'll need to ask someone from the consensus team. @coot, does that ring any bell to you or do you know someone for whom it might :no_mouth: ?

**Comment by nikolaglumac** [comment]
@tdiesler can you please check if this issue still persists on the latest Daedalus Mainnet 3.2.0 🙏

**Comment by tdiesler** [comment]
I've since been able to send with 3.2.0. We can close this if you like.

**Comment by coot** [comment]
As far as I know the consensus can deal with some small clock skew, but once it goes above some threshold consensus would error.  This could happen when changing system clock.  Consensus team might be better point of contact for such errors.
