### ISSUE TITLE
Stake Pool tab no longer displayed

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/daedalus#2320]
Version: 3.1.0
Build: #15733

<img width="277" alt="image" src="https://user-images.githubusercontent.com/244946/105844865-2d276d80-5fda-11eb-9c6a-c10ea74fd081.png">

**Comment by nikolaglumac** [comment]
@tdiesler it shows after a while. Daedalus sometimes receives shelley era hardfork info from the Api slower than usual and thus the button shows up with delay (1-2 mins or so). This is a known issue in the cardano-wallet component and the Adrestia team is working on the fix.

**Comment by nikolaglumac** [comment]
@tdiesler this issue will be fixed after this PR is merged: https://github.com/input-output-hk/daedalus/pull/2325

**Comment by nikolaglumac** [comment]
The fix for this issue is now available in Daedalus Mainnet 3.3.0.
Please update your version of Daedalus either through the automatic update or manually by downloading the installer from: https://daedaluswallet.io/en/download/
Thank you for your patience!
