### ISSUE TITLE
Daedalus reads Windows drive storage instead of the one it has been installed to

### ISSUE THREAD

**Issue by Whoffie** [input-output-hk/daedalus#2326]
As my main SSD has been filling up, I recently installed an m.2 NVME drive to my system, nearly void of any files (save for a few .txt and image files). Unfortunately, when Daedalus is installed on that drive, it says my drive storage is too low. 

Proof the mainnet folder is in my drive
![image](https://user-images.githubusercontent.com/76015073/106341402-c668b500-6262-11eb-8250-614f617bc5f2.png)

Error message

![image](https://user-images.githubusercontent.com/76015073/106341420-dd0f0c00-6262-11eb-98ff-aaed7e1c4dc8.png)

I'm also obliged to mention that the drive is mounted to a folder, which is probably the root of this bug. The software should probably check if the directory has a drive mounted or not.

**Comment by nikolaglumac** [comment]
Hi @Whoffie!

Daedalus only checks for the main drive's available space and not the one on which Daedalus is installed.
The reason for that is that the state directory which contains blockchain data and takes a lot of storage space is always stored on the main drive.  **There is no way of changing the drive for that state directory at the moment.**
You can find the location of that directory by opening Daedalus Diagnostics dialog from the Application menu.

What I suggest is to move the "chain" subfolder to a drive that has more space and then adding a symlink pointing to the new location.

Good luck!

**Comment by Whoffie** [comment]
Thanks for the clarification, I'll do that. 👍
