### ISSUE TITLE
Daedalus stuck in Connecting State

### ISSUE THREAD

**Issue by KevinRiordan** [input-output-hk/daedalus#2327]
I have been using the wallet with no issues for days and went to dedicate some stake to a pool earlier today. eveything seeme fine. i came back and it was closed and now it is stuck in the connecting state.

**Comment by KevinRiordan** [comment]
reinstalled and it connected will now try to restore

**Comment by nikolaglumac** [comment]
Hi @KevinRiordan!
Sorry to hear about the issue...
Keep us posted 🙏

**Comment by nikolaglumac** [comment]
Hi @KevinRiordan! Any news?

**Comment by KevinRiordan** [comment]
Reinstalled and says error occured when trying to restore a shelley daedalus. cant restore...

**Comment by nikolaglumac** [comment]
@KevinRiordan if you know your wallet's recovery phrase, I would suggest you delete the state directory and sync from scratch, and then try to restore the wallet.

**Comment by nikolaglumac** [comment]
Hi @KevinRiordan!
Any news? 🙏

**Comment by nikolaglumac** [comment]
@KevinRiordan I am afraid you need to re-sync your wallet.
Please first **make sure you have your wallet's recovery phrase** and then:
1. Uninstall Daedalus
2. Delete the state directory
3. Install Daedalus and restore your wallet
