### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by Codanalt** [input-output-hk/daedalus#2328]
Hi,
I have a suggestion to improve the installation experience.
For security reasons I'm using two accounts on my Windows10 PC.
One admin-account for installations and another user-account (non-admin) for the daily work.
If I start the setup (while I'm logged into the user account) it shows me this error-message:

![grafik](https://user-images.githubusercontent.com/78271616/106363353-5fadcf00-6328-11eb-9c0e-c4c7ca57fa94.png)

It would be nice, if there is a User Account Control window instead to type in the admin credentials.
(Of course I could install it with right click and "run as administrator") :)

**Comment by nikolaglumac** [comment]
Hi @Codanalt!
This error is shown because you have another instance of Daedalus running while you are trying to run the installer.
Please exit all running Daedalus instances and then run the installer again.
Cheers!

**Comment by Codanalt** [comment]
Thanks for the fast reply.
Yes, that would be an explanation, but I'm pretty sure that there is no Daedalus instance running. In this case, my user has no write permission to the file (cardano-node.exe), so it can't be updated. (Only the admin-user can.)
So maybe it would be helpful, to implement an elevation prompt or - if Daedalus is open - a user-friendly message (like "please close Daedalus wallet"), if the installer can't replace the file.
Just as a suggestion to improve the installer at this point. :)

**Comment by nikolaglumac** [comment]
Thanks!
We'll need our DEVOPS team to assist us here...
@disassembler @cleverca22 can you guys please look into this? 🙏

**Comment by danielmain** [comment]
Hi @Codanalt sorry for letting you so long waiting. As far I know, it is the first time someone requests this feature (correct me please if I am wrong). 

If for security reason, only an administrator is allowed to install software on your machine:

Some workarounds:
- log in as the administrator and update Daedalus
- Run Daedalus as administrator (right-click on the shortcut) and update it.
- Alternatively, installing Daedalus in your User space is also possible. 
![image](https://user-images.githubusercontent.com/4303099/145867838-e4521405-ede9-4e9d-a37c-e2270046c1e0.png)
