### ISSUE TITLE
My stake pool doesnt show in daedalus

### ISSUE THREAD

**Issue by crash007** [input-output-hk/daedalus#2343]
Hi,
My stake pool wape [wape](https://adapools.org/pool/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa) doesnt show in Daedalus.
Accoring to pooltool.io the metadata is verified. I have also registered the pool where I used pooltool.ios metadata generator and I increased the pledge. Still the pool doesnt show up. 
 
Trying the Smash api returns 404 for my poolid `
wget  https://smash.cardano-mainnet.iohk.io/api/v1/metadata/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa`
for references:
[WAPE pooltool](https://pooltool.io/pool/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa/l)
[WAPE adapools](https://adapools.org/pool/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa)

**Comment by nikolaglumac** [comment]
I can't get https://smash.cardano-mainnet.iohk.io/api/v1/metadata/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa to load?

**Comment by crash007** [comment]
NOme either I get 404 not found @nikolaglumac

**Comment by crash007** [comment]
Do I need to wait a certain number of epochs before it show?

**Comment by nikolaglumac** [comment]
Please use this URL to verify if your stake pool is available on SMASH: https://github.com/input-output-hk/daedalus/issues/2117#issuecomment-768480271
If it is not then you don't get to see it in Daedalus.

**Comment by crash007** [comment]
The command `https://smash.cardano-mainnet.iohk.io/api/v1/metadata/df01dcb3a9e8966b6376e6e6db8739fff72cb769a3b5174736520baa/b87ec11ff23a60ac9f2b3e6ed2a96b15519237839df115594e13d915717dbe0e`

returns the stake pools meta data
`{"name": " WAPE Stake pool", "ticker": "WAPE", "description": "Stakepool located in north of Sweden", "homepage": "https://www.wape.nu"}`

But the stake pool wont still not show in daedalus for me.

**Comment by nikolaglumac** [comment]
I can see your stake pool in my Daedalus Mainnet instance:

![Screenshot 2021-02-05 at 19 56 31](https://user-images.githubusercontent.com/376611/107076837-4b684700-67ec-11eb-9295-b95911b03f14.png)

I believe you only need to wait for Daedalus to pick it up...
Try restarting Daedalus.

**Comment by crash007** [comment]
Great you can see it. I still cant see it in my wallet after several restarts. Can I force a stake pool refresh in daedauls without reinstall it?

**Comment by nikolaglumac** [comment]
Yes - you can do the following to trigger Daedalus to re-fetch all the stake pool data:

> 1. Access to `Help - Daedalus Diagnostics` (or press  `⌘ + D` on Mac or `Ctrl + D` on Windows and Linux) 
> 2. On `Daedalus state directory` click `Open`
> ![Screenshot 2021-02-05 at 20 21 46](https://user-images.githubusercontent.com/376611/107079187-c717c300-67ef-11eb-8f3e-8fa88913dd8c.png)
> 3. Close Daedalus
> 4. Access the folder `wallets` on the state directory
> 5.  Search for the file `stake-pools.sqlite` and delete it
> ![Screenshot 2021-02-05 at 20 22 00](https://user-images.githubusercontent.com/376611/107079215-ced76780-67ef-11eb-8fde-ffc3ea34e043.png)
> 6. Reopen Daedalus

**Comment by nikolaglumac** [comment]
The screenshots are from an old version and not the one I am using. Please wait for it and your stake pool will show up.

**Comment by crash007** [comment]
Yes now it finally shows. Thanks so much for you time and help!

**Comment by nikolaglumac** [comment]
Glad to hear!
