### ISSUE TITLE
Wallet runs, but user interface does not open on Linux

### ISSUE THREAD

**Issue by conjohnerton** [input-output-hk/daedalus#2346]
System Specs: AMD 3600 CPU on Manjaro (and Ubuntu VM). 

The wallet works as expected on the same computer using Windows 10. On linux, the wallet process is running, but the interface is not popping up. Could it be an electron issue?

**Comment by nikolaglumac** [comment]
@conjohnerton is this a case of Daedalus window showing but being blank (completely white or black) or you are not seeing the window at all?

**Comment by conjohnerton** [comment]
The Daedalus wallet just isn't showing a window at all! 😓

**Comment by nikolaglumac** [comment]
Well, we are running Daedalus in Ubuntu VMs all the time. This must be related to your setup or your VM/Ubuntu config...
