### ISSUE TITLE
Negative transaction, is this a bug?

### ISSUE THREAD

**Issue by dadepo** [input-output-hk/daedalus#2349]
I just noticed there is a negative transaction on my wallet. I find it strange as I am new to cryptocurrencies and I have never transferred money out of the wallet. This is seen in the screenshot below:

Would you be kind enough to investigate if this is a bug somewhere? Or something about the interface I do not understand.

Thanks! :)

![Screenshot 2021-02-07 at 23 04 10](https://user-images.githubusercontent.com/272535/107160807-ce2e0500-6998-11eb-82a6-4cb7416250c7.png)

**Comment by nikolaglumac** [comment]
@dadepo this is the delegation registration transaction. It includes 2 ADA deposit of your wallet’s delegation certificate and a ~0.17 ADA fee.
This was an outgoing transaction and that is why the amount is shown as negative.
