### ISSUE TITLE
Import ADA Private Key from Atomic Wallet into Daedalus?

### ISSUE THREAD

**Issue by automaticprofits** [input-output-hk/daedalus#2362]
Hello,

How may we Import ADA Private Key from Atomic Wallet into Daedalus?

Thank you.

**Comment by nikolaglumac** [comment]
In what format is this private key?

**Comment by automaticprofits** [comment]
I don't know how to answer that question.  What are the different types of formats?

This key has 180 characters.

**Comment by nikolaglumac** [comment]
@CarlosLopezDeLara will look into this and get back to you here in the thread.
Thank you for your patience!

**Comment by CarlosLopezDeLara** [comment]
@automaticprofits I'm still digging around on Atomic docs, but what I know for sure is that the 12-word recovery phrase you get from them helps you to restore a Legacy Wallet, the same that you find under Settings>PrivateKeys>Cardano>LegacyPrivateKey. 

We still  need to find how they are building the Shelley wallet starting from that same 12-word. I'm awaiting response from them. 

Importing from xprv should be possible. Still working on this. I'll keep you posted.

**Comment by Mendez849** [comment]
@automaticprofits Hello Mate, Sorry to hear about your issue, you can contact Atomic Wallet Support on Telegram via the weblink www.t.me/theatomicwallet. They'll be happy to resolve your issue. Cheers.

**Comment by nikolaglumac** [comment]
@CarlosLopezDeLara any news on this one?

**Comment by nikolaglumac** [comment]
@automaticprofits Atomic wallet still uses Byron wallets only. There is no way to import those into Daedalus.
I suggest you to create a Shelley wallet in Daedalus and move your funds to it so you can delegate them and earn rewards.
