### ISSUE TITLE
"Show used" toggle button everytime is on

### ISSUE THREAD

**Issue by haripetrov** [input-output-hk/daedalus#2365]
Hello team,

I don't know if this is normal behaviour but when I turn off the toggle button "show used" under the section "Your wallet addresses" > "Receiving addresses" of my Windows Daedalus Wallet (ver. 3.2.0), the next time when I start the wallet app it's still active. And this is every time. Could we change the logic so that once it's selected to be turned off to stay that way?
![изображение](https://user-images.githubusercontent.com/1268290/108092732-abc97500-7085-11eb-8c55-43919739ca6f.png)

**Comment by nikolaglumac** [comment]
Hi @haripetrov!
This behavior is per design. 
We will discuss this on our usual UI/UX design calls and get back to you.
Thanks for the feedback!

**Comment by haripetrov** [comment]
Thank you @nikolaglumac!

There is another example which can be useful regarding this setting. Bittrex global are having this toggle button:
![image](https://user-images.githubusercontent.com/1268290/109384769-d7572580-78f7-11eb-9ae4-6a0f7ddf0266.png)
Once you activate it every time when you login it's the same view which is very convenient.

**Comment by nikolaglumac** [comment]
This has been implemented and released in the scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience 🙏
