### ISSUE TITLE
JavaScript error: failed to get 'appData' path

### ISSUE THREAD

**Issue by teoman002** [input-output-hk/daedalus#2374]
I got an error after my first installation on a Linux Mint 19 x64 machine.
After starting the wallet software I received this error message:

![image](https://user-images.githubusercontent.com/1367821/108262351-1c938e80-7165-11eb-9acf-a5b1ce2be6ff.png)

**Comment by nikolaglumac** [comment]
OpenSuse is not officially supported: https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements
Still, you might try these steps to get Daedalus Mainnet working: https://iohk.zendesk.com/hc/en-us/articles/900000776446-Installing-Daedalus-Mainnet-on-Linux-

**Comment by teoman002** [comment]
I am running Linux mint, its a fork of Ubuntu, which is said to be supported.
Does that mean only Ubuntu is supported?

**Comment by nikolaglumac** [comment]
Officially yes. Please make sure you covered all these steps: https://iohk.zendesk.com/hc/en-us/articles/900000776446-Installing-Daedalus-Mainnet-on-Linux-
