### ISSUE TITLE
Send Amount UI Bug

### ISSUE THREAD

**Issue by alex-stout** [input-output-hk/daedalus#2377]
Hello,

There is a bug when entering zeros after the decimal point for the amount of ada to send. 

### This works fine:
![image](https://user-images.githubusercontent.com/17804548/108321987-83776e80-718a-11eb-94cb-33214c512b47.png)

### This does not work:
![image](https://user-images.githubusercontent.com/17804548/108321939-722e6200-718a-11eb-884e-966e573ee2e2.png)
The amount entered was `1.0000` on the keyboard.

The result is the modal not popping up when clicking next. No console errors either. 

This was tested in Mac OS and Windows running the latest version of Daedalus 3.3.0.

**Comment by nikolaglumac** [comment]
Thanks for raising this!

@ManusMcCole @miorsufianiohk @gabriela-ponce please check this out 🙏

**Comment by nikolaglumac** [comment]
The issue has been fixed in https://github.com/input-output-hk/daedalus/pull/2379
We will be releasing this in the next Daedalus update.
Thanks for reporting this @alex-stout 🙌

**Comment by nikolaglumac** [comment]
Fix released in Daedalus 3.3.1: https://daedaluswallet.io/en/download/
