### ISSUE TITLE
Cancelling vote registration will still deduct 0.17 ada

### ISSUE THREAD

**Issue by chsami** [input-output-hk/daedalus#2384]
When canceling a vote registration the transaction will still continue and deduct 0.17 ada

https://explorer.cardano.org/en/transaction?id=f487ea731b5cf1b5eb9d37bb217b8ccff9a85cdeb8145bb4941820b29ca6f7d5

![image](https://user-images.githubusercontent.com/23292806/108475179-a9873680-7290-11eb-9049-3b67259cb5cb.png)

**Comment by nikolaglumac** [comment]
This is expected. If you cancel the registration after you make the transaction you can not get this ada back.
It has already been spent on the fees.
