### ISSUE TITLE
Vote registration takes more than 30min and failed

### ISSUE THREAD

**Issue by dipterix** [input-output-hk/daedalus#2385]
I tried twice to register to vote, but each time it took more than 30min to respond. The coin was sent but got no feedback (frozen at step 3 and cannot enter the step 4)

Is there any hardware requirement to vote?

**Comment by nikolaglumac** [comment]
@dipterix sorry to hear about your trouble!

There is no special hardware requirements to vote. 
Please make sure to:
- not let your machine go to sleep / hibernation during voting registration
- try to have the Daedalus window focused during voting registration step 3
- before attempting to register make sure to restart your machine and have only Daedalus Mainnet running.

Let us know if this helped 🙏

**Comment by dipterix** [comment]
@nikolaglumac I followed your suggestions. It failed after running for hours. (Daedalus went back to re-sync with the mainnet)

In addition, I also aligned my computer time with my local time (+- 0.01s).
I'm using macbook pro 2017 with 4 core i7, 16GB RAM and 256 GB NVMe SSD. 

The Ada was sent successfully within minutes, but waiting for confirmation took so long.

**Comment by nikolaglumac** [comment]
And you didn't see it getting confirmed in the Voting registration wizard step 3?

**Comment by dipterix** [comment]
I don't think so. It was stuck in the 3rd step trying to confirm, not "confirmed". I don't know what's the interface next.

**Comment by nikolaglumac** [comment]
Would you be so kind to do send us the logs?

**Comment by dipterix** [comment]
Sure, that'll be the best. Is there any way to get the logs?

**Comment by nikolaglumac** [comment]
Please use the “Download logs” option from application menu.

**Comment by nikolaglumac** [comment]
@dipterix any news on the logs?

**Comment by dipterix** [comment]
@nikolaglumac sorry for being late. I just sent to your gmail

**Comment by nikolaglumac** [comment]
Thanks! I have checked them and they are not helpful as the information we need was already "rotated out" in the logs. 
So we can only get this information if you do another attempt to register and then send us logs 10 mins after the registration attempt.

**Comment by dipterix** [comment]
Thanks. The bug is fixed after upgrading to `3.3.1`
