### ISSUE TITLE
Crash when trying to Save PDF

### ISSUE THREAD

**Issue by sorki** [input-output-hk/daedalus#2390]
Happens on the last step of voting fund registration:

```
(electron:17060): GLib-GIO-ERROR **: 21:51:46.107: No GSettings schemas are installed on the system
[launcher:Notice:15] [2021-02-19 20:51:46.88 UTC] Wallet exited with exitcode: ExitFailure (-5)
[launcher:Notice:15] [2021-02-19 20:51:46.88 UTC] Daedalus exited with ExitFailure -5, will shutdown cardano-launcher
```

My system is pretty minimal and I don't have a lot of standard distro stuff installed. I do have `xdg-open` and correct XDG settings since it can open URLs in browser. `xdg-open some.pdf` seems to work as well.

**Comment by sorki** [comment]
Similar to  #2255

**Comment by nikolaglumac** [comment]
This works as expected on [officially supported operating systems](https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements) with default configuration.
Please update your system in order to use the "Save PDF" feature.

**Comment by sorki** [comment]
It says it's aimed at `All Linux distributions` - I'm on NixOS but without Gnome, looks like I'm just missing `gsettings-desktop-schemas` (maybe it could be part of Daedalus Nix closure).

**Comment by nikolaglumac** [comment]
Yes but it is officially tested against:
- Ubuntu 18.04 LTS, Ubuntu 20.04 LTS
- Fedora 28 

@cleverca22 could you look into the Nix closure `gsettings-desktop-schemas`...

**Comment by sorki** [comment]
I'll test this locally and submit a PR if it helps, trouble is I need to go through complete registration process - maybe I should try this against testnet.

**Comment by nikolaglumac** [comment]
That would be great 🙏

**Comment by sorki** [comment]
Investigating this I realized this was caused by my system switching to incompatible graphics stack without reboot so it wasn't able to launch any graphical applications including file selection dialog.

`XDG_DATA_DIR` is configured correctly in chroot and has `gsettngs-desktop-schemas`.

There's not much you can do about this and it's pretty unlikely users are going to hit this. One idea to improve this would be to save the generated pdf before opening the dialog and copying it to user selected dir. This is more of a proposal for another issue I guess as it could include UX for listing already generated pdfs from deadalus.
