### ISSUE TITLE
Bug: Wallet which has been undelegated using Yoroi still shows as delegated in Daedalus

### ISSUE THREAD

**Issue by katakombi** [input-output-hk/daedalus#2392]
See title, should be easy to reproduce.
I can attach info about my wallet if necessary.

**Comment by nikolaglumac** [comment]
The wallet is still delegated for 2 epochs after you trigger undelegation in Yoroi.
Please state when you did the undelegation and provide a screenshot of the Daedalus "Delegation center" screen.
Thanks!

**Comment by katakombi** [comment]
Thanks for the reply. I did the undelegation last epoch. I cant remember when exactly I guess 17th of Feb. Strangely enough I can't find a transaction in my Yoroi wallet where I received back the 2 Ada deposits. Is however states that it is undelegated. 

I still suspect this could lead to problematic behaviour ... e.g. I could try to redelegate in daedalus, and what would happen? Does it assume I did pay the 2Ada already? It should probably update the screen to show that the wallet is actually not delegated.

I will add a screenshot of daedalus asap.

**Comment by katakombi** [comment]
![image](https://user-images.githubusercontent.com/5052427/108624830-99658780-7447-11eb-8ca1-e5964873fc49.png)
NB I couldn't test redelegation because I need 10 Ada miminum for that...

**Comment by nikolaglumac** [comment]
Please provide the Daedalus logs so that I can look into that more closely.

**Comment by katakombi** [comment]
Can I somehow PM it? The zip file is huge and I wonder what all is contained in these logs...

**Comment by nikolaglumac** [comment]
Feel free to send it to my email: niglumac@gmail.com
There is nothing compromising in the logs.

**Comment by katakombi** [comment]
Here are the logs...
[logs-2021-02-21T193124.0181Z.zip](https://github.com/input-output-hk/daedalus/files/6018417/logs-2021-02-21T193124.0181Z.zip)

**Comment by nikolaglumac** [comment]
Thanks @katakombi!
I have checked the logs and you are right - we have a bug in Daedalus...

```
"delegation":{
  "next":[{"status":"not_delegating","changes_at":{"epoch_start_time":"2021-02-24T21:44:51Z","epoch_number":250}}],
  "active":{"status":"delegating","target":"pool1ljywsch33t7gaf02aeeqkqpuku0ngpwl9fm04t7u5sl5xyunmgp"}
}
```

☝️ your wallet is indeed undelegated from epoch 250. Daedalus should show that in the UI.
We will work on this in our next sprint which starts tomorrow.

Thanks!

cc @darko-mijic

**Comment by katakombi** [comment]
That's great news. Thanks!

**Comment by nikolaglumac** [comment]
The fix for this issue is now available in Daedalus Flight 4.0.0-FC1: https://daedaluswallet.io/en/flight/
We will be releasing it on Daedalus Mainnet next week.
Thank you for the patience!

**Comment by katakombi** [comment]
Thanks! I will check the fix once 4.0.0 is released.

**Comment by katakombi** [comment]
I installed FC meanwhile and although I did not repeat the full test and unstake a staked wallet it is showing the previously unstaked wallet as staked.
I hope this is enough of a confirmation but leave it up to you devs to close this bug.
Thanks a lot for the fix!

**Comment by nikolaglumac** [comment]
Thanks for confirming this @katakombi!
Closing this issue now...
