### ISSUE TITLE
please type your passphrase hidden wallet stuck, no prompt

### ISSUE THREAD

**Issue by europound** [input-output-hk/daedalus#2393]
please type your passphrase hidden wallet stuck, no prompt
daedalus is not working with Trezor T
no prompt for hidden wallet password
just stuck spinning at export the public keys on your device

**Comment by nikolaglumac** [comment]
Closing this one as it is a duplicate of https://github.com/input-output-hk/daedalus/issues/2238
Please follow that thread for more info.
