### ISSUE TITLE
Proper transaction history for taxation purposes

### ISSUE THREAD

**Issue by Straightpool** [input-output-hk/daedalus#2394]
**Short summary**
Whilst Daedalus 3.3.0#16556 transaction details have been improved, the details are still not useable for direct imports into taxation software as the documentation logic is not following best practice.

**Current situation**
Example case: Wallet A sends 10 ADA to wallet B with a fee of 0.17 ADA on timestamp X
- Wallet A shows an outgoing transaction on timestamp X with outgoing funds of 10.17 ADA and a fee of 0.17 ADA
- Wallet B shows an incoming transaction on timestamp X with incoming funds of 10 ADA
- The CSV transaction file for wallet A omits reporting the fee otherwise same as the report of wallet A
- The CSV transaction file for wallet B is equal to the report of wallet B

**Desired state**
Example case: Wallet A sends 10 ADA to wallet B with a fee of 0.17 ADA on timestamp X
- Wallet A shows an outgoing transaction on timestamp X with outgoing funds of 10 ADA and a fee of 0.17 ADA
- Wallet B shows an incoming transaction on timestamp X with incoming funds of 10 ADA (no change)
- The CSV transaction file for wallet A shows an outgoing transaction with 10 ADA with the fee of 0.17 ADA in a separate column declared as fee
- The CSV transaction file for wallet B is equal to the report of wallet B (no change)

**Benefits of change**
If the data in the wallet view and CSV exports follows best practice, this data is much more easily importable into crypto tax software such as Accointing.

**Comment by nikolaglumac** [comment]
Thanks for raising this @Straightpool!
We've just recently got the separated fee value in the scope of transaction details and enables us to improve the CSV export feature. We will for sure be improving this.
Just to be 100% clear - this change will only impact the CSV export and not the transactions within Daedalus UI.

Cheers!

**Comment by Straightpool** [comment]
> Thanks for raising this @Straightpool!
> We've just recently got the separated fee value in the scope of transaction details and enables us to improve the CSV export feature. We will for sure be improving this.
> Just to be 100% clear - this change will only impact the CSV export and not the transactions within Daedalus UI.

Thank you Nikola!

If you do not want to change the transaction view within Deadalus UI, I do suggest the following additions to the CSV export:

For withdrawals:
- Add column "fee",  e.g. "0.17"
- Add column "Amount before fee" e.g. "10" in my above example

By just adding those 2 columns the utility of the CSV export is increased a lot while remaining consistent to the Daedalus UI.

While you are at it, I would also highly recommend to change the format in the "Date&Time" columns to a more easily parseable format.

Currently non-standard:
2021-01-14T202501.0000Z

Best practice:
01/14/2021 20:25:01
mm/dd/yyy hh:mm:ss

**Comment by nikolaglumac** [comment]
Thanks @Straightpool!
We will look into this.

> Currently non-standard:
2021-01-14T202501.0000Z

> Best practice:
01/14/2021 20:25:01
mm/dd/yyy hh:mm:ss

The date format you are proposing is missing timezone info.
The format we are using is the ISO 8601 standard.

cc @darko-mijic

**Comment by Straightpool** [comment]
> The date format you are proposing is missing timezone info.
> The format we are using is the ISO 8601 standard.

Good point! I looked into the ISO 8601 standard, may I suggest to use ISO 8601 extended for timestamps? This allows for pretty straightforward Excel parsing like this (ignoring the timezone, but still very useful):

`=TEXT(DATEVALUE(MID(<CELL>,1,10))+TIMEVALUE(MID(<CELL>,12,8)),"mm/dd/yyyyy hh:mm:ss")`

(Yeah, Excel does still not parse `yyyy-mm-dd"T"hh:mm:ss".0000Z"`)

Basic:
2021-01-14T202501.0000Z
Extended:
2021-01-14T20:25:01.0000Z

**Comment by nikolaglumac** [comment]
We'll check it out. Thanks!

**Comment by nikolaglumac** [comment]
Hi @Straightpool!
The changes you requested have been implemented in https://github.com/input-output-hk/daedalus/pull/2451 and will be released in the next Daedalus version.
Thanks for the patience 🙏

**Comment by nikolaglumac** [comment]
This has been implemented and released in the scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience! 🙏 

PS. We will be updating the transaction details display shortly too. It will match what you requested. Thanks for raising this once again!
