### ISSUE TITLE
Add support for multiple accounts per HW device

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/daedalus#2397]
Please have a look at the account feature in [ADALite](https://adalite.io). There you can create independent wallets from the same HW device.

```
Shelley extended public key (1852'/1815'/1'/)
```

A feature that folks are used to in LedgerLive as well

**Comment by nikolaglumac** [comment]
Thanks for raising this @tdiesler!
We are aware of this feature request and have it in our backlog.
Will let you know as soon as the implementation work starts.
Thank you for the patience! 🙏

**Comment by amutiso** [comment]
+1 ccVault/Eternl, Trezor Suite on Trezor T also support secondary accounts in the same wallet. 
It's mid 2022. What is the likelihood of this backlog item making into a release?

**Comment by tdiesler** [comment]
out-of-date
