### ISSUE TITLE
Continue without clock synchronization...

### ISSUE THREAD

**Issue by feraldruid22** [input-output-hk/daedalus#2405]
Ok so I have to say after this bug being present in ALL deadalus versions up until to the latest one I have to say 1 thing:

IM SICK OF THIS SHIT!!!

![sht](https://user-images.githubusercontent.com/68493405/109172895-8a524280-7783-11eb-96e3-8f6e1abf0603.png)

No matter what I use ntpd, chrony... It always says the clock is not synchronized. Yes the f it is.

**Comment by nikolaglumac** [comment]
@feraldruid22 you obviously have some specific network configuration or a firewall which prevents Daedalus from reaching the NTP service...

**Comment by nikolaglumac** [comment]
@feraldruid22 did you have time to check your firewall / network-configuration?

**Comment by feraldruid22** [comment]
Yes now I figured out what's going on you must have hardcode the NTP servers inside deadalus.
Bad practice. Of course the box is firewalled and I only let out connection to my own NTP server on the LAN.
You should consider first using either the ntp of the local machine or the default ntp by ntpd.conf and not to make connections outside.
If I allow 123 UDP/TCP to anywhere then it works.

**Comment by nikolaglumac** [comment]
I am glad to hear that resolved the issue.
The NTP servers are configured on the https://github.com/input-output-hk/cardano-node level. Please open a ticket there 🙏
