### ISSUE TITLE
Staking/voting rewards history

### ISSUE THREAD

**Issue by aljosa** [input-output-hk/daedalus#2410]
Daedalus depends on cardano-wallet, where is the issue (in cardano-wallet or some other dependency you use) which is preventing detailed overview of staking/voting transactions?

I'd like to track the non-daedalus dependency that's blocking this.

**Comment by nikolaglumac** [comment]
This is a duplicate of https://github.com/input-output-hk/daedalus/issues/2347
Please follow that thread instead. We are limited by the cardano-wallet API: https://github.com/input-output-hk/cardano-wallet

**Comment by aljosa** [comment]
@nikolaglumac there is no issue in cardano-wallet tracking this requirement?

**Comment by nikolaglumac** [comment]
AFAIK it is only present in JIRA and not in GH.
