### ISSUE TITLE
[feature] Newly created wallet should not need to sync history

### ISSUE THREAD

**Issue by jonathancross** [input-output-hk/daedalus#2415]
When creating a new wallet in an instance of Daedalus that has already synced older wallets, Daedalus will immediately go through a long, slow process of syncing:

> The balance and transaction history of this wallet is 34.87% synced with the blockchain.

This makes no sense as there is verifiably zero transactions and zero balance on a newly generated wallet.

Instead, Daedalus should recognize that this wallet is _already synced_ and skip unnecessarily looking up history.

**Comment by nikolaglumac** [comment]
Hi @johnalotoski!

I agree with you but there is nothing we can do on Daedalus side to change this.
This is not a Daedalus but a cardano-wallet change request. Once they implement this, it will automatically work like that in Daedalus.
Please open a ticket on https://github.com/input-output-hk/cardano-wallet

Thanks!
