### ISSUE TITLE
[feature] Add "birthday" (aka "block height") option when restoring wallet

### ISSUE THREAD

**Issue by jonathancross** [input-output-hk/daedalus#2416]
When restoring a wallet from seed phrase, the user should have an option to set a so-called "birthday" (block height or date) of the first transaction.  The idea is that transactions from older blocks can be ignored unless they have direct bearing on UTXOs owned by this wallet.

The goal is dramatically faster syncing.

I am coming at this from the Bitcoin / Monero space where this feature has been part of the UX for a long time.  Perhaps there is something different in Cardano which prevents such a speedup?

**Comment by nikolaglumac** [comment]
Hi @jonathancross,

This sounds interesting 🤔 
I am not sure we can do that but it is once again a question for https://github.com/input-output-hk/cardano-wallet.
Please open a ticket there 🙏 

Thanks!
