### ISSUE TITLE
Shared seed between Trezor Model T and Ledger Nano S give different ADA wallets

### ISSUE THREAD

**Issue by nocmonkey** [input-output-hk/daedalus#2417]
I'm new to hardware wallets so not sure if this is a Daedalus problem or a problem with one of the hw wallets' firmware/app or just user error.  I use a Ledger Nano S as a backup hw wallet to my Trezor Model T.  All other cryptocurrency wallets, that I use, are in sync except for the ADA wallet.  I didn't use a passphrase on either hw wallet.  I added both hw wallets on Daedalus 3.3.1 on Ubuntu 20.04.

**Comment by nikolaglumac** [comment]
cc @darko-mijic @tomislavhoracek

**Comment by nikolaglumac** [comment]
cc @ManusMcCole

**Comment by ManusMcCole** [comment]
I tested this and my findings are in line with @nocmonkey. I restored the seed from my Ledger Nano S (balance of 15 ADA) on my Trezor Model T and it restores an empty wallet in Daedalus @nikolaglumac

**Comment by nikolaglumac** [comment]
What about restoring the same BTC wallet in both Trezor and Ledger?

**Comment by ManusMcCole** [comment]
Yes it seems they are standard across devices.I found this online "Ledger and Trezor support the same consensus standards and so the seeds are reversible. You can use a Ledger seed on Trezor, and you can use a Trezor Seed on Ledger, which we will go over today" at https://medium.com/@vasyavovich87/how-to-restore-ledger-wallet-with-trezor-wallet-seed-backup-ed5498d3588f. Is that sufficient confirmation ?

**Comment by ManusMcCole** [comment]
I tested it with my Ledger and Trezor and for BTC it restores the same wallet @nikolaglumac

**Comment by nikolaglumac** [comment]
OK thanks @ManusMcCole. This is very interesting and I guess we should have a broader discussion on this topic with @darko-mijic @KtorZ and @rvl.

**Comment by KtorZ** [comment]
Hi. This is "normal". Ledger and Trezor uses a different algorithm for generate root keys from seed. Trezor uses even a different method between 18-word phrases and 24-word phrases. You can find more details here: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md

Also: Cardano is not Bitcoin :blush: ...

**Comment by nikolaglumac** [comment]
Thanks @KtorZ! With that being said I will now close this ticket.
@nocmonkey we suggest you to use another Ledger device as a backup for Ledgers, and another Trezor device as a backup for Trezors. Thanks!
