### ISSUE TITLE
Pasting Recovery Phase removes spaces

### ISSUE THREAD

**Issue by adamwojt** [input-output-hk/daedalus#2419]
**Current Behaviour:**
Pasting space separated sequence of words into `Recovery phrase` text field removes spaces.
![image](https://user-images.githubusercontent.com/45100954/109612751-e0830500-7b38-11eb-85f1-9819c913589a.png)
**Expected Behaviour**
Spaces are preserved so that user can just click `Check recovery phrase`

**Comment by nikolaglumac** [comment]
Hi @adamwojt!

This is per design as we wanted to make sure users are not keeping their recovery phrases in a digital format as the only safe option is keeping it on a piece of paper.
However, there might be cases where pasting would be a good option.
We will give this another thought.

Thanks!

**Comment by adamwojt** [comment]
@nikolaglumac I personally think this is strange way to let user know that storing phrases digitally is not encouraged as this would come up after they would've already stored it digitally.

I think not being able to copy it when created might be enough? Just thinking at loud here.

Ps. Thanks for multi asset support, I am testing `flight` version and it's looking great!

**Comment by nikolaglumac** [comment]
> @nikolaglumac I personally think this is strange way to let user know that storing phrases digitally is not encouraged as this would come up after they would've already stored it digitally.

@adamwojt this is just a part of it. The wallet-creation wizard warns the user not to store the recovery phrase in a digital format too.

> I think not being able to copy it when created might be enough? Just thinking at loud here.

This is already implemented long ago.

> Ps. Thanks for multi asset support, I am testing flight version and it's looking great!

Glad to hear that 😄

**Comment by JamesRobertKelley** [comment]
I prefer to paste instead of type because of key loggers. I've actually pulled words out of the BIP list to drag and drop before.

**Comment by g4m3r0** [comment]
> 
> 
> I prefer to paste instead of type because of key loggers. I've actually pulled words out of the BIP list to drag and drop before.
Most keyloggers also log your clipboard.

**Comment by nikolaglumac** [comment]
This feature has been implemented in https://github.com/input-output-hk/daedalus/pull/2459 and is to be released in next Daedalus version.
Thanks for the patience 🙏

**Comment by nikolaglumac** [comment]
Hi all,

the fix for this issue has been released on Daedalus Flight within the 4.1.0-FC1 version: https://github.com/input-output-hk/daedalus/releases/tag/4.1.0-FC1
You can use the automatic update within existing  to get the new version or download it on the official Daedalus website: https://daedaluswallet.io/en/flight/

_PS: We will release the same fix on Daedalus Mainnet tomorrow around 16:00 UTC._

Thanks for the patience!

**Comment by nikolaglumac** [comment]
Daedalus Mainnet 4.1.0 has been released and includes this fix.
Thanks for the patience!
