### ISSUE TITLE
Why can't we allow volunteers to submit for more translations?

### ISSUE THREAD

**Issue by JasinYip** [input-output-hk/daedalus#2423]
Cardano is more and more famous, more and more people come from different countries. But now Daedalus wallet still only support English and Japanese. 

I found some of Cardano lovers sent pull requests for other language support but all been rejected for the internal maintain process reason. Reply by @nikolaglumac :

> at this moment in time, we can not accept additional translation as it would be hard to maintain it without internal translation/audit process.

![image](https://user-images.githubusercontent.com/7105264/109639150-d2110980-7b89-11eb-91d3-c9df00304d7f.png)

It's been two years and the internal translation is still **zero** release and still rejecting voluntary PRs, it doesn't make sense.

**Comment by nikolaglumac** [comment]
Hi @JasinYip!

> at this moment in time, we can not accept additional translation as it would be hard to maintain it without internal translation/audit process.

Unfortunately, we still suffer from the same problem...

You need to understand that every single line of text added to Daedalus needs to be proofread and translated into all languages Daedalus supports. This means that we need a dedicated translator and proofreader (as they can not be the same person) for every additional language we show in the UI (so it's 2 more people per single additional language). We can not rely on outside contributors for this as there are often times where we need to add last-minute changes and for those, we need to have internal people that are always present.
We **do appreciate** the intentions of people that wanted to contribute by adding translations for various languages, but we simply can not use those at the moment.

Still, I completely agree with you that we should start adding more languages. This is a product decision and @darko-mijic will manage this request.

Thanks for bringing this up and also thanks for the patience 🙏

**Comment by nikolaglumac** [comment]
I will close this issue as our process doesn't allow us to accept external contributions in terms of additional language translations. We are considering adding more languages and I hope we will be able to add them soon.
Thank you for your patience!
