### ISSUE TITLE
Daedalus.io Broken Link

### ISSUE THREAD

**Issue by alex-stout** [input-output-hk/daedalus#2430]
Hi,

I couldn't find the repo for the website, so I'm posting this here. The link to this repo is not working on the daedalus.io link.

The specific link that's not working is:
<img width="1581" alt="Screen Shot 2021-03-03 at 10 40 03 AM" src="https://user-images.githubusercontent.com/17804548/109839646-f104af80-7c0c-11eb-941c-8bdbe02327cd.png">

The link is pointed to `https://github.com/input-output-hk/input-output-hk` which is a GH 404.

**Comment by nikolaglumac** [comment]
What is the URL of this website @alex-stout?

**Comment by nikolaglumac** [comment]
I found it - will report to our web team. Thanks for reporting!

![Screenshot 2021-03-03 at 18 44 46](https://user-images.githubusercontent.com/376611/109848441-8ffecb00-7c50-11eb-9221-cf24b4989b93.png)

**Comment by nikolaglumac** [comment]
This has now been fixed! Thanks for reporting!
