### ISSUE TITLE
Cardano launcher fails, due to update 3.3.2

### ISSUE THREAD

**Issue by Benruren** [input-output-hk/daedalus#2435]
I downloaded the install file for the update but installation failed, and now I cannot start Daedalus. Thoughts?
![Capture](https://user-images.githubusercontent.com/59262178/109874437-08708680-7c67-11eb-915f-f952de10cfba.PNG)

**Comment by nikolaglumac** [comment]
Try restarting your machine. Most likely you had old version of Daedalus running while attempting to install/run the new one.

**Comment by Benruren** [comment]
> Try restarting your machine. Most likely you had old version of Daedalus running while attempting to install/run the new one.

Thank you, it worked just fine! It really is amazing how the simplest fix is generally the solution. I restarted and it allowed me to install and login. It took its sweet time to login but that he did. Thank you again!
