### ISSUE TITLE
Daedalus not connecting to network after update to 3.3.2

### ISSUE THREAD

**Issue by dadepo** [input-output-hk/daedalus#2438]
I recently upgraded Daedalus 3.3.2 and shortly after, the wallet could not connect to the network. This has been the case for over 24hrs now. 

I initially thought maybe my ISP was blocking the network, but I tried with TunnelBear VPN and still the same.

Here is the output of running `uname -a`:

`MacBook-Air-2.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64`

Any ideas what could be going wrong?

**Comment by dadepo** [comment]
Here is the logs, I downloaded it from the page that shows up after not being able to connect to the network. I thought it might be helpful to also have this.

[logs-2021-03-03T214251.0162Z.zip](https://github.com/input-output-hk/daedalus/files/6081919/logs-2021-03-03T214251.0162Z.zip)

**Comment by nikolaglumac** [comment]
Please try restarting the machine.

**Comment by dadepo** [comment]
I have tried restarting the machine also. That did not help

**Comment by dadepo** [comment]
Don't know if this has anything to do with the issue. But I withdraw some funds from an exchange to the wallet, and the signs of trouble started when the funds was not being reflected in my wallet. I then restarted the wallet and since then it has refused to be synced with the network

**Comment by nikolaglumac** [comment]
@dadepo we will check the logs. Thanks for the patience.

**Comment by nikolaglumac** [comment]
Logs point to some cardano-node errors:

```
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4229][0m [2021-03-03 21:42:24.09 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 54.176.152.50:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4230][0m [2021-03-03 21:42:24.12 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 3.129.177.185:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4231][0m [2021-03-03 21:42:24.15 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 18.132.163.206:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4231][0m [2021-03-03 21:42:24.17 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 18.132.163.206:3001 outcome: ConnectSuccessLast
[35m[Oluwadad:cardano.node.ErrorPolicy:Notice:42][0m [2021-03-03 21:42:24.17 UTC] IP 54.176.152.50:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[Oluwadad:cardano.node.ErrorPolicy:Notice:42][0m [2021-03-03 21:42:24.17 UTC] IP 3.129.177.185:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[31m[Oluwadad:cardano.node.DnsSubscription:Error:4231][0m [2021-03-03 21:42:24.27 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.132.163.206:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))
[33m[Oluwadad:cardano.node.ErrorPolicy:Warning:42][0m [2021-03-03 21:42:24.27 UTC] IP 18.132.163.206:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))))) 200s 200s
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4249][0m [2021-03-03 21:42:34.13 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 18.133.69.202:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4249][0m [2021-03-03 21:42:34.15 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 18.133.69.202:3001 outcome: ConnectSuccessLast
[31m[Oluwadad:cardano.node.DnsSubscription:Error:4249][0m [2021-03-03 21:42:34.23 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.133.69.202:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))
[33m[Oluwadad:cardano.node.ErrorPolicy:Warning:42][0m [2021-03-03 21:42:34.23 UTC] IP 18.133.69.202:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))))) 200s 200s
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4267][0m [2021-03-03 21:42:44.09 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 54.179.126.222:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4268][0m [2021-03-03 21:42:44.12 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 18.133.89.80:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4268][0m [2021-03-03 21:42:44.14 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 18.133.89.80:3001 outcome: ConnectSuccessLast
[35m[Oluwadad:cardano.node.ErrorPolicy:Notice:42][0m [2021-03-03 21:42:44.14 UTC] IP 54.179.126.222:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[31m[Oluwadad:cardano.node.DnsSubscription:Error:4268][0m [2021-03-03 21:42:44.22 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.133.89.80:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))
[33m[Oluwadad:cardano.node.ErrorPolicy:Warning:42][0m [2021-03-03 21:42:44.22 UTC] IP 18.133.89.80:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))))) 200s 200s
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4286][0m [2021-03-03 21:42:54.09 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 54.176.152.50:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4287][0m [2021-03-03 21:42:54.12 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 3.129.177.185:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4288][0m [2021-03-03 21:42:54.15 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt Start, destination 18.132.163.206:3001
[35m[Oluwadad:cardano.node.DnsSubscription:Notice:4288][0m [2021-03-03 21:42:54.18 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Connection Attempt End, destination 18.132.163.206:3001 outcome: ConnectSuccessLast
[35m[Oluwadad:cardano.node.ErrorPolicy:Notice:42][0m [2021-03-03 21:42:54.18 UTC] IP 54.176.152.50:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[Oluwadad:cardano.node.ErrorPolicy:Notice:42][0m [2021-03-03 21:42:54.18 UTC] IP 3.129.177.185:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[31m[Oluwadad:cardano.node.DnsSubscription:Error:4288][0m [2021-03-03 21:42:54.25 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.132.163.206:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))
[33m[Oluwadad:cardano.node.ErrorPolicy:Warning:42][0m [2021-03-03 21:42:54.26 UTC] IP 18.132.163.206:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 23231300, blockPointHash = 43fc3fab1c5e8c1460bc8b7be10caf1e1bc33805dd5a5da24fde8269969eadb9})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 4197609 (fromList [])) (Value 926826464 (fromList [])))))),LedgersFailure (LedgerFailure (UtxowFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = "972f7110522ed5a404a3f744a0467e2d2d1b54ca179b8d42c6390515626fec8c"}) 0])))))])})))))))))) 200s 200s
```

@rvl @dcoutts can you assist us here? 🙏

**Comment by PSLLSP** [comment]
I observe similar probem at Linux (Ubuntu).
Linux build 16919, Cardano Node 1.25.1, Cardano Wallet 2021.2.15

Sync status is 91.52% and it doesn't continue, Daedalus reports it cannot connect to network. I cannot see any problem with network connection and I see more than 200 GB of free disk space. I tried to restart wallet but issue is not fixed. Diagnostic screen reports that Cardano node is not syncing and it is not responding.
 This bug report is written on PC with Deadelus, is this a proof that my PC has network connectivity??

**Comment by nikolaglumac** [comment]
@PSLLSP can you also share your logs?

**Comment by eddex** [comment]
I have similar issues on Windows 10. I'm using a fresh installation of v3.3.2, never had the app or any other Cardano wallet installed on this system before.

Windows build 16919, Cardano Node 1.25.1, Cardano Wallet 2021.2.15
[logs-2021-03-04T153520.0574Z.zip](https://github.com/input-output-hk/daedalus/files/6085697/logs-2021-03-04T153520.0574Z.zip)

When I open the app, at first the "Cardano node syncing" seems to be ok (green). But the blockchain verification never goes above 0.00%. After a few minutes the loading screen shows up again, indicating that the Cardano node is not syncing.

I have tried to reboot my PC and restarted the app multiple times but it was always the same.

**Comment by nikolaglumac** [comment]
@PSLLSP @dadepo can you perhaps also check if the problem persists while using VPN?

**Comment by dadepo** [comment]
> @PSLLSP @dadepo can you perhaps also check if the problem persists while using VPN?

Yes. I did check with VPN yesterday, and also checked again now. Issue still persist

**Comment by PSLLSP** [comment]
My wallet is synchronized, I updated my first entry (https://github.com/input-output-hk/daedalus/issues/2438#issuecomment-790720515), I prepared log file.

**Comment by dadepo** [comment]
@nikolaglumac how much free disk space is required? It is currently stuck at 99.91% and I have 14.26GB free. Sounds okay?

**Comment by nikolaglumac** [comment]
> My wallet is synchronized, I updated my first entry ([#2438 (comment)](https://github.com/input-output-hk/daedalus/issues/2438#issuecomment-790720515)), I prepared log file.

So your issue has been resolved? 
Well, RAM size is not a bottleneck here. The initial syncing requires a lot of CPU and the cardano-node uses up to CPU cores which means they will most likely run flat out at that time...

**Comment by nikolaglumac** [comment]
> @nikolaglumac how much free disk space is required? It is currently stuck at 99.91% and I have 14.26GB free. Sounds okay?
> 
> edit: Also, I am running the wallet on the Mac, while the rest on this thread are running on Windows/Linux. So the issue might be different?

@dadepo yes that should be enough free space. Daedalus would warn you in case it detect you don't have enough free disk space. Sometimes it takes an unusually long time for Daedalus to connect to the network (more than 20 mins) so I advise you to stay patient and let it run for at least half an hour 🙏

**Comment by dadepo** [comment]
> so I advise you to stay patient and let it run for at least half an hour 🙏

I had it running overnight yesternight, still did not complete. I uninstalled it, deleted the data and I am currently restoring the wallet. At 98.99% now...so fingers crossed

**Comment by dadepo** [comment]
Ok, now another problem 😪

I had two wallets. I started restoring both wallets yesternight, and the progress was showing for both...then I woke up this morning and saw the progress was only showing for one of the two wallets.

The first wallet has finished synchronizing now and all seems fine.

But now I tried restoring the second wallet, but I kept getting an error where I need to put the spending password, as can be seen in the attached screenshot.

The problem is not the recovery phase, because I have used it a couple of times, and the error did not occur at that point. The error is occuring now when I attempt to set the spending password. And the error message is generic, so that does not even help with what could be going wrong

Please any suggestions?

![Screenshot 2021-03-05 at 09 49 00](https://user-images.githubusercontent.com/272535/110090833-05c17e80-7d98-11eb-8cfe-dc838727807e.png)

**Comment by dadepo** [comment]
Here are the new log files:

[logs-2021-03-05T085156.0527Z.zip](https://github.com/input-output-hk/daedalus/files/6089286/logs-2021-03-05T085156.0527Z.zip)

**Comment by nikolaglumac** [comment]
OK so in the logs I can see this error:

```
{"at":"2021-03-05T08:46:19.247Z","env":"mainnet:macOS:20.1.0","ns":["daedalus","v3.3.2","*mainnet*"],"data":{"error":{"code":"unexpected_error","message":"That's embarrassing. Your wallet looks good, but I couldn't open a new database to store its data. This is unexpected and likely not your fault. Perhaps, check your filesystem's permissions or available space?"}},"app":["daedalus"],"msg":"AdaApi::restoreWallet error","pid":"","sev":"error","thread":""}
```

This is an API error thrown by the cardano-wallet. I would suggest you to restart your machine and try again and let us know if that helped. If not, then we will have to raise this with the Adrestia team.

**Comment by dadepo** [comment]
I restarted and the second wallet pops up

...currently syncing at 95.2%

**Comment by dadepo** [comment]
Phew all synced now!

I must say, I get the impression that Daedalus still has a lot of rough edges and feels quite unstable. Probably something the Cardano crew is aware of already...but it definitely looks like more effort still needs to go into polishing things up.

Thanks for the help thus far, and I am quite happy that everything seems to be working fine...atleast for now!

**Comment by nikolaglumac** [comment]
I am happy your issue has been resolved!
There is always room for improvement and all of the Cardano teams are doing their best to provide our users with the best quality software. To be honest we don't get many reports such as yours... 
Still, Daedalus architecture is quite complex and it can happen that some of the components fail due to different platform configurations, network specifics, etc. These are almost impossible to avoid 😞 
This is why we are always here to help and to make sure you are able to use our software.
Thanks for the patience!

**Comment by dadepo** [comment]
Thanks for the help too! 🙏

**Comment by dadepo** [comment]
FYI: Getting disconnected again and not reconnecting :( 

It really looks like something went wrong with the latest release of Daedalus (or maybe the issue is somewhere else?) as I started using the wallet around December last year, and never experienced this level of connectivity issues until now.

**Comment by nikolaglumac** [comment]
Can you try Daedalus Flight? It has a newer version of cardano-wallet: https://daedaluswallet.io/en/flight/

**Comment by dadepo** [comment]
FYI, I am currently restoring the wallet. The same issue popped up after a recent upgrade. This seems to always happen with new upgrades. Perhaps something to look into?

**Comment by nikolaglumac** [comment]
@dadepo this is due to the change in the cardano-node's block storage mechanism as described in the release notes: https://iohk.zendesk.com/hc/en-us/articles/900006759746-Daedalus-4-1-0-release-notes

> After upgrading, you will need to wait at least 30 minutes for Daedalus to start. This is due to changes in the block storage mechanism which requires a full verification of the locally-stored copy of the Cardano blockchain.

It is indeed awkward but there is nothing we can do on our end :-( 

Thank you for your patience! 🙏
