### ISSUE TITLE
Synchronization with the blockchain not working. DNS server fail-over issue.

### ISSUE THREAD

**Issue by eddex** [input-output-hk/daedalus#2442]
This is related to my [comment](https://github.com/input-output-hk/daedalus/issues/2438#issuecomment-790813158) in #2438.

**System information**

Daedalus v3.3.2
Windows build 16919, Cardano Node 1.25.1, Cardano Wallet 2021.2.15

**Problem**

When I open the daedalus app, at first the "Cardano node syncing" seems to be ok (green). But the blockchain verification doesn't proceed (stays at the current percentage). After a few minutes the loading screen shows up again, indicating that the Cardano node is not syncing.

**Additional information**

The DHCP server in my network is configured to provide 2 different DNS servers. The first is a [Pi-Hole](https://pi-hole.net/). The Pi-Hole DNS server may or may not be running. Therefore a second DNS server (the router) is sent by the DHCP server.

Usually Windows and any other apps are trying to connect to the first DNS server (Pi-Hole). If it's available, the first DNS server (Pi-Hole) is used. Otherwise a fail-over is applied and the second DNS server (router) is used.

It seems like the daedalus wallet can't handle this situation. Using [Wireshark](https://www.wireshark.org/) to look at the network traffic, I see many requests to the first DNS server (Pi-Hole) which is not running. As soon as I start the Pi-Hole DNS server, the blockchain synchronization starts working.

**Comment by eddex** [comment]
Don't know if this is related, but now after I was successfully able to sync the blockchain, my wallet doesn't sync.

In the logs I can see the following error: 
`[31m[cardano-wallet.wallet-engine:Error:25][0m [2021-03-06 12:39:38.04 UTC] c0d523e1: Unexpected error following the chain: user error (restoreBlocks: given chain isn't a valid continuation. Wallet is at: 5f20df93<-[d2d90d10-0#0] but the given chain continues starting from: 5f20df93<-[89d9b5a5-0#0])`

**Comment by nikolaglumac** [comment]
@eddex please submit a ticket here: https://iohk.zendesk.com/hc/en-us/requests/new
Make sure you add all the details and the Daedalus logs.
