### ISSUE TITLE
Consume a lot of ressources at launch

### ISSUE THREAD

**Issue by GabScher** [input-output-hk/daedalus#2448]
Hi,
When I launch Deadalus app, it uses about half of my CPU ressources and my MacBook Pro heats up to 80°C which is inconvenient. Is is normal? Until now, I didn't want my computer to be that hot so I systematically killed the app...

My conf is a 2018 MacBook Pro, 4 cores 8Go Ram up to date.
Thanks

**Comment by nikolaglumac** [comment]
This normal during the initial syncing process as it is CPU intensive.
Once Daedalus gets fully synced it won't need so much CPU and thus it won't consume so much resources nor heat up your MacBook.
