### ISSUE TITLE
Copied Ledger Wallet can't be accessed anymore

### ISSUE THREAD

**Issue by pheelLikeWater** [input-output-hk/daedalus#2455]
When copying the Wallet from one to another device or e.g. from Daedalus Main to Flight Wallet folder, I cannot access the Wallet anymore.
This might be correct because of privacy issues.

The issue:
But when I click on the Wallet within Daedalus I am getting a message, where I shall change my password, which is not working and well. But for a user it is misleading because I am always getting a "wrong password" message that does not make any sense.

What I want to have:
Maybe a better solution would be to remove the password change dialog with an authorization dialog for Ledger/Trezor. Where a user can reauthorize its Ledger Wallet.

If I am totally wrong, please do not take it amiss :D.

**Comment by nikolaglumac** [comment]
You are not supposed to do that. This is not an option Daedalus supports as the other Daedalus instance thinks that your Ledger wallet is a software wallet as you can not copy all the data from the other instance.
