### ISSUE TITLE
Blank Window While SSH X FWD Remote Access

### ISSUE THREAD

**Issue by dinobagio** [input-output-hk/daedalus#2469]
Hi,

I'm sorry if the place is not appropriate for this kind of question,

My ENV

  "env": "mainnet:Linux:5.4.105-1-MANJARO",
  "ns": [
    "daedalus",
    "v3.3.2",
    "*mainnet*"
  ],
  "data": {
    "cardanoNodeVersion": "1.25.1",
    "cardanoWalletVersion": "2021.2.15",
    "cpu": "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz",
}

Daedalus launch OK while accessing through my MANJARO xfce desktop,

But empty window when accessing through remote SSH/X Forwarding,

Any idea why ?

**Comment by nikolaglumac** [comment]
Hi @dinobagio!
MANJARO is not officially supported platform but perhaps @cleverca22 can help us out here 🙏 
Thanks!

**Comment by katakombi** [comment]
This issue should be independent on the distribution being used. Have you tried to run x11vnc on the server side and connect via xfreerdp?

**Comment by dinobagio** [comment]
No but i can try,

But it's weird because I can access all the other apps this way, i mean
using XoSSH.

What could cause this ?

Maybe missing some ENV params ?

Can you try on your side so that I can understand whether it's related to
my ENV or not ?

**Comment by katakombi** [comment]
I tried it using Linux Mint 20. The window shows up but it stays blank white and nothing is being displayed.

**Comment by dinobagio** [comment]
Same as in my case then.
Which window manager ?
Xfce/cinnamon/kde ?

**Comment by katakombi** [comment]
Mate. No compositing, no desktop effects.

**Comment by dinobagio** [comment]
Ok then I'll try to debug window rendering,

What is interesting in x forward is that it's more efficient than vnc
remote which takes the whole desktop.

Can daedalus logs can help tu understand ?

**Comment by katakombi** [comment]
No. Logs look perfectly fine. No errors.

**Comment by dinobagio** [comment]
I've seen a similar issue here :
https://github.com/electron/electron/issues/22775

Can you tell me whether you use shared memory, and if we can prevent daedalus yo use it in such case ?

**Comment by katakombi** [comment]
Thanks to this electron issue I could make it work:
`
DEBUG_SHELL=1 ~/.local/share/Daedalus/mainnet_flight/namespaceHelper
`
You enter a shell. The launch daedalus within the sandbox:
`
QT_X11_NO_MITSHM=1 daedalus
`
It is effing slow but it works. But the alternative is to bind mount /tmp/.X11-unix and /dev/shm which I couldn't succeed in. Maybe the devs can implement a switch...

**Comment by dinobagio** [comment]
OK thank you It worked for me as well,
Could remote access my wallet.
Anyway, for sure a switch (~ --no-xshm) would much appreciated,
To be continued...

**Comment by danielmain** [comment]
If you have more questions, pls contact us
