### ISSUE TITLE
Daedalus in docker container - Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by laplasz** [input-output-hk/daedalus#2477]
Dockerfile:
```
FROM ubuntu:20.04
RUN apt-get update; apt-get -y install bsdmainutils tzdata libcanberra-gtk-module libcanberra-gtk3-module
RUN groupadd -g 64000 wallet
RUN useradd -ms /bin/bash wallet -u 64626 -g 64000
USER wallet
ENV HOME /home/wallet
ADD daedalus-3.3.1-mainnet-16693.bin /home/wallet
WORKDIR /home/wallet
#RUN sh daedalus-3.3.1-mainnet-16693.bin
CMD bash
```
docker run:
```
docker run -it -u wallet --privileged -e DISPLAY=$DISPLAY -v $HOME/.Xauthority:/home/wallet/.Xauthority -v /tmp/.X11-unix:/tmp/.X11-unix --network host --name daedalus daedalus bash
```
installation was successful, buy running `.local/bin/daedalus-mainnet` the window of Daedalus displayed but without any content.
And getting the following error:
```
[launcher:Notice:11] [2021-03-25 13:12:31.08 UTC] Locking file so that multiple applications won't run at same time
[launcher:Info:11] [2021-03-25 13:12:31.08 UTC] Generating the certificates!
[launcher:Info:11] [2021-03-25 13:12:31.31 UTC] Does update installation exist: UpdaterDoesntExist
[launcher:Error:11] [2021-03-25 13:12:31.31 UTC] The updater file is missing!
[launcher:Notice:11] [2021-03-25 13:12:31.31 UTC] Starting the wallet with arguments: WalletArguments {getWalletArguments = []}
/nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
/nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
Gtk-Message: 13:12:32.090: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:12:32.092: Failed to load module "canberra-gtk-module"
```
I am using docker because on the host machine I getting this error: #2115
can you help me on this one?

**Update:** using virtulabox now it working even I am getting this warning. Probably X11 issue like in #2350? 

THanks

**Comment by nikolaglumac** [comment]
This indeed sounds like the same issue as https://github.com/input-output-hk/daedalus/issues/2350
Virtualbox should work fine - we use it all of the time so this issue must be some misconfiguration on your side.
I suggest you to debug your setup or perhaps try running Daedalus with the "Blank screen fix" mode on:
![Screenshot 2021-04-22 at 09 08 14](https://user-images.githubusercontent.com/376611/115670970-4b3b0a80-a34a-11eb-91d3-dc62345862f1.png)
(it should be reachable from the Daedalus application menu even if the window is blank)

**Comment by laplasz** [comment]
So does this mean that Daedalus is not supported running in a docker container?

**Comment by nikolaglumac** [comment]
It is not officially supported: https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements
