### ISSUE TITLE
Cannot install Daedalus 3.3.2 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by fighterleslie** [input-output-hk/daedalus#2478]
Following the instruction [here](https://iohk.zendesk.com/hc/en-us/articles/900000776446), I can't install `daedalus-3.3.2-mainnet-16919.bin` on a Ubuntu 18.04 LTS laptop successfully. The error message is below:

> ./nix/store/apzfc51a2aki7xdyzifldp1nm4w8a1am-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory

Following is my `/etc/nix/nix.conf`:

> substituters = https://hydra.iohk.io https://cache.nixos.org/
> trusted-substituters =
> trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
> max-jobs = 2  # run at most two builds at once
> cores = 0     # the builder will use all available CPU cores
> extra-sandbox-paths = /System/Library/Frameworks
> build-users-group =

The laptop has 4 CPUs, 16GB memory, 66GB available SSD disk space.

**Comment by fighterleslie** [comment]
It's 10 days and no one replied, I'll close this.

**Comment by nikolaglumac** [comment]
Sorry @fighterleslie - I was on leave up until today.
@ManusMcCole @miorsufianiohk @gabriela-ponce can someone check this please?

**Comment by ManusMcCole** [comment]
Hi @fighterleslie. I was unable to reproduce the issue you are having on Linux Ubuntu 18.04. Could you try with the newest production version of [Daedalus](https://daedaluswallet.io/en/download/). Hopefully this will solve the issue. If the command to run ./daedalus-2.5.0-mainnet-15326.bin is not working you could try bash ./daedalus-2.5.0-mainnet-15326.bin also directed at the folder containing the Daedalus download

**Comment by fighterleslie** [comment]
> Hi @fighterleslie. I was unable to reproduce the issue you are having on Linux Ubuntu 18.04. Could you try with the newest production version of [Daedalus](https://daedaluswallet.io/en/download/). Hopefully this will solve the issue. If the command to run ./daedalus-2.5.0-mainnet-15326.bin is not working you could try bash ./daedalus-2.5.0-mainnet-15326.bin also directed at the folder containing the Daedalus download

@ManusMcCole Thank you for your reply. Actually I successfully installed daedalus-3.3.2-mainnet-16919.bin on another Ubuntu 16.04 laptop, although Ubuntu 16.04 is not officially supported. I think some libraries on my Ubuntu 18.08 OS may be broken.

You can leave this issue closed.
