### ISSUE TITLE
Daedalus 3.3.2 - Kernel panic (GPUWatchdog) on macOS 10.15.7

### ISSUE THREAD

**Issue by mreed911** [input-output-hk/daedalus#2481]
[Daedalus Mainnet Helper (GPU)_2021-03-26-152448_Mikes-Office-Mac-Mini.crash.zip](https://github.com/input-output-hk/daedalus/files/6214673/Daedalus.Mainnet.Helper.GPU._2021-03-26-152448_Mikes-Office-Mac-Mini.crash.zip)

Under heavy load, I opened Daedalus.  Everything froze.  I waited, but the watchdog panic'ed the system and I got to reboot.

I'm attaching the unsymbolicated log here and can provide anything else asked.
```
Process:               Daedalus Mainnet Helper (GPU) [56078]
Path:                  /Applications/Daedalus Mainnet.app/Contents/Frameworks/Daedalus Mainnet Helper (GPU).app/Contents/MacOS/Daedalus Mainnet Helper (GPU)
Identifier:            Daedalus Mainnet Helper (GPU)
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Frontend [56067]
User ID:               502

Date/Time:             2021-03-26 15:22:57.877 -0500
OS Version:            Mac OS X 10.15.7 (19H524)
Report Version:        12

Crashed Thread:        1  GpuWatchdog

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [56078]
```

**Comment by nikolaglumac** [comment]
@mreed911 can you please update to latest Daedalus 4.0.5 and try again?

**Comment by nikolaglumac** [comment]
@mreed911 any news?

**Comment by mreed911** [comment]
Haven't seen it since - but only saw it once.  Only filed to submit the logs just in case.  Welcome to close/can't reproduce.

**Comment by nikolaglumac** [comment]
Alright! Will close it then. Feel free to re-open it in case it happens again!
Thanks for the support!
