### ISSUE TITLE
Daedaus Flight fails to sent One Hundred of Quadrillion Cardano's Native Tokens

### ISSUE THREAD

**Issue by WhitemanE0** [input-output-hk/daedalus#2487]
I've minted the 9,223,372,036,854,775,807 tokens I've called ATHOMs.
Nine Quintillions and some.
Although Daedaus Flight is able to diplay the amount correct, it's unable to sent A Hundred of Qadrillions ATHOM's, giving at amount of Assets to be sent an error "Please give a valid Amount". But don't see what is an issue to  send A Hundred of Quadrillions ATHOM's and more till the total CAP of Nine Quintillions. [https://whiteman.ru/blockart/daedalus_bug.png](proofpic).

FYI: While experementing with the minting of maximum possible amount of Assets I found bugs in every tool I've used: cardano-cli, Daedaus and Yoroi. I will report them separately, but generally I kindly advice respectable development team be aware of checking upper limits of everything.

**Comment by matiwinnetou** [comment]
I think this fixes it: https://github.com/input-output-hk/cardano-wallet/pull/2676

**Comment by nikolaglumac** [comment]
Not entirely... We also need this one: https://github.com/input-output-hk/daedalus/pull/2472

**Comment by nikolaglumac** [comment]
The fix for this one has been included in Daedalus Flight 4.2.0-FC1.
The issue still persists on hardware wallets but should not be there on software ones.
@WhitemanE0 can you please give it a go?

**Comment by nikolaglumac** [comment]
The fix for this one has been released in Daedalus Mainnet 4.2.0.
Thanks for the patience!
