### ISSUE TITLE
Better token info display

### ISSUE THREAD

**Issue by morrigan** [input-output-hk/daedalus#2502]
It's great that native tokens are supported but the display of the token name is kinda secondary and feels like lacking the UX user is expecting.

![image](https://user-images.githubusercontent.com/4976604/113415004-8f2b9700-93be-11eb-9681-ccaeeec21277.png)

Would be great if through the app token name is clearly visible rather than some non-user friendly ids.

**Comment by nikolaglumac** [comment]
ASCII names are misused. These are NOT supposed to be used as "the name" of the token. The real name is a part of the token's metadata which the creator of the token needs to register. Soon this will be possible here https://github.com/input-output-hk/cardano-metadata-submitter/#readme

This is how it will look like (screenshots are from the live Testnet Daedalus version):
![image](https://user-images.githubusercontent.com/376611/114367665-f1ce2100-9b7c-11eb-92f6-05c5fbf02019.png)
![image-1](https://user-images.githubusercontent.com/376611/114367676-f4307b00-9b7c-11eb-99d8-569bff41be34.png)
