### ISSUE TITLE
Import Wallet Via Daedalus State Directory and Secret.Key File but no ADA in it

### ISSUE THREAD

**Issue by olafeyikan** [input-output-hk/daedalus#2507]
Hi, in 2017 I created 2 wallets in same application (Daedalus wallet) gave both different password. Fast forward 2019 I deleted the wallet as I can not remember the passwords. 

I used the 12 recovery phrase and was able to restore 1 of the wallet, the second is yet to be restored, I have used both the State Directory and Secret.Key from my desktop to restore the wallet but all to no result, I saw the history and transactions from my first wallet the second is still 0 ADA. Is there something I am doing wrong?

**Comment by KtorZ** [comment]
@olafeyikan I've transferred your issue to Daedalus as it seems to be a better fit. Could you clarify the situation a little because I am unclear with your explanations :thinking: 

Let me try to re-formulate:

- You had 2 wallets, created during the Byron era. 
- You do have two 12-word recovery phrases, one for each wallet.
- You do also still have your state directory from 2017, and the secret.key from it. 
- You have restored your first wallet successfully; could see the history and a balance you expected.
- You have tried restoring your second wallet using:
    - The recovery phrase
    - The secret.key
   and either ways, the wallet appears to have an empty balance.


Is that correct? 
Do you see any transaction in the history of the second wallet? 
Is your local node fully synced with the blockchain? Are the wallet synced?

**Comment by olafeyikan** [comment]
Do you see any transaction in the history of the second wallet? **NO (only in the first wallet)**
Is your local node fully synced with the blockchain? Are the wallet synced? **YES** 

You had 2 wallets, created during the Byron era. **YES**
You do have two 12-word recovery phrases, one for each wallet. **Yes**
You do also still have your state directory from 2017, and the secret.key from it. **I have only 1 State directory and 1 secret.key file as the second wallet was created / added after the first on the same Daedalus wallet**
You have restored your first wallet successfully; could see the history and a balance you expected. **Yes**
You have tried restoring your second wallet using: **Here is what is interesting I have 1 State Directory and 1 Secret.key should i have 2?**
The recovery phrase
The secret.key
and either ways, the wallet appears to have an empty balance.

**Comment by olafeyikan** [comment]
Any idea what i should do please?

**Comment by olafeyikan** [comment]
Hello again support team: 

If I have 2 wallets on the same Daedalus application does that mean I will have 2 Daedalus State Directory or Secret.key files? this is what happened to me, I created 2 wallets on the same Daedalus Application running on my desktop. today I rimport wallet and can only see the primary wallet and its transaction details, I can not see the other transaction from the other wallet. 

Is this normal?

**Comment by nikolaglumac** [comment]
@olafeyikan if you have the 12-word wallet recovery phrases for both wallets, then there is no point of discussing the "state directory / secret.key" aspect of it as you don't need those.

If after restoring a wallet from your wallet recovery phrase you get no transaction history and a zero balance I am 100% sure you are not using the correct recovery phrase.

Perhaps you only used the first of these two wallets?
Are you 100% sure the second wallet (which now appears empty) was ever used?

**Comment by olafeyikan** [comment]
Hi Nikolaglumac, thank you for your response, Yes i had 2 wallets created within application, I wrote the second 12 -  word out for both and for some reasons i could restore one, this was what lead to me restoring via the state directory / secret.key. So yes you are correct after restoring the second wallet from state directory / secret.key, I got no transaction history and a zero balance.

regards,

**Comment by nikolaglumac** [comment]
Thanks for clarifying that @olafeyikan.
This leads me to believe that the second wallet you restored has never been used and thus has no transaction history and zero balance. There is no other way for this to happen - especially since you tried both the wallet recovery phrase restoration as well as importing wallets from your secret.key file.
Please try hard to remember if you ever used that wallet or if you have some track of the transactions you know were made from or to it.
Thanks!

**Comment by olafeyikan** [comment]
Hi again, I understand, but i did created the second wallet.

**Comment by nikolaglumac** [comment]
But have you ever used it? Each wallet you create in Daedalus has it's own wallet recovery phrase, it's own addresses, transaction history, and a balance.
If you have only created it but never sent any funds to it, then it is supposed to be empty.

**Comment by olafeyikan** [comment]
I did send funds into it in 2017, but did not send out of it. I send funds from Binance into it.

**Comment by nikolaglumac** [comment]
Can you please find the transaction ID and send it to us? We need to confirm that the transaction was successful.

**Comment by olafeyikan** [comment]
is it safe to send it here?

**Comment by nikolaglumac** [comment]
Feel free to either open a support ticket: https://iohk.zendesk.com/hc/en-us/requests/new
... or send transaction details directly to me at nikola.glumac@iohk.io

**Comment by olafeyikan** [comment]
I just sent it over to you..

**Comment by nikolaglumac** [comment]
Are you sure this was the only transaction made from and to that wallet?

**Comment by olafeyikan** [comment]
Yes i am sure, I have not reason to lie, I tried to send it to a paper wallet when i did not remember my password but i did not have success doing that. so i deleted both wallets since I could not retrieve the passwords.

**Comment by nikolaglumac** [comment]
So let me get this straight, these are the steps you took:
1. Created this wallet
2. Sent one transaction to that wallet which was successful and you were able to see that transaction in the wallet's history and the balance was correct
3. You tried to send that ada from that wallet to a paper wallet but failed to do so
4. Then you deleted it from Daedalus
5. You tried to restore it from a state directory and a recovery phrase and have found this wallet to be empty and has no transaction history?

**Comment by olafeyikan** [comment]
that is correct. when i did the transfer from Binance to my wallet i got the balance there. It was there for months, then i did not remember the password, so i tried to send it all to a paper wallet, i believe without the correct password the paper wallet thing did not work either, still a novice and trying to understand how to do the whole thing.. 

I hope this all make sense. But you are correct..

**Comment by nikolaglumac** [comment]
We have concluded the wallet recovery phrase and the state-directory/secret.key are not matching the wallet @olafeyikan was trying to find. Seems like the 2nd wallet was not matching the one which had funds sent to it.
Please remember that the secret.key file contains only wallets that were visible in the Daedalus UI at that point in time as if you delete a wallet it also gets removed from the secret.key file. That is what happened here.
I hope @olafeyikan you will be able to find a correct wallet recovery phrase or perhaps locate a backup of the state directory from the time you had this wallet in Daedalus UI 🙏
