### ISSUE TITLE
Staking Process is Painful and shows the wrong amount?

### ISSUE THREAD

**Issue by colemickens** [input-output-hk/daedalus#2508]
I drug the slider to "2,000", then picked a pool, then went through everything and signed the transaction, and then at the end, this is the confirmation I got. I don't know if this is a localization issue, but it's a bit alarming.

![wat2](https://user-images.githubusercontent.com/327028/113775994-49344300-96de-11eb-9ce2-1353bb02cb2e.PNG)

This thing is way too slow to be considered usable, too, imo. (20-40+ seconds to load on a gigabit connection?)

Oh my god, no it switched back to the slider and then I moved it and now I have to start the wait all over again. Truly, please understand I say this for effect, not to be mean, this is not usable, I'm losing interest in making it work here quickly. **Please remove the slide on the staking screen**.

**Comment by nikolaglumac** [comment]
@colemickens can you please clarify what you see as a wrong amount / localization issue on the confirmation dialog?

**Regarding the performance issues and the slider**
Stake pool rankings and potential rewards are depending on the amount of stake you wish to delegate.
This is why we have the slider. Sure, it is painfully slow - but this has nothing to do with your Internet connection speed.
The data is being processed locally by the locally running cardano-node/cardano-wallet which takes a lot of time since there are many stake pools nowadays. The respective teams are working on performance improvements and I hope we will be able to have them in Daedalus soon.

**Comment by colemickens** [comment]
I had selected **2000** units of ADA to stake, then when I clicked a pool and went through the process and got to the very end, I got the screenshot above show "2.000000 units of ADA".

RE: performance, I thought the stake pool ratings were leveraging IOHK's SMASH servers? The description of this makes it sound like its meant to address this exact thing?

Maybe if this were fast, the slider UX would make sense? But as is I still feel like just letting me type in a number (that is the same as what shows up in the confirmation ) would be better.

**Comment by nikolaglumac** [comment]
> I had selected 2000 units of ADA to stake, then when I clicked a pool and went through the process and got to the very end, I got the screenshot above show "2.000000 units of ADA".

You have misunderstood the meaning of "Deposit". This has nothing to do with the value of the slider.
You are always delegating **all the funds** you have in your wallet.
The deposit is required only for your first-ever delegation as your wallet's delegation certificate needs to be registered on the chain. Every subsequent delegation preference change will not include a deposit.

> RE: performance, I thought the stake pool ratings were leveraging IOHK's SMASH servers? The description of this makes it sound like its meant to address this exact thing?

SMASH servers only speed up the process of fetching stake pool metadata and that is not the cause of the performance degradation. There are many many factors that the cardano-wallet needs to take into account when it comes to ranking the list of stake pools based on the stake you have selected to delegate.

> Maybe if this were fast, the slider UX would make sense? But as is I still feel like just letting me type in a number (that is the same as what shows up in the confirmation ) would be better.

You have misunderstood the point of "Deposit".

**Comment by colemickens** [comment]
Oh. I see. I guess maybe this be changing (I hope I get this right) since I think the ability to stake to different pools from one wallet is coming soon?

Anyway, thank you for the multiple detailed replies; you are correct, I have indeed misunderstood, it's now clicked into place a bit better, thank you for taking the time. Given this all seems by-design I'll close this out.

**Comment by nikolaglumac** [comment]
Happy to help @colemickens 😎
