### ISSUE TITLE
UI: Rightmost column of stake pools are not visible (in grid view). 

### ISSUE THREAD

**Issue by strongheart1** [input-output-hk/daedalus#2513]
In the example screenshot below the following stake pools are not visible: no. 16, 32, 48, 64 .... 
(depending on the window size).
DAEDALUS 4.0.4; Linux build 17475

![Screenshot](https://user-images.githubusercontent.com/35747159/114089782-daf6a880-98b6-11eb-8f5c-41b9af5ef6fa.png)

**Comment by nikolaglumac** [comment]
Thanks for reporting this @strongheart1 - we are looking into it!

**Comment by nikolaglumac** [comment]
This issue has been fixed in https://github.com/input-output-hk/daedalus/pull/2517 and released in Daedalus 4.0.5.
Thanks for reporting it! 🙏
