### ISSUE TITLE
Unsupported firmware

### ISSUE THREAD

**Issue by europound** [input-output-hk/daedalus#2516]
trezor t Firmware version
Your current firmware version is 2.3.5.

Up to date

daedalus 4.0.4

why is that?

**Comment by nikolaglumac** [comment]
@europound can you clarify please?
What message are you seeing and where?
Screenshot and more context would help us a lot.

cc @tomislavhoracek

**Comment by tomislavhoracek** [comment]
@europound That means you need to update your Trezor device firmware.
Just follow these instructions: https://wiki.trezor.io/User_manual:Updating_the_Trezor_device_firmware

**Comment by nikolaglumac** [comment]
Thanks @tomislavhoracek!

@europound please update your Trezor to firmware version **2.3.6** by following the steps from https://wiki.trezor.io/User_manual:Updating_the_Trezor_device_firmware
