### ISSUE TITLE
Wallet not open NewsFeed

### ISSUE THREAD

**Issue by marcondesmacaneiro** [input-output-hk/daedalus#2522]
Version 4.0.5#17596

In Windows 10, Daedalus not open the NewsFeed.

Daedalus Flight open normaly

![erro_daedalus](https://user-images.githubusercontent.com/113733/114884179-f0e6fa80-9ddb-11eb-8f04-dae0b309a331.png)

**Comment by nikolaglumac** [comment]
It works fine on macOS 🤔 
@miorsufianiohk can you please check it out on Windows 10?

**Comment by miorsufianiohk** [comment]
Hi @marcondesmacaneiro ,

Thank you for contacting us. I attempted to replicate the issue that you raised but unfortunately was not successful. Could you please kindly restart Daedalus and retry. If the issue remains, it would be great if you could take a video of it + full details of your operating system (ie the maker, specs + touchscreen or not etc).

I look forward to receiving your reply in due course.

Many thanks,
Mior

**Comment by marcondesmacaneiro** [comment]
my computer doesn't have touch screen. But today the wallet show normally the news feed.
