### ISSUE TITLE
Missing Wallet Balance – Daedalus 4.0.5

### ISSUE THREAD

**Issue by Tranilator** [input-output-hk/daedalus#2523]
Hi there,

After update from 4.0.4 to 4.0.5, wallet balance and conversion options no longer appear in primary the summary window:

![image](https://user-images.githubusercontent.com/38444216/114964423-10e8ed80-9eb2-11eb-8de7-f5c960479d66.png)

Thanks!

**Comment by nikolaglumac** [comment]
Hi! This is a known issue due to a change in the conversion currency formats and here's a quick fix: https://iohk.zendesk.com/hc/en-us/articles/900005736566

**Comment by Tranilator** [comment]
Thanks for pointing me in the right direction 🙂
