### ISSUE TITLE
Linux cardano-cli path?

### ISSUE THREAD

**Issue by alex-stout** [input-output-hk/daedalus#2524]
I just switched over to Ubuntu. Is there a way to use the cardano-cli similar to how you can use it on MacOS?

**Comment by nikolaglumac** [comment]
@alan-mcnicholas can you help us out here? I am not sure if cardano-cli is available on Ubuntu...

**Comment by alan-mcnicholas** [comment]
The cardano-cli (and other binaries) are installed to the nix store; you can find the path with the following:
```ls -l ~/.daedalus/nix/store/*daedalus*/bin/*cardano-cli```
I hope this helps :)

**Comment by nikolaglumac** [comment]
Thanks @alan-mcnicholas 🙏

**Comment by alex-stout** [comment]
Thank you!

**Comment by alex-stout** [comment]
@alan-mcnicholas Got the chance to try executing the cli on my machine and I'm getting a `No such file or directory` error. It's weird because I'm running a 64-bit system and the file does exist and is executable.

Sorry to open back up this issue...

**Comment by alan-mcnicholas** [comment]
No worries! I should have tried it on my own system before recommending it, I am digging further and hope to have an answer asap. This is not a supported scenario as part of Daedalus so while there are no guarantees, I will do my best.

**Comment by alan-mcnicholas** [comment]
The binaries can only be ran in the chroot in this instance. An alternative would be to download the cardano artifacts directly https://hydra.iohk.io/build/6092531/download/1/cardano-node-1.26.2-linux.tar.gz and use them as such, this is beyond the realm of Daedalus however. I hope this helps! :)

**Comment by alex-stout** [comment]
Awesome. Thank you very much
