### ISSUE TITLE
Delegations Pools Have Same Rank

### ISSUE THREAD

**Issue by dinobagio** [input-output-hk/daedalus#2528]
Hi,
Not sure if it's wrong or not but I have two wallets, which I've delegated to two different SPO,
When I go to the delegation center tab, I can see these delegations for my two wallets, but the 2 distinct SPOs have the same rank displayed,
Is that possible ?
Thanks in advance

![daedalus_same_ranks](https://user-images.githubusercontent.com/16324000/115365535-c2df2d00-a1c4-11eb-9fd6-21701870bbbb.png)

Dadedalus Mainnet 4.0.5

**Comment by nikolaglumac** [comment]
@dinobagio this is expected. The stake pools you are delegating to do are unranked. The last ranked pool has the rank of 553.

![Screenshot 2021-04-20 at 10 54 42](https://user-images.githubusercontent.com/376611/115367895-dee3ce00-a1c6-11eb-81b6-601791ecf6e0.png)

**Comment by dinobagio** [comment]
Oh OK ! Apologies.

**Comment by nikolaglumac** [comment]
No worries - it is always better to ask 🙂
