### ISSUE TITLE
Missing stake pool

### ISSUE THREAD

**Issue by AJFunk** [input-output-hk/daedalus#2532]
I recently registered a stake pool under the TREES ticker, but it does not show up in Daedalus.

It works in Yoroi, ADAPools (https://adapools.org/pool/010135d6c273b169481091d1b1486ec8e21b978de354c1572f3c4429) and other sites.

I recently discovered that this ticker was used already and retired
https://adapools.org/pool/b98514bb7c8fe8efaa6762d6ae811ad2fbb783653f7af1aba12ba201

I'm guessing that Daedalus may be filtering out my stake pool because it shares a ticker with a retired one?

**Comment by tomislavhoracek** [comment]
Thank you for contacting us @AJFunk  . We will check this and get back to you.

**Comment by nikolaglumac** [comment]
@AJFunk did you make sure your stake pool is listed on SMASH?

You can call the Smash-Server like:
`https://smash.cardano-mainnet.iohk.io/api/v1/metadata/<poolid>/<metahash>`
* Replace the with your Pool-ID in hex or bech format and with your Meta-Hash in hex.

If it isn't then Daedalus won't show it.

**Comment by AJFunk** [comment]
After doing some more digging, I think the issue is on my end. I updated to pool metadata.json, but I did not create a new metadata hash and resubmit my registration certificate with the updated hash.

Thank you for taking a look!
