### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by pieterhouwen** [input-output-hk/daedalus#2535]
When I leave Daedalus open for a longer period of time to keep up with the blockchain it sometimes goes up to 3,5 GB RAM usage. Why is this necessery and how can I lower this?

**Comment by nikolaglumac** [comment]
@pieterhouwen can you please send us a screenshot of the memory usage stats?
Daedalus runs couple of processes, including cardano-node and cardano-wallet, and we need to know which of these is using most of this memory 🙏

**Comment by pieterhouwen** [comment]
![Screenshot 2021-04-23 093535](https://user-images.githubusercontent.com/10866686/115836045-4beda280-a417-11eb-94bd-825f3b6f55bd.png)

**Comment by nikolaglumac** [comment]
Thanks @pieterhouwen! We will investigate this and get back to you. Thanks for the patience!

@gabriela-ponce @ManusMcCole can you please try to reproduce this?
Please give it a shot on all 3 platforms and make sure to keep an eye on all Daedalus processes (including cardano-wallet and cardano-node). Thanks!

**Comment by gabriela-ponce** [comment]
@nikolaglumac I was able to reproduce this in Windows and in macOS (still checking Linux, I'll add my results on this comment later)
[Here's a video](https://drive.google.com/file/d/1tSvBrrfW_1FDN_qy9PZzOVUM4ucPK2d0/view?usp=sharing) from Windows. In the span of 5 minutes, the memory usage reaches 4 GB (I started capturing the video when I first open Daedalus, it was synced and had no wallets)
A few screenshots from macOS with similar results (Daedalus was synced and had 1 hardware wallet): 

- Daedalus: Minute [0](https://drive.google.com/file/d/1SrogPjby_3qYn7rreggvcwV3WiJH0dGY/view?usp=sharing), [3](https://drive.google.com/file/d/1sfDtME3ZNpiFmJ5F1E_A5SER44suDaO5/view?usp=sharing) and [6](https://drive.google.com/file/d/10xQ8NF0sj1znfAmJF6FfqGo4fOBR9VtD/view?usp=sharing)
- Cardano: Minute [0](https://drive.google.com/file/d/1ZeT46RpV6nNdU0ap2SQ127x8FBnHhW4S/view?usp=sharing), [3](https://drive.google.com/file/d/1sfDtME3ZNpiFmJ5F1E_A5SER44suDaO5/view?usp=sharing) and [6](https://drive.google.com/file/d/1D2uHWoQM_eEYC4XhRDZTAhdfkPV3_bsr/view?usp=sharing)

**Comment by nikolaglumac** [comment]
@pieterhouwen this is normal cardano-node memory usage and is a direct result of the current UTXO growth. This is also the reason we recommend having 8 GB of RAM to run Daedalus as per: https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements

In other words, I am afraid there is nothing you can do to reduce the memory footprint.

**Comment by kevinhammond** [comment]
As @nikolaglumac says, `cardano-node` is currently using approx. 3.5GB of RAM on all platforms, including MacOS.  Since Daedalus is a full node wallet, there is no way to reduce the memory usage at this point in time, and we therefore recommend using a system with 8GB of RAM, which will give headroom for growth.  There is ongoing development work that will reduce this requirement in time.

**Comment by yanniedog** [comment]
![image](https://user-images.githubusercontent.com/25560742/118349867-b5844b00-b596-11eb-8a92-3ed12db3ee8d.png)

**Comment by yanniedog** [comment]
Overall, this is approaching 5.5GB of RAM usage.

Excessive?

**Comment by nikolaglumac** [comment]
No @yanniedog - this is expected. For now...

**Comment by OlegWebmaster** [comment]
![2021-09-24_14-55](https://user-images.githubusercontent.com/18643614/134670383-fab99a4e-0f40-48e4-b53d-2ccead815226.png)
It isn't normal memory usage, I think!

**Comment by nikolaglumac** [comment]
@OlegWebmaster please open a ticket on https://github.com/input-output-hk/cardano-node
Thanks!
