### ISSUE TITLE
Small mouse pointer on HiDPI screen and 2x scaling on Linux

### ISSUE THREAD

**Issue by rufat-badal** [input-output-hk/daedalus#2559]
Minor visual bug that I have on the Linux (Ubuntu 20.04) client of Daedalus.
Daedalus seems to not respect the 200% scaling on my 4k Screen, but only for the mouse. All the UI elements are properly scaled.
In case further information is needed I can happily provide it.

**Comment by nikolaglumac** [comment]
@rufat-badal can you please share a screenshot?

**Comment by nikolaglumac** [comment]
@miorsufianiohk can you please try to reproduce this?

**Comment by rufat-badal** [comment]
Thanks for the fast reply!

Tiny mouse pointer:
![small pointer](https://user-images.githubusercontent.com/19675055/117943231-32e85b00-b30c-11eb-9b62-3a350c3c575a.png)

Normal mouse pointer:
![normal pointer](https://user-images.githubusercontent.com/19675055/117943272-3c71c300-b30c-11eb-8ec7-224ac1777fcc.png)

**Comment by miorsufianiohk** [comment]
Hi @rufat-badal,

Thank you so much for letting us know about the issue. I am able to replicate it with non HiDPI screen when I increased the scaling to 150%. I had a few applications opened. When I moved the cursor to different applications, they all respected the new scaling except Daedalus. @nikolaglumac , I took a [video capture here](https://drive.google.com/file/d/1mJrjX97WDINJtCDjQq5H5c8DHM0DEY8h/view?usp=sharing)

Many thanks,
Mior

**Comment by nikolaglumac** [comment]
Thanks both! 

@miorsufianiohk please create a JIRA ticket for this and put it into our backlog. Thanks!

**Comment by baizon** [comment]
I've fixed it by using this workaround: 
> Create the directory ~/.icons/default and inside a file named index.theme with the following contents: 
```
[Icon Theme]
Inherits=breeze_cursors
```
>Execute the following command: 
`$ ln -s /usr/share/icons/breeze_cursors/cursors ~/.icons/default/cursors`

Source: [https://wiki.archlinux.org/title/KDE#Plasma_cursor_sometimes_shown_incorrectly](https://wiki.archlinux.org/title/KDE#Plasma_cursor_sometimes_shown_incorrectly)

**Comment by wout** [comment]
I just want to mention here that there are more (Electron-based) apps Electron-based apps have this issue on Linux. [Mailspring](https://github.com/Foundry376/Mailspring) is another one for example.

**Comment by nikolaglumac** [comment]
This issue is to be fixed in https://github.com/input-output-hk/daedalus/pull/2206
Thanks for the patience!

**Comment by danielmain** [comment]
Fixed in #2206
