### ISSUE TITLE
Daedalus can not connect to network on arch - getNetworkInfo error

### ISSUE THREAD

**Issue by mdhen** [input-output-hk/daedalus#2563]
I installed daedalus on arch by running the official bin, when I start it (after the intial run where i set the settings and accepted the EULA) it just stalls on "connecting to network"

This is the output when I run it in terminal:

> LauncherCLI {launcherConfigPath = LauncherOptionPath {getLauncherOptionPath = "/nix/var/nix/profiles/profile-mainnet/etc/launcher-config.yaml"}, walletExitCodes = Nothing, updaterExitCodes = Nothing}
> [launcher:Notice:11] [2021-05-13 18:23:36.24 UTC] Starting cardano-launcher
> [launcher:Notice:11] [2021-05-13 18:23:36.24 UTC] Launcher substituted ENV variables: Object (fromList [("walletLogging",Bool False),("legacySecretKey",String "Secrets/secret.key"),("cluster",String "mainnet"),("nodeConfig",Object (fromList [("kind",String "shelley"),("network",Object (fromList [("configFile",String "/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/config.yaml"),("topologyFile",String "/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/topology.yaml"),("genesisFile",String "/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/genesis.json")])),("configurationDir",String "")])),("legacyStateDir",String "/home/mdhen/.local/share/Daedalus/mainnet"),("launcherLogsPrefix",String "/home/mdhen/.local/share/Daedalus/mainnet/Logs/pub"),("nodeBin",String "cardano-node"),("isStaging",Bool True),("cliBin",String "cardano-cli"),("updaterPath",String ""),("syncTolerance",String "300s"),("workingDir",String "/home/mdhen/.local/share/Daedalus/mainnet"),("tlsConfig",Object (fromList [("ca",Object (fromList [("commonName",String "Daedalus Self-Signed Root CA"),("expiryDays",Number 3650.0),("organization",String "Daedalus")])),("clients",Array [Object (fromList [("commonName",String "Daedalus Frontend"),("expiryDays",Number 365.0),("organization",String "Daedalus")])]),("server",Object (fromList [("commonName",String "Daedalus Wallet Backend"),("expiryDays",Number 365.0),("altDNS",Array [String "localhost",String "localhost.localdomain",String "127.0.0.1",String "::1"]),("organization",String "Daedalus")]))])),("networkName",String "mainnet"),("legacyWalletDB",String "Wallet"),("updaterArgs",Array []),("updateRunnerBin",String "update-runner"),("smashUrl",String "https://smash.cardano-mainnet.iohk.io"),("cardanoAddressBin",String "cardano-address"),("logsPrefix",String "/home/mdhen/.local/share/Daedalus/mainnet/Logs"),("isFlight",Bool False),("daedalusBin",String "daedalus-frontend"),("nodeImplementation",String "cardano"),("walletBin",String "cardano-wallet"),("stateDir",String "/home/mdhen/.local/share/Daedalus/mainnet"),("updateArchive",String ""),("metadataUrl",String "https://tokens.cardano.org"),("updateWindowsRunner",String ""),("tlsPath",String "/home/mdhen/.local/share/Daedalus/mainnet/tls")])
> [launcher:Notice:11] [2021-05-13 18:23:36.24 UTC] Locking file so that multiple applications won't run at same time
> [launcher:Info:11] [2021-05-13 18:23:36.24 UTC] Generating the certificates!
> [launcher:Info:11] [2021-05-13 18:23:36.39 UTC] Does update installation exist: UpdaterDoesntExist
> [launcher:Error:11] [2021-05-13 18:23:36.39 UTC] The updater file is missing!
> [launcher:Notice:11] [2021-05-13 18:23:36.39 UTC] Starting the wallet with arguments: WalletArguments {getWalletArguments = []}
> /nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
> /nix/store/kl6lr3czkbnr6m5crcy8ffwfzbj8a22i-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
> Fontconfig warning: no <cachedir> elements found. Check configuration.
> Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
> Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
> (node:10060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (node:10060) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> {"at":"2021-05-13T18:23:37.307Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"systemLocale":"en-GB"},"app":["daedalus"],"msg":"Detected system locale","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.310Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"startTime":"2021-05-13T18:23:37.306Z"},"app":["daedalus"],"msg":"Daedalus is starting at 2021-05-13T18:23:37.306Z","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.311Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"cardanoNodeVersion":"1.25.1","cardanoWalletVersion":"2021.3.4","cpu":[{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":1348,"times":{"user":9353200,"nice":300,"sys":2195000,"idle":53313200,"irq":137100}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":1400,"times":{"user":8623100,"nice":700,"sys":1930800,"idle":54273400,"irq":424300}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":1400,"times":{"user":9987100,"nice":300,"sys":2361100,"idle":52603100,"irq":131800}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":2100,"times":{"user":8644700,"nice":4400,"sys":1942100,"idle":54523800,"irq":107000}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":2100,"times":{"user":9253900,"nice":400,"sys":2125400,"idle":53665800,"irq":120400}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":1744,"times":{"user":7712300,"nice":200,"sys":1874600,"idle":55753200,"irq":98300}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":3419,"times":{"user":9041300,"nice":500,"sys":2420900,"idle":51691500,"irq":722100}},{"model":"AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx","speed":1700,"times":{"user":8091200,"nice":100,"sys":1872400,"idle":55282200,"irq":110100}}],"daedalusVersion":"4.0.5","isBlankScreenFixActive":false,"network":"mainnet","osName":"Linux","platformVersion":"5.12.3-arch1-1","ram":"14642126848","startTime":"2021-05-13T18:23:37.306Z"},"app":["daedalus"],"msg":"Updating System-info.json file","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.312Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"systemLocale":"en-GB"},"app":["daedalus"],"msg":"Detected system locale","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.341Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Renderer Error Handler started","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.354Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Main Error Handler started","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.373Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"mainnet-PREVIOUS-CARDANO-PID":9731},"app":["daedalus"],"msg":"CardanoNode: get mainnet-PREVIOUS-CARDANO-PID success","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.377Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"previousPID":9731},"app":["daedalus"],"msg":"CardanoNode: checking if previous cardano-node process is still running","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.378Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"name":"cardano-node","pid":9731},"app":["daedalus"],"msg":"CardanoNode: checking if cardano-node process (PID: 9731) is still running","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.403Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"processName":"cardano-node"},"app":["daedalus"],"msg":"CardanoNode: No previous cardano-node process is running anymore","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.404Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"name":"cardano-node","pid":9731},"app":["daedalus"],"msg":"CardanoNode: no cardano-node process (PID: 9731) is running","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.404Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"state":"starting"},"app":["daedalus"],"msg":"CardanoNode: transitions to <starting>","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.405Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"startupTries":1},"app":["daedalus"],"msg":"CardanoNode#start: trying to start cardano-node for the 1 time","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.406Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"nodeImplementation":"cardano"},"app":["daedalus"],"msg":"Node implementation","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.407Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Launching Wallet with --mainnet flag","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.407Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"tokenMetadataServer":"https://tokens.cardano.org"},"app":["daedalus"],"msg":"Launching Wallet with --token-metadata-server flag","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.408Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"walletOptions":{"nodeImplementation":"cardano","nodeConfig":{"configurationDir":"","kind":"shelley","network":{"configFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/config.yaml","genesisFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/genesis.json","topologyFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/topology.yaml"}},"cluster":"mainnet","stateDir":"/home/mdhen/.local/share/Daedalus/mainnet","tlsPath":"/home/mdhen/.local/share/Daedalus/mainnet/tls","syncTolerance":"300s","nodeLogFile":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"/home/mdhen/.local/share/Daedalus/mainnet/Logs/pub/","maxFiles":4},"size":0},"walletLogFile":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"/home/mdhen/.local/share/Daedalus/mainnet/Logs/pub/","maxFiles":4},"size":0},"cliBin":"cardano-cli","isStaging":true,"metadataUrl":"https://tokens.cardano.org"},"launcherConfig":{"networkName":"mainnet","stateDir":"/home/mdhen/.local/share/Daedalus/mainnet","nodeConfig":{"kind":"shelley","configurationDir":"","network":{"configFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/config.yaml","genesisFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/genesis.json","topologyFile":"/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/topology.yaml"}},"syncToleranceSeconds":300,"childProcessLogWriteStreams":{"node":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"/home/mdhen/.local/share/Daedalus/mainnet/Logs/pub/","maxFiles":4},"size":0},"wallet":{"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"autoDestroy":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"/home/mdhen/.local/share/Daedalus/mainnet/Logs/pub/","maxFiles":4},"size":0}},"installSignalHandlers":false,"tlsConfiguration":{"caCert":"/home/mdhen/.local/share/Daedalus/mainnet/tls/server/ca.crt","svCert":"/home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.crt","svKey":"/home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.key"},"tokenMetadataServer":"https://tokens.cardano.org"}},"app":["daedalus"],"msg":"Setting up CardanoLauncher now...","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.408Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Creating state directory /home/mdhen/.local/share/Daedalus/mainnet (if it doesn't already exist)","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.409Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Starting cardano-node now...","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.417Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"command":"cardano-node","args":["run","--socket-path","cardano-node.socket","--shutdown-ipc","3","--topology","/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/topology.yaml","--database-path","chain","--port","33085","--config","/nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/config.yaml"],"shutdownMethod":2,"cwd":"/home/mdhen/.local/share/Daedalus/mainnet"},"app":["daedalus"],"msg":"node: Service.start: trying to start cardano-node run --socket-path cardano-node.socket --shutdown-ipc 3 --topology /nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/topology.yaml --database-path chain --port 33085 --config /nix/store/793w0g409m6x2kz7lq4bk3s2fjcljhh7-node-cfg-files/config.yaml","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.427Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"command":"cardano-wallet","args":["serve","--shutdown-handler","--port","37277","--database","/home/mdhen/.local/share/Daedalus/mainnet/wallets","--tls-ca-cert","/home/mdhen/.local/share/Daedalus/mainnet/tls/server/ca.crt","--tls-sv-cert","/home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.crt","--tls-sv-key","/home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.key","--token-metadata-server","https://tokens.cardano.org","--sync-tolerance","300s","--mainnet","--node-socket","/home/mdhen/.local/share/Daedalus/mainnet/cardano-node.socket"],"shutdownMethod":1,"apiPort":37277},"app":["daedalus"],"msg":"wallet: Service.start: trying to start cardano-wallet serve --shutdown-handler --port 37277 --database /home/mdhen/.local/share/Daedalus/mainnet/wallets --tls-ca-cert /home/mdhen/.local/share/Daedalus/mainnet/tls/server/ca.crt --tls-sv-cert /home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.crt --tls-sv-key /home/mdhen/.local/share/Daedalus/mainnet/tls/server/server.key --token-metadata-server https://tokens.cardano.org --sync-tolerance 300s --mainnet --node-socket /home/mdhen/.local/share/Daedalus/mainnet/cardano-node.socket","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.661Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"Waiting for tcp port 127.0.0.1:37277 to accept connections...","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.664Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"... port is ready.","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.666Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"pid":10127},"app":["daedalus"],"msg":"CardanoNode#start: cardano-node child process spawned with PID 10127","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.666Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"pid":10134},"app":["daedalus"],"msg":"CardanoNode#start: cardano-wallet child process spawned with PID 10134","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.667Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"msg":{"ReplyPort":37277}},"app":["daedalus"],"msg":"CardanoNode: received message","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:37.669Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"state":"running"},"app":["daedalus"],"msg":"CardanoNode: transitions to <running>","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:38.990Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"[HW-DEBUG] INIT TREZOR","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.043Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: requesting node state","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.044Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"state":"running"},"app":["daedalus"],"msg":"ipcMain: Received request from renderer for node state","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.044Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: requesting node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.046Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"cardanoNodePID":10127,"cardanoWalletPID":10134}},"app":["daedalus"],"msg":"ipcMain: Received request from renderer for cardano status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.085Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: Updating node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.086Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"isNodeResponding":false,"isNodeSyncing":false,"isNodeInSync":false,"hasBeenConnected":false,"cardanoNodePID":0,"cardanoWalletPID":0}},"app":["daedalus"],"msg":"ipcMain: Received request from renderer to cache cardano status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.301Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"state":"running"},"app":["daedalus"],"msg":"NetworkStatusStore: handling node state <running>","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.301Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"state":"running"},"app":["daedalus"],"msg":"NetworkStatusStore: handling cardano-node state <running>","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.302Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: requesting tls config from main process","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.302Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"ipcMain: Received request from renderer for tls config","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.303Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"cardanoNodePID":10127,"cardanoWalletPID":10134}},"app":["daedalus"],"msg":"NetworkStatusStore: received cached node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.304Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: Updating node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.304Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"isNodeResponding":false,"isNodeSyncing":false,"isNodeInSync":false,"hasBeenConnected":false,"cardanoNodePID":10127,"cardanoWalletPID":10134}},"app":["daedalus"],"msg":"ipcMain: Received request from renderer to cache cardano status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.356Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: received tls config from main process","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.357Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"NetworkStatusStore: requesting node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.358Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"isNodeResponding":false,"isNodeSyncing":false,"isNodeInSync":false,"hasBeenConnected":false,"cardanoNodePID":10127,"cardanoWalletPID":10134}},"app":["daedalus"],"msg":"ipcMain: Received request from renderer for cardano status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.394Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"status":{"isNodeResponding":false,"isNodeSyncing":false,"isNodeInSync":false,"hasBeenConnected":false,"cardanoNodePID":10127,"cardanoWalletPID":10134}},"app":["daedalus"],"msg":"NetworkStatusStore: received cached node status","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.494Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"[HW-DEBUG] INIT LEDGER","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.495Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"[HW-DEBUG] OBSERVER INIT","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:39.508Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{},"app":["daedalus"],"msg":"[HW-DEBUG] OBSERVER INIT - listener started","pid":"","sev":"info","thread":""}
> {"at":"2021-05-13T18:23:41.005Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"error":{}},"app":["daedalus"],"msg":"AdaApi::getNetworkInfo error","pid":"","sev":"error","thread":""}
> {"at":"2021-05-13T18:23:43.003Z","env":"mainnet:Linux:5.12.3-arch1-1","ns":["daedalus","v4.0.5","*mainnet*"],"data":{"error":{}},"app":["daedalus"],"msg":"AdaApi::getNetworkInfo error","pid":"","sev":"error","thread":""}

and this is the output of ip addr:

> 
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
> link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
> inet 127.0.0.1/8 scope host lo
> valid_lft forever preferred_lft forever
> inet6 ::1/128 scope host
> valid_lft forever preferred_lft forever
> 2: enp3s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
> link/ether f8:75:a4:50:d5:5b brd ff:ff:ff:ff:ff:ff
> 4: wlp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
> link/ether 28:7f:cf:68:2c:e8 brd ff:ff:ff:ff:ff:ff
> inet 192.168.0.134/24 brd 192.168.0.255 scope global dynamic noprefixroute wlp1s0
> valid_lft 590816sec preferred_lft 590816sec
> inet6 fe80::d6d1:741e:f1a3:2f3/64 scope link noprefixroute
> valid_lft forever preferred_lft forever
> 5: enp5s0f3u1u1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
> link/ether f8:75:a4:50:d5:5c brd ff:ff:ff:ff:ff:ff

and a screenshot of the daedalus diagnostics screen
![20210513_16h59m41s_grim](https://user-images.githubusercontent.com/49368431/118191803-2ef33080-b413-11eb-8b2a-ee9e351f9137.png)

**Comment by laplasz** [comment]
similar issue #2413 - but in your case Daedalus version is newer than 4.0.4..

**Comment by nikolaglumac** [comment]
How long did you keep it running?

**Comment by nikolaglumac** [comment]
> similar issue #2413 - but in your case Daedalus version is newer than 4.0.4..

I don't see how this would be connected nor similar to https://github.com/input-output-hk/daedalus/issues/2413

**Comment by laplasz** [comment]
> > similar issue #2413 - but in your case Daedalus version is newer than 4.0.4..
> 
> I don't see how this would be connected nor similar to #2413

yeah that ticket is from cardano-node:
https://github.com/input-output-hk/cardano-node/issues/2413

**Comment by nikolaglumac** [comment]
@mdhen please leave Daedalus running for at least half an hour. Sometimes it takes even a full hour to initially connect depending on various factors...

**Comment by laplasz** [comment]
can it be a workaround to add more relay nodes into topology.yaml file?

**Comment by nikolaglumac** [comment]
I don't think that would help. Please just keep Daedalus running and it will eventually connect.
This is far from a good UX but I still ask you to be patient - we are working on adding more info during the connecting stage so that users see what stage Daedalus and the underlying cardano-node are...

**Comment by mdhen** [comment]
I'm going to attach the logs that daedalus lets you dl, I was not getting the "having trouble connecitng to network
[logs-2021-05-18T142201.0338Z.zip](https://github.com/input-output-hk/daedalus/files/6502051/logs-2021-05-18T142201.0338Z.zip)
" popup earlier but I just got it. Will leave it running all day today and let you know if it connects or not.

**Comment by nikolaglumac** [comment]
If you haven't seen it then you definitely didn't wait long enough. Please keep it running and let us know what's the outcome.

**Comment by nikolaglumac** [comment]
@mdhen I have checked the logs. Your case is quite strange - I can see that both cardano-wallet and cardano-node are operating normally. However, Daedalus API requests all fail but without an error code. Do you have some specific firewall rules enforced on your localhost?

**Comment by mdhen** [comment]
i have no firewall rules set up on the localhost.

**Comment by nikolaglumac** [comment]
It looks as something is blocking Daedalus from accessing the cardano-wallet API.
Not sure what else besides firewall could be. Perhaps localhost misconfiguration 🤷 
It is definitely something specific to your system.

**Comment by mdhen** [comment]
Seems that the problem was my /etc/hosts file, after updating it to the reccomended format on the arch wiki:

127.0.0.1        localhost
::1              localhost
127.0.1.1        myhostname.localdomain        myhostname

it connected in a few minutes.

**Comment by nikolaglumac** [comment]
Glad to hear! Thanks for letting us know!
