### ISSUE TITLE
SSD cache

### ISSUE THREAD

**Issue by yanniedog** [input-output-hk/daedalus#2566]
I have a 500gb external SSD drive, with 8GB of RAM.

Your software is using almost ~5.5GB of my available 8GB of RAM.

How do I make Daedalus free up my precious 8GB RAM, and use my abundant SSD storage instead?

**Comment by nikolaglumac** [comment]
90% of this memory usage is on the cardano-node side. Please open a ticket at https://github.com/input-output-hk/cardano-node
