### ISSUE TITLE
Cannot send NFT

### ISSUE THREAD

**Issue by oanhsaitec** [input-output-hk/daedalus#2574]
Hi there, 
Currently we mint a thousands NFT with scenario as below:
1. We minted NFTs  by ~ 24 transactions, each transaction contain 100 NFTs
2. After that, we sent 50 NFTs ( = 50 transactions, respectively) to others. And the fee arround 1.9 ADA for total
3. But for now, we try to send NFT, the fee is higher (~ 6ADA  ) and unsuccessful.
![error-transfer-daedalus](https://user-images.githubusercontent.com/67568662/119635007-762ee780-be3d-11eb-9c2b-55e9cea5c52b.jpg)

I assumed that cardano blockchain network merged all UTXOs to one. And now it is too long (because we have thousand of NFTs) so cardano got stuck when calculate tx-in and tx-out (the time out got from server, I think)

Thanks!

**Comment by matiwinnetou** [comment]
I believe this is the same error that a few members of Cardano community had with wallets with significant amount of NFTs. What these people needed to resort to is using command line and then they were able to move funds and NFTs from the wallet as a workaround.

**Comment by oanhsaitec** [comment]
Thank you @nikolaglumac
