### ISSUE TITLE
Daedalus 4.1.0 Upgrade causing full node resync

### ISSUE THREAD

**Issue by mreed911** [input-output-hk/daedalus#2585]
Upgraded from 4.0.5 to 4.1.0 on OS X 10.15.7.  Daedalus is now doing a full resync.  It looks like it completely threw out my locally stored copy during the upgrade (I saw the release notes) and is instead doing a full resync.  Any logs I can provide that would help, I'm happy to.

**Comment by nikolaglumac** [comment]
Hi @mreed911,

This is unfortunately expected :-(

It happens as a result of changes in the block storage mechanism which requires a full verification of the locally-stored copy of the Cardano blockchain: https://iohk.zendesk.com/hc/en-us/articles/900000461883-Daedalus-Mainnet-Known-Issues

Sorry for the inconvenience and thanks for the patience!
