### ISSUE TITLE
BUG: Copying address from Daedalus Generated Address PDF breaks it

### ISSUE THREAD

**Issue by AlexDochioiu** [input-output-hk/daedalus#2588]
Version: Daedalus 4.0.5
Issue: Copying the address from the PDF somehow removes one character(from the middle), making the address invalid.

This behaviour is consistent on both MacOS and Windows (did not test linux).

[broken_address_daedalus.pdf](https://github.com/input-output-hk/daedalus/files/6596626/broken_address_daedalus.pdf)

**Comment by nikolaglumac** [comment]
@gabriela-ponce please investigate this on all 3 platforms 🙏

**Comment by AlexDochioiu** [comment]
Might be worth mentioning that the PDF was open on macOS using Brave Browser (so the default Chromium PDF viewer). Not sure how it was opened on windows because it's not me who's tested there.

**Comment by gabriela-ponce** [comment]
Hi @AlexDochioiu, thanks for the report.
I've verified this on MacOS using Brave browser and I can confirm that this is a bug. These are the test that I ran:

1 - Copy the address from the document on another PDF reader and compare it with the same address copied from Brave. The latter was indeed missing a character. Check [this](https://drive.google.com/file/d/1ALwfSmUCaVZQbUq0AcNIAxlM3fZOHIQx/view?usp=sharing) video.
2 - Create a new PDF document containing the same address (without missing any character) and repeat test #1. There was no difference between the addresses. Check [this](https://drive.google.com/file/d/1SWpjyt7Hhh2GxfWdyhX0bHsi9Oe7gW7t/view?usp=sharing) video.
3 - Check the difference between an address copied from Daedalus and the same address copied from a document on Brave Browser. No difference between those addresses. Check [this](https://drive.google.com/file/d/1rXHwpJ5knatVe_4hGCorJu0AsMLFEH2y/view?usp=sharing) video.

@nikolaglumac As this doesn't happen with other addresses, my conclusion is that there is something in this address that is causing one of the characters to be ignored. At the same time, it doesn't reproduce with other PDF documents using the same address, so it may be related to how the document is created.
I'll continue investigating this in Windows and Linux and share if the results are different.

**Comment by AlexDochioiu** [comment]
@gabriela-ponce The person that generated this address tried it again on Daedalus 4.1.0 (Windows 10). The issue persists. He said that the address is copied poorly from Edge but works well when opening with Adobe Acrobat Reader.

My assumption is that there's a bug in the Chromium PDF Reader causing it. However, you might still want to find a workaround (maybe change something in how the PDF is generated) because that could be quite problematic.

**Comment by AlexDochioiu** [comment]
@gabriela-ponce Update: I asked the person to generate PDFs on more addresses using the same wallet. They are all broken. Some of them are actually missing 2 characters.

**Comment by gabriela-ponce** [comment]
@AlexDochioiu Thank you for the additional information. I was able to reproduce this issue with the document attached to the [original report](https://github.com/input-output-hk/daedalus/issues/2588#issue-911232043) on all platforms, using Brave, Chrome and Edge. 
However, it didn't reproduce with [the test document](https://drive.google.com/file/d/1vtkymm-n4kPkD3Grzcd0Ql_oObaaqB65/view?usp=sharing) I created with the same address. Also couldn't reproduce this with any other wallet or in browsers like Safari and Firefox.
Just to double-check, does this issue reproduce only with this wallet? Do you have any other wallet that reproduces the same issue when generating PDFs?

**Comment by AlexDochioiu** [comment]
@gabriela-ponce I asked the person to generate a PDF from another wallet. There was no problem. It seems that only that particular wallet has problems when generating PDFs.

**Comment by gabriela-ponce** [comment]
@AlexDochioiu Thanks for the information. In order to find the pattern that is causing this issue, could you send us a few of the PDF documents generated for this wallet? 10 different addresses for the wallet that is failing would be ok. If any of the address is copied correctly, please also include it so we can compare it with the rest.

**Comment by gabriela-ponce** [comment]
@AlexDochioiu Are you still reproducing this issue? If so, can you check my previous comment, please? Thank you!

**Comment by gabriela-ponce** [comment]
Hello @AlexDochioiu! I was wondering if you are still reproducing this issue. If so, please check [this comment](https://github.com/input-output-hk/daedalus/issues/2588#issuecomment-855897334) so we can get more information to address it. Thank you!

**Comment by AlexDochioiu** [comment]
@gabriela-ponce I mentioned previously that it's not my wallet that had this issue. Unfortunately I cannot ask the person for more addresses.

**Comment by gabriela-ponce** [comment]
@AlexDochioiu As we need additional information to address this problem, I would recommend asking the user that is facing this issue to submit a support request from Daedalus, in case they can't access this thread (Access to _Help - Support Request_). They could attach these files at the bottom of the form.

**Comment by danielmain** [comment]
Closed due to inactivity

**Comment by marcin-mazurek** [comment]
PR that addresses the issue: https://github.com/input-output-hk/daedalus/pull/2925
