### ISSUE TITLE
All hell breaks loose when there are a lot of native tokens in the wallet

### ISSUE THREAD

**Issue by ElGatoLoco** [input-output-hk/daedalus#2597]
I am using Daeadlus 4.1.0 on MacOS and in one of the wallets I have a few hundred tokens which were created and sent there by an external script. Now, sending them out of the wallet is a really annoying experience. At first, I managed to send 50 tokens out and it took ages for the UI to calculate the fees and min ADA value. Now, the second transaction I'm trying for almost an hour, which has only ten tokens, seems to break the UI completely:

The fees are not being calculated, this is hanging for minutes and my laptop is burning (possible memory leak?)
![image](https://user-images.githubusercontent.com/7573121/121890878-1d0af300-cd1b-11eb-86de-376742df88f1.png)

This doesn't make sense, I have over 800 ADA in my wallet and there are no errors in the UI itself
![image](https://user-images.githubusercontent.com/7573121/121891028-488ddd80-cd1b-11eb-9d65-27198259b3fe.png)
![image](https://user-images.githubusercontent.com/7573121/121890987-3f9d0c00-cd1b-11eb-8dca-2973d2266e7e.png)

**Comment by matiwinnetou** [comment]
This is a know issue and it is very close to a solution.

**Comment by miorsufianiohk** [comment]
Thank you for the question @ElGatoLoco and thank you for answering @matiwinnetou . 

We can confirm that this issue has been rectified by cardano-wallet release v2020-06-11 and will be incorporated in the next release of Daedalus.

Kind regards,
Mior

**Comment by ElGatoLoco** [comment]
@miorsufianiohk Thanks for clearing this up. 

Though, I suspect you meant v2021-06-11, instead of v2020-06-11.

**Comment by miorsufianiohk** [comment]
> @miorsufianiohk Thanks for clearing this up.
> 
> Though, I suspect you meant v2021-06-11, instead of v2020-06-11.

Hi @ElGatoLoco ,

Apologies. I have corrected the year now 😄 . Thank you for letting me know 👍 

Kind regards,
Mior

**Comment by nikolaglumac** [comment]
@ElGatoLoco the fix for this issue has been released in the scope of Daedalus Flight 4.2.0-FC1.
It should be available on Daedalus Mainnet in a few days too. Thanks for the patience!

**Comment by nikolaglumac** [comment]
The fix for this has been released in Daedalus Mainnet 4.2.0.
Thanks for the patience!
