### ISSUE TITLE
FR: Daedalus should have a "de-register stake key" option

### ISSUE THREAD

**Issue by erikd** [input-output-hk/daedalus#2602]
The `cardano-wallet` already supports this: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/quitStakePool so it is probably just a matter of hooking it up to the UI and testing.

**Comment by daniloprates** [comment]
We have [this done](https://github.com/input-output-hk/daedalus/pull/2351), but currently [disabled](https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/config/walletsConfig.js#L46). I'll discuss it with @darko-mijic, when he is back.

**Comment by nikolaglumac** [comment]
Closing this ticket as it is a duplicate of: https://github.com/input-output-hk/daedalus/issues/2367
