### ISSUE TITLE
BUG: Daedalus Wallet - Cannot find module index.js when opening

### ISSUE THREAD

**Issue by 27joaco** [input-output-hk/daedalus#2603]
Hi, I've tried to open my daedalus wallet today and is giving me a programming error.
This is the first time it happens, never had any problem running it in my Linux Mint 20.1 Ulyssa (base: Ubuntu 20.04 focal).
Attached print screen of the error:
![dae](https://user-images.githubusercontent.com/24530663/122780069-dcfcc080-d284-11eb-9788-c69dbeb47aae.png)

Attached txt of everything the consoles gives me when I run the process:
[runprocess.txt](https://github.com/input-output-hk/daedalus/files/6687373/runprocess.txt)

If I can give any further information, let me know.

**Comment by miorsufianiohk** [comment]
Dear @27joaco,

Thank you for contacting us. We'll have this check and get back to you as soon as we can.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hey guys @input-output-hk/daedalus-qa,

If you have some time to spare, could you also check this issue together with me please.

Thank you 👍

**Comment by miorsufianiohk** [comment]
Hi @27joaco,

Could you provide us with these info please:

DAEDALUS build number, Linux build version, Cardano Node version and Cardano Wallet version

You could get them from the menu: Daedalus -> About Daedalus.

I look forward to hearing from you soon.

Thank you,
Mior

**Comment by miorsufianiohk** [comment]
Hi @27joaco,

Thank you for getting back to us. Do you still have the executable? if you do, could you let me have the name of it please. It should be something like "daedalus-4.1.0-mainnet-xxxxx.bin".

Thank you,
Mior

**Comment by 27joaco** [comment]
@miorsufianiohk,
Unfortunately I don't since I've installed it a while a go. However it was pretty updated because I've opened it without issues a couple of days ago. Should've been between the 16th and 18th of this month but I cannot recall exactly.

**Comment by miorsufianiohk** [comment]
Dear @27joaco,

Thank you for the info. The date that you downloaded the software has given us enough information 👍 . We'll get back to you once we have any more updates.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hi @27joaco,

If you haven't removed the software, could you send me the file "System-info.json" please. It could be found in the folder Daedalus/mainnet/Logs/pub

Thank you,
Mior

**Comment by 27joaco** [comment]
Hi @miorsufianiohk,
I cannot attach that file type so I'll try to write it down here:
{"at":"2021-06-16T18:01:32.274Z","env":"mainnet:Linux:5.4.0-74-generic","ns":["daedalus","v4.1.0","*mainnet*"],"data":{"cardanoNodeVersion":"1.26.2","cardanoWalletVersion":"2021.5.26","cpu":[{"model":"Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz","speed":3100,"times":{"user":128100,"nice":100,"sys":38700,"idle":243200,"irq":0}},{"model":"Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz","speed":3100,"times":{"user":157000,"nice":0,"sys":32900,"idle":209600,"irq":0}},{"model":"Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz","speed":3099,"times":{"user":108000,"nice":600,"sys":45900,"idle":268000,"irq":0}},{"model":"Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz","speed":3100,"times":{"user":123200,"nice":200,"sys":31700,"idle":263900,"irq":0}}],"daedalusVersion":"4.1.0","isBlankScreenFixActive":false,"network":"mainnet","osName":"Linux","platformVersion":"5.4.0-74-generic","ram":"8207962112","startTime":"2021-06-16T18:01:32.274Z"},"app":["daedalus"],"msg":"Updating System-info.json file","pid":"","sev":"info","thread":""}

Please if I can assist you with any other information, let me know.

**Comment by miorsufianiohk** [comment]
Thank you very much @27joaco . We have sufficient information now. We'll let you know when we have new updates on the issue 👍 

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hi @27joaco,

Thank you for your patience. Could you clarify how did you run the app? Did you run the installer downloaded from daedaluswallet.io or did you download the release branch from github and run on terminal?

Thank you,
Mior

**Comment by 27joaco** [comment]
Hi @miorsufianiohk,
I've just execute it from my shortcut as always and I tried execute it from terminal just to see the error as I've showed you in the print screen:
daedalus-mainnet in the terminal

I installed it with the installer from daedaluswallet.io
but as I've said before, it was quite some time ago.

**Comment by miorsufianiohk** [comment]
Hi @27joaco ,

Could you uninstall the app, delete the state directory and try reinstalling the app again please. However, please back up the wallet(s) and make sure you have your wallet(s) recovery phrase(s). Further instruction could be found [here on how to delete the state directory](https://iohk.zendesk.com/hc/en-us/articles/360039511853-Delete-the-contents-of-the-state-directory).

Please let us know if you have any question regarding this.

Many thanks,
Mior

**Comment by 27joaco** [comment]
Hi @miorsufianiohk,

I've uninstalled the app like this:
chmod -R +w ~/.daedalus
rm -rf ~/.local/bin/daedalus* ~/.daedalus
rm -f ~/.local/share/applications/Daedalus*.desktop
rm -rf ~/.config/Daedalus*
rm -rf ~/.local/share/Daedalus

Installed it again with ./daedalus-4.1.0-mainnet-18213.bin
And is now running.

Do you need any further information?

**Comment by nikolaglumac** [comment]
Since this is an isolated incident and you got Daedalus running in the end I will close this ticket. Thanks!
