### ISSUE TITLE
can't verify signature on ubuntu

### ISSUE THREAD

**Issue by macovedj** [input-output-hk/daedalus#2605]
I'm currently following the instructions [here](https://daedaluswallet.io/en/download/#modal=download_pgp_instructions_linux)

After running `gpg2 --keyserver hkp://pool.sks-keyservers.net --search-keys signing.authority@iohk.io`
I get 
`gpg: error searching keyserver: No name`
`
gpg: keyserver search failed: No name
`

Thoughts?

**Comment by miorsufianiohk** [comment]
Dear @macovedj,

Thank you for contacting us. We will look into this issue and get back to you as soon as we could.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hi @macovedj ,

We have conducted our investigation and found out that the keyserver is no longer operational. Whilst waiting for our webteam to update the information, could you try this command out with an alternative server and let us know the outcome please:

`gpg2 --keyserver hkp://Keys.Openpgp.org --search-keys signing.authority@iohk.io`

Many thanks,
Mior

**Comment by macovedj** [comment]
Indeed, that did it for me.  I also took a look through this repo to see if the web page was there to correct, but I'm guessing it's somewhere else.  If you know where the repo is located, I wouldn't mind updating the instructions.

**Comment by miorsufianiohk** [comment]
Dear @macovedj ,

Thank you for the kind offer. We have passed the info to another team that will update the details in due course.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hi @macovedj ,

I hope that you are well. Just to let you know that we have updated the instruction. Appreciate if you could please check and let us know of any issue.

Once again, we apologise for any inconvenience and we look forward to hearing from you.

Kind regards,
Mior

**Comment by dmitrii-gaico** [comment]
Closing the ticket as Instruction was the root and it was updated so no more issues with verification are expected.
