### ISSUE TITLE
Daedalus 4.2.0 losing connection to node on Linux 

### ISSUE THREAD

**Issue by wout** [input-output-hk/daedalus#2620]
Daedalus version: 4.2.0
Linux version: elementary OS Odin (Based on Ubuntu 20.04 LTS)

Two days ago I did an in-app update to version 4.2.0 and I'm having trouble ever since. After the update, the app got into a loop where it tried to connect to the network but failed, reloaded and started connecting again. So yesterday evening I completely removed Daedalus and installed it fresh. This morning everything looked good, so I connected my wallet (Ledger) and it synced to 100%. For a moment everything looked fine until about an hour later when it lost connection again.

![Screenshot from 2021-07-12 09-33-56@2x](https://user-images.githubusercontent.com/107324/125282093-ea025200-e30e-11eb-88dc-84091469f374.png)

The logs:

```
...
[34m[cardano-wallet.pools-db:Info:12][0m [2021-07-12 08:23:23.15 UTC] Starting connection pool for /home/wout/.local/share/Daedalus/mainnet/wallets/stake-pools.sqlite
[34m[cardano-wallet.main:Info:12][0m [2021-07-12 08:23:23.22 UTC] Wallet backend server listening on https://127.0.0.1:38553/
[34m[cardano-wallet.pools-engine:Info:42][0m [2021-07-12 08:23:23.28 UTC] Chain following starting. Requesting intersection using 2160 checkpoints, the latest being 1d44a38a<-[fbd107cc-34511790#5969256]
[35m[cardano-wallet.network:Notice:18][0m [2021-07-12 08:23:23.34 UTC] Couldn't connect to node (x2). Retrying in a bit...
[35m[cardano-wallet.network:Notice:16][0m [2021-07-12 08:23:23.34 UTC] Couldn't connect to node (x2). Retrying in a bit...
[35m[cardano-wallet.network:Notice:35][0m [2021-07-12 08:23:23.40 UTC] Couldn't connect to node (x2). Retrying in a bit...
[35m[cardano-wallet.network:Notice:54][0m [2021-07-12 08:23:23.53 UTC] Couldn't connect to node (x2). Retrying in a bit...
[34m[cardano-wallet.pools-engine:Info:41][0m [2021-07-12 08:23:23.56 UTC] Successfully checked health HealthStatusSMASH {status = "OK", version = "1.4.0"}
[33m[cardano-wallet.network:Warning:18][0m [2021-07-12 08:23:23.59 UTC] Couldn't connect to node (x3). Retrying in a bit...
[33m[cardano-wallet.network:Warning:16][0m [2021-07-12 08:23:23.59 UTC] Couldn't connect to node (x3). Retrying in a bit...
[33m[cardano-wallet.network:Warning:35][0m [2021-07-12 08:23:23.65 UTC] Couldn't connect to node (x3). Retrying in a bit...
[33m[cardano-wallet.network:Warning:54][0m [2021-07-12 08:23:23.78 UTC] Couldn't connect to node (x3). Retrying in a bit...
[33m[cardano-wallet.network:Warning:18][0m [2021-07-12 08:23:24.10 UTC] Couldn't connect to node (x4). Retrying in a bit...
[33m[cardano-wallet.network:Warning:16][0m [2021-07-12 08:23:24.10 UTC] Couldn't connect to node (x4). Retrying in a bit...
[33m[cardano-wallet.network:Warning:35][0m [2021-07-12 08:23:24.15 UTC] Couldn't connect to node (x4). Retrying in a bit...
[33m[cardano-wallet.network:Warning:54][0m [2021-07-12 08:23:24.28 UTC] Couldn't connect to node (x4). Retrying in a bit...
[35m[cardano-wallet.ntp-client:Notice:52][0m [2021-07-12 08:23:24.35 UTC] ntp client experienced timeout using IPv6 protocol
[34m[cardano-wallet.api-server:Info:66][0m [2021-07-12 08:23:24.70 UTC] [RequestId 0] [GET] /v2/network/information
...
```

**Comment by nikolaglumac** [comment]
Where are you based?
Did this happen before?
Can you try out a different Internet provider?

**Comment by wout** [comment]
I'm in Brighton, UK.
This never happened before, it started after upgrading to version 4.2.0.
I'm on a 200 Mbit connection from Virgin Media, but I just tried on my Phone's hotspot and it's the same.

![Screenshot from 2021-07-12 14-34-22@2x](https://user-images.githubusercontent.com/107324/125296572-56d11880-e31e-11eb-974c-614deceb2438.png)

From the logs:

```
...
[33m[cardano-wallet.network:Warning:18][0m [2021-07-12 13:32:16.83 UTC] Couldn't connect to node (x36). Retrying in a bit...
[33m[cardano-wallet.network:Warning:16][0m [2021-07-12 13:32:16.83 UTC] Couldn't connect to node (x36). Retrying in a bit...
[33m[cardano-wallet.network:Warning:37][0m [2021-07-12 13:32:16.88 UTC] Couldn't connect to node (x36). Retrying in a bit...
[33m[cardano-wallet.network:Warning:48][0m [2021-07-12 13:32:16.96 UTC] Couldn't connect to node (x36). Retrying in a bit...
```

**Comment by nikolaglumac** [comment]
@wout please leave it running for 30-60 mins.

**Comment by wout** [comment]
@nikolaglumac Okay, I did that and it finally came through. And I think I know now what was going on before. The Cardano node eats a lot of resources. When it's starting up, it fills up the RAM almost completely, sometimes to the point that my computer becomes almost unresponsive and I have to other apps in order to keep it running. So probably the cardano node choked and died before.

![Screenshot from 2021-07-12 15-21-14@2x](https://user-images.githubusercontent.com/107324/125304456-846d9000-e325-11eb-8bf5-4ba4928f2190.png)

This is on my laptop. My desktop has 32GB RAM so it's not an issue there.

**Comment by nikolaglumac** [comment]
Glad to hear it recovered - sometimes (especially on laptops) it tends to take ~30 mins to start :-(

What is the RAM size on your laptop?

cc @dmitrii-gaico @CarlosLopezDeLara @jakewyo

**Comment by wout** [comment]
It has 16GB RAM, so most of the time it's doing fine. But the cardano node needs 6.5GB apparently.

Thanks for your help!

**Comment by nikolaglumac** [comment]
Alright! I will close the ticket then. Cheers!
