### ISSUE TITLE
Can't set a spending password for Daedalus

### ISSUE THREAD

**Issue by neroclaudio78** [input-output-hk/daedalus#2623]
Hi all,

I just updated Daedalus 4.2.0. When I try to access my ledger nano s wallet I get the following message: 
"Your wallet is not protected with a spending password. To keep your wallet secure and start using it in Daedalus, you need a spending password."

So I click on the butten set a password. It says typein a new password. When I fill in a new password it tells me the password is strong. When I fill in the box repeat new password it matches. But then when I click on the button save I get: incorrect wallet password. 

So It tells that my wallet is not protected with a spending password en tells me to create one, but then it tells me the wallet password is not correct. 

Can anyone help me with this? 

Thanks

**Comment by nikolaglumac** [comment]
@tomislavhoracek can you please help us here?

**Comment by neroclaudio78** [comment]
I installed the Yoroi extension with Google Chrome and fortunately, I can send and receive funds with my Ledger S. 
But I still can't access my Ledger through the Daedalus App, so hopefully you can help me with that. Thanks

**Comment by dmitrii-gaico** [comment]
@neroclaudio78 Hello. Could you please try to re-install Daedalus 4.2.0 and pair your Nano S from the scratch? Make sure that after uninstall process you delete the Daedalus state directory. 
Uninstall instruction : https://iohk.zendesk.com/hc/en-us/articles/360013170694-Uninstall-Daedalus-and-remove-wallet-s-data-

Make sure you have your software wallets recovery phrases available so you can restore them after the app is re-installed.

Thank you and please let me know if it helps to resolve the issue.

**Comment by dmitrii-gaico** [comment]
@neroclaudio78 Hello. Could you please advise if you have any updates?
Thank you.

**Comment by neroclaudio78** [comment]
@dmitrii-gaico I re-installed Daedalus before but that didnt work. But I never deleted the Daedalus state directory. 
Now I follow the steps in the uninstall instructions it worked. So I can access my funds through Daedalus again. 
Thanks for your help!

**Comment by dmitrii-gaico** [comment]
@neroclaudio78 yw! I was glad to help.
Regards, Dmitrii.
