### ISSUE TITLE
DnsSubscription : Connection timed out behind a proxy

### ISSUE THREAD

**Issue by bcoste** [input-output-hk/daedalus#2628]
I use a Daedalus testnet wallet version 4.2.0 under Windows 10.
My wallet node failed to sync the relay relays-new.cardano-testnet.iohkdev.io with a "Connection timed out" error.

As I'm behind an http proxy, is it possible to specify it somewhere in a Daedalus config file ?

Notice that I've the same issue with cardano-rosetta under linux ubuntu (see https://github.com/input-output-hk/cardano-rosetta/issues/389).

Errors in my node.logs :
> [35m[SYM-9204:cardano.node.DnsSubscription:Notice:1983][0m [2021-07-22 08:14:51.20 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 54.151.49.138:3001
[31m[SYM-9204:cardano.node.DnsSubscription:Error:1973][0m [2021-07-22 08:15:12.09 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Exception, destination 3.9.80.183:3001 exception: Network.Socket.connect: <socket: 1460>: failed (Connection timed out (WSAETIMEDOUT))
[35m[SYM-9204:cardano.node.ErrorPolicy:Notice:44][0m [2021-07-22 08:15:12.09 UTC] IP 3.9.80.183:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 1460>: failed (Connection timed out (WSAETIMEDOUT)))) 20s

**Comment by gabriela-ponce** [comment]
Hello @bcoste, apologies for the slow reply. At the moment it is not possible to configure Daedalus to run behind a proxy.

**Comment by nikolaglumac** [comment]
@bcoste please leave Daedalus running - sometimes it takes a long time for the node to connect... (sometimes even 30 - 60 mins)

**Comment by bcoste** [comment]
As a new feature, is it possible to add parameters to specify proxy settings ?

**Comment by danielmain** [comment]
Hi @bcoste you seem to be the first case that needs to connect Daedalus behind an HTTP proxy. We don't plan to have a plan to support it. I encourage you to ask this feature here 🙏 https://github.com/input-output-hk/cardano-node/issues
