### ISSUE TITLE
Memory usage on Linux is through the roof

### ISSUE THREAD

**Issue by wout** [input-output-hk/daedalus#2631]
I'm experiencing memory issues with Daedalus on a daily basis. Today I did a comparison with macOS, and there memory usage is much less than half:

- Daedalus 4.2.0 macOS: 2.14GB
- Daedalus 4.2.0 Linux (elementary OS 6 based on Ubuntu 20.04 LTS): 5.60GB

What I'm talking about is cardano-node taking up the memory, not the electron wrapper itself. So probably I need to report this issue on the cardano-node repo, but I wanted to mention it here becuase the app is affected by it. And I notice this on my relay nodes as well (they used to be 4GB, now 8GB).

I've got a Linux laptop with 16GB RAM, and I have to close a bunch of apps just to be able to open Daedalus. It's not a comfortable situation. And https://github.com/input-output-hk/daedalus/issues/2620 is the result of it.

**Comment by gabriela-ponce** [comment]
Hello @wout. This memory usage is expected at the moment and you would probably experience this on all platforms. For reference, I've checked the RAM usage of _cardano-node_ on [macOS BigSur](https://drive.google.com/file/d/1wAxdCI2sSathCggzMEf_0I22jwMBYBbJ/view?usp=sharing) 11.4 and on [Ubuntu 20.04](https://drive.google.com/file/d/1CRd_ZzwUr7uDBBXZagR3iT-N9H42tHp6/view) and obtained similar results.
You can find more information about this topic [here](https://github.com/input-output-hk/daedalus/issues/2535#issuecomment-826987215) and [here](https://github.com/input-output-hk/daedalus/issues/2535#issuecomment-827480094).

**Comment by wout** [comment]
@gabriela-ponce You're right, I must have looked in the wrong place because on macOS is also close to 6GB. Thanks anyway for your reply.

**Comment by sauerburger** [comment]
I have 8GB ram + 1GB swap on my Debian laptop and cannot run Daedelus without it being killed by the OOM -- even with every other application closed.

Maybe the memory requirements of 8GB are not valid anymore?

**Comment by wout** [comment]
> Maybe the memory requirements of 8GB are not valid anymore?

TBH, I don't think running Daedalus on 8GB ram is feasible. On my 16GB laptop, I need to close half of the apps to run it, and even then it's on the edge.
