### ISSUE TITLE
Daedalus improperly started

### ISSUE THREAD

**Issue by haripetrov** [input-output-hk/daedalus#2634]
On Windows 10 when you pin shortcut to your taskbar you cannot start Daedalus. This is the error that appears:
![image](https://user-images.githubusercontent.com/1268290/127980426-1daf182e-79f8-4e0e-9764-e30bef733643.png)

**Comment by nikolaglumac** [comment]
This is expected. You have to pin the original shortcut that was created during the Daedalus installation as it contains launcher info which is missing if you create the shortcut yourself.

**Comment by haripetrov** [comment]
Thank you very much for this clarification.
