### ISSUE TITLE
Retiring pool indicator missing in Delegation Center

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/daedalus#2637]
When a pool is marked for retirement, a red square in top right corner of its entry in Stake Pools section (list of ~2800 pools) is added. However, in Delegation Centre section where the user's current delegated pools for each wallet are shown, this indicator is currently missing and user will only discover that the pool they're staking with is due to retire if they hover their mouse over it.

**Comment by nikolaglumac** [comment]
@dmitrii-gaico can you please check this?

**Comment by dmitrii-gaico** [comment]
@nikolaglumac Sure, I'll check and get back with report.
Thank you.

**Comment by dmitrii-gaico** [comment]
@nikolaglumac I can confirm the issue. Red square indicator is missing at Delegation Center screen when wallet is delegated to retiring pool. Production Build 18540 Testnet.
Thank you.

**Comment by nikolaglumac** [comment]
Thanks for confirming this @dmitrii-gaico - please create a ticket for this 🙏

**Comment by darko-mijic** [comment]
@daniloprates, please create a ticket for this.

**Comment by daniloprates** [comment]
@darko-mijic I'm handling it in the scope of DDW-728

**Comment by dmitrii-gaico** [comment]
Closing the ticket as issue were fixed.
