### ISSUE TITLE
SMASH Metadata documentation link is broken in settings.stakePools

### ISSUE THREAD

**Issue by bboerst** [input-output-hk/daedalus#2645]
In the latest Daedalus release (4.2.1#18759) when navigating to Settings/Stake pools, the `StakePool Metadata Aggregation Server (SMASH)` link is 404'ing.

I believe that:
https://github.com/input-output-hk/daedalus/blob/caac11bfcdaf7918989871da5f661a665e15f4dd/source/renderer/app/i18n/locales/en-US.json#L304

...should maybe be updated to:
```
https://docs.cardano.org/getting-started/operating-a-stake-pool/SMASH
```

**Comment by miorsufianiohk** [comment]
Dear @bboerst ,

Thank you for letting us know of this issue. I could confirm that I am also seeing the same behaviour on build 18759. I have passed the information to the team for further action and will provide further update in due course.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Hi again @bboerst ,

Just to let you know that this issue has been fixed in build 18793 which should be incorporated in the next release of Daedalus. Once again, many thanks for bringing up this issue. Wishing you a great weekend.

Kind regards,
Mior

**Comment by miorsufianiohk** [comment]
Dear @bboerst ,

I hope that you are well. Just to inform you that I am closing this issue as it has been fixed. Please do let us know if you still find the same problem in the next Daedalus release that has this fix.

Many thanks,
Mior
