### ISSUE TITLE
Daedalus NOT SYNCING completely 

### ISSUE THREAD

**Issue by SeverSava** [input-output-hk/daedalus#2648]
Hi to all,

I've been trying for the last week to make Daedalus node work, but no luck as of yet. 
The problem I have as it can be seen from the pictures attached is that the node is not completing the syncing with the network. 
I have checked the "Connecting to network message" article and the system requirements. The only thing that is not a match in my case is the RAM. I have 7.5 instead of 8. Would this cause this problem?   

One other thing: I have transferred £250 worth of ADA to Daedalus before attempting the sync. This made my money unavailable to me as I can't withdraw them now or even see them, as the GUI is not allowing me anywhere else except the sync page. How do I get my money back, please?

If I were to uninstall and reinstall Daedalus node wallet, would the recovery phrase be enough to do it? Can you please help me uninstall and reinstall Daedalus?

kind regards, 
Sever

[logs-2021-08-14T125812.0261Z.zip](https://github.com/input-output-hk/daedalus/files/6988776/logs-2021-08-14T125812.0261Z.zip)
![Screenshot from 2021-08-14 13-43-19](https://user-images.githubusercontent.com/15107056/129490541-6e9621c8-6994-4758-9d01-9ecc38d5a2c7.png)
![Screenshot from 2021-08-12 14-02-33](https://user-images.githubusercontent.com/15107056/129490546-6cf3979d-a67a-4b74-8934-eef2a1dd05ec.png)

**Comment by SeverSava** [comment]
My problem got solved thanks to this lovely chap and his bright advice :)

![Screenshot from 2021-08-15 22-48-00](https://user-images.githubusercontent.com/15107056/129493799-01bff54e-a8e6-4265-bcf4-772c8674d23d.png)

**Comment by nikolaglumac** [comment]
The verification of the blockchain sometimes takes a very long time (up to an hour!) but it should eventually be complete and Daedalus would connect to the network. If you don't see it recovering within an hour then it is suggested to do a full re-sync as described in the following Support Portal article: https://iohk.zendesk.com/hc/en-us/articles/360009484874-Delete-and-re-sync-blockchain-data

I am glad do hear you were able to fix the issue 🎉
