### ISSUE TITLE
I nearly lost my funds..

### ISSUE THREAD

**Issue by john5480** [input-output-hk/daedalus#2651]
Hi, I've got some ada since Jan 2018 with Deadalus 1.0.3769 , but this verison cannot connect network now. 
What I  have:
1. the laptop with old 1.0.3769 and new version 4.2.1, and secret key inside
2. 12words recover phrase but recoverd with no funds

When import from secret key, I can see my funds, but I cannot do any transaction without spending password. I've tried many ways to get back my funds but faild, I've got no idea.

**Comment by matiwinnetou** [comment]
I think you have a mistake in your 12 words because they should for sure recover funds. Did you import this as Byron Era Wallet?

**Comment by john5480** [comment]
> I think you have a mistake in your 12 words because they should for sure recover funds. Did you import this as Byron Era Wallet?

I've only record 12 words, it should not be wrong.. 

import is Byron Wallet

**Comment by john5480** [comment]
Can I send out my funds without spending password?

**Comment by matiwinnetou** [comment]
To my knowledge not because secret key is encrypted. Imagine somebody stole your computer, would you want them to be able to send your ADA somewhere?

**Comment by nikolaglumac** [comment]
> 2. 12words recover phrase but recoverd with no funds

@john5480 you must have saved a wrong wallet recovery phrase.

> When import from secret key, I can see my funds, but I cannot do any transaction without spending password. I've tried many ways to get back my funds but faild, I've got no idea.

As @matiwinnetou pointed out - your wallet's private key stored in the secret.key file is encrypted by your spending password. In order to move your ada you must remember your password OR the correct wallet recovery phrase. There is no other way.

**Comment by dokywhale** [comment]
@nikolaglumac i only have a password, where can i found secrete.key file?
