### ISSUE TITLE
Giveaway scam banner

### ISSUE THREAD

**Issue by staaky** [input-output-hk/daedalus#2652]
Based on [Charles' latest video warning about giveaway scams](https://www.youtube.com/watch?v=p_3rVkKkl5o), here's a suggestion that could help push that warning even more inside Daedalus, because the newsfeed is easily overlooked.

Having a banner like this stick around until clicked away might save some people.

![Daedalus Banner](https://user-images.githubusercontent.com/5575/130533707-c7e6fa2d-078f-4b8b-91bd-af22e39c5c98.png)

![Daedalus Banner Bottom](https://user-images.githubusercontent.com/5575/130534721-5d1684e8-b954-46a3-8c52-6012db3680f7.png)

**Comment by nikolaglumac** [comment]
Thanks for bringing this up!
We will consider implementing this.
cc @darko-mijic @daniloprates @alexander-rukin

**Comment by dmitrii-gaico** [comment]
Closing the ticket as no additional clarification required.
