### ISSUE TITLE
Share wallet address - Unable to select "You have verified the address"

### ISSUE THREAD

**Issue by brandonmcgarvey** [input-output-hk/daedalus#2656]
Daedauls 4.2.1
Windows 10 21H1
Using with Trezor Model T

IMO, this is a rather low priority issue, but I am no longer able to select the "You have verified the address" check box when using the share wallet address from Receive menu. I am using this with a Trezor Model T hardware wallet if relevant. The Export key properly comes up on the device, which I confirm and then address comes up as well, which I also confirm. However, after confirming from device, I am unable to select the "You have verified the address" check box. This is not a big deal for me as I am just going in to copy the address. Attached is screenshot of checkbox I am referring to. I was able to select this checkbox in the previous version of Daedalus.

![daedalus](https://user-images.githubusercontent.com/77640045/131556174-39ed43ad-67f0-4c6f-8785-673d9d3d3530.jpg)

**Comment by nikolaglumac** [comment]
cc @tomislavhoracek

**Comment by tomislavhoracek** [comment]
@brandonmcgarvey  Thank you for contacting us and for the detailed instructions. We will have this check and get back to you as soon as possible.

**Comment by tomislavhoracek** [comment]
@brandonmcgarvey  I checked the issue. "You have verified the address" label / checkbox is not clickable. Are you able to scroll to the bottom and select one of the answers (yes / no,reverify)? Once you click that, "You have verified the address" checkbox should be checked or you will proceed with the re-verifying process.

![Trezor verification](https://user-images.githubusercontent.com/18653950/132010401-ce01cab5-4ab0-42ca-a6ea-e7e157d3a563.png)

**Comment by brandonmcgarvey** [comment]
> @brandonmcgarvey I checked the issue. "You have verified the address" label / checkbox is not clickable. Are you able to scroll to the bottom and select one of the answers (yes / no,reverify)? Once you click that, "You have verified the address" checkbox should be checked or you will proceed with the re-verifying process.
> 
> 

🤦‍♂️Well I feel kind of of dumb. Yes that worked. I didn't even realize that was there, but I know before I was able to just check the box. Thank you for taking the time.

**Comment by tomislavhoracek** [comment]
@brandonmcgarvey hehe no worries, we are here to help!
