### ISSUE TITLE
Daedalus Testnet Sync get stuck at slot 426654 epoch 153

### ISSUE THREAD

**Issue by abdellahaski** [input-output-hk/daedalus#2659]
Hello, 
My Daedalus Testnet sync gets stuck every time on that slot, I tried restarting everything, I uninstalled and reinstalled it again but still the same.

Logs: [Google Drive](https://drive.google.com/drive/folders/1upNNgJxrUjzK7wYZICyiUBmB5m4FBJHR?usp=sharing)

**Comment by nikolaglumac** [comment]
What is the version of your Daedalus Testnet?

**Comment by abdellahaski** [comment]
It's v4.3.0

**Comment by nikolaglumac** [comment]
@abdellahaski can you try to do a full re-sync please?

**Comment by dmitrii-gaico** [comment]
@nikolaglumac I installed Testnet latest dev build 4.3.0 \ 1.29.0 and was able to sync 0-100% with no issues or stuck states. Last network block 154.
@abdellahaski Could you please make sure you are following the Uninstall instruction and try to re-sync from the scratch ?
Instruction below : 
https://iohk.zendesk.com/hc/en-us/articles/360013170694-Uninstall-Daedalus-and-remove-wallet-s-data

**Comment by abdellahaski** [comment]
Hello, Thanks guys for the help but unfortunately I still face the same issue I installed and removed all the files, reinstalled again, and got stuck on epoch 153, restarted the Node still the same.

The mainnet is working without a problem, and also I have a small Ubuntu server on the same network running a Testnet node that syncs without a problem. (it's currently not running)


![image](https://user-images.githubusercontent.com/10819089/132228828-64fa11a4-6069-47b3-a511-6f8a5b27b18d.png)

**Comment by nikolaglumac** [comment]
Thanks for the details! We will investigate further...

**Comment by dmitrii-gaico** [comment]
@abdellahaski Hello, hope you are fine. 
Could you please do the steps below as I would like to gather more information for further research.
1. Clean Daedalus re-install ( I believe you already did it and this did not resolved the issue. However let's do it one more time to keep logs small.
2. Once you face the issue and you are stuck at epoch 153 please Close the Daedalus and then attach the Node log.
3. Open CMD and navigate to C:\Program Files\Daedalus Testnet Once there hit the "cardano-node.exe --version" and please share the output.

Thank you in advance.

**Comment by nikolaglumac** [comment]
Any news @abdellahaski? We would really appreciate if you could send us the info @dmitrii-gaico requested 🙏

**Comment by abdellahaski** [comment]
Sorry, I wasn't able to provide the info, was on vacation :).
Actually, an update to 4.3.1 resolved the issue, it's syncing now to 100%.
Thanks guys for the help

**Comment by nikolaglumac** [comment]
Glad to hear that!
Thanks for letting us know!
