### ISSUE TITLE
SSE4 support for installing daedalus

### ISSUE THREAD

**Issue by saeed-saeedi** [input-output-hk/daedalus#2664]
On an old machine with dual core, I can install daedalus on windows 10, but on the same machine when I want install daedalus on ubuntu 20.04, it says "ERROR: your cpu lacks sse4 support, cardano will not work"

**Comment by nikolaglumac** [comment]
I would say this has to be due to specifics of your Linux setup.
@disassembler @cleverca22 any clue?

**Comment by saeed-saeedi** [comment]
I tried a minimum installation for ubuntu. is thee any missing packages? I ran update and upgrade before daedalus installation.

**Comment by danielmain** [comment]
@saeed-saeedi I am sorry to tell you that we need that CPU feature SSE4. We have to check that here: https://github.com/input-output-hk/daedalus/blob/66427855ff4eb513b9500d91bafc7baafa6e6db3/default.nix#L391

I am impressed that you were able to run it on Windows. carndano-node requires a lot of memory and CPU resources, and being executed in an older than 2008 CPU is definitely not expected.
