### ISSUE TITLE
checksum and signature fail for latest (4.3.1) version on download page!

### ISSUE THREAD

**Issue by sitcsitc** [input-output-hk/daedalus#2669]
This is alarming!
I was about to download from https://daedaluswallet.io/en/download/

both verifications fail:
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  daedalus-4.3.1-mainnet-18992.bin
and
gpg: BAD signature from "IOHK Signing Authority <signing.authority@iohk.io>" [full]

**Comment by nikolaglumac** [comment]
@dmitrii-gaico can you please check this?

**Comment by dmitrii-gaico** [comment]
@sitcsitc Hello and thank you for your report.
Could you please share more information about your "verification fail" such as which exactly steps were used and would you also mind to attach screenshots of outputs for our further research.

From my side both verifications Passed. Please see details below.

SHA256
![image](https://user-images.githubusercontent.com/83477982/133039707-32a859a2-baf9-41ac-b31a-9cf4594b298a.png)

Signature
![image](https://user-images.githubusercontent.com/83477982/133039900-6f8b319b-1b8f-4e4e-a9ce-1d875e38b9ee.png)

Thank you in advance.

**Comment by nikolaglumac** [comment]
cc @CarlosLopezDeLara @jakewyo

**Comment by sitcsitc** [comment]
Thank you for looking into this! I now see that my / partition was full and the download of daedalus binary was corrupted. Thank you for taking this seriously and sorry for the noise.

gpg: Good signature from "IOHK Signing Authority <signing.authority@iohk.io>" [full]

**Comment by dmitrii-gaico** [comment]
@sitcsitc nice to hear it worked fine for you. Closing the ticket as it was resolved.
cc @nikolaglumac
