### ISSUE TITLE
I would like to translate the messages for portuguese pt_BR

### ISSUE THREAD

**Issue by lucassimon** [input-output-hk/daedalus#2674]
Hi I would like to translate the `locales` and `i18n` message files to Brazilian Portuguese.

And for that is there any command to generate these `locales` in each folder? Or just copy and paste the `en-US` file and proceed with the translation?

**Files**

- `https://github.com/input-output-hk/daedalus/blob/develop/translations/translation-runner.js`

- [ ] Adds `pt-BR` on the array

**locales/i18n directories** 

- https://github.com/input-output-hk/daedalus/tree/develop/source/renderer/app/i18n/locales

- [ ] Creates the files with the respective locales

- [ ] Creates the translated file in `term-of-use` subdirectory

- https://github.com/input-output-hk/daedalus/tree/develop/source/main/locales

- [ ] Creates locale file

**Comment by nikolaglumac** [comment]
Thank you for your contribution! Unfortunately, at this moment in time, we can not accept this translation as it would be hard to maintain it without internal translation/audit process.
