### ISSUE TITLE
Cardano-sl still in use by build-installer-unix.sh

### ISSUE THREAD

**Issue by Zerophase** [input-output-hk/daedalus#2678]
Looking at the Cardano-sl repo it's supposedly deprecated in favor of another script. It's still being used by build-installer-unix.sh. Should it still be in use for a Nix install?

**Comment by danielmain** [comment]
Hi @Zerophase, I was looking in our source code and in fact we are not using cardano-sl anymore. Could you pls tell me on in which line of https://github.com/input-output-hk/daedalus/blob/develop/scripts/build-installer-unix.sh you mean ?

Thank you!

**Comment by Zerophase** [comment]
Let me see if I can find it. I'll have to reconfigure my PKGBUILD to test.

**Comment by nikolaglumac** [comment]
Cardano-sl is definitely not being used anywhere any more. It's been like that for a long time actually. Closing this ticket...
