### ISSUE TITLE
unable to restore my wallet Daedalus wallet

### ISSUE THREAD

**Issue by AaronGenereaux** [input-output-hk/daedalus#2679]

**Comment by AaronGenereaux** [comment]
i am a new user. 

I get "an error occurred" after clicking continue from the "wallet name, spending password creation page"
I have two wallet recovery phrase's and I have tried them both. They both verify but then when I go to the next step I get the aforementioned. 

I tried deleting Daedalus and reinstalling already.

**Comment by miorsufianiohk** [comment]
Hi @AaronGenereaux ,

Thank you for contacting us. From the log, I could see that you might have attempted to restore the same wallets many times. After deleting and reinstalling Daedalus, did it fix your issue?

Thanks,
Mior

**Comment by miorsufianiohk** [comment]
Closing this issue. Considered fixed.
