### ISSUE TITLE
How to clear cached mainnet files?

### ISSUE THREAD

**Issue by kimiotakemura** [input-output-hk/daedalus#2682]
Daedalus took about 12~15GB of my disk space, I would like to clear the downloaded files. is it possible? if i can delete them, can i still use the wallet?

**Comment by nikolaglumac** [comment]
You can not continue using Daedalus if you delete the downloaded data.
You will also lose all your wallets if you do that so make sure to have their wallet recovery phrases safely stored.

All the downloaded data is stored in the so-called "state" directory. You can find more about it in the following article: https://iohk.zendesk.com/hc/en-us/articles/360013170694-Uninstall-Daedalus-and-remove-wallet-s-data
