### ISSUE TITLE
Daedalus crashes on 10 bit/color (30 bit) displays on Linux - 

### ISSUE THREAD

**Issue by bhlevca** [input-output-hk/daedalus#2694]
Daedalus (4.3.1 stable, not flight) crashes at startup. From start posts 2 errors and it ends after it retries a few times. See below.

I suspected from the start that the color space may be a problem and the last message about the compositor confirmed it.

I believe that it is a small fix to make it work. All the applications that I have using Electron except Daedalus work. I see that Daedalus is based on electron and I have other applications such as Signal Desktop and Skype that work flawlessly in a 10 bit/color environment.  

It is likely that just an Electron upgrade may do the trick. 

Below the line is some output:
------------------------------------------------------------------------------------------------------------
```

Gtk-Message: 19:06:03.594: Failed to load module "colorreload-gtk-module"
Gtk-Message: 19:06:03.594: Failed to load module "window-decorations-gtk-module"
..... 
many lines
.....
t":11,"commandLine":{}}}},"app":["daedalus"],"msg":"uncaughtException::gpu-process-crashed: not-killed","pid":"","sev":"error","thread":""}
[71708:1006/190606.006240:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
[launcher:Notice:15] [2021-10-06 23:06:06.20 UTC] Wallet exited with exitcode: ExitFailure (-5)
[launcher:Notice:15] [2021-10-06 23:06:06.20 UTC] Daedalus exited with ExitFailure -5, will shutdown cardano-launcher

```

**Comment by nikolaglumac** [comment]
Daedalus setup on Linux is quite specific.
Hope @cleverca22 will have time to look into this.

**Comment by danielmain** [comment]
Hi @bhlevca we just upgraded electron to version 13. There was an [Issue](https://github.com/electron/electron/issues/21414) in older Electron, would you pls tell us if this issue still exists?

**Comment by bhlevca** [comment]
Hi,

No problem anymore. Daedalus has been working fine on my 10 bit colr
display for a while now.

Thanks
Bogdan
