### ISSUE TITLE
Daedalus testnet 4.3.2 crashes on windows 10

### ISSUE THREAD

**Issue by angelstakepool** [input-output-hk/daedalus#2695]
Replaced Daedalus Testnet 4.3.1 and now this version crashes all the time.  Deleted the user profile folder and issue persists

**Comment by nikolaglumac** [comment]
Sorry to hear about these issues @angelstakepool :-(
Please first make sure you have your wallet recovery phrases safely stored and then proceed to:
- [Locate the state directory](https://iohk.zendesk.com/hc/en-us/articles/360039391494-Open-the-state-directory) of the **Testnet** instance (be careful not to delete the Mainnet one)
- Close Daedalus Testnet
- Uninstall Daedalus Testnet
- Delete the Daedalus Testnet state directory
- Restart your machine
- Install Daedalus Testnet again
- Run it again 🙏 

If this doesn't work, please send your logs and we will look into it further.

Thanks!

**Comment by tomyfalgui** [comment]
https://gist.github.com/tomyfalgui/fae9e38f1d81c1281e5fc686d08f3941

Here @nikolaglumac

**Comment by tomyfalgui** [comment]
yep,  the same thing happens for me. i was able to start it up once when i first synced the cardano-node. subsequent uses just made it crash immediately. The daedalus window would pop up, the logo would show and then it would freeze and exit.

**Comment by angelstakepool** [comment]
> Is it Daedalus crashing or the node? Do you see the screen stating that "Cardano node has crashed" or is it that whole Daedalus window vanishes?

vanishes -> 🎩

**Comment by angelstakepool** [comment]
@nikolaglumac 

Sure, installing now ...

**Comment by nikolaglumac** [comment]
Many thanks 😊

**Comment by nikolaglumac** [comment]
Hi all!
Yesterday we released Daedalus Testnet 4.4.1 which includes the fix for crashes on Windows.
Please use the auto-update feature or download the latest version from the official Daedalus Testnet website: https://testnets.cardano.org/en/testnets/cardano/get-started/wallet/
Once again sorry for the inconvenience and thanks for the support!
