### ISSUE TITLE
Can't send token in transaction: "Not enough ada. Try to move a smaller amount!"

### ISSUE THREAD

**Issue by katakombi** [input-output-hk/daedalus#2696]
I'd like to move a share of my WMT tokens from one wallet to another using Daedalus. I plan to get this done until Monday because I'd like to stake only a portion of these.

However, it always fails with a note "Not enough ada. Try to move a smaller amount!" This happens AFTER I type the spending password. I even deposited some additional Ada in case that would be the problem and my balance shows > 4 - this should be sufficient, no?

I am not willing to try to send a smaller amount of WMT especially since this looks like a bug: I even reproduce this message when I type an arbitrary spending password....wth? :D

Dear devs, please PM me if you need my wallet address.

Daedalus version 4.3.1 - mainnet

**Comment by nikolaglumac** [comment]
Are you sure this is an official Daedalus Mainnet? 
The latest version is 4.3.1 and not 4.3.2...

**Comment by katakombi** [comment]
Yep... sorry my wrong: I am running version 4.3.1, mainnet

**Comment by nikolaglumac** [comment]
> I've tried using the amount that has been suggested (around 1.39 Ada), 1.5 Ada, 2 Ada, all Ada. The result was always the same. I have 10k WMT and want to send 5k of it.

I believe the problem is that there is not enough ada left in the wallet to cover the remaining WMT tokens.
Please try send more ada to this wallet (so that it totals at least 10 ADA) and then try to send out the amount that the wallet recommends.

> It now occurred to me I might have messed up my spending password - is there a way to validate it without actually having to do a transaction?

Unlikely. If you want to test it out you can use the "Change password" option on the wallet "Settings" screen.

**Comment by dmitrii-gaico** [comment]
@katakombi Hello. Could you please advise if you still experience any issues with Daedalus (latest release)? Thank you in advance.

**Comment by katakombi** [comment]
I hardly use daedalus now to transfer token. If you give me exact instructions I will see what I can do to test something that comes close to the previous issue.

**Comment by katakombi** [comment]
that being said, I have no issues with daedalus although I use it mainly as a backend to submit my nami / etrnl transactions

**Comment by dmitrii-gaico** [comment]
@katakombi Thank you for your feedback! A lot of improvements were done so I just needed to make sure you no longer facing any issues. Please open a new ticket if you going to experience any issues in future or would like to suggest any improvements.
