### ISSUE TITLE
Hi @macovedj ,

### ISSUE THREAD

**Issue by fhcalderon87** [input-output-hk/daedalus#2706]
Hi @macovedj ,

I was also trying the verification in Ubuntu and again the keyserver is not available (old and new). Please let me know if there is another alternative.

We have conducted our investigation and found out that the keyserver is no longer operational. Whilst waiting for our webteam to update the information, could you try this command out with an alternative server and let us know the outcome please:

`gpg2 --keyserver hkp://Keys.Openpgp.org --search-keys signing.authority@iohk.io`

Many thanks,
Mior

_Originally posted by @miorsufianiohk in https://github.com/input-output-hk/daedalus/issues/2605#issuecomment-867643304_

**Comment by nikolaglumac** [comment]
@fhcalderon87 @miorsufianiohk what is this about?
