### ISSUE TITLE
Daedalus Mainnet 4.4.0 immediately crashes upon startup

### ISSUE THREAD

**Issue by tomyfalgui** [input-output-hk/daedalus#2711]
My problem is similar to #2695. After updating my daedalus mainnet to 4.4.0, the daedalus window pops up and then freezes after a second and then crashes.

**Comment by dmitrii-gaico** [comment]
@tomyfalgui Thank you for assistance, we are currently researching this issue. 
Thank you!

**Comment by Valvorian** [comment]
How can I roll back to 4.3.1? Any help appreciated. Thank you.

**Comment by nikolaglumac** [comment]
Hi all!
Yesterday we released Daedalus 4.4.1 which includes the fix for crashes on Windows.
Please use the auto-update feature or download the latest version from the official Daedalus website: https://daedaluswallet.io/en/download/
Once again sorry for the inconvenience and thanks for the support!
