### ISSUE TITLE
User experience request - tokens are hard to interact with

### ISSUE THREAD

**Issue by Jack-0** [input-output-hk/daedalus#2713]
![Screenshot from 2021-10-20 09-10-26](https://user-images.githubusercontent.com/24880289/138060804-175494ee-621d-4f6e-858c-50650e28735b.png)

Please review the token search method. I believe any product must have good user interfaces. 

Searching for tokens via the fingerprint is not user friendly. This is a request to change it. So that at least the ASCII readable version of the token is present at some point in the token drop box. Allowing the user to make a bit more sense of the fingerprint.

Picture related, Thanks Jack-0

**Comment by daniloprates** [comment]
Thanks you @Jack-0, this is a very valuable suggestion and it should be soon discussed in our team.
