### ISSUE TITLE
Can't connect to ledger on 4.4.1

### ISSUE THREAD

**Issue by elipwns** [input-output-hk/daedalus#2718]
![image](https://user-images.githubusercontent.com/5620009/138211490-5ee867a1-c809-4203-a914-032e3afc46fa.png)

**Comment by nikolaglumac** [comment]
Please provide more info:
- Daedalus logs
- Operating system info
- Machine details (CPU, RAM, etc$
- Ledger details (type, firmware, cardano app version) 
- Are you able to use your Ledger device with Ledger Live / Yoroi / AdaLite
- Were you able to pair your Ledger with earlier versions if Daedalus
- Dis you make sure Ledger Live / Yoroi / AdaLite was not running while trying to pair Ledger with Daedalus?

Thanks!

**Comment by tomislavhoracek** [comment]
@elipwns Problem is probably with the corrupted Daedalus state directory. 
Can you please clean your state directory: https://iohk.zendesk.com/hc/en-us/articles/360039511853-Delete-the-contents-of-the-state-directory 
If you are still not able to restore your hardware wallet please follow the instructions @nikolaglumac  mentioned.

p.s. If you have other wallets, please ensure you have mnemonics for them before removing the state directory.

**Comment by elipwns** [comment]
Sorry, was out elk hunting. I cleared my state directory, and then my ledger was connected just like before once it had fully synced the chain. Sorry for late response / not enough debug info in OP.

**Comment by tomislavhoracek** [comment]
@elipwns I'm happy to hear that everything is ok now :)
