### ISSUE TITLE
MacOS upgrade followed and lost all information

### ISSUE THREAD

**Issue by lukehinds** [input-output-hk/daedalus#2720]
I have a nano ledger S, so I know my ADA is safe, but reporting this as a UX bug.

Opened the daedalus app to check what my rewards may have been from staking and noticed the UI told me a new version was out. So I clicked on the link and upgraded. The upgrade went through with no issue. Reopened the app and all previous state is completely lost and it's like a fresh install. 

I figure I will be able to restore from syncing my ledger nano again, but it's not a very good user experience to have an upgrade wipe everything out. 

macOS 10.15.7 (19H2)

![image](https://user-images.githubusercontent.com/7058938/138348678-15a3a19f-6a4d-46d7-93e6-a765c5910c89.png)

**Comment by dmitrii-gaico** [comment]
@lukehinds Hello! Could you please advise if you still facing the issue? I might be the known issue that sometimes Wallets are vanished and displayed just fine after the app restart.
Thank you in advance.

**Comment by dmitrii-gaico** [comment]
Closing the record due to inactivity. If you still facing the issue please create a new card so we can continue investigation. Thank you.
