### ISSUE TITLE
unknown delegate on daedalus

### ISSUE THREAD

**Issue by KIDx** [input-output-hk/daedalus#2729]
Rewards address: stake1uxxz9r7uhdpeglnv855lqpapdg2hdsxj6pz7yu9lgqhy3ysru3hms

unknown delegate on daedalus :
![image](https://user-images.githubusercontent.com/2316836/139518983-220d4da4-2e3b-47ed-83cb-2aff1535f8ad.png)
![image](https://user-images.githubusercontent.com/2316836/139518998-3c08a6e8-8e51-46f7-8c60-adf37088b78c.png)

on https://adapools.org/stake/stake1uxxz9r7uhdpeglnv855lqpapdg2hdsxj6pz7yu9lgqhy3ysru3hms :
![image](https://user-images.githubusercontent.com/2316836/139518736-820c8261-213d-464b-b26f-cbcd7a70bd3a.png)

**Comment by ssoto2** [comment]
I am also experiencing the same issue 

Daedalus Version: 4.4.1
Wallet: Ledger Key Enabled
Delegating To: Meld5 ISPO

![Selection_611](https://user-images.githubusercontent.com/5123879/139567396-8c9d02af-3538-447a-85a9-1e5bfb06f555.png)

![Selection_612](https://user-images.githubusercontent.com/5123879/139567368-909263ba-a19a-4c25-915d-afdf826c0ecd.png)

**Comment by dmitrii-gaico** [comment]
Hello. Thank you for your reports. @KIDx @ssoto2 
Looks like the Meld5 ISPO is missing metadata and as result it is displayed as "unknown".
Could you please advise when you noticed that it is displayed as "Unknown" ? Did it showed up correctly previously?
Thank you in advance.

**Comment by ssoto2** [comment]
@dmitrii-gaico I wish I could provide a more exact time but I just recently noticed as i don't go in to the delegation page that often. 

Regarding the question had the MELD pool showed up in the delegation panel, yes it did. The first time I have noticed it not being there in Daedalus is after 4.4.1 upgrade.

**Comment by CarlosLopezDeLara** [comment]
The pool was updated a few days ago (Oct/27): [https://cardanoscan.io/transaction/39751912efced3faa178817a00492560f4faadce15f7f3abc22fa68dcd6f6466?tab=poolcertificates](https://cardanoscan.io/transaction/39751912efced3faa178817a00492560f4faadce15f7f3abc22fa68dcd6f6466?tab=poolcertificates)

Metadata seems to be wrong.  SMASH replies with: 


```
curl --silent "https://smash.cardano-mainnet.iohk.io/api/v1/errors/4d4e74fd118c8ac009b8c9fcb7e5e8d6ef297bbdc36aa794282c71ef?fromDate=27.10.2021"

[{"utcTime":"1635364624.015767s","poolId":"4d4e74fd118c8ac009b8c9fcb7e5e8d6ef297bbdc36aa794282c71ef","retryCount":9,"cause":"Hash mismatch from poolId '4d4e74fd118c8ac009b8c9fcb7e5e8d6ef297bbdc36aa794282c71ef' when fetching metadata from 'https://git.io/JcFsY'. Expected 7d22c00f2688c054b095cfd7f5e46f3539f3ddc09951fadde7e59589e4248a76 but got 2511c235da5f6440b26b38bc9135a4b434500f65f3db7fe9770b35c2ad681efa.","poolHash":"7d22c00f2688c054b095cfd7f5e46f3539f3ddc09951fadde7e59589e4248a76","time":"27.10.2021. 19:57:04"},

´´´

Since SMASH is finding errors, it does not put the pools metadata in cache for Daedalus to use. So Daedalus displays it as UNKNOWN. It is the SPO who has to resolve the issue with the metadata.

**Comment by kk-hainq** [comment]
@CarlosLopezDeLara Is there a potential cache or delay in the above SMASH? We've fixed the metadata mismatch issue two days ago with Yoroi, for example, reflected correctly. For example with the above pool:
- https://pool.vet/#4d4e74fd118c8ac009b8c9fcb7e5e8d6ef297bbdc36aa794282c71ef

**Comment by ssoto2** [comment]
I am now seeing Meld SP showing up Daedalus! Don't know what has changed or if something was out of sync, but the SP is showing up now! Thanks, Guys! 

![Selection_617](https://user-images.githubusercontent.com/5123879/140062309-d39d5be2-319e-4997-ad6f-5a257a7fb058.png)

**Comment by kk-hainq** [comment]
Awesome! I guess we can close this issue now then.

**Comment by dmitrii-gaico** [comment]
Great to hear it was resolved. Closing the ticket. Thank you.
