### ISSUE TITLE
Gift Card Support

### ISSUE THREAD

**Issue by RNDfr** [input-output-hk/daedalus#2743]
It would be interesting to have Gift Card support in Daedalus, allowing gift card creation and tools to empty a gift card. I wrote a short article about Gift Cards [on Reddit](https://www.reddit.com/r/cardano/comments/qpf87q/cardano_gift_cards), and I made a live demo of a gift card generator [here](https://randomfrenchpool.com/en/cards).

Here are the relevant points:

>Gift cards are paper wallets intended to be gifted (fancy documents bundled with instruction and mnemonic words). Gift cards are potentially beneficial for the ecosystem since they allow to easily gift Cardano to people who don’t own a wallet or an exchange account (thus good for adoption).
>
>The main risk with Gift Cards is that the person receiving the funds could use the restored wallet as its own (thus putting more funds on an insecure wallet).

Here are three Gift Card features that could be integrated into Daedalus:
1. Gift Card Generation: A menu to generate a paper wallet bundled with instructions.
2. Gift Card Restoration: A menu to automatically restore and empty a gift card to a secure wallet.
3. Gift Card Detection: A feature that detect when a gift card is restored (in the classic wallet restore menu) and propose a Gift Card restoration (2.) instead.

Concerning (3.): one way to detect if a restored wallet is a Gift Card would be to generate every Gift Card with 'gift' as their first word. 
However, it would reduce the wallet possibilities from 2048^24 to 2048^23 (a potential security risk). 

I posted a Gift Card Standard proposal [on GitHub](https://github.com/RNDfr/crypto-gift-card-standards/blob/main/cardano/ADA-CGC01.md), which could be used as a joint base for different services willing to integrate gift cards.

**Comment by RNDfr** [comment]
I'm trying to submit a [CIP](https://forum.cardano.org/t/cip-cardano-gift-cards/87219) for a technical specification as [suggested](https://github.com/Emurgo/yoroi-frontend/issues/2525) by one of Yoroi's developers.

**Comment by daniloprates** [comment]
Thanks @RNDfr, we'll keep an eye on the CIP.
