### ISSUE TITLE
High resource usage

### ISSUE THREAD

**Issue by asanchez1987** [input-output-hk/daedalus#2754]
Hi,

I'm aware Daedalus is a full node wallet and it downloads a full copy of the Cardano blockchain and verifies every transaction. Once it is 100% synced, I guess it keeps validating incremental changes.

Is it expected for the underlying cardano-node process to use 1024.6GiB VSZ, 9.6GiB RES, 118.9 %CPU?
Many times I can't perform other lightweight tasks on the system if I have Daedalus running in the background, as the system starts swapping and becomes unusable.

Below and attached there's more info about the system, versions and some stats. Previous Daedalus versions already exhibited this problem for me:

Daedalus 4.5.1, Linux build 19747, Cardano Node 1.30.1, Cardano Wallet 2021.9.29.
The system has 4 cores, 2 threads per core, 15.4 GiB RAM.
Debian 11.

My impression looking at pmap output is that most of the usage comes from anon pages. Without looking at the code, I'm wondering if the process is mmap()'ing synced files into memory somehow or if there's a memory leak somewhere?

I'd appreciate some feedback on this.

Thanks!
[top.txt](https://github.com/input-output-hk/daedalus/files/7580468/top.txt)
[pmap.txt](https://github.com/input-output-hk/daedalus/files/7580474/pmap.txt)
[ps.txt](https://github.com/input-output-hk/daedalus/files/7580475/ps.txt)
[free_m.txt](https://github.com/input-output-hk/daedalus/files/7580476/free_m.txt)

**Comment by nikolaglumac** [comment]
Hi @asanchez1987!
We are working on optimising Cardano Node's memory usage through the RTS flags.
This however, requires a lot of testing and therefore we need a bit more time to test it before releasing it.
Thank you for the patience!
Cheers!

**Comment by asanchez1987** [comment]
Hi @nikolaglumac ,

Thanks for your feedback. I guessed this was an already known issue.
Just out of curiosity, has the source of the high memory footprint been identified?

If that's the case, can you elaborate on why this happens?

Are the synced blocks from the chain mmaped() into memory?

Thanks!

**Comment by nikolaglumac** [comment]
Mainly UTXO growth. This is more of a question for https://github.com/input-output-hk/cardano-node

**Comment by zinigor** [comment]
@nikolaglumac I'm happy to help test various RTS parameters if you need volunteers for that. Do you have documentation about how to do that somewhere that I can read?

**Comment by dmitrii-gaico** [comment]
Daedalus 4.8.0 had released and includes the RTS Flags Mode which improves the RAM usage on any machines if enabled. 
Please open a new card if you still experience any issues with Daedalus.
Thank you!
