### ISSUE TITLE
Trezor T Exporting the public key failed

### ISSUE THREAD

**Issue by JPBrier** [input-output-hk/daedalus#2777]
After upgrading my Trezor T to firmware 2.4.3, i cant no longer send transactions or pair more wallets on Daedalus since it gives me the error of "Exporting the public key failed".

Any workaround on this ?

**Comment by JPBrier** [comment]
I've managed to fix it downgrading to version 2.4.2, waiting on the fix for version 2.4.3.

**Comment by tomislavhoracek** [comment]
@JPBrier Thanks for letting us know. 
Issues are reported to the Trezor team.
https://github.com/trezor/connect/issues/966
