### ISSUE TITLE
Ledger Nano S works only if it's connected and unlocked BEFORE Windows Daedalus is launched

### ISSUE THREAD

**Issue by benapetr** [input-output-hk/daedalus#2789]
This is extremely annoying and insecure - the only way to get Daedalus to work with Ledger Nano S is to connect it and unlock it and THEN start Daedalus (which sometimes takes >1 hour to start) so I have to leave unlocked connected hardware wallet at my desktop for a very long time.

If you first start Daedalus and connect the wallet later, then any combination of connecting / unlocking hardware wallet just doesn't work. On other hand when I am working on Linux with hw wallet CLI, it works perfectly.

Also if you own multiple hardware wallets, you need to restart Daedalus (10minutes to several hours) every time you want to swap them.

OS: Windows 10

**Comment by CarlosLopezDeLara** [comment]
This is a known issue. The team is working to fix it. You can track https://github.com/input-output-hk/daedalus/pull/2698
