### ISSUE TITLE
Cannot pair Trezor Model T with Daedalus after upgrading the firmware version to 2.4.3

### ISSUE THREAD

**Issue by rideorwalk** [input-output-hk/daedalus#2795]
I've upgraded my Trezor Model T firmware yesterday to version `2.4.3` and right after doing so I could no longer send a transaction in Daedalus using my paired wallet, I kept getting `Exporting the public key failed`. 

What I've tried:
- I've wiped my Trezor Model T and reset it
- I've uninstalled and reinstalled Trezor Suite
- I've upgraded Trezor bridge
- I've unpaired my Trezor from Daedalus

but every time I try to pair it I now get the same public key error:
<img width="40%" src="https://user-images.githubusercontent.com/92498313/147162802-93d38661-7cf4-49b3-a4a2-14e536cdd583.png" />

It worked fine right before upgrading the firmware version so my guess is an issue with the new version?

**Comment by tomislavhoracek** [comment]
@rideorwalk It is a known issue and here is the explanation
https://github.com/input-output-hk/daedalus/issues/2790

Let us know if you will have more problems with that. Thanks.
