### ISSUE TITLE
Clicking "Wallet Settings ⌘ ;" has no effect

### ISSUE THREAD

**Issue by pjivers** [input-output-hk/daedalus#2796]
**Issue**

On the MacOS version of Daedalus Mainnet, sometimes clicking the "Wallet Settings ⌘ ;" option under the "Daedalus Mainnet" menu has no effect. Similarly, using the hotkey combination `⌘ + ;` has no effect. This is only an intermittent issue though, as clicking on the wallets icon and clicking away again seems to fix it.

https://user-images.githubusercontent.com/1411509/147398450-d2b92a52-3c03-4d34-9b48-d890b057e051.mp4

**How to reproduce**
1. Navigate to wallets screen
2. Click "Add wallet"
3. Click another tab in the left pane to navigate away, e.g. "Settings"
4. Click "Wallet Settings ⌘ ;" option under the "Daedalus Mainnet" menu OR use the `⌘ + ;` hotkey combo

**Environment**
- Daedalus Mainnet (4.6.0#20052)
- MacOS 12.0.1 (21A559)
- M1 Max CPU

**Comment by danielmain** [comment]
Hi @pjivers thank you for find and report this Issue!

**Comment by pjivers** [comment]
No worries, @danielmain. Glad I can help.

**Comment by danielmain** [comment]
This Issue will be solved here: [DDW-860](https://input-output.atlassian.net/browse/DDW-860)

**Comment by danielmain** [comment]
This bug will be fixed here: [DDW-881](https://input-output.atlassian.net/browse/DDW-881)

**Comment by dmitrii-gaico** [comment]
Closing the card as the issue was fixed and would be included into the upcoming releases.
Thank you for report!
