### ISSUE TITLE
Daedalus 4.6.0 with Trezor - Issue exporting public key

### ISSUE THREAD

**Issue by brandonmcgarvey** [input-output-hk/daedalus#2800]
HI. Daedalus with Trezor Model T is unable to export the public key if I try to send ADA or use Share address. I have tried closing out of Daedalus, disconnecting the Trezor and reconnecting, but it still gives me this error. I know this was working somewhat recently, but I am not sure if it stopped working on the latest build or the one prior. I verified that I can send from this Trezor wallet using Yoroi.
![daedalusTrezor](https://user-images.githubusercontent.com/77640045/147698524-4921d02b-975c-4068-8399-ed8c67fce8c7.png)

**Comment by danielmain** [comment]
Hi @brandonmcgarvey It is a known issue 🙁 and here is the explanation and the workaround [#2790](https://github.com/input-output-hk/daedalus/issues/2790#issuecomment-996678116)

**Comment by brandonmcgarvey** [comment]
Thank you. I downgraded fw and it is working again.
