### ISSUE TITLE
error while loading shared libraries: libdl.so.2

### ISSUE THREAD

**Issue by mnn** [input-output-hk/daedalus#2802]
I have download today the binary, but when I try to run it, it crashes:
```sh
<> ./daedalus-4.6.0-mainnet-20052.bin
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```
But it looks like I have the library installed:
```sh
<> locate libdl.so.2
/usr/lib/libdl.so.2
/usr/lib32/libdl.so.2
/var/lib/snapd/snap/core/11798/lib/i386-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/11798/lib/x86_64-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/11993/lib/i386-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/11993/lib/x86_64-linux-gnu/libdl.so.2
```
Maybe the installer is jailed in some kind and only uses its own libraries, so it doesn't see the system ones?

<details>
<pre>
<> inxi -Fxzc0
System:
  Kernel: 5.15.7-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0
    Desktop: i3 4.20.1 Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Desktop Mobo: ASRock model: X570 Phantom Gaming X
    serial: <superuser required> UEFI: American Megatrends v: P4.40
    date: 06/23/2021
CPU:
  Info: 8-core model: AMD Ryzen 7 3800X bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2322 high: 3972 min/max: 2200/4559 boost: enabled
    cores: 1: 3972 2: 2005 3: 2004 4: 2022 5: 2057 6: 2738 7: 2058 8: 2057
    9: 3770 10: 2021 11: 2033 12: 2059 13: 2001 14: 2241 15: 2056 16: 2058
    bogomips: 124843
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU102 [GeForce RTX 2080 Ti Rev. A] vendor: ASUSTeK
    driver: nvidia v: 495.44 bus-ID: 10:00.0
  Display: x11 server: X.Org 1.21.1.2 driver: loaded: nvidia resolution:
    1: 1920x1080~60Hz 2: 3840x2160~60Hz 3: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 495.44 direct render: Yes
Audio:
  Device-1: NVIDIA TU102 High Definition Audio vendor: ASUSTeK
    driver: snd_hda_intel v: kernel bus-ID: 10:00.1
  Device-2: AMD Starship/Matisse HD Audio vendor: ASRock
    driver: snd_hda_intel v: kernel bus-ID: 12:00.4
  Sound Server-1: ALSA v: k5.15.7-1-MANJARO running: yes
  Sound Server-2: sndio v: N/A running: no
  Sound Server-3: JACK v: 1.9.19 running: no
  Sound Server-4: PulseAudio v: 15.0 running: yes
  Sound Server-5: PipeWire v: 0.3.40 running: yes
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 07:00.0
  IF: wlp7s0 state: down mac: <filter>
  Device-2: Intel I211 Gigabit Network vendor: ASRock driver: igb v: kernel
    port: e000 bus-ID: 09:00.0
  IF: enp9s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-3: Realtek RTL8125 2.5GbE vendor: ASRock driver: r8169 v: kernel
    port: d000 bus-ID: 0b:00.0
  IF: enp11s0 state: down mac: <filter>
  IF-ID-1: wg0 state: unknown speed: N/A duplex: N/A mac: N/A
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 3-2:2
  Report: rfkill ID: hci0 rfk-id: 1 state: up address: see --recommends
Drives:
  Local Storage: total: 2.5 TiB used: 1.92 TiB (76.8%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 250GB
    size: 232.89 GiB temp: 46.9 C
  ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 250GB
    size: 232.89 GiB temp: 49.9 C
  ID-3: /dev/nvme2n1 vendor: Samsung model: SSD 970 EVO Plus 250GB
    size: 232.89 GiB temp: 47.9 C
  ID-4: /dev/sda vendor: Western Digital model: WD20EZRZ-00Z5HB0
    size: 1.82 TiB
Partition:
  ID-1: / size: 219.27 GiB used: 182.91 GiB (83.4%) fs: ext4 dev: /dev/dm-0
    mapped: luks-78d47a35-fb47-4d0e-b017-a7f88b2644d1
  ID-2: /boot/efi size: 299.4 MiB used: 424 KiB (0.1%) fs: vfat
    dev: /dev/nvme2n1p1
Swap:
  ID-1: swap-1 type: partition size: 8.8 GiB used: 81.5 MiB (0.9%)
    dev: /dev/dm-1 mapped: luks-c9fb1ecf-ca30-4a76-86d9-d22e7a0f0ef3
Sensors:
  System Temperatures: cpu: 40.5 C mobo: 41.5 C gpu: nvidia temp: 45 C
  Fan Speeds (RPM): fan-1: 0 fan-2: 1062 fan-3: 0 fan-4: 775 fan-5: 764
    fan-6: 0 fan-7: 909 gpu: nvidia fan: 36%
Info:
  Processes: 9633 Uptime: 7h 46m Memory: 31.27 GiB used: 21.07 GiB (67.4%)
  Init: systemd Compilers: gcc: 11.1.0 clang: 13.0.0 Packages: 2870
  Shell: Zsh v: 5.8 inxi: 3.3.11
</pre>
</details>

**Comment by danielmain** [comment]
Hi @mnn I can't reproduce your error. Would you please give us more information about on what machine are you trying to install Daedalus? 

Run this and paste it here pls:
- `uname -mra`
- `cat /etc/issue`

Thank you in advance!

**Comment by mnn** [comment]
Sure, here it is:
```sh
<> uname -mra
Linux xxx 5.15.7-1-MANJARO #1 SMP PREEMPT Wed Dec 8 10:09:19 UTC 2021 x86_64 GNU/Linux
<> cat /etc/issue
Manjaro Linux \r  (\n) (\l)



<>
```

I replaced the name of my machine with `xxx` in the output of `uname`. I think both pieces of info are mentioned in the OP (the `▶ Details` should be possible to unfold by clicking on it, at least for me it seems to be working).

**Comment by danielmain** [comment]
You are using an arch based Linux. I have only NixOS and Ubuntu to test :( 
Do you have any distro (preferably Debian based) to try? 

Also we could check if your installer is corrupted? Please run this:

`sha256sum daedalus-4.6.0-mainnet-20052.bin`

**Comment by mnn** [comment]
```sh
<> sha256sum daedalus-4.6.0-mainnet-20052.bin
a14d88a794acf4c61c0c706150ee149fd53b1d9e4a6720bcda56b12f31832efd  daedalus-4.6.0-mainnet-20052.bin
```

It seems to match the hash on the site.

> You are using an arch based Linux. I have only NixOS and Ubuntu to test :(
Do you have any distro (preferably Debian based) to try?

Unfortunately not, just this Manjaro and a live Arch somewhere. Later this week I could try live Debian.

**Comment by mnn** [comment]
Tried it in Debian Buster and it works.

While I understand you don't want to support more distros, your page is a bit misleading then:

> Aimed at all Linux distributions

Manjaro/Arch are no niche distros, on DistroWatch in last year Manjaro sits on 3rd place and on Steam, Manjaro and Arch are second and third respectively (I realize that's not an accurate market share, but it is an important indicator). I would suggest to start looking at Arch compatibility, since this year is launching Steam Deck which will have Arch-based distro preinstalled (preorders shortly after opening were over hundred thousand users). Since Valve is switching, it is expected that gamedevs will also switch from supporting only Ubuntu to SteamOS (Arch-based, should be very close to Arch). You could try looking at some "container" tech like appimage or flatpack, since they are quite distro-agnostic.

I am glad now I didn't buy more ADA, because using anything in VM is a pain thus I am avoiding it as much as I can. Kinda disappointing, I was interested in Cardano because of the tech (I dabble in Haskell myself) :disappointed:.

**Comment by danielmain** [comment]
Hi @mnn you are right I haven't checked the distro watch for a while and yes, we should consider Manjaro. What do you think @daniloprates ?

Here I made a video, I tested Manjaro Linux in a virtual machine and it works! look here please: https://www.youtube.com/watch?v=1WUNM7cNf-s

**Comment by mnn** [comment]
Thank you for taking the time to test it on a clean Manjaro, that didn't even occurr to me to try.

So it's probably something with my Manjaro setup... Any way to enable logging in the installer? I tried passing `-v` and `--verbose` but it doesn't do anything.

```
<> ./daedalus-4.6.0-mainnet-20052.bin --verbose
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```

Is this some kind of nix container? I didn't have good experience with nix in the past, it looks like it continues to haunt me :smile:.

**Comment by mnn** [comment]
Did some searching and found out about `LD_DEBUG`. Here's I believe the relevant part:

```
22475   │    2729618: find library=libdl.so.2 [0]; searching
22476   │    2729618:  search path=glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/x86_64/x86_64:tls/x86_64:tls/x86_64:tls:x86_64/x86_64:x86_64:x86_64:     (LD_LIBRARY_PAT
        │ H)
22477   │    2729618:   trying file=glibc-hwcaps/x86-64-v3/libdl.so.2
22478   │    2729618:   trying file=glibc-hwcaps/x86-64-v2/libdl.so.2
22479   │    2729618:   trying file=tls/x86_64/x86_64/libdl.so.2
22480   │    2729618:   trying file=tls/x86_64/libdl.so.2
22481   │    2729618:   trying file=tls/x86_64/libdl.so.2
22482   │    2729618:   trying file=tls/libdl.so.2
22483   │    2729618:   trying file=x86_64/x86_64/libdl.so.2
22484   │    2729618:   trying file=x86_64/libdl.so.2
22485   │    2729618:   trying file=x86_64/libdl.so.2
22486   │    2729618:   trying file=libdl.so.2
22487   │    2729618:  search cache=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/etc/ld.so.cache
22488   │    2729618:  search path=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/glibc-hwcaps/x86-64-v3:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.3
        │ 3-55/lib/glibc-hwcaps/x86-64-v2:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/x86_64/x86_64:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2
        │ .33-55/lib/tls/x86_64:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/x86_64:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls:/n
        │ ix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64/x86_64:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64:/nix/store/2zchy9mdx
        │ 3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64:/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib      (system search path)
22489   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/glibc-hwcaps/x86-64-v3/libdl.so.2
22490   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/glibc-hwcaps/x86-64-v2/libdl.so.2
22491   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/x86_64/x86_64/libdl.so.2
22492   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/x86_64/libdl.so.2
22493   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/x86_64/libdl.so.2
22494   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/tls/libdl.so.2
22495   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64/x86_64/libdl.so.2
22496   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64/libdl.so.2
22497   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/x86_64/libdl.so.2
22498   │    2729618:   trying file=/nix/store/2zchy9mdx3kk166i98cx5sriq2c1bdsn-glibc-2.33-55/lib/libdl.so.2
22499   │    2729618:
22500   │ ./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libdl.so.2: cannot open shared obje
        │ ct file: No such file or directory
```

My layman guess would be that for some reason it can't load the library from the nix "container".

I also noticed these errors (not sure if relevant to my problem):

```
1066   │    2727148: find library=libnss_files.so.2 [0]; searching
1067   │    2727148:  search path=glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/x86_64/x86_64:tls/x86_64:tls/x86_64:tls:x86_64/x86_64:x86_64:x86_64:     (LD_LIBRARY_PATH
       │ )
1068   │    2727148:   trying file=glibc-hwcaps/x86-64-v3/libnss_files.so.2
1069   │    2727148:   trying file=glibc-hwcaps/x86-64-v2/libnss_files.so.2
1070   │    2727148:   trying file=tls/x86_64/x86_64/libnss_files.so.2
1071   │    2727148:   trying file=tls/x86_64/libnss_files.so.2
1072   │    2727148:   trying file=tls/x86_64/libnss_files.so.2
1073   │    2727148:   trying file=tls/libnss_files.so.2
1074   │    2727148:   trying file=x86_64/x86_64/libnss_files.so.2
1075   │    2727148:   trying file=x86_64/libnss_files.so.2
1076   │    2727148:   trying file=x86_64/libnss_files.so.2
1077   │    2727148:   trying file=libnss_files.so.2
1078   │    2727148:  search cache=/etc/ld.so.cache
1079   │    2727148:   trying file=/usr/lib/libnss_files.so.2
1080   │    2727148:
1081   │    2727148:
1082   │    2727148: calling init: /usr/lib/libnss_files.so.2
1083   │    2727148:
1084   │    2727148: /usr/lib/libnss_files.so.2: error: symbol lookup error: undefined symbol: _nss_files_getcanonname_r (fatal)
1085   │    2727148: /usr/lib/libnss_files.so.2: error: symbol lookup error: undefined symbol: _nss_files_gethostbyaddr2_r (fatal)
1086   │    2727148: /usr/lib/libnss_files.so.2: error: symbol lookup error: undefined symbol: _nss_files_getpublickey (fatal)
1087   │    2727148: /usr/lib/libnss_files.so.2: error: symbol lookup error: undefined symbol: _nss_files_getsecretkey (fatal)
1088   │    2727148: /usr/lib/libnss_files.so.2: error: symbol lookup error: undefined symbol: _nss_files_netname2user (fatal)
1089   │    2727148: find library=libnss_systemd.so.2 [0]; searching
```

**Comment by danielmain** [comment]
@mnn maybe you should try to reinstall your Manjaro. I hope you saw the video I created in order to know if Daedalus runs on Manjaro.

**Comment by danielmain** [comment]
About how to log/verbose the Installer, I can ask here in the company for that. But you would need to wait, :( Many of my colleagues have vacations.

**Comment by danielmain** [comment]
@mnn have you check this? https://ostechnix.com/fix-pacman-error-loading-shared-libraries-error-arch-linux/

I encourage you to try NixOS is my distro right now ;)

**Comment by cleverca22** [comment]
i believe this kind of issue happens when /tmp fills up when you run the installer
and due to a bug, it wont re-unpack things if you fix the free space and run it again

check /tmp for any large folders, clean them up, and then try again

**Comment by mnn** [comment]
@cleverca22 I don't believe that's an issue I am facing. I let running `watch -n 1 'df -h | grep /tmp | tee -a df.log ; date | tee -a df.log'` and in other terminal I ran the installer.

```
<> df -h | head -n1
Filesystem              Size  Used Avail Use% Mounted on
<> cat df.log
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:29 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:30 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:31 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:32 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:33 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:05:34 CET
tmpfs                    16G   58M   16G   1% /tmp
Po 24. ledna 2022, 20:05:35 CET
tmpfs                    16G  106M   16G   1% /tmp
Po 24. ledna 2022, 20:05:36 CET
tmpfs                    16G  143M   16G   1% /tmp
Po 24. ledna 2022, 20:05:37 CET
tmpfs                    16G  164M   16G   2% /tmp
Po 24. ledna 2022, 20:05:38 CET
tmpfs                    16G  181M   16G   2% /tmp
Po 24. ledna 2022, 20:05:39 CET
tmpfs                    16G  198M   16G   2% /tmp
Po 24. ledna 2022, 20:05:40 CET
tmpfs                    16G  215M   16G   2% /tmp
Po 24. ledna 2022, 20:05:41 CET
tmpfs                    16G  232M   16G   2% /tmp
Po 24. ledna 2022, 20:05:42 CET
tmpfs                    16G  248M   16G   2% /tmp
Po 24. ledna 2022, 20:05:43 CET
tmpfs                    16G  265M   16G   2% /tmp
Po 24. ledna 2022, 20:05:44 CET
tmpfs                    16G  282M   16G   2% /tmp
Po 24. ledna 2022, 20:05:45 CET
tmpfs                    16G  299M   16G   2% /tmp
Po 24. ledna 2022, 20:05:46 CET
tmpfs                    16G  316M   16G   2% /tmp
Po 24. ledna 2022, 20:05:47 CET
tmpfs                    16G  332M   16G   3% /tmp
Po 24. ledna 2022, 20:05:49 CET
tmpfs                    16G  349M   16G   3% /tmp
Po 24. ledna 2022, 20:05:50 CET
tmpfs                    16G  366M   16G   3% /tmp
Po 24. ledna 2022, 20:05:51 CET
tmpfs                    16G  383M   16G   3% /tmp
Po 24. ledna 2022, 20:05:52 CET
tmpfs                    16G  399M   16G   3% /tmp
Po 24. ledna 2022, 20:05:53 CET
tmpfs                    16G  416M   16G   3% /tmp
Po 24. ledna 2022, 20:05:54 CET
tmpfs                    16G  434M   16G   3% /tmp
Po 24. ledna 2022, 20:05:55 CET
tmpfs                    16G  451M   16G   3% /tmp
Po 24. ledna 2022, 20:05:56 CET
tmpfs                    16G  467M   16G   3% /tmp
Po 24. ledna 2022, 20:05:57 CET
tmpfs                    16G  485M   16G   4% /tmp
Po 24. ledna 2022, 20:05:58 CET
tmpfs                    16G  502M   16G   4% /tmp
Po 24. ledna 2022, 20:05:59 CET
tmpfs                    16G  518M   16G   4% /tmp
Po 24. ledna 2022, 20:06:00 CET
tmpfs                    16G  541M   16G   4% /tmp
Po 24. ledna 2022, 20:06:01 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:06:02 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:06:03 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:06:04 CET
tmpfs                    16G   26M   16G   1% /tmp
Po 24. ledna 2022, 20:06:05 CET
```

It looks like in `/tmp` was 15.5GB free when the installer crashed.

**Comment by plamut** [comment]
**Update** - I might have figured out what could be wrong, the library installed on my system seems to be too old.

For a start I followed [this StackOverflow answer](https://stackoverflow.com/a/21173918/5040035). I set the `LD_LIBRARY_PATH` environment variable to point to the location of the `libdl.so.2` library found above by the `locate` command:
```
$ export LD_LIBRARY_PATH="/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
```

Running the Daedalus installer again now produced a different error:
```
$ ./daedalus-4.8.0-mainnet-20689.bin 
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot)
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nix/store/bz317974raly88wakps7h1y7p9l81hgz-gcc-10.3.0-lib/lib/libstdc++.so.6)
```

It seems that it requires GLIBC_2.33+, but what was the version installed on my system?
```
$ apt-cache policy libc6
libc6:
  Installed: 2.27-3ubuntu1.4
  Candidate: 2.27-3ubuntu1.4
```
My version is only `2.27`, so could that be the cause?

I have yet to try installing Daedalus on a system with more recent dependencies, but posting this here for the reference in case the clue might prove useful to some.

**Comment by plamut** [comment]
Just for the record, I tried compiling glibc 2.35 from source and installing into a custom path (to not override the existing system installation). When I set `LD_LIBRARY_PATH` to point to that installation directory, the shell became unusable:
```
$ export LD_LIBRARY_PATH="/path/to/myglibc-2.35/lib:$LD_LIBRARY_PATH"
$ ls
Segmentation fault (core dumped)
$ man
unset Segmentation fault (core dumped)
```
Clearly, pointing to too new a version of `libdl.so.2` was a dead end, unless I messed up something when compiling it. Clearing the environment variable made the shell session usable again:
```
$ unset LD_LIBRARY_PATH
$ ls
foo bar baz
```
Any other ideas?

(still have to try running Daedalus in a container, though)

**Comment by dmitrii-gaico** [comment]
@plamut @mnn Hello. I apologize for the delay. Please let me know if you are still experiencing any issue with running latest Daedalus build otherwise I would like to close the ticket. Thank you in advance!

**Comment by mnn** [comment]
@dmitrii-gaico Yes, the issue is still present. Just tested it with freshly downloaded binary:

```sh
<> ./daedalus-4.11.0-mainnet-21857.bin
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
<> locate libdl.so.2
/usr/lib/libdl.so.2
/usr/lib32/libdl.so.2
/var/lib/snapd/snap/core/13308/lib/i386-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/13308/lib/x86_64-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/13425/lib/i386-linux-gnu/libdl.so.2
/var/lib/snapd/snap/core/13425/lib/x86_64-linux-gnu/libdl.so.2
<> uname -mra
Linux xxx 5.18.10-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Jul 7 16:55:16 UTC 2022 x86_64 GNU/Linux
```

**Comment by plamut** [comment]
@dmitrii-gaico Same result as @mnn, the issue still occurs on my system, I'm afraid. I currently use a virtual machine as a semi-OK workaround (slow, as my total system RAM is only 16 GB, and I cannot allocate all of it to the VM).

```
$ sha256sum daedalus-4.11.0-mainnet-21857.bin 
46531a963d69687ca31dd68d471e0428f3d1bc2962da045d2e2618502463ad9b  daedalus-4.11.0-mainnet-21857.bin
```

```
$ ./daedalus-4.11.0-mainnet-21857.bin 
./nix/store/s74k20bgs8bm8267mifzxsmkgm2n94hb-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```

```
$ locate libdl.so.2
/lib/i386-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libdl.so.2
/lib64/libdl.so.2
/snap/core/13308/lib/i386-linux-gnu/libdl.so.2
/snap/core/13308/lib/x86_64-linux-gnu/libdl.so.2
/snap/core/13425/lib/i386-linux-gnu/libdl.so.2
/snap/core/13425/lib/x86_64-linux-gnu/libdl.so.2
/snap/core18/2409/lib/i386-linux-gnu/libdl.so.2
/snap/core18/2409/lib/x86_64-linux-gnu/libdl.so.2
/snap/core20/1494/usr/lib/i386-linux-gnu/libdl.so.2
/snap/core20/1494/usr/lib/x86_64-linux-gnu/libdl.so.2
/snap/core20/1518/usr/lib/i386-linux-gnu/libdl.so.2
/snap/core20/1518/usr/lib/x86_64-linux-gnu/libdl.so.2
/usr/local/myglibc-2.35/lib/libdl.so.2
```

```
$ uname -mra
Linux xxxxx 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you for looking into this in advance!

**Comment by danielmain** [comment]
Hi @plamut would you help me to reproduce it? What ubuntu version are you using?
Run pls `cat /etc/issue` and paste it here and I can try to reproduce it ;) 

I don't understand this:
>  currently use a virtual machine as a semi-OK workaround
You say you have to run Daedalus on a virtual machine, which is running what Linux version?

**Comment by plamut** [comment]
@danielmain 
```
$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l
```

It's worth noting that it's an old system running for 4+ years, and I imagine a lot of Frankenstein bloat has accumulated in these years. It's likely that the issue won't be reproducible under a clean Ubuntu 18.04 installation.... meh.

FWIW, I actually had Daedalus installed at some point, but then removed it because I was short on storage space. When re-installing it a few months later, though, I encountered this installation error that persists to date.

> You say you have to run Daedalus on a virtual machine, which is running what Linux version?

Ubuntu 20.04 running in Oracle VirtualBox, the wallet was installed flawlessly.

**Comment by danielmain** [comment]
Hi @plamut I took the time to install/run Daedalus in a VM running Ubuntu 18.04.6 LTS
![image](https://user-images.githubusercontent.com/4303099/180724779-bc9cb0d3-9041-4968-9e25-de47a6e53ef5.png)
![image](https://user-images.githubusercontent.com/4303099/180724813-b6c39ee1-5383-4a1a-bc73-6164719f2042.png)
![image](https://user-images.githubusercontent.com/4303099/180724837-2340f415-29d2-4cf1-8e8e-e30e4134f952.png)
No Issues

So, I recommend you to fix your Linux setup 🙏 
Please understand 🙇‍♂️, we can only help people here with issues related to Daedalus not Linux itself

**Comment by plamut** [comment]
@danielmain Thank you for looking into this.

For the reference (for future readers), "Frankenstein" was just my speculation, not a definite claim, because I had Daedalus successfully running on the very same machine as late as in September 2021 - but with the issue being non-reproducible could hint that the problem could be on my machine.

Cannot say much about the reasons why @mnn experienced the same issue.

**Comment by danielmain** [comment]
Thank you @plamut for understanding.

@mnn would you help me to reproduce it?
