### ISSUE TITLE
Daedalus wallet issue, Keep getting error when trying to reimport my wallet

### ISSUE THREAD

**Issue by irishann69** [input-output-hk/daedalus#2810]
Good evening,

I am trying to reinstall my wallet but I keep getting error despite my 24 word seed phrase being correct. I am 100% guaranteed that these are my seed phrases but I keep getting error. I have reinstalled my Daedalus wallet and while the node is synching, I can see my wallet there and it is updating. However, when the node has synced 100% and attempt to reimport wallet using my seed phrases, I keep getting error?

Please help me

**Comment by danielmain** [comment]
Hi @irishann69, would you please share more information? 

- What operating system are you using
- What Daedalus version.
- What is the error message

IMPORTANT: Please do not share the 24 words here and nowhere.

Thank you :)

**Comment by irishann69** [comment]
Daniel Thank you so so much for getting back to m.

But I figured out that with my update, I had never verified signature of file, hence issue.

Thankfully all good.

Again thank you for your kind response.

Take care

**Comment by danielmain** [comment]
Happy to help you :)
