### ISSUE TITLE
Export CSV with raw numbers.

### ISSUE THREAD

**Issue by jodeknudt** [input-output-hk/daedalus#2851]
Right now the exporting of the transactions use the preset number format.
Is it possible to  export the csv as a raw number format without the space/comma/period string-character.

The aesthetics of the number format are great and to my liking. but when i want to start fooling around with spreadsheets. it's just an extra step to remove the noise. :-)

**Comment by szymonmaslowski** [comment]
Hi @jodeknudt, thanks for your message. We will consider your suggestion and come back shortly with the decision.

**Comment by szymonmaslowski** [comment]
Hi @jodeknudt. We agreed your suggestion is valuable so we plan to implement it in the future.

**Comment by jodeknudt** [comment]
Thank you for the feedback, looking forward towards to this little tadpole of a change.

**Comment by dmitrii-gaico** [comment]
Thank you for your report. Closing the card as the feature was implemented and would be included into the upcoming release.
