### ISSUE TITLE
Pairing Ledger device with Daedalus on a windows machine fails

### ISSUE THREAD

**Issue by minh0722** [input-output-hk/daedalus#2876]
I'm having a very annoying problem when trying to pair a Ledger device with Daedalus on Windows machine and Ledger is not recognized. The screen is still asking user to connect and unlock the wallet. I have to connect and unlock the Ledger device before running Daedalus. This seems like an known issue but nothing is raised here so I decided to create the issue here

https://iohk.zendesk.com/hc/en-us/articles/360038741393

**Comment by dmitrii-gaico** [comment]
Hello. Yes, this is a known issue and it is currently in our ToDo list to be fixed.
Thank you for your report!

**Comment by minh0722** [comment]
PR created [here](https://github.com/input-output-hk/daedalus/pull/2698) but some conflicts need resolving

**Comment by dmitrii-gaico** [comment]
@minh0722 Hello. Could you please advise if issue is still reproducible for you using latest Mainnet release. Thank you in advance!

**Comment by minh0722** [comment]
The issue is now not reproducible in 4.10.0. Thanks for the great work!
