### ISSUE TITLE
Moving HDD into my new computer

### ISSUE THREAD

**Issue by soobin93** [input-output-hk/daedalus#2880]
Hi I'm trying to move my HDD into my new computer as my old one has suddenly died last night...
What's worse is that I've just realised that I have lost my notepad where I've written my security words...
I'm wondering if my daedalus wallet will still be logged in and working even if I just move my HDD into my new computer.
Please help!

P.S let me know if this is not the right place to post this kind of questions, I couldn't find any one to ask yet.

**Comment by danielmain** [comment]
Hi @soobin93 this should not be a problem as long the Daedalus state directory stays in the same path

Windows: `C:\Users\soobin93\AppData\Roaming\Daedalus Mainnet`
Linux: `/home/soobin93/.local/share/Daedalus/mainnet`
