### ISSUE TITLE
Daedalus keep returning the sync to old epochs

### ISSUE THREAD

**Issue by bruno-nirello** [input-output-hk/daedalus#2887]
## Problem:

Daedalus keep returning the sync to old epochs, it syncs for almost 90%, them stops saying  validating blocks... syncing blocks... and finally it goes back to 74%.

I already tried with a Ubuntu 20.04 still same issue.
i tried to sync the clock with a NTP every minut to keep the clock in sync
I have an SSD 1TB ADATA SX8200

![image](https://user-images.githubusercontent.com/30416677/154868155-e386abe0-8c58-4f77-95fe-f91a94839b43.png)

[logs-2022-02-20T224927.0223Z.zip](https://github.com/input-output-hk/daedalus/files/8105122/logs-2022-02-20T224927.0223Z.zip)

**Comment by marcin-mazurek** [comment]
Hi @bruno-nirello, for better visibility, we've raised a corresponding issue in cardano-node repository, you should be able to track the progress there: https://github.com/input-output-hk/cardano-node/issues/3708

**Comment by dmitrii-gaico** [comment]
@bruno-nirello Hello. Could you please advise if you still experiencing the issue using latest Daedalus release ? If so can I kindly ask you if you have a possibility to check the issue on another PC. Thank you in advance!

**Comment by bruno-nirello** [comment]
hi @dmitrii-gaico i still have the problem with daedalus 4.9.1 in my PC with ryzen, but not in my office laptop with Intel.

**Comment by dmitrii-gaico** [comment]
@bruno-nirello Thank you for reply. Am I right that you experience the issue on Windows / Ubuntu but on the same PC ? It might be that the issue is hardware related. It would be great if you can run some memory checks to make sure it is not faulty. I have checked the app on two different desktops one is with Ryzen 3600 and another one is Ryzen 7 4800h and both synced with no issues.

**Comment by bruno-nirello** [comment]
@dmitrii-gaico thank you for the advice, i will look for a software that scan errors on memory. Maybe the node is more sensitive to that.

**Comment by bruno-nirello** [comment]
after swithing all the memories, i found one that was having errors, i will close the issue, thanks @dmitrii-gaico @marcin-mazurek
