### ISSUE TITLE
Unable to clear warning triangle when token's recommended decimal places is 0

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/daedalus#2903]
When viewing tokens I sometimes see an orange triangle indicating that I should review the recommended decimal places.

**Happy path**
If the recommended decimal places is greater than 0 then I can open the settings and click "Save" to apply recommended value which also dismisses the warning triangle.

**Buggy path**
If the recommended decimal places is 0 then when I open the settings the "Save" button is disabled so I cannot apply the recommended value to dismiss the warning triangle

![Screenshot_20220303_133411](https://user-images.githubusercontent.com/74595920/156575234-67c2f55b-6969-4c1e-bdba-371f7cc06106.png)

Daedelus Version: 4.8.0#20689
OS: Linux KDE Ubuntu 20.04.3 LTS

**Comment by dmitrii-gaico** [comment]
Hello. Thank you for your report. This issue is known and it would be fixed in the next release. cc @CarlosLopezDeLara

**Comment by shawnbusuttil** [comment]
https://github.com/input-output-hk/daedalus/pull/2905

There is a PR open for this.
