### ISSUE TITLE
high ram usage

### ISSUE THREAD

**Issue by ramanicus** [input-output-hk/daedalus#2923]
cardano-node.exe consuming 8,708.8 MB of RAM, i read that it could use around 2.5-3 gb or ram, but 8.7 seems excessive, is there a solution for this?

**Comment by marcin-mazurek** [comment]
Hi @ramanicus!

Daedalus is a full node wallet - as the blockchain grows, memory usage does too. While in the past you could observe memory usage of 2.5-3 GB, currently you can expect 8 GB or more. The current hardware recommendation is to have at least 16 GB of RAM: https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-system-requirements

Having said that, in Daedalus 4.8.0 we introduced experimental RTS flags that could help reduce the RAM usage: https://iohk.zendesk.com/hc/en-us/articles/4415304990745-Enabling-RTS-Flags

Please also see similar reports from the past: https://github.com/input-output-hk/daedalus/issues/2535#issuecomment-826987215 and https://github.com/input-output-hk/daedalus/issues/2535#issuecomment-827480094

If your device does not meet the hardware requirements, you may want to consider using a light wallet such as [Yaroi](https://yoroi-wallet.com/#/). 

Please let me know if this answers your question.

**Comment by ramanicus** [comment]
Thank you for your fast response, I'm switching to Yaroi.  I did like the
daedalus, but i normally have 9GB free, and when I load it leaves me with 1
and sometimes 0 mem free.

**Comment by marcin-mazurek** [comment]
Thank you for your feedback!
