### ISSUE TITLE
Errata in "ADD A TOKEN" in Japanese environment

### ISSUE THREAD

**Issue by sakakibaraakio** [input-output-hk/daedalus#2931]
![スクリーンショット 2022-03-23 173840](https://user-images.githubusercontent.com/69729884/159657795-d8bcc05d-8212-4d23-aec9-3d61589f1dd0.png)

In the "ADD A TOKEN" field of a remittance, the bottom buttons in English are "Cancel" and "ADD", but in Japanese they are "キャンセル（Cancel）" and "キャンセル".

There is no problem with the function, only with the notation.
If you select "キャンセル" on the right, the token will be added.

**Comment by marcin-mazurek** [comment]
Hi @sakakibaraakio, a fix was added to this PR: https://github.com/input-output-hk/daedalus/pull/2921. It should be released with the next Daedalus release.

**Comment by dmitrii-gaico** [comment]
Closing the card as the issue was fixed and would be included into the upcoming release. Thank you for reporting it!
