### ISSUE TITLE
What is the point of keeping the older Daedalus versions on disk?

### ISSUE THREAD

**Issue by kedicesur** [input-output-hk/daedalus#2936]
I have noticed that several older versions of Daedalus are kept under the `.local/share/Daedalus/mainnet/Downloads` folder (Linux). Daedalus is already taking up a huge space on the disk. Especially considering that each version is like ~450Mb and an older version won't work anyway, can we not get rid of the olders once an upgrade to the latest version is successfully completed?

**Comment by shawnbusuttil** [comment]
It has been agreed that these should be deleted on all platforms.

Can you confirm, @daniloprates?

**Comment by dmitrii-gaico** [comment]
@kedicesur Thank you for your report. The issue would be fixed in the upcoming release.

**Comment by danielmain** [comment]
This has been fixed in the latest testnet release and coming in the next Daedalus mainnet release. The PR that solved it is: https://github.com/input-output-hk/daedalus/pull/2941
