### ISSUE TITLE
how to run after use yarn build

### ISSUE THREAD

**Issue by codingbeast** [input-output-hk/daedalus#2974]
can anyone please provide or guide how to use application after build by using 
yarn build

the app is working fine when I use yarn dev  but after using the build command 
I don't know how to run.

**Comment by danielmain** [comment]
Hi @codingbeast, I assume you want to build an artefact? We don't use yarn for that, we use nix for building.

Examples:

For Mac

```
sh ./scripts/build-installer-unix.sh --build-id ${number}
```

For Linux

```
nix-build -Q release.nix -A "${cluster}.installer.x86_64-linux" --argstr buildNum "$BUILDKITE_BUILD_NUMBER" -o csl-daedalus
```

But you can check the shell scripts located under ./scripts/

**Comment by codingbeast** [comment]
HI @danielmain Thank you for the help but the Linux command is not working.

**Comment by michalrus** [comment]
Hey, @codingbeast, depending on what you need (I’m assuming the `mainnet` network):

### Linux installer which will work anywhere: 

```
$ nix-build -A wrappedBundle --argstr cluster mainnet
# the installer is in result/
```

### Nix derivation which you can `nix-copy-closure` to another Nix-enabled system: 

```
$ nix-build -A daedalus --argstr cluster mainnet
# the executable will be under result/bin/
```

**Comment by michalrus** [comment]
@codingbeast unfortunately, you need to run `scripts/` from the root directory of the Daedalus project – it’s on my list to fix soon

**Comment by codingbeast** [comment]
@danielmain  and @michalrus Thank you for the help.

**Comment by codingbeast** [comment]
@michalrus  Can you please help me with how to create a Windows and Mac installer?

**Comment by michalrus** [comment]
Sure!

### Windows installer – has to be built on Linux (!)

```
$ cd daedalus/
$ nix-build -A windows-installer --argstr target "x86_64-windows" --argstr cluster "mainnet"
```
It will be in `result/`.

### macOS installer – has to be built on macOS

```
$ cd daedalus/
$ scripts/build-installer-unix.sh --clusters mainnet
```
It will be in `installers/csl-daedalus/daedalus-...-0.pkg`.
