### ISSUE TITLE
tsx or ts compiled file not working.

### ISSUE THREAD

**Issue by codingbeast** [input-output-hk/daedalus#2976]
when I try to try to edit something in TSX or ts file it's not showing when I run the app.
for example, I edit something in
<pre>source/renderer/app/components/settings/categories/SupportSettings.tsx</pre>

after that, I am running
<pre>
yarn lint
yarn compile 
yarn check:all
yarn dev
<pre>

but the edited text is not showing.

**Comment by danielmain** [comment]
Sorry @codingbeast I dont understand your question. What are you trying to change?

**Comment by codingbeast** [comment]
![Screenshot from 2022-05-07 18-30-30](https://user-images.githubusercontent.com/19985985/167255575-5b33e740-931c-4cf6-8f36-1b8ab28e5517.png)
just for testing I changed this highlighted text but its not showing when I run app by <pre>yarn dev</pre>

**Comment by danielmain** [comment]
Do you know how `react-intl` works? 

We use JSON files for the translations. What you are trying to change is only a "defaultMessage".

**Comment by codingbeast** [comment]
but why its not showing in app ?
