### ISSUE TITLE
 too many symbolic links encountered error on startup

### ISSUE THREAD

**Issue by codingbeast** [input-output-hk/daedalus#2984]
when I try to run the app using yarn dev
the Cardano-node is not started and shows too many symbolic links encountered
I am using (ubuntu ).
![Screenshot from 2022-05-15 12-55-31](https://user-images.githubusercontent.com/19985985/168462048-5bbbf631-1db4-4317-884c-fa99404a91f3.png)

**Comment by michalrus** [comment]
Hey, @codingbeast, can you commit & push all your local changes to your fork, and give me the link to that commit, so that I can reproduce?

Thank you!

**Comment by codingbeast** [comment]
Hi I have fixed the use by using a direct file instead of symbolic links

**Comment by michalrus** [comment]
I would still like to get a look at what caused this, but if you cannot show it, then fine.

Happy you were able to fix this on your own. :wave:
