### ISSUE TITLE
I used the import function and restored it, but a remittance error occurs.

### ISSUE THREAD

**Issue by hirohiro8382** [input-output-hk/daedalus#2985]
I am Japanese. I'm sorry I can't speak English.

I imported it with secret.key which has no password set. I entered the name, set the remittance password, and restored it. The balance is also displayed.

I get an error message when I try to send money to a new wallet.

You can send money from the new address, but not from the ADA address assigned by Cardano.

What's happening with this? I will attach a log, so please solve it.

ARIGATO
<img width="855" alt="スクリーンショット 2022-05-16 16 11 03" src="https://user-images.githubusercontent.com/105627957/168554040-7cbf8720-c632-43ef-a61e-12ef60b0862f.png">
[logs-2022-05-16T073356.0169Z.zip](https://github.com/input-output-hk/daedalus/files/8698523/logs-2022-05-16T073356.0169Z.zip)
U

**Comment by danielmain** [comment]
Hi @hirohiro8382

**Comment by hirohiro8382** [comment]
> Hi @hirohiro8382 you need a password. A valid password is mandatory.

Thank you. I set a remittance password when I imported secret.key, isn't that password?


You can successfully transfer money with this password from an address containing a small amount of ADA. However, if you try to send more than that amount, you will get an error.

The remittance password was not set when the initial Daedalus wallet was created
![スクリーンショット 2022-05-16 20 42 16](https://user-images.githubusercontent.com/105627957/168585319-cd7846c2-3366-4618-9880-88ce22388600.png)
.

**Comment by hirohiro8382** [comment]
>>>https://github.com/input-output-hk/daedalus/issues/1234
↑↑↑↑↑↑
I've checked all of these issues, but there was no solution.

If it is a secret.key with no password set, I think that the contents are an unencrypted master key. I want to use it and import from YOROI.

Is there a way to see the contents of this secret.key?

**Comment by dmitrii-gaico** [comment]
@hirohiro8382 Hello. Please submit a request with all the details via Service Desk. https://iohk.zendesk.com/hc/en-us Thank you in advance!

**Comment by hirohiro8382** [comment]
> @hirohiro8382 Hello. Please submit a request with all the details via Service Desk. https://iohk.zendesk.com/hc/en-us Thank you in advance!

IOHK does not look it up. The people here are kinder.

I'm sorry, but the situation is that this problem is currently occurring only in the secret.key that hiroki.okeya@gmail.com has, and it is a fairly low priority.
As stated in the Daedalus Terms of Service, please be sure to keep the recovery phrase. We have been asking users from the beginning to solve this problem because this recovery phrase has been lost. The reality is that we cannot allocate this resource.
 
If you find out something, we will contact you again.
 
We apologize for any inconvenience, and thank you for your continued support.
IOHK Technical Support Des
<img width="779" alt="スクリーンショット 2022-05-17 8 33 35" src="https://user-images.githubusercontent.com/105627957/168699176-7b4a2510-912f-41d4-b179-08558cee01a5.png">
k

**Comment by hirohiro8382** [comment]
Every time I restore a secret.key that doesn't have this password, I'm asked for a password. Does that mean it's reset every time



「This wallet is not password protected when sent.」
It is written like this.
<img width="674" alt="スクリーンショット 2022-05-17 8 31 05" src="https://user-images.githubusercontent.com/105627957/168699498-8aca244f-c43c-4e35-99de-6e8445fb17e6.png">
?

**Comment by danielmain** [comment]
Hi @hirohiro8382 we have several people reporting having the same problem by using the same secret.key pls respond the questions my colleagues in IOHK support are asking you.

**Comment by hirohiro8382** [comment]
> Hi @hirohiro8382 we have several people reporting having the same problem by using the same secret.key pls respond the questions my colleagues in IOHK support are asking you.
> 
> We are here only developers fixing software issues.

thank you.I will ask IOHK again.

I think it is the same as this problem. # 3142

____________________________________________________________
There are 3 separate bugs from the 2017 code which apply to this.

One is that the cardano-sl wallet never generated address indices in the hardened index range.
The other is that deriveXPub used the wrong range for hardened indices.
The last seems to be an off-by-one error for address indices.
I need to run some tests locally to reproduce it --then we can use a few CLI commands to verify with your wallet, and then we can come up with the procedure to spend the funds.
_______________________________________________________

Is there a way to fix this bug?
