### ISSUE TITLE
Decimal places should default to recommended

### ISSUE THREAD

**Issue by HeptaSean** [input-output-hk/daedalus#2987]
The decimal places for native tokens default to 0, even if the recommended value according to the token registry is something else.

Also, at least in the Daedalus Flight 4.10.0 I have installed, all warning signs that the current decimal places setting is not the recommended one are gone.

Lastly, it is odd that before changing the decimal places, Daedalus displays, e.g., 8272 SUNDAE, and after changing it, it displays 0.008272 SUNDAE. This cannot both be true: 8272 SUNDAE≠0.008272 SUNDAE Ask any mathematician.

Since Daedalus already knows from the token registry that 0.008272 SUNDAE is correct (if it is a good idea to depend on an off-chain data source for determining “correct” is another question, but all other wallet apps do the same), it should display 8272 ×10^(-6) SUNDAE or 8272 µSUNDAE or something like that, when the decimal places are set to 0.

**Comment by danielmain** [comment]
Hi @daniloprates would you pls evaluate this? thank you!

**Comment by HeptaSean** [comment]
Off-Topic: Can you remove the scam attempt in https://github.com/input-output-hk/daedalus/issues/2987#issuecomment-1128056530?

**Comment by daniloprates** [comment]
@HeptaSean thanks for your report. Some legal concerns led us to decide on the implementation this way. We will re-evaluate to see if it's possible to have this improvement and let you know.
