### ISSUE TITLE
Running v1.0.0

### ISSUE THREAD

**Issue by maneetgoyal** [input-output-hk/daedalus#2992]
![image](https://user-images.githubusercontent.com/25290212/170177177-ce910c3e-540a-42cb-af7b-1ad9626548c8.png)

Hi all,

Due to some restrictions, I need to use v1.0.0 but it shows me the above error. Please suggest if v1.0.0 can be used or I'll have to stick to the latest/greater versions?

**Comment by danielmain** [comment]
Hi @maneetgoyal of course this version is not maintained anymore. I can't imagine what restrictions do you have, but for security reasons and compatibility you need to use the latest version https://daedaluswallet.io/en/download/
