### ISSUE TITLE
URGENT - Old secret key not work on latest version of Daedalus

### ISSUE THREAD

**Issue by crazypioneer** [input-output-hk/daedalus#3004]
DEAR Daedalus Team!

I have some money on this Daedalus.
I charged about 5 years ago.
Recently, I have to transfer some money to another address but I couldn't because error occurs.
I think this is because old secret key.

I find that Daedalus team updated the wallet algorithm.
I think this is the problem.

CAN YOU PLEASE HELP ME?
Best Regards.

**Comment by danielmain** [comment]
Hi @crazypioneer we haven't changed that algorithm, you need to enter the correct passphrase when importing the secret.key  to make transactions. 

Would you please contact our support here: https://iohk.zendesk.com/hc/en-us/categories/360000877653-Daedalus-Mainnet

**Comment by crazypioneer** [comment]
@danielmain 
Thank you for your answer.
There was no problem importing secret.key file.
Can I import secret.key file with wrong passphrase?

**Comment by dmitrii-gaico** [comment]
@crazypioneer Hello! Thank you for your report. Could you please create a service desk request and share the details and circumstances as all the "secret keys" issues should be addressed via Service Desk first. Then if any DEV help would be required we would join the thread. Thank you in advance!
