### ISSUE TITLE
Node stops synchonizing at epoch 340, slot 417,281 (InvalidBlock)

### ISSUE THREAD

**Issue by frozencopper** [input-output-hk/daedalus#3006]
I didn't use Daedalus for a while so there was an update (4.10 -> 4.11.0#21857) when I started it a few days ago. After restarting Daedalus tried to verify and update the on-disk blockchain. But it sucked at a certain point. Restarting Daedalus and the PC didn't change that problem. 

I started to google a little bit an found the advice to delete the content of the chain folder. After restarting it took a realy long time to download and verify the chain but after about one day I had a similar Problem. The node stopped synchonizing. Restarting the node didn't help. 

The current state is the following:
When I start Daedalus, it takes a while and stucks at epoch 340, slot 417,281. 

When I look into the node.log there is an invalid block error: 

`[35m[PC:cardano.node.ErrorPolicy:Notice:44][0m [2022-06-30 16:43:56.61 UTC] IP 13.229.13.24:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[PC:cardano.node.ErrorPolicy:Notice:44][0m [2022-06-30 16:43:56.61 UTC] IP 18.223.202.44:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[PC:cardano.node.ErrorPolicy:Notice:44][0m [2022-06-30 16:43:56.61 UTC] IP 52.14.186.237:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[PC:cardano.node.ErrorPolicy:Notice:44][0m [2022-06-30 16:43:56.61 UTC] IP 18.182.219.85:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[35m[PC:cardano.node.ErrorPolicy:Notice:44][0m [2022-06-30 16:43:56.61 UTC] IP 18.158.211.17:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[31m[PC:cardano.node.DnsSubscription:Error:33447][0m [2022-06-30 16:43:57.19 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 3.19.78.159:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 61934091, blockPointHash = 4ab62c9d77c38c6969f80214d066d7bf9ea4084e04b1043e00fddf1dc441f7ac})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 12038901 (fromList [(PolicyID {policyID = ScriptHash "13e3f9964fe386930ec178d12a43c96a7f5841270c2146fc509a9f3e"},fromList [("ClayNationPitch22327",1),("ClayNationPitch72",1)]),(PolicyID {policyID = ScriptHash "2afb448ef716bfbed1dcb676102194c3009bee5399e93b90def9db6a"},fromList [("BISON",10000002006)]),(PolicyID {policyID = ScriptHash "4bf184e01e0f163296ab253edd60774e2d34367d0e7b6cbc689b567d"},fromList [("PaviaMinus215Minus182",1),("PaviaPlus206Plus80",1)]),(PolicyID {policyID = ScriptHash "5a2cdc6e3aa9612fe4676672f443e7efd39c309d45e7919a4bf27750"},fromList [("BossPlanetDistrictTwo10410",1)]),(PolicyID {policyID = ScriptHash "6ac8ef33b510ec004fe11585f7c5a9f0c07f0c23428ab4f29c1d7d10"},fromList [("MELD",215183914)]),(PolicyID {policyID = ScriptHash "6f87aa2ea552ecd24732d62831916ece54c52348417398085358cbed"},fromList [("StoneAgeHooligan2043",1)]),(PolicyID {policyID = ScriptHash "852526a77c45662e981181ed9b0afca13cfd8e45c169a20b37832ea7"},fromList [("Mucca154",1)]),(PolicyID {policyID = ScriptHash "884892bcdc360bcef87d6b3f806e7f9cd5ac30d999d49970e7a903ae"},fromList [("PAVIA",224)]),(PolicyID {policyID = ScriptHash "8a93cd0b1d610e7bab7419a4c8d8e79ed6f02ad73dc70ed7602f2602"},fromList [("Jukeboys1520",1)]),(PolicyID {policyID = ScriptHash "984394dcc0b08ea12d72b8833292e3c3197d7a8ac89aad61d2f5aa9e"},fromList [("EARTH_token",51015360000)]),(PolicyID {policyID = ScriptHash "9a9693a9a37912a5097918f97918d15240c92ab729a0b7c4aa144d77"},fromList [("SUNDAE",100468551)]),(PolicyID {policyID = ScriptHash "a0028f350aaabe0545fdcb56b039bfb08e4bb4d8c4d7c3c7d481c235"},fromList [("HOSKY",574055755)]),(PolicyID {policyID = ScriptHash "b92f6473f18d4b38733d022fd89f3cacc1484fab6eddfd3c5d4b9494"},fromList [("DP07351",1)]),(PolicyID {policyID = ScriptHash "bb78d3b6638537d6df7ae43791ead3d50e75fdae82131eff2b7ae994"},fromList [("UnboundedEarthMinus104Plus94",1),("UnboundedEarthMinus107Plus90",1),("UnboundedEarthMinus121Minus121",1),("UnboundedEarthMinus87Minus51",1)]),(PolicyID {policyID = ScriptHash "c76e5286fce9e6f5c9b1c5a61f74bc7fa89ed0f946ff2ae5d875f2cb"},fromList [("ElMatador1782",1)]),(PolicyID {policyID = ScriptHash "c9c4d9e7fdec835f0cb95b15348509872322a888a9fac4f64dfef0ec"},fromList [("SohoKids1626",1)]),(PolicyID {policyID = ScriptHash "d4162cfa26718e8a4357226ffbfc3df6a210b2a4d5727ecbfd1e8eac"},fromList [("FUDBUD4183",1),("FUDBUD6295",1)]),(PolicyID {policyID = ScriptHash "dbc31b04d90b37332813cb4cee3e8f79994643d899a5366797e745ee"},fromList [("FUD",228087324862)]),(PolicyID {policyID = ScriptHash "f4873b426a498350c579690bd1f4a369d5d7b521c778acf322f77334"},fromList [("DRAPE05145",1),("DRAPE07504",1)])])) (Value 12038901 (fromList [(PolicyID {policyID = ScriptHash "13e3f9964fe386930ec178d12a43c96a7f5841270c2146fc509a9f3e"},fromList [("ClayNationPitch22327",1),("ClayNationPitch72",1)]),(PolicyID {policyID = ScriptHash "2afb448ef716bfbed1dcb676102194c3009bee5399e93b90def9db6a"},fromList [("BISON",10000002006)]),(PolicyID {policyID = ScriptHash "4bf184e01e0f163296ab253edd60774e2d34367d0e7b6cbc689b567d"},fromList [("PaviaMinus215Minus182",1),("PaviaPlus206Plus80",1)]),(PolicyID {policyID = ScriptHash "5a2cdc6e3aa9612fe4676672f443e7efd39c309d45e7919a4bf27750"},fromList [("BossPlanetDistrictTwo10410",1)]),(PolicyID {policyID = ScriptHash "6ac8ef33b510ec004fe11585f7c5a9f0c07f0c23428ab4f29c1d7d10"},fromList [("MELD",215183914)]),(PolicyID {policyID = ScriptHash "6f87aa2ea552ecd24732d62831916ece54c52348417398085358cbed"},fromList [("StoneAgeHooligan2043",1)]),(PolicyID {policyID = ScriptHash "852526a77c45662e981181ed9b0afca13cfd8e45c169a20b37832ea7"},fromList [("Mucca154",1)]),(PolicyID {policyID = ScriptHash "884892bcdc360bcef87d6b3f806e7f9cd5ac30d999d49970e7a903ae"},fromList [("PAVIA",224)]),(PolicyID {policyID = ScriptHash "8a93cd0b1d610e7bab7419a4c8d8e79ed6f02ad73dc70ed7602f2602"},fromList [("Jukeboys1520",1)]),(PolicyID {policyID = ScriptHash "984394dcc0b08ea12d72b8833292e3c3197d7a8ac89aad61d2f5aa9e"},fromList [("EARTH_token",51015360000)]),(PolicyID {policyID = ScriptHash "9a9693a9a37912a5097918f97918d15240c92ab729a0b7c4aa144d77"},fromList [("SUNDAE",100468551)]),(PolicyID {policyID = ScriptHash "a0028f350aaabe0545fdcb56b039bfb08e4bb4d8c4d7c3c7d481c235"},fromList [("HOSKY",574055755)]),(PolicyID {policyID = ScriptHash "b92f6473f18d4b78733d022fd89f3cacc1484fab6eddfd3c5d4b9494"},fromList [("DP07351",1)]),(PolicyID {policyID = ScriptHash "bb78d3b6638537d6df7ae43791ead3d50e75fdae82131eff2b7ae994"},fromList [("UnboundedEarthMinus104Plus94",1),("UnboundedEarthMinus107Plus90",1),("UnboundedEarthMinus121Minus121",1),("UnboundedEarthMinus87Minus51",1)]),(PolicyID {policyID = ScriptHash "c76e5286fce9e6f5c9b1c5a61f74bc7fa89ed0f946ff2ae5d875f2cb"},fromList [("ElMatador1782",1)]),(PolicyID {policyID = ScriptHash "c9c4d9e7fdec835f0cb95b15348509872322a888a9fac4f64dfef0ec"},fromList [("SohoKids1626",1)]),(PolicyID {policyID = ScriptHash "d4162cfa26718e8a4357226ffbfc3df6a210b2a4d5727ecbfd1e8eac"},fromList [("FUDBUD4183",1),("FUDBUD6295",1)]),(PolicyID {policyID = ScriptHash "dbc31b04d90b37332813cb4cee3e8f79994643d899a5366797e745ee"},fromList [("FUD",228087324862)]),(PolicyID {policyID = ScriptHash "f4873b426a498350c579690bd1f4a369d5d7b521c778acf322f77334"},fromList [("DRAPE05145",1),("DRAPE07504",1)])]))))))))])}))))))))`

How to solve this problem?

Thanks for your help!!!

**Comment by danielmain** [comment]
Hi @frozencopper sorry to read that. I will ask the node team. But I would appreciate if you can create an issue [here](https://github.com/input-output-hk/cardano-node) next time :)

**Comment by danielmain** [comment]
@dorin100 would you please 🙏 take a look on the logs here. Thank you!!

**Comment by dorin100** [comment]
Hi @frozencopper sorry to hear that you have issues. In order to get a better idea about what is happening we would need some more info like:
1. what network are you trying to connect to (Mainnet, Testnet)?
2. what Daedalus version are you using?
3. please provide the full node logs 
4. can you try updating to the latest version of Daedalus?

**Comment by danielmain** [comment]
Closed due inactivity
