### ISSUE TITLE
How to run a full node on my server and use Daedalus as lite wallet connecting to my full node?

### ISSUE THREAD

**Issue by danger89** [input-output-hk/daedalus#3026]
Hi,

Currently Daedalus is trying to do everything on the same machine. However, I would like to run the Cardano full node on my server machine (running 24/7). And I would like to open Daedalus on my desktop pc, which could be able to connect to the full node on my local server. Allowing very fast start-up times and less strain on the desktop.

How can I do this setup?

Regards,
Melroy van den Berg

Ps. I think the Cardano full node running on the server is not the problem. The issue is how can I configure Daedalus to use my full node from my server (within my local area network) instead of locally spinning-up a Cardano full node.

**Comment by danielmain** [comment]
Hi @danger89 thank you for your Idea. This is unfortunately not so simple, since `cardano-wallet` communicates with `cardano-node` via local IPC and not TCP. 
We are not planning to do it in the short/mid-term, but I will definitely tell our product owner about it 😉

cc: @daniloprates @mariusb

**Comment by danger89** [comment]
That is very sad to hear. I really hope this could be an option in the near future. Since that will really help the user experience of daedalus.

**Comment by danielmain** [comment]
Hi @danger89 I hope you can understand us, this is not so simple to do it from Daedalus. There is one video of someone who connected Nami-Wallet to Daedalus, this might be interesting for you? https://www.youtube.com/watch?v=_-WDEaSnaWU

**Comment by danger89** [comment]
Related: https://github.com/input-output-hk/cardano-wallet/issues/1556
