### ISSUE TITLE
Feature Request: Make it possible to recover a wallet with the Ledger seed phrase

### ISSUE THREAD

**Issue by NuclearPsychedelic** [input-output-hk/daedalus#3034]
Ledger Nano Devices generate different wallets than Daedalus from the same recovery phrase. If someone would break or lost ledger hardware wallet there are no quick and user-friendly way to get access to the funds. The only user-friendly ways are to either purchase another ledger or manually generating private keys from ledger-created recovery phrase, which would require a lot of technical knowledge, not to mention that Ledger, the company, may go bankrupt at some point in the future, making it impossible to buy a new device.
That's why the possibility to restore a wallet in Daedalus from ledger-created recovery phrase would be very useful.
Of course, I know that under normal circumstances a recovery phrase from cold wallet should not be used in hot wallets. As I mentioned above, it would only be an available option to quickly access funds should a user not have access to their Ledger device.

**Comment by danielmain** [comment]
Hi @NuclearPsychedelic 

You are aware that the key reason for using hardware wallets is that your private key never leaves your hardware wallet and is never exposed. 

No one (not even Daedalus) can recover a private key from the hardware wallet.
The legdger-seed-phrase is a method that ledger uses to construct your private key again. Ledger is not open-source, so we cannot do anything from our side.

My recommendation to you is to buy multiple ledger-hardware-wallets and use the same seed phrase for all of them. So if you lost one, you can still access your wallet from a different stick.

**Comment by NuclearPsychedelic** [comment]
Hello @danielmain !
I am aware of that, but unpleasant situations can still arise. Of course, provided nothing goes wrong, the requested feature would not be used. Still, there are countless people who lose, accidentally destroy or otherwise lose access to their hardware devices. I should also mentioned that I experimented with an old and unused seed to see if funds were recoverable with only the seed phrase and a hot wallet, no ledger. It worked with two other blockchains, one of which was Bitcoin. This leads me to believe that it is a Cardano and Ledger specific issue. I assumed that there is a standard way to derive private keys from seed phrases and Cardano wallets do not abide by that. Please correct me if I am wrong
