### ISSUE TITLE
I want to know the hash of the spending password 

### ISSUE THREAD

**Issue by okepod** [input-output-hk/daedalus#3037]
Is there a way to check from the sqlite file?

Or I would like to know the method (algorithm) to convert from password phrase to hash.

**Comment by Montolva** [comment]
Happy to provide you with further informations regarding Cardano ecosystem. Kindly reach out with a short summary of your queries. https://t.me/Montolvacardano

**Comment by danielmain** [comment]
hi @okepod the password is not stored in Electron but in `cardano-wallet` check here:

https://github.com/input-output-hk/cardano-wallet/blob/675f55fd854e0210dd9cfcd81f4a1b10ccaab15f/lib/wallet/api/http/Cardano/Wallet/Api/Http/Shelley/Server.hs#L815
