### ISSUE TITLE
Failed to start all required subscriptions

### ISSUE THREAD

**Issue by Jtlie** [input-output-hk/daedalus#3046]
Hi,

My Daedalus wallet doesn't sync anymore. At some point it goes back to the first screen, and it's stuck on 'Replaying ledger from on-disk blockchain 2%'. The logs also keep saying "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions. I tried changing my firewall settings but that doesn't work. I even tried with my fire wall off. Please help me solve this.

![image](https://user-images.githubusercontent.com/7568979/194727060-8cd0f937-9e0a-4320-94f8-ac46e2282c64.png)

`[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:12.73 UTC] before next, messages elided = 73246860
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:12.73 UTC] Pushing ledger state for block 7375259fad4c4f25a8b3568ef0e52bb89fe09cf42ac3c66b54dc1c16638d7397 at slot 73256855. Progress: 89.01%
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:12.73 UTC] Pushing ledger state for block cf01cbc19ddb934866be0046116513c51bbee161ad9cd9d8673fd08d51caf7c3 at slot 73256873. Progress: 89.05%
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:12.75 UTC] Pushing ledger state for block a7e38d52c79370dee8f7d0cdcc456b5e4789f73f4e50862172d1f0d1a06004ff at slot 73256909. Progress: 89.13%
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:17.21 UTC] before next, messages elided = 73256936
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:17.21 UTC] Pushing ledger state for block 70e0f66caddab503fa75f2dfff25ad338874e32569547100b94a4b24c70e5a99 at slot 73261830. Progress: 100.00%
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:17.21 UTC] Valid candidate at tip 0be7cb2d2ac1bf7cbf5cd41f495473f1a82d254aec93d50384fa3fd88a9c95f0 at slot 73216551
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:17.21 UTC] Initial chain selected
[34m[DESKTOP-:cardano.node.ChainDB:Info:19][0m [2022-10-08 19:11:17.21 UTC] Opened db with immutable tip at 70b8ea4534f0fb8698ae016232123bd06c44395255bfe058a2f8090ca9311ef3 at slot 73216550 and tip 70e0f66caddab503fa75f2dfff25ad338874e32569547100b94a4b24c70e5a99 at slot 73261830
[33m[DESKTOP-:cardano.node.shutdown:Warning:19][0m [2022-10-08 19:11:17.22 UTC] Will terminate upon reaching NoShutdown
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49][0m [2022-10-08 19:11:17.22 UTC] CreatingServerSocket 127.0.0.1:53160
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49][0m [2022-10-08 19:11:17.22 UTC] ConfiguringServerSocket 127.0.0.1:53160
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49][0m [2022-10-08 19:11:17.22 UTC] ListeningServerSocket 127.0.0.1:53160
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49][0m [2022-10-08 19:11:17.22 UTC] ServerSocketUp 127.0.0.1:53160
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:49][0m [2022-10-08 19:11:17.22 UTC] RunServer (127.0.0.1:53160 :| [])
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] CreateSystemdSocketForSnocketPath (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0")
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] CreatedLocalSocket (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0")
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] ConfiguringLocalSocket (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0") (FileDescriptor 524)
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] ListeningLocalSocket (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0") (FileDescriptor 524)
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] LocalSocketUp (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0") (FileDescriptor 524)
[34m[DESKTOP-:cardano.node.DiffusionInitializationTracer:Info:53][0m [2022-10-08 19:11:17.22 UTC] RunLocalServer (LocalAddress "\\\\.\\pipe\\cardano-node-mainnet.3944.0")
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:11:37.23 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:11:58.24 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:12:19.25 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:12:40.26 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:13:01.27 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:13:22.28 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:13:43.28 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:14:04.29 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:14:25.30 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:14:46.31 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:51][0m [2022-10-08 19:15:07.32 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions`

**Comment by danielmain** [comment]
Hi @Jtlie I just checked my Daedalus and is syncing fine. 

Would you please provide here the logs?
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/4303099/194747574-4c02a031-e9e9-4883-b96f-e715317f9225.png">


Thank you!

**Comment by Jtlie** [comment]
[logs-2022-10-08T181855.0513Z.zip](https://github.com/input-output-hk/daedalus/files/9741469/logs-2022-10-08T181855.0513Z.zip)

**Comment by danielmain** [comment]
@Jtlie have you checked this: 
https://iohk.zendesk.com/hc/en-us/articles/4406070442137-Get-to-know-your-node-logs

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/4303099/195115332-f09736cf-821c-498c-8733-95a6fd6011dd.png">

You seem to have a Firewall or something blocking your machine to connect to `relays-new.cardano-mainnet.iohk.io`
