### ISSUE TITLE
Improve Daedalus

### ISSUE THREAD

**Issue by kedicesur** [input-output-hk/daedalus#3072]
It ate my SSD and I decided to move the gargantuan `~/.local/share/Daedalus` directory to HDD. There is no way to do this from Daedalus UI so I had to do it manually and posted about it [here](https://cardano.stackexchange.com/a/9340/7742). Initially the directory was 78.5GB in size and after 14+ hours of resync and whatnot it is now like 96.5GB. During this lifetime like process while monitoring the CPU activity I have never ever seen 2 threads among the availabe 8 hitting 100% at the same time. You can download 18 GB in 15-20 minutes and I just cant understand what's happening in that 14+ hours. Perhaps you should look into WASM with Electron or a better way of implementing the threads. This wasteful process is preventing Cardano being green.

**Comment by danielmain** [comment]
Hi @kedicesur what is consuming cpu and time is the verification of every block of the entire cardano Blockchain since the genesis block not the Download. 

That is the beauty of a secure full node Wallet, your machine verifies locally the integrity of the Blockchain. 

Light wallets do this job for you and are much faster but then you have to trust them 😉. I hope I could somehow explain how a Full Node Wallet works.

**Comment by michalrus** [comment]
A small question in addition to @danielmain’s excellent answer:

> Perhaps you should look into WASM with Electron

Did you see the increased CPU usage in Electron’s process, and not in native `cardano-node`? That would be unusual

**Comment by kedicesur** [comment]
@michalrus I have an 8 thread CPU on this machine. So once a single thread is fully engaged the total CPU occupation is like 12.5~13% on Gnome System Monitor. So let's watch the average CPU consumprions of these processes in the three phases of Daedalus .
**1. Start Up (When there is no UI)**
- `cardano-node` process takes up  **13%** so I think it occupies a thread by itself.
-  `cardano-wallet` **1%**
- `electron` **7%**
- `electron --type=gpu-process` **1%**

**2. UI Shows but Still Synching**
- `cardano-node` process takes up  **7%** so I think still single threaded but it shares a thread with something else (perhaps `cardano-wallet`)
-  `cardano-wallet` **4%**
- `electron` **3%**
- `electron --type=gpu-process` **3%**

**3. Daedalus in Synch and Working as a Node**
- `cardano-node` process takes up  **24%** so I think it now occupies 2 threads all by itself.
-  `cardano-wallet` **4%**
- `electron` **3%**
- `electron --type=gpu-process` **3%**

So the main issue seems to be at 1st and 2nd stages where all the time is spent and Daedalus is not functional to the user. Would it be reasonable to say that the available processing power is poorly utilized?

**Comment by deepfire** [comment]
> So the main issue seems to be at 1st and 2nd phases where all the time is spent and Daedalus is not functional to the user. Wouldn't it be reasonable to say that the available processing power is poorly utilized?

The startup phase is doing chain replay, which is a lightweight for of block application.

You're indeed right in noting that we don't have block application parallelised -- and yes it can be.

@dcoutts has plans for the future, as usual : -)

**Comment by kedicesur** [comment]
@deepfire Just an idea on how parallel verification can be implemented. Storing Cardano BC state hashes either within Cardano BC or a separate indexing BC once in every n blocks.
![](https://i.ibb.co/Ns94WBX/BC.png)

**Comment by danielmain** [comment]
@kedicesur any suggestion (GitHub Issue) or maybe a contribution (Pull Request) related how cardano-node should behave use please the following repositories 🙏:

- https://github.com/input-output-hk/ouroboros-network
- https://github.com/input-output-hk/cardano-node
