### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/daedalus#3073]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

Explain how to make a contribution (Contributing MD)
Include the Standard Code of Conduct
Identify the Core Maintainers

**Comment by danielmain** [comment]
@ThatGuyLLC who are you?

**Comment by ThatGuyLLC** [comment]
Christian Taylor, Open Source Analyst on Constellation team, worked with Marcin and Kevin H on the above
