### ISSUE TITLE
Spend specific UTXO(s)

### ISSUE THREAD

**Issue by gernotpokorny** [input-output-hk/daedalus#3079]
With Cardano we have an UTXO based ledger and a rewards address.

I'd like to spend specific UTXOs in particular the ones of the staking rewards and it seems that this is not possible with Daedalus.

With Electrum (a Bitcoin wallet) for example it is quite easy to optionally select the UTXOs to spend. There are various reasons why somebody would want to do that.

Daedalus internally of course will also have some algorithm which selects the UTXOs. It shouldn't be not that difficult to instead let the user select the UTXOs.

Could this please be implemented in the future?

Thank you.

**Comment by danielmain** [comment]
Hi @gernotpokorny we do not have yet this functionality to select which UTXOs to use. Would you please propose this change in this repository (which is our backend) https://github.com/input-output-hk/cardano-wallet

Thank you in advance!

**Comment by gernotpokorny** [comment]
I opened the issue there as you suggested. But I have to mention that this is not a backend issue only. I assume the majority of the work will be in the frontend.

[https://github.com/input-output-hk/cardano-wallet/issues/3581](https://github.com/input-output-hk/cardano-wallet/issues/3581)
