### ISSUE TITLE
why does this sync action seem to not be resume-able? 

### ISSUE THREAD

**Issue by ofirgeller** [input-output-hk/daedalus#3220]
it take a long time and if I want to use my computer memory for something else it will stat from 0 next time I start the app.

![image](https://github.com/user-attachments/assets/6682016e-4840-458c-ae8c-ce4443443680)

**Comment by michalrus** [comment]
Hey @ofirgeller,

That percentage is not syncing, it's replaying what's already on your disk. Once you let it finish (especially after a `cardano-node`/Daedalus update), it should be more/less instantaneous the next time you run it.

The sync percentage (writing from the network to your disk) will pick up where you left it, though.

**Comment by michalrus** [comment]
@ofirgeller, it's not that simple unfortunately, but for a detailed explanation, please ask [IntersectMBO/cardano-node](https://github.com/IntersectMBO/cardano-node). :)

**Comment by ofirgeller** [comment]
@michalrus  I did not mean to suggest that it is "simple" or "easy", hope I did not offend. I was asking if it is possible and saying it think it has value. 

can we maybe put it on some feature board along with the value it might have?

**Comment by michalrus** [comment]
Possibly, but _Daedalus_ doesn't implement (and thus control) this behavior, we just _use_ the Cardano node.

That's why I suggested moving this discussion to the  [IntersectMBO/cardano-node](https://github.com/IntersectMBO/cardano-node) issue tracker. :)

**Comment by ofirgeller** [comment]
behavior is controlled by underlining project ([cardano-node](https://github.com/IntersectMBO/cardano-node))

**Comment by michalrus** [comment]
Discussion [moved to cardano-node](https://github.com/IntersectMBO/cardano-node/issues/5963).
