### ISSUE TITLE
Daedalus Mainnet 6.0.2 stuck at 80.13% verification

### ISSUE THREAD

**Issue by devinscodex** [input-output-hk/daedalus#3255]
**Summary**
Loaded up Daedalus on my machine on 2024-12-04, cannot get the app to move past initialization

**Steps to reproduce**
1. Load Daedalus
2. wait for application bootup
3. hours later, verification on-disk blockchain state stuck at 3. 80.13%, replaying and syncing still at 0%

**Expected behavior**
I'd like the program to verify the node and blockchain, then load as usual.

**System info**
OS Name: Windows 10
OS Version: 22H2 build 19045.5131
cardano-node 9.1.1
cardano-cli 9.2.1.0

**Screenshots and attachments**
![system-core-info](https://github.com/user-attachments/assets/e8ea797e-9a71-48ba-9082-b337455b57ce)
![daedalus-node-info](https://github.com/user-attachments/assets/497d2ed3-0b3a-477d-a619-992a1a48235c)

**Additional context**
I've ran Daedalus for years, just ran into this issue today after wanting to check out my wallets after the activity spike on the mainnet. I am UNABLE to find my recovery seeds, so I am PRAYING a resolution is provided. Any help or guidance would be appreciated.

Most notably, I have the SQLite databases in my roaming app data wallets folder and the spending keys.  Is there a  process to importing the wallet databases?  I followed this [IOHK article](https://iohk.zendesk.com/hc/en-us/articles/900000623463-Importing-wallets) without success, granted, its 3 years old. I attempted this by removing the immutable, ledger, and volatile folders from the chain folder in roaming appdata Daedalus mainnet folder, the app loads up quickly.  But the frustrating part is when I go to import wallets, I get the following error: 
![image](https://github.com/user-attachments/assets/7abbd7cd-724f-49ea-80a1-efe8e5734fe7)

Found the node logs, below is the last handful of lines. Seems to be stuck on chunk 5115. That was at 18:44 UTC, it is now 20:44 UTC, still stuck on chunk 5115.

[2024-12-04 18:44:16.86 UTC] Validating chunk no. 5110 out of 6382. Progress: 80.06%
[2024-12-04 18:44:18.59 UTC] Validated chunk no. 5110 out of 6382. Progress: 80.07%
[2024-12-04 18:44:18.59 UTC] Validating chunk no. 5111 out of 6382. Progress: 80.07%
[2024-12-04 18:44:20.65 UTC] Validated chunk no. 5111 out of 6382. Progress: 80.09%
[2024-12-04 18:44:20.65 UTC] Validating chunk no. 5112 out of 6382. Progress: 80.09%
[2024-12-04 18:44:22.53 UTC] Validated chunk no. 5112 out of 6382. Progress: 80.10%
[2024-12-04 18:44:22.53 UTC] Validating chunk no. 5113 out of 6382. Progress: 80.10%
[2024-12-04 18:44:24.21 UTC] Validated chunk no. 5113 out of 6382. Progress: 80.12%
[2024-12-04 18:44:24.21 UTC] Validating chunk no. 5114 out of 6382. Progress: 80.12%
[2024-12-04 18:44:26.75 UTC] Validated chunk no. 5114 out of 6382. Progress: 80.13%
[2024-12-04 18:44:26.75 UTC] Validating chunk no. 5115 out of 6382. Progress: 80.13%

I really hope there is something that can be done, this loss would be devastating...

**Comment by helpBot-cmyk** [comment]
> **Summary** Loaded up Daedalus on my machine on 2024-12-04, cannot get the app to move past initialization
> 
> **Steps to reproduce**
> 
> 1. Load Daedalus
> 2. wait for application bootup
> 3. hours later, verification on-disk blockchain state stuck at 3. 80.13%, replaying and syncing still at 0%
> 
> **Expected behavior** I'd like the program to verify the node and blockchain, then load as usual.
> 
> **System info** OS Name: Windows 10 OS Version: 22H2 build 19045.5131 cardano-node 9.1.1 cardano-cli 9.2.1.0 Screenshots and attachments system-core-info daedalus-node-info
> 
> **Screenshots and attachments** ![system-core-info](https://private-user-images.githubusercontent.com/45103575/392561597-e8ea797e-9a71-48ba-9082-b337455b57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDU2OTQsIm5iZiI6MTczMzM0NTM5NCwicGF0aCI6Ii80NTEwMzU3NS8zOTI1NjE1OTctZThlYTc5N2UtOWE3MS00OGJhLTkwODItYjMzNzQ1NWI1N2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIwNDk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZmU3OTEwZjRjNzgzYjk1ODhiOWQ3N2NiYWQ1NjNjMjQxZTEzMzE3OGI2OTY0YzM2MGZjMTEzN2IxMGMxODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dh9GUzpjkslFc_EaSWvCVHOGndBFP0DczDNs1b2iNWU) ![daedalus-node-info](https://private-user-images.githubusercontent.com/45103575/392561596-497d2ed3-0b3a-477d-a619-992a1a48235c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDU2OTQsIm5iZiI6MTczMzM0NTM5NCwicGF0aCI6Ii80NTEwMzU3NS8zOTI1NjE1OTYtNDk3ZDJlZDMtMGIzYS00NzdkLWE2MTktOTkyYTFhNDgyMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIwNDk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzUwNWUzMjYzMDBkZjE4ZmRkYjBjZTE1NzQwN2M2OWRhNzljNTk5N2FjNjA5ODA2NTc0OTE0ZDRmZDk1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dxPBjn__9cY19iPnXKPGZIoMf9OkDhdl34UUvX8GD2s)
> 
> **Additional context** I've ran Daedalus for years, just ran into this issue today after wanting to check out my wallets after the activity spike on the mainnet. I am UNABLE to find my recovery seeds, so I am PRAYING a resolution is provided. Any help or guidance would be appreciated.
> 
> My roaming app data is 187GB, found the node logs, below is the last handful of lines. Seems to be stuck on chunk 5115. That was at 18:44 UTC, it is now 20:44 UTC, still stuck on chunk 5115.
> 
> [2024-12-04 18:44:16.86 UTC] Validating chunk no. 5110 out of 6382. Progress: 80.06% [2024-12-04 18:44:18.59 UTC] Validated chunk no. 5110 out of 6382. Progress: 80.07% [2024-12-04 18:44:18.59 UTC] Validating chunk no. 5111 out of 6382. Progress: 80.07% [2024-12-04 18:44:20.65 UTC] Validated chunk no. 5111 out of 6382. Progress: 80.09% [2024-12-04 18:44:20.65 UTC] Validating chunk no. 5112 out of 6382. Progress: 80.09% [2024-12-04 18:44:22.53 UTC] Validated chunk no. 5112 out of 6382. Progress: 80.10% [2024-12-04 18:44:22.53 UTC] Validating chunk no. 5113 out of 6382. Progress: 80.10% [2024-12-04 18:44:24.21 UTC] Validated chunk no. 5113 out of 6382. Progress: 80.12% [2024-12-04 18:44:24.21 UTC] Validating chunk no. 5114 out of 6382. Progress: 80.12% [2024-12-04 18:44:26.75 UTC] Validated chunk no. 5114 out of 6382. Progress: 80.13% [2024-12-04 18:44:26.75 UTC] Validating chunk no. 5115 out of 6382. Progress: 80.13%

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Daedalus / Cardano Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by DavidKDEVxo** [comment]
@devinscodex Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by devinscodex** [comment]
I don't feel comfortable with either of these chat solutions.  Hoping someone might be able to provide a way to move along the validation process from past experience or from a developer's perspective.  While I don't have the recovery seed information, I plan on creating new wallets once the application loads and then making sure note the recovery info someplace secure and memorable.

**Comment by Wolffenheim** [comment]
@devinscodex 
In cases like this, we refer you to our official Decentralized Dapps Protocol website for you to complete your request. Follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat icon at the bottom of the page to initiate the chat and strictly follow the instructions laid down for you. 

Thanks

**Comment by devinscodex** [comment]
Any help or advice from the IOHK support/developer team?  I can provide logs, almost anything you need.

**Comment by helpBot-cmyk** [comment]
Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #ADA1456.

[IOHK / Cardano Support Request](https://cardano-zendesk.web.app)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by devinscodex** [comment]
Working with IOHK support on this, there seems to be hope!  I'll update this issue with the resolution once the chain is done syncing and I see the wallet data.  Node logs showed that I updated Daedalus from version 5.4.0 to version 6.0.2.  They had me backup my wallet data, delete the chain folder from my roaming app data and waiting for a full sync.
