### ISSUE TITLE
Version 7.0 Cannot Start Cardano Node on Linux

### ISSUE THREAD

**Issue by fajard01** [input-output-hk/daedalus#3258]
I upgraded my Daedalus wallet for the most recent version 7.0. However it wouldn't start properly. It always says 'Unable to run cardano node'. I tried cleaning up the old files, reinstalling but the problem persists. Any help?

**Comment by michalrus** [comment]
I'm sorry about that, we're working on this issue:
* #3257

**Comment by jhrcek** [comment]
Just for reference, I'm seeing the same issue on fedora linux (I assume the fix will also work it for fedora).

**Comment by michalrus** [comment]
@jhrcek yes. As a quick fix you can install the upcoming 7.0.1 manually:

https://update-cardano-mainnet.iohk.io/daedalus-7.0.1-71715-mainnet-28179e85e-x86_64-linux.bin
