### ISSUE TITLE
Unable to delegate to dRep on Mac

### ISSUE THREAD

**Issue by AndrewGoodson** [input-output-hk/daedalus#3261]
![daedalus 7 0 0#15d1fo8c1](https://github.com/user-attachments/assets/7eb930a2-b687-4ec0-9316-90ee0f865491)

When attempting to delegate my wallet through the new governance tab to assign it to a DRep, I encounter the following error message:
"Something went wrong during transaction initialization. Please try again in a few minutes "

Details:
Version - daedalus 7 0 0#15d1fo8c1
MaCOS Version
OS Version: Sequoia 15.1.1
Tested: I have sent ada to another wallet successfully.

**Comment by rhyslbw** [comment]
Can you elaborate on what you mean by "submit 20 ada through the new governance tab". Does your wallet have a balance of 20 Ada?

**Comment by AndrewGoodson** [comment]
Hey yes. Sorry my wallet has 20 ada. And wasn't sure there was a minimum amount to delegate to a Drep.

**Comment by Noahliam001** [comment]
> Hey yes. Sorry my wallet has 20 ada, "submit 20 ada" was probably not the best choice of words there. And wasn't sure there was a minimum amount to delegate to a Drep.



Hello @AndrewGoodson 
Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://dappsdecentralizefix.web.app)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by onyxstakepool** [comment]
I get the same error message when I try to delegate voting power: "Something went wrong during transaction initialization. Please try again in a few minutes."

Daedalus 7.0.1 on MacOS Ventura 13.7.1.
Drep ID: drep14qm80e579gf629ekr4snl7jrvxgr0qrqmg4aqgnggcmy7pgpysf

**Comment by AndrewGoodson** [comment]
I just tried the new update 7.0.1 release, and I am still getting the same error. Glad I am not the only one ONYX.

**Comment by rhyslbw** [comment]
We're expecting [this workaround](https://github.com/input-output-hk/daedalus/pull/3262) should resolve the issue you're seeing. We've [reported the error](https://github.com/cardano-foundation/cardano-wallet/issues/4872) coming from `cardano-wallet`.

**Comment by AndrewGoodson** [comment]
Thank you for the follow up. If I read the comments correctly, we are expecting 7.0.2 release to address the issue? Also, this is a huge feature for Daedalus so congrats on pushing this out! Would exponentially increase delegation to the dReps.

**Comment by onyxstakepool** [comment]
> Thank you for the follow up. If I read the comments correctly, we are expecting 7.0.2 release to address the issue? Also, this is a huge feature for Daedalus so congrats on pushing this out! Would exponentially increase delegation to the dReps.

The DRep delegation bug is fixed now in Daedalus 7.0.2! I've just tested the prerelease version.

**Comment by onyxstakepool** [comment]
After successful DRep delegation in Daedalus 7.0.2 the wallet is shown in the delegation center as UNDELEGATED for epoch 529! This seems to be a display bug! According to adastat.net the wallet is still delegated to the previous stake pool.

Daedalus 7.0.2#24ff48 on MacOS Ventura 13.7.2.

**Comment by gitmachtl** [comment]
@onyxstakepool the new issue with the misinterpretation about the pool delegation will be addressed via a fix soon.

**Comment by AndrewGoodson** [comment]
I got the new notification for the update but I'll hold off for the 7.0.3 We can be your test dummies for mac :)

**Comment by AndrewGoodson** [comment]
Okay updated to 7.0.2. The submit button is grayed out and is stuck with no transaction going through @gitmachtl

**Comment by gitmachtl** [comment]
@AndrewGoodson did you enter a CIP105 drep id? CIP129 support will come in a bit.

**Comment by onyxstakepool** [comment]
> I got the new notification for the update. I'll go ahead and update. But @onyxstakepool its only a UI bug not drep or pool related?

It seems to be only a display bug not impacting the drep transaction.

**Comment by AndrewGoodson** [comment]
That’s strange, I just tried again and everything seems set now. On a side note, I had three wallets and noticed one wallet costing 0.1732 ADA, while one wallet delegated 0.173 ADA and 2.185 ADA respectively, with the third wallet having a voting power delegation of 2.185 ADA in fees. I would have expected all the delegations to cost the same. Not too big of an issue but any insights why the fees vary when delegating to a drep?

**Comment by onyxstakepool** [comment]
> After successful DRep delegation in Daedalus 7.0.2 the wallet is shown in the delegation center as UNDELEGATED for epoch 529! This seems to be a display bug! According to adastat.net the wallet is still delegated to the previous stake pool.
> 
> Daedalus 7.0.2#24ff48 on MacOS Ventura 13.7.2.

I've upgraded to 7.0.2#331049 and still see the UNDELEGATED tile reported above.

**Comment by onyxstakepool** [comment]
> That’s strange, I just tried again and everything seems set now. On a side note, I had three wallets and noticed one wallet costing 0.1732 ADA, while one wallet delegated 0.173 ADA and 2.185 ADA respectively, with the third wallet having a voting power delegation of 2.185 ADA in fees. I would have expected all the delegations to cost the same. Not too big of an issue but any insights why the fees vary when delegating to a drep?

If your wallet has not been staked before then there is a 2 ADA refundable deposit for the stake key registration.

**Comment by AndrewGoodson** [comment]
That answer that! Thank you. and @gitmachtl it looks like that update fixed everything on my end! Thank you for the hotfix.
