### ISSUE TITLE
Nix os dependency

### ISSUE THREAD

**Issue by benjyz** [input-output-hk/daedalus#399]
Want to try deadalus, but in the shell script there is nix OS dependency. In the readme I find "NixOS is a GNU/Linux distribution that aims to improve the state of the art in system configuration management. " Why does installer point to a linux distro? This requires more explanation.

**Comment by darko-mijic** [comment]
@benjyz: Testnet version of Daedalus can be downloaded from [https://test.daedaluswallet.io/](https://test.daedaluswallet.io/). Keys for importing wallet with Ada are available here: [https://tada.iohk.io/](https://tada.iohk.io/).

**Comment by benjyz** [comment]
Thanks, will try. Still don't understand where the nixOS dependency comes from. Is this for virtualization?

**Comment by darko-mijic** [comment]
Daedalus is currently shipping with Ada cryptocurrency and full Cardano node. CI builds the installers and bundles the Cardano node with Daedalus. `nix` is a dependency needed for the Cardano node integration.

Here is a link to Cardano SL repo: [https://github.com/input-output-hk/cardano-sl](https://github.com/input-output-hk/cardano-sl) and Cardano documentation: [https://cardanodocs.com](https://cardanodocs.com).
