### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by asifssarker** [input-output-hk/daedalus#512]

**Comment by hydro13** [comment]
false positive , it’s likely triggers by the auto update function and the fact that the program is not signed by a trusted Microsoft dev (unknown publisher)

**Comment by c0ndensate** [comment]
I would feel a lot more secure if the devs gave a checklist to validate the authenticity of the application software. Also, there is no explanation of digital signature where the user downloads the installer off the website. I think clicking the download link should first show a popup that explains digital signature and then the user can download the file. No other sites explain that and it would make your site stand out more.

**Comment by asifssarker** [comment]
How can we be so sure about it? When there are several antivirus including McAfee and Avast have alerted this issue. I'm not sure why it has something to do with MS trust, whereas a question of malware? I found the latest update has some improvement but not fully clean yet! 

Well, I think some wallets software may require some sort of Malware to run it properly and that's the choice they have to make. I wish you are right anyway.﻿

**Comment by domenkozar** [comment]
@c0ndensate that's planned, we still need to discuss how to do that exactly.

**Comment by nikolaglumac** [comment]
> Daedalus software downloads are signed with IOHK’s organizational PGP key. To support verification, a checksum is published for each installer with instructions for verifying their signatures and checksums on the Daedalus download web page. This enables users to verify the integrity of a download so they can be sure that they are using the true version of our software. Step-by-step instructions for checksum and signature verification are available on the download page.

More info can be found on the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360011330194-Installer-integrity-verification
