### ISSUE TITLE
failed npm install on Ubuntu

### ISSUE THREAD

**Issue by skecskes** [input-output-hk/daedalus#521]
Hi,

I was trying to `npm install` it from source, but failed to due to missing biased opener dependency. I fixed it by adding it to list of dependencies>
`npm install biased-opener --save`

**Comment by brooks-ideas-admin** [comment]
I received a different error from npm install on Ubuntu 16.04.
```
41419 verbose pkgid v8-debug@0.7.7
41420 verbose cwd /home/shawn/cardano/git/daedalus
41421 verbose Linux 4.4.0-97-generic
41422 verbose argv "/home/shawn/.nvm/versions/node/v8.9.1/bin/node" "/home/shawn/.nvm/versions/node/v8.9.1/bin/npm" "install"
41423 verbose node v8.9.1
41424 verbose npm  v5.5.1
41425 error code ELIFECYCLE
41426 error errno 1
41427 error v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
41427 error Exit status 1
41428 error Failed at the v8-debug@0.7.7 install script.
```
I've attached the full npm install log file in case it is helpful.
[2017-11-10T18_09_18_733Z-debug.log](https://github.com/input-output-hk/daedalus/files/1462633/2017-11-10T18_09_18_733Z-debug.log)

**Comment by shawnim** [comment]
Oops, just noticed I was signed in with brooks-ideas-admin account. This is my usual account.
I'm happy to test any Daedalus on Linux builds.
Shawn

**Comment by VaclavSynacek** [comment]
Fro m the build instructions:
> Note: requires a node version >= 4 and an npm version >= 3. This project defaults to 6.x

So your environment is not of the supported versions.

**Comment by domenkozar** [comment]
Please follow https://github.com/input-output-hk/daedalus/issues/492 for official linux support
