### ISSUE TITLE
missing ca.crt

### ISSUE THREAD

**Issue by skecskes** [input-output-hk/daedalus#522]
After following all the steps from https://cardanodocs.com/for-contributors/building-from-source/ and after npm install I am trying to run the wallet. Somehow it's failing for missing ca.crt. How can I get this one?
I'm using Ubuntu 16.04. 

```
stefan@myBox:~/Projects/daedalus$ npm start

> daedalus@0.8.0 start /home/stefan/Projects/daedalus
> cross-env NODE_ENV=production electron ./

[19:41:32:0202] [error] Error while loading ca.crt: Error: ENOENT: no such file or directory, open '/home/stefan/Projects/daedalus/tls/ca/ca.crt'
```

Thank you for help.

**Comment by cleverca22** [comment]
https://github.com/input-output-hk/daedalus/blob/master/installers/build-certificates-unix.sh

the cert files are normally generated by this script after the installer has ran

**Comment by skecskes** [comment]
```
stefan@myBox:~/Projects/daedalus$ bash ./installers/build-certificates-unix.sh 
Generating certificates.
OpenSSL 1.1.0f  25 May 2017

============================================================================
[1/10] Creating database
============================================================================
[2/10] Choosing OpenSSL message digest
Elected message digest 'sha256'
Updating: ca.conf client.conf server.conf
sed: can't read ca.conf: No such file or directory
sed: can't read client.conf: No such file or directory
sed: can't read server.conf: No such file or directory
```

So I solved it by going into installer folder and running it:
```
cd installer
bash build-certificates-unix.sh 
```
The certificates were installed into installer/tls folder, so I had to copy them one folder up. I assume there is issue in unix script with path on second step.

**Comment by domenkozar** [comment]
To build the installer from source use `scripts/build-installer-unix.sh` or `scripts/build-installer-win64.bat`

**Comment by gwpl** [comment]
As you may see people using [Archlinux daedalus](https://aur.archlinux.org/packages/daedalus) package, also are subject of this issue. 

As `@codybonney` wrote [there](https://aur.archlinux.org/packages/daedalus) on 2017-12-17 :+1: 

> Looks like daedalus, when launched, is looking for a certificate at:
> 
> $(pwd)/tls/ca/ca.crt
> I see that this package creates one at:
> 
> src/daedalus/tls/ca.crt

**Comment by nikolaglumac** [comment]
Fixed in https://github.com/input-output-hk/daedalus/tree/0.12.0
