### ISSUE TITLE
Daedalus wallet is an HTTP download

### ISSUE THREAD

**Issue by dionyziz** [input-output-hk/daedalus#543]
The current wallet download for mac is served over HTTP. This means that regardless of the security features of Daedalus itself, and regardless of the fact that the main website is served via HTTPS, a malicious network man-in-the-middle can replace the binary and inject a coin-stealing virus.

Please use a direct HTTPS link to the CDN.

**Comment by dionyziz** [comment]
@CharlesHoskinson This follows up on our conversation regarding the security of Daedalus.

**Comment by domenkozar** [comment]
@dionyziz we are working on this and should be resolved shortly.

**Comment by dionyziz** [comment]
@domenkozar Thank you, do let me know when there has been some progress! :)

**Comment by johnsintal** [comment]
Still no fix? Can we get the hash of the file to confirm?

**Comment by cleverca22** [comment]
```
a6fc6ae00e7739a6e05c7879d1159760  Daedalus-installer-1.0.3253.pkg
756e3038f7e69273c473fd189619f1771684f74e  Daedalus-installer-1.0.3253.pkg
13992425b5408abb60e75bcf8ae01916c2d214d921f68d923eae594ef7a080d6  Daedalus-installer-1.0.3253.pkg
01e9f7f51d946b6d6c5b7937ecfe90c341ab507f9575796b6def89b98a737d3cb16fe8c88216352ead17a648a6793bd923aa6413a09f5900f27da314a8ae5ee6  Daedalus-installer-1.0.3253.pkg
```
the md5, sha1, sha256, and sha512

**Comment by dionyziz** [comment]
This is literally a one-byte change on the website, adding an "s" after "http". Is there a GitHub repo where I can make this pull request so that our users are safer? :)

**Comment by johnsintal** [comment]
I believe it still downloads unsecured even if you add a `s` to `http`

**Comment by dionyziz** [comment]
The `s` has been added, and I have confirmed that the content is now served via https correctly. Thanks!
