### ISSUE TITLE
Windows launch error

### ISSUE THREAD

**Issue by bitcartel** [input-output-hk/daedalus#549]
Daedalus (1.0.3402)
1. Clean boot into Windows 10.
2. Launch, get error:
![image](https://user-images.githubusercontent.com/194979/33155272-0ebbfeac-cfa4-11e7-8e46-fd37c160f8d4.png)
3. Launch again, wallet runs as expected.

**Comment by domenkozar** [comment]
This will be fixed in next mainnet release.

**Comment by tgreiser** [comment]
This appears to be fixed now.
