### ISSUE TITLE
Windows wallet executable is not code-signed

### ISSUE THREAD

**Issue by bitcartel** [input-output-hk/daedalus#550]
The Windows installer is code-signed by IOHK, but the installed wallet executable is not code-signed.

![image](https://user-images.githubusercontent.com/194979/33155404-68ff8770-cfa5-11e7-85a3-0bd12ad9ce56.png)

**Comment by domenkozar** [comment]
This will be fixed in next mainnet release.

**Comment by domenkozar** [comment]
Fixed.
