### ISSUE TITLE
Connecting to server error on mac

### ISSUE THREAD

**Issue by rnkhouse** [input-output-hk/daedalus#560]
I am getting connecting to server error on mac wallet. I tried restarting computer and re-installed the wallet itself. But, no luck.

[2017-11-30 22:15:54:0847] [debug] Connection Lost. Reconnecting …
[2017-11-30 22:15:55:0194] [error] CardanoClientApi::syncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1026:11)\n    at exports._exceptionWithHostPort (util.js:1049:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8090",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8090
}
[2017-11-30 22:15:55:0195] [debug] Connection Lost. Reconnecting …

Please see the attachment.

<img width="716" alt="screen shot 2017-11-28 at 10 23 11 pm" src="https://user-images.githubusercontent.com/3238963/33356496-ca1fe59c-d48a-11e7-83b0-613c1f1a7b62.png">

**Comment by justinbretting** [comment]
Having same issue on a mac. Originally loaded up fine but started hanging as soon as I tried to send some funds from exchange to wallet. Original install kept saying something like 99.16% synced, but after re-installing I'm now getting this screen hanging. Not sure exactly where to check for logs. version 1.0.3253 on Mac Sierra.

**Comment by ahumblenerd** [comment]
Same issue here.

**Comment by ernaneluis** [comment]
same as well

**Comment by cleverca22** [comment]
is `cardano-node` running in `ps aux`?
are there any interesting errors in `~/Library/Application Support/Daedalus/Logs/cardano-node.log`

**Comment by ernaneluis** [comment]
I fixed by installing it again.

**Comment by justinbretting** [comment]
I found this via twitter and it resolved my issue. Specifically I had to restart 🙄 #rookiemistake 

https://forum.cardanohub.org/t/iohk-statement-connecting-to-network-issue/1545

Encouraging to see they’re taking the issue seriously and going to improve the UX accordingly!

**Comment by nikolaglumac** [comment]
Please follow the instructions from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360010522913--Cannot-Connect-to-Network-message
