### ISSUE TITLE
How to define `linux` in the install command

### ISSUE THREAD

**Issue by doublehops** [input-output-hk/daedalus#562]
I'm confused by the command in the install section where it says `where OS is either linux or osx` as there is no mention of `OS` in the instructions.

**Comment by zyrorl** [comment]
IOHK doesn't give a fuck about linux users, don't even bother.

**Comment by doublehops** [comment]
That's disappointing. I think I have it installed now but not sure what command to run to start it.

**Comment by mariano54** [comment]
Any plan for linux support?

**Comment by cleverca22** [comment]
@mariano54 #578 is being beta-tested internally and will give support on any linux with [nix](https://nixos.org/nix/) installed

**Comment by domenkozar** [comment]
Merging into #492 for the linux installer
