### ISSUE TITLE
Daedalus coin total incorrect

### ISSUE THREAD

**Issue by ADA4life** [input-output-hk/daedalus#566]
I have a strange one…all Daedalus blocks are synced and I’m into the wallet on both my PC and laptop.

I have 4 total transactions showing on both the PC and laptop, however the correct coin total is only showing on the laptop.

Pc is only showing 25% of my coins, laptop Daedalus shows all the coins.

100% syned and looking at Daedalus on both machines.  

I have restarted both the wallet and the computer to no avail. I then deleted Daedalus, after reinstalling Daedalus the wallet still remembered my wallet and key information after updating the blocks to 100%. I am in the wallet but the coin total is still incorrect.

I have even deleted the DB-1.0 file per Daedalus Support request.

It seems like the PC is somehow missing some blocks, however these transactions were completed over a week ago and they show thousands of confirmations.

Can you please help me?  Windows 10 is the PC not acting properly

**Comment by nikolaglumac** [comment]
Please try re-syncing both of your Daedalus clients: https://iohk.zendesk.com/hc/en-us/articles/360009484874-Delete-and-re-sync-blockchain-data
