### ISSUE TITLE
Outdated version # in 'About' dialog box

### ISSUE THREAD

**Issue by k0k0b34n** [input-output-hk/daedalus#572]
The 'About' dialog box still has 0.8.2 as the version number. Current version for Windows is 1.0.3402.
![image](https://user-images.githubusercontent.com/25877435/33521905-49ebb236-d794-11e7-90e1-75816aa5f4cb.png)

**Comment by DominikGuzei** [comment]
Hey @k0k0b34n thanks for your feedback, `0.8.2` is the current `Daedalus` version … we are currently improving the version label to be more concise (show exactly which Daedalus / cardano version and build is used)
