### ISSUE TITLE
New Receive Address not automatically generated after using previous one

### ISSUE THREAD

**Issue by k0k0b34n** [input-output-hk/daedalus#577]
It seems that a new receive address is not automatically generated after using a previous one. On the 'Receive' page there is a message that reads: "To protect your privacy, new addresses are generated automatically once you use them."

**Comment by shunfan** [comment]
I had the same issue. If the statement is correct, you should always see a non-used address in the "Generated addresses" section. However, sometimes I see all of them are used. Recently, I made a new transaction from Binance to my wallet, but I didn't see any new address gets generated automatically.

**Comment by nikolaglumac** [comment]
Text copy has been updated to reflect the actual behavior:
![text-copy](https://user-images.githubusercontent.com/376611/51973437-f1ef1400-247d-11e9-8db9-ac1812765f07.png)
