### ISSUE TITLE
Failed to connect to 127.0.0.1:8090. Logs screenshot attached

### ISSUE THREAD

**Issue by tranceporter** [input-output-hk/daedalus#583]
Hi,

My friend is using 1.0.3769.0 version of the wallet, and we tried deleting log files, syncing time from internet as per FAQ and nothing helped. We even tried opening port 8090 from windows firewall. Daedalus.bat file has node timeout of 30 already. What are we doing wrong here? This is on windows 10 machine.

https://cdn.discordapp.com/attachments/388779459341451264/388797229210664960/image.jpg

https://cdn.discordapp.com/attachments/388779459341451264/388797635462430730/image.jpg

**Comment by humanoidcreature** [comment]
Same here.

**Comment by cleverca22** [comment]
connection refused means the firewall allowed it, but the program at the other end isnt running
what does it say in `cardano-node.log` ?

**Comment by tranceporter** [comment]
Will check with my friend to get some details from cardano node logs

**Comment by stepanhack** [comment]
Happens to me too. A fix I found is reinstalling the app (no need to uninstall, just override it with latest version)

**Comment by tranceporter** [comment]
Hi @cleverca22 

Here is line from cardano log that tells a bit more info on what is failing..

https://cdn.discordapp.com/attachments/388779459341451264/389201781009285121/image.jpg

**Comment by cleverca22** [comment]
@tranceporter my first guess is that you closed the wallet while it was restoring, it should fix itself if left open for an hour

**Comment by tranceporter** [comment]
OK mate, will pass that comment down to my friend

**Comment by tranceporter** [comment]
Nope still no dice sorry. Any other suggestions? Would you need the entire cardano.log to find out?

**Comment by cleverca22** [comment]
yeah, that would be the next best place to look

**Comment by amalleo25** [comment]
Same issue for me. I've checked that the time is synced and added a firewall exception with no luck. Launching daedalus.bat does work for me but I'd like to see this fixed when launching the exe.

**Comment by rokburgar** [comment]
I had the same error. Solved it with removing some unused etc/hosts development "dns" lookups.

**Comment by tranceporter** [comment]
@rokburgar which dns lookups in particular?

**Comment by rokburgar** [comment]
Removed only one record which had my static ip mapped to some domain. Probably used it for development some time ago.

**Comment by tranceporter** [comment]
Are we talking about the same etc/hosts file in system32/drivers folder? Was the dns entry made by daedalus wallet?

**Comment by rokburgar** [comment]
Yes. No deaedalus hasnt done that. As I said I probably messed with it to test some things in the past.

**Comment by tranceporter** [comment]
Ah ok cheers

**Comment by nikolaglumac** [comment]
Please follow the instructions from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360010522913--Cannot-Connect-to-Network-message
