### ISSUE TITLE
Purpose of pivileged access in MacOS installer

### ISSUE THREAD

**Issue by gabriel** [input-output-hk/daedalus#587]
What's the purpose of the privileged access in the MacOS installer?

Is there a method of uninstall?

Looked through source and docs and couldn't (easily) find what's up.

Thanks!

**Comment by nikolaglumac** [comment]
@cleverca22 @disassembler @deepfire @rvl can you guys please answer this question? 🙏

**Comment by nikolaglumac** [comment]
@disassembler please help us out here 🙏
