### ISSUE TITLE
Stuck at syncing with blockchain

### ISSUE THREAD

**Issue by athanclark** [input-output-hk/daedalus#588]
I'm using the latest version of the Mac executable - it was downloading the majority of the blockchain just fine, but now it's stuck at 92.16% for hours - I've tried restarting the program without better results.

**Comment by ilanus** [comment]
@athanclark I don't believe that the issue relates to recent implementations of Daedalus, but rather your local environment. I assume your network is refusing to connect to the certain network address to synchronize with this block at 92.16%, verify that you're not behind any proxy/firewall.

**Comment by athanclark** [comment]
I apologize, you're correct - it was just stuck for some reason. I wonder if a note could be added in the ui. Thanks!
