### ISSUE TITLE
Incompatibility with Umlaut in Windows user name

### ISSUE THREAD

**Issue by Horschig** [input-output-hk/daedalus#592]
Hey guys,
just wanted to check this one out and got stuck at the "Connecting to Network" screen. The reason for this was the Umlaut in my username. Therefore, Daedalus was looking in a non-existing folder on my PC (as evident from the log-file). I solved this manually now by just creating that folder. I sent the log-file to you via Daedalus.

**Comment by domenkozar** [comment]
@Horschig does it connect now, after fixing the log folder name?

**Comment by maxx981** [comment]
I have the same issue here. The username unfortunately contains a french accent. After creating the folder I got to the next screen for choosing a language. Now the client is syncing.

**Comment by Horschig** [comment]
Excuses for the late reply - yes, that did fix the issue for me as well

**Comment by nikolaglumac** [comment]
> Up until this release, Windows users who had non-Latin characters in their Windows usernames were unable to use Daedalus. The first fix will ensure that these users will now be able to use Daedalus in Windows.

This issue has been resolved since Daedalus 0.11.1: https://github.com/input-output-hk/daedalus/tree/0.11.1
