### ISSUE TITLE
hot mode triggers slow warning

### ISSUE THREAD

**Issue by h4ck3rm1k3** [input-output-hk/daedalus#597]
The standard hot mode triggers this warning, 
https://developers.google.com/web/updates/2016/08/removing-document-write

I dont see the value of having the the if value, are we even using the non hot local build ?

https://github.com/h4ck3rm1k3/daedalus/tree/hothack this code hack removes the hot flag check

**Comment by nikolaglumac** [comment]
Sorry for the late response. Daedalus setup has been completely refactored (a couple of times) since you have posted this question. There are some cases when we don't need the "hot" build.
