### ISSUE TITLE
UI improvement: hide/show used addresses toggle

### ISSUE THREAD

**Issue by leeschmidt4** [input-output-hk/daedalus#598]
On the "Receive" tab from within a wallet, there is a text button containing the text either "hide used" or "show used".

Currently, the button text reflects the action you can take (i.e. clicking on "show used" will show used addresses) -- which is an ambiguous piece of UI. Upon first look, there is no way to determine if this is an action button, or a label describing the state of the list.

My recommendation is to change this piece of UI to a standard checkbox labeled with "hide used" which defaults to checked. It's more intuitive.

**Comment by DominikGuzei** [comment]
Thanks for the feedback @leeschmidt4, I will forward this to our designer and schedule a task for this improvement! 👍

**Comment by nikolaglumac** [comment]
Hide/Show used addresses toggle feature has been implemented in: https://github.com/input-output-hk/daedalus/tree/0.11.0
