### ISSUE TITLE
UI improvement: label "copy" icon with text

### ISSUE THREAD

**Issue by leeschmidt4** [input-output-hk/daedalus#599]
On the "Receive" tab from within a wallet, the top-most displayed wallet addressed is followed by a copy icon. It should be labeled with "Copy address" instead of just a lone icon (the same way it's done from within the list of addresses).

**Comment by nikolaglumac** [comment]
This has been implemented a while ago... Closing this ticket.

![Screenshot 2021-02-02 at 09 19 58](https://user-images.githubusercontent.com/376611/106571776-dc62c800-6537-11eb-8d3e-e5f16ba63040.png)
![Screenshot 2021-02-02 at 09 19 52](https://user-images.githubusercontent.com/376611/106571778-dd93f500-6537-11eb-88db-1b03c2f94060.png)
