### ISSUE TITLE
UI improvement: add a tooltip for "Transaction assurance security level" from settings

### ISSUE THREAD

**Issue by leeschmidt4** [input-output-hk/daedalus#600]
In the "Settings" tab from within a wallet, add a tooltip for "Transaction assurance security level".

Or add a link that says "What is this?" and takes you to https://cardanodocs.com/cardano/transaction-assurance/

**Comment by nikolaglumac** [comment]
@leeschmidt4 there is no more any concept of "Transaction assurance security level" in latest Daedalus version.
