### ISSUE TITLE
Ledger Nano Compatibility

### ISSUE THREAD

**Issue by martellalex** [input-output-hk/daedalus#604]
Hi . . . where is ledger nano compatibility on the roadmap?  And is there an issue or branch that I can follow to track progress?

Thanks!

**Comment by gwpl** [comment]
IMHO issue is more general -> it's issue of giving possibility for users to "always keep their prive keys offline", cold storage. As first solution, let them make even simple setup one may run on old offline computer (or cheap Raspberry Pi...), later, more convenient ones to arrive like Ledger Nano S or Trezor (with it's 25th secret word feature) -> I've extended scope a bit here: https://github.com/input-output-hk/daedalus/issues/607

**Comment by darko-mijic** [comment]
@martellalex Ledger Nano S support for Cardano version of Daedalus is currently being built. The first stage, which includes Ledger Nano S application and NodeJS API for interacting with it is half done. After that phase, development will continue with the implementation of external wallets support for Cardano node (private keys stored outside, in this case on Ledger device) and integration with Daedalus.
Unfortunately, we can not provide estimates at this time.

**Comment by martellalex** [comment]
Thanks tons for the status update - appreciate you can't give an estimate but really grateful you guys are working on it

**Comment by nikolaglumac** [comment]
Ledger Nano support is still not available but it is on our todo list.
Please keep track of future Daedalus releases.
