### ISSUE TITLE
Cold storage (hardware) solutions - Ledger, Trezor, Offline laptop

### ISSUE THREAD

**Issue by gwpl** [input-output-hk/daedalus#607]
As people file requests for Ledger Nano S ([here](https://github.com/input-output-hk/daedalus/issues/604)), Trezor or similar solution.

Let me file this issue as more generic and tackling the essence:

* Offline storage of private key

Therefore, "ability to keep private key offline" even on separate laptop and use it just to sign transactions, would be great. It's possible with Ethereum, Bitcoin... 
And IMHO it's way faster to deliver as solution before arriving with Ledger and Trezor (and maybe would help them develop support after all...).
And still, those with big stake in ADA, apart from discomfort, could at least have ability to run some (even  image of linux distro, premade just for given purpose), running offline, and have this old offline cheap computer (or cheap computer like Raspberry Pi) for one purpose -> to safeguard their privatekey for their Cardano.

Of course, more convenient solutions like Trezor (which offers "25th word" for creating hidden wallets - great feature), or Ledger Nano S, would be really nice and convenient. However IMHO first it to deliver any solution providing security, security through distrust, through distrust I mean "to never keep for any moment private key on any online device" (that's why solutions like "install Daedalus for a moment and delete and later recover" does not address the concern, just limit time frame of exposure.

**Comment by darko-mijic** [comment]
@gwpl, here is the answer to the request of Ledger Nano S support:
https://github.com/input-output-hk/daedalus/issues/604#issuecomment-352752883

**Comment by gwpl** [comment]
Thanks.

Please let me update that this is security critical in light of Intel Management Engine security vulnerability INTEL-SA-00086 AKA IME issue, impacting tons of Intel based devices after 2008.

**Comment by jonathancross** [comment]
FYI: Apparently the [TREZOR Model T supports Cardano](https://wiki.trezor.io/Cardano_(ADA)) via the [ADA Lite](https://github.com/vacuumlabs/adalite) (https://adalite.io/app)... may be helpful if anyone wants to implement support here in Daedalus.

**Comment by Smedzlatko** [comment]
Are there plans for adding the Ledger/Trezor support in the near future? Is there any time estimate when this issue will be revisited?

**Comment by SebastienGllmt** [comment]
@Smedzlatko Daedalus team is working on it at https://github.com/input-output-hk/cardano-js-sdk

In the meantime, you can use Ledger & Trezor in both Yoroi and Adalite. Once Daedalus supports hardware wallets, you can easily move back since the same hardware wallet can be used with multiple interfaces (Daedalus or otherwise)

**Comment by mmahut** [comment]
Do we have any progress on this issue?

**Comment by nikolaglumac** [comment]
Ledger Nano X, Ledger Nano S, and Trezor Model T support has been added to Daedalus Mainnet in November of 2020.
Thanks for the patience!
