### ISSUE TITLE
error Couldn't find package "web3-requestManager" on the "npm" registry.

### ISSUE THREAD

**Issue by madnight** [input-output-hk/daedalus#610]
OS: Arch Linux
npm --version
5.6.0
node --version
9.3.0
Master version 
e02add010587aa0847726613ab56f44e5dfaf837

**Comment by nikolaglumac** [comment]
Daedalus now uses nix setup which means you no longer need to run `npm install` manually: https://github.com/input-output-hk/daedalus#start-daedalus-using-demo-cluster
