### ISSUE TITLE
No ability to import secret.key

### ISSUE THREAD

**Issue by CryptonZylog** [input-output-hk/daedalus#615]
Instructions on the official [faucet](https://tada.iohk.io/) seem quite simple, however there's no way to import the given secret.key into Daedalus.
> 1. Install Daedalus
> 2. Import your secret.key at start.
> 3. Send your first transaction

My only guess is it's an option when you add a new wallet, however that button is disabled.

![image](https://user-images.githubusercontent.com/1175100/34237529-0459bf16-e5b2-11e7-9666-87416b97fb59.png)

**Comment by DominikGuzei** [comment]
@CryptonZylog you cannot import faucet wallets on the mainnet (that's the default Daedalus connects to if you use the offical installer) … if you want to run Daedalus against the testnet you need to run it locally + [cardano-sl](https://github.com/input-output-hk/cardano-sl/) with testnet configuration.
