### ISSUE TITLE
password rules changes

### ISSUE THREAD

**Issue by jedahan** [input-output-hk/daedalus#619]
Could you remove the password restrictions? I use a manager that does not meet all the requirements, but it strictly better than a) me coming up with my own to remember b) not using a password at all.

Maybe hint that 'its not a good password, are you sure?' kinda dialog.

**Comment by nikolaglumac** [comment]
Current password format rules have been approved by the security audit and reducing these restrictions would have a negative security impact.

**Comment by jedahan** [comment]
Sorry for not clarifying, I propose to have the restrictions changed from content of the password to a minimum length.

**Comment by nikolaglumac** [comment]
We need to enforce all of the following validation rules: 
https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/utils/validations.js#L11
