### ISSUE TITLE
Wallet stuck syncing

### ISSUE THREAD

**Issue by Shockwave414** [input-output-hk/daedalus#620]
Worked fine for a few days and this started happening.

![capture](https://user-images.githubusercontent.com/34796951/34321488-0f76c74e-e7de-11e7-9a44-638d57c8f45e.JPG)

**Comment by h4ck3rm1k3** [comment]
What does your node log say?

When I start the node it shows syncing
```
[node.wallet.servant:INFO:ThreadId 4143] [2017-12-27 13:27:24.72 UTC] 
GET
    :> api
    :> settings
    :> sync
    :> progress
   Status: OK 0.000295229s > progress=408851/408851 peers=0
[node.plugin.ntp-check:INFO:ThreadId 4075] [2017-12-27 13:27:25.88 UTC] Stopped
[node.wallet.servant:INFO:ThreadId 4075] [2017-12-27 13:27:25.88 UTC] 
```

and later 
```
[node.worker.slotting.slotting:NOTICE:ThreadId 582] [2017-12-27 13:43:31.01 UTC] New slot has just started: 20156th slot\
 of 18th epoch
[node.worker.us:DEBUG:ThreadId 569] [2017-12-27 13:43:31.01 UTC] There are no new confirmed update proposals for our app\
lication
[node.worker.block:DEBUG:ThreadId 573] [2017-12-27 13:43:31.01 UTC] Our tip header: MainBlockHeader:
    hash: 11761ce0cdd9bfaac4b2b5ad11b8bda4515ef18130ccf64cd65ec82d13724708
    previous block: 3911d916e22289c338fecf7ae1b5e6a325a254261e3af4b1698b15ab4a88e3bc
    slot: 20103rd slot of 18th epoch
    difficulty: 408851
    leader: pub:1bc97a2f
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = epoch #0, iPk = pub:1bc97a2f, dPk = pub:61261\
a95 } }
    block: v0.1.0
    software: cardano-sl:0
```

**Comment by h4ck3rm1k3** [comment]
So what do you see on these api calls
https://localhost:8090/api/settings/sync/progress
I get 
```
{
    "Right": {
        "_spLocalCD": {
            "getChainDifficulty": {
                "getBlockCount": 412713
            }
        },
        "_spNetworkCD": {
            "getChainDifficulty": {
                "getBlockCount": 412713
            }
        },
        "_spPeers": 0
    }
}```

and 
https://localhost:8090/api/info
```
{
    "Right": {
        "cabalVersion": "1.0.3",
        "apiVersion": "v0",
        "gitRevision": "a32aa645d1329422e9ffcc17dec1d1cccba0f7fa",
        "softwareVersion": "cardano-sl:0"
    }
}
```

**Comment by Djeisen642** [comment]
I have a similar issue. I've been trying to sync back up off and on for a couple weeks now.

**Comment by Djeisen642** [comment]
{"Right":{"_spLocalCD":{"getChainDifficulty":{"getBlockCount":731322}},"_spNetworkCD":{"getChainDifficulty":{"getBlockCount":778717}},"_spPeers":0}}

{"Right":{"cabalVersion":"1.1.0","apiVersion":"v0","gitRevision":"eef095fdf","softwareVersion":"csl-daedalus:4"}}

**Comment by nikolaglumac** [comment]
Please see this article from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360011536933-Synchronization-will-not-complete
