### ISSUE TITLE
Can't exit or force quit Daedalus on macOS

### ISSUE THREAD

**Issue by erf** [input-output-hk/daedalus#621]
Sometimes ( not sure what triggers it ) i can't exit or force quit Daedalus, it stays stuck in the Dock.

I'm on macOS, Sierra high 10.13.2 (17C88) on Daedalus Version 1.0.3619.

**Comment by greggdourgarian** [comment]
Not a dev on the project but suspect memory deadlocks given Haskell garbage collection issues.  Seems to be getting worse as the blockchain gets longer.

**Comment by ZzAntares** [comment]
I'm experiencing the same issue.

**Comment by fnoyer** [comment]
me as well !

**Comment by nikolaglumac** [comment]
These issues should be resolved in the latest Daedalus release.
