### ISSUE TITLE
Wallet can't start on macOS Sierra

### ISSUE THREAD

**Issue by lucianboboc** [input-output-hk/daedalus#622]
I'm trying to open the wallet on macOS Sierra and it works 1/30 times if i do a restart but 99% of the time i can't start it, it becomes unresponsive.
It will stay in the launch bar for about 1-2 minutes then i have to force quit because it will have the "Application not responding" message.
Is there anything i can do to fix this? Thanks,

<img width="333" alt="screen shot 2017-12-24 at 14 25 26" src="https://user-images.githubusercontent.com/1366904/34326489-5fcf7d66-e8b6-11e7-8d9d-06423fd672a0.png">

**Comment by greggdourgarian** [comment]
Not a dev on the project but curious because Apple keeps on shoving the 'upgrade to sierra' on me...have u tried 1) rebooting, 2) verified you have enough memory, 3) verified if enough disk space?

**Comment by lucianboboc** [comment]
Hi,
 
 Yes i checked all those elements and everything is fine.
I using little snitch but everything is approved and i also tried to stop it while running the wallet app.
 I’ve seen this is an app written in javascript, i’m an iOs dev and i’m familiar with UIKit and a few Cocoa apis but not with web technologies used for desktop.
 Anyway if there is any info i can provide just let me know.
 
 Regards,

--

Lucian Boboc
iOS Consultant
@lucianboboc

**Comment by Fabs** [comment]
I have the same problem, on my logs at `==> Logs/cardano-node.log <==`. I see

[node.worker.security:ERROR:ThreadId 557] [2017-12-27 11:05:21 CET] self: enqueue instruction EnqueueAll {enqNodeType = NodeRelay, enqMaxAhead = MaxAhead 1, enqPrecedence = PHigh} failed to enqueue message MsgRequestBlockHeaders Nothing to forwarding sets [[]]

**Comment by greggdourgarian** [comment]
Hi guys...also, like many, having intermittent problems with Daedalus on mac (not Sierra).  

Just had a situation in which Daedalus was hanging the rest of my system.  Looked suspicious that Daedalus (Haskell?) is causing undetected deadlocks...memory allocation deadlocks.  Haskell garbage collection and lazy evaluation may be the sticky wicket here.  Rebooting sometimes works i'm because it frees up memory.   

As the Cardano blockchain gets longer, memory issues would likely get worse and cause hangs which is what we are seeing here.

**Comment by Bema** [comment]
Also not opening in El Capitan 10.11.6

`
Process:               cardano-launcher [433]
Path:                  /Applications/Daedalus.app/Contents/MacOS/cardano-launcher
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Application Specific Information:
/Applications/Daedalus.app/Contents/MacOS/./librocksdb.5.1.2.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   librocksdb.5.1.2.dylib        	0x00000001108be87e std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, rocksdb::OptionTypeInfo, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, rocksdb::OptionTypeInfo> > >::unordered_map(std::initializer_list<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, rocksdb::OptionTypeInfo> >) + 734
1   librocksdb.5.1.2.dylib        	0x00000001108c996a _GLOBAL__sub_I_column_family.cc + 18186
2   dyld                          	0x00007fff65a7710b ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
3   dyld                          	0x00007fff65a77284 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
4   dyld                          	0x00007fff65a738bd ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
5   dyld                          	0x00007fff65a73852 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 198
6   dyld                          	0x00007fff65a73743 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 127
7   dyld                          	0x00007fff65a739b3 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
8   dyld                          	0x00007fff65a660f1 dyld::initializeMainExecutable() + 208
9   dyld                          	0x00007fff65a69d98 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3596
10  dyld                          	0x00007fff65a65276 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 512
11  dyld                          	0x00007fff65a65036 _dyld_start + 54
`

**Comment by lucianboboc** [comment]
Any updates on this? I provided the team the logs, is there a known issue, anything we can help with?

**Comment by nikolaglumac** [comment]
These issues should be resolved in the latest Daedalus release.
