### ISSUE TITLE
Daedalus build from master hangs on syncing block 100.00%

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/daedalus#623]
Daedalus build from [master](https://github.com/input-output-hk/daedalus) hangs on syncing block 100.00%. Several users report this issue. See [here](https://forum.cardanohub.org/t/has-anyone-tried-building-the-cardano-sl-project/195/9?u=zmeel) and [here](https://github.com/input-output-hk/daedalus/issues/603). User [h4ck3rm1k3](https://github.com/h4ck3rm1k3) forked a [branch](https://github.com/h4ck3rm1k3/cardano-sl) and apparently solved this issue.

Is this a know issue or is this due to incorrect build? Is there an official fix?

I have build both cardano-sl and daedalus on Ubuntu 17.10. Cardano-sl started with ./connect-to-mainnet is running smoothly.

**Comment by h4ck3rm1k3** [comment]
duplicate of 603 . The issue is to use a more modern version that supports that api. My branch does not contain any code changes, just marks a version that I used.

**Comment by zmeel** [comment]
Rebuild the whole thing from scratch. See [build instructions](https://github.com/zmeel/cardano-sl).

No luck. Still hangs on syncing blocks 100.00%. The major difference between my build and the build of [h4ck3rm1k3](https://github.com/h4ck3rm1k3/cardano-sl) is that mine is build using **nix-build** and he used the **stack method** (the scripts/build/cardano-sl.sh script). 

My build does not include the time diff api. 

Hopefully one of the developers could shed some light on this...

**Comment by h4ck3rm1k3** [comment]
stack works as well as nix for me, important is that your server and client agree on the https://localhost:8090/api/settings/time/difference api call. If you have a new version of the client it expects that api to be implemented.

**Comment by h4ck3rm1k3** [comment]
Here are some debug techniques 

This shows you the current revision and build env.

https://localhost:8090/api/info
```{
    "Right": {
        "cabalVersion": "1.0.3",
        "apiVersion": "v0",
        "gitRevision": "a32aa645d1329422e9ffcc17dec1d1cccba0f7fa",
        "softwareVersion": "cardano-sl:0"
    }
}```

**Comment by zmeel** [comment]
Closing this for now. I have rebuild Cardano-sl in  a Docker container running Debian and used this [fork](https://github.com/h4ck3rm1k3/cardano-sl) of Cardano-sl. Building went fine and wallet is restoring.

**Comment by h4ck3rm1k3** [comment]
Here is my writeup on using the API directly, have not tried this to make a transfer but should work https://steemit.com/utopian-io/@h4ck3rm1k3st33m/how-to-use-the-api-from-postman-via-the-swagger-json-on-debian-sid-64bit-gnu-linux
