### ISSUE TITLE
PureScript Discussion

### ISSUE THREAD

**Issue by athanclark** [input-output-hk/daedalus#624]
I'm not sure if you all have considered it, but would you be open to an implementation of daedalus in purescript, or at least a partial implementation?

Purescript's React.js bindings are really nice; it properly codifies the react component methodology, and with the Thermite library (Redux analogue), it's very convenient to realize a properly reactive system that works with react-native or electron, as you're using in this application.

Especially with all the haskell, purescript wouldn't hurt I don't too bad I don't think. Especially given paf31's latest design with proper push-pull frp behaviors, I don't see why there wouldn't be any use of some cutting edge tech in the wallet. Additionally, there is a lot of proper type-codification of the traditional Node.js interfaces, coupled with explicit `TChan`-like references, it's pretty easy to create sophisticated programs that are much more correct than usual, when working with a single-threaded javascript.

**Comment by DominikGuzei** [comment]
@athanclark we did consider purescript for Daedalus but actually just replaced the single purescript middleware we had with Flow.js typed Javascript because it's hard to hire frontend developers for such a niche language. Also … it's a very new and unstable environment without backing from major players like Facebook, Google etc.

**Comment by paluh** [comment]
@athanclark I really like your idea of pure Purescript implementation of a wallet. Maybe it is worth to separate bridge code which seems to be under removal from official repo into separate Purescript library as a base for further work...

**Comment by athanclark** [comment]
@paluh Definitely, it could be useful for any arbitrary field - either hosting Main itself, or being used as a library / coupling for sophisticated logic, or for implementations of UI components using a well-typed interface into React components.

Do you know the daedalus architecture well? I might dabble, but I'm not sure if there's extensive docs on the architecture philosophy or anything.
