### ISSUE TITLE
Generate account offline

### ISSUE THREAD

**Issue by athanclark** [input-output-hk/daedalus#627]
Can an account be generated offline? I'm not sure how proof of stake models differ from traditional ones, but it's usually a crucial feature for the paranoid to be able to generate an account, backup code and receiving address while disconnected from the network, that way you can (ideally) audit the code and run it at your own discretion, store the backup code in a paper wallet or something, then wipe the computer.

Has there already been discussion on this? I think it would be hard to avoid; my github-fu didn't show anything in the issues yet.

**Comment by greggdourgarian** [comment]
Nothing i've seen.  You can take a brand new computer, install the wallet, paper save your pass phrase, then delete the wallet etc.   They are also working on Nano S integration which i heard is not far off.

**Comment by athanclark** [comment]
Hmm, so do accounts need acknowledgement from the network or something?

**Comment by cleverca22** [comment]
i believe you can use services like https://iancoleman.io/bip39/ to generate a 12 word passphrase, which can then be used within daedalus
but you need to restore it into daedalus to know what addresses it can receive ada at

source: https://github.com/input-output-hk/cardano-sl/issues/2036#issuecomment-354951151

**Comment by athanclark** [comment]
Oh perfect, so an account's backup code / private key is a bona-fide random number? If that's the case, I think daedalus could benefit from the option of _not_ connecting to the network, or performing other duties while the connection is being established.
