### ISSUE TITLE
self signed certificate error

### ISSUE THREAD

**Issue by asim** [input-output-hk/daedalus#630]
Running into the following issue on mac OS. Any advice?

```
[2017-12-29 17:30:52:0864] [error] CardanoClientApi::syncProgress error: {
  "stack": "Error: self signed certificate in certificate chain\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:584:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)",
  "message": "self signed certificate in certificate chain",
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
```

**Comment by jurisz** [comment]
had same issue, 
on daedalus dir 
> mkdir tls/ca && cp tls/ca.crt tls/ca
as from
https://github.com/hcvst/cardano-daedalus-docker/blob/master/daedalus/Dockerfile

**Comment by asim** [comment]
I inevitably had to restart my machine so it is potentially related to cache of time sync.

**Comment by tanzeelrana** [comment]
[14:34:16:0744] [error] AdaApi::syncProgress error: {
  "stack": "Error: self signed certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:188:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)",
  "message": "self signed certificate",
  "code": "DEPTH_ZERO_SELF_SIGNED_CERT"
}
