### ISSUE TITLE
request a  installer for GNU/Linux

### ISSUE THREAD

**Issue by cmatomic** [input-output-hk/daedalus#631]
I leave a recommendation for developers to use appimage for software distribution on GNU / Linux systems.
https://appimage.org/

**Comment by kfiresmith** [comment]
Piling onto this thread mostly to say that frankly I'm surprised that there still isn't a Linux version of the wallet, which makes Cardano an outlier in the cryptocurrency landscape.  Disappointing.  

I'd recommend AppImage if you are looking to do a universal installer.

**Comment by archfan** [comment]
I agree. Linux support should be getting a higher priority. AppImage is a good format for those kind of endeavours.

**Comment by domenkozar** [comment]
Merging into #492
