### ISSUE TITLE
UX issue when creating wallet, very hard to re-focus window without having to start over.

### ISSUE THREAD

**Issue by dannyvankooten** [input-output-hk/daedalus#633]
When setting up my first Daedalus wallet I switched to another application while working on one of the last steps of the setup process. I then clicked on the only visible part of the Daedelus application window to return focus to it but this made me have to start over with the wallet set-up process entirely. 

It would be a neat little UX improvement if it weren't so easy to undo the few setup steps I've been through already.

**Comment by nikolaglumac** [comment]
It is no longer possible to cancel/close the wallet creation dialogs by clicking on the overlay once you submit the 1st step.
