### ISSUE TITLE
outdated instruction in features/README.md

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/daedalus#636]
Please update `Launch the backend (cardano-sl) in production/staging mode`-instruction.

There is no `scripts/launch/staging.sh` within cardano-sl repository.

Related [cardano-sl issue 2221](https://github.com/input-output-hk/cardano-sl/issues/2221)

**Comment by nikolaglumac** [comment]
Instructions have been updated: https://github.com/input-output-hk/daedalus/blob/develop/features/README.md
