### ISSUE TITLE
I want to translate to Korean

### ISSUE THREAD

**Issue by KimUJeon** [input-output-hk/daedalus#637]
Hello sir.
I want to translate Daedalus program for Korean 
But, I don't know how to translate in this way... Do I need to get admission to translate?

**Comment by SebastienGllmt** [comment]
I believe if you want to translate to Korean you simply have to edit this file:
https://github.com/input-output-hk/daedalus/blob/master/app/i18n/locales/ko-KR.json

You can look at the files for other languages for examples.

**Comment by KimUJeon** [comment]
Can I translate terms of use too?
I'm still working with new files

**Comment by iasinDev** [comment]
Hi, based on this, I also translated this into spanish if you want: https://github.com/input-output-hk/daedalus/pull/653
