### ISSUE TITLE
NPM run dev hangs on "webpack: wait until bundle finished: /dist/bundle.js"

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/daedalus#640]
Here are the logs

If I try and run
> npm run dev

After a clean build, the process hangs on
> webpack: wait until bundle finished: /dist/bundle.js

Any idea what causes this or how to debug? This is with latest master on Windows.
> [0] npm
> [0]  WARN invalid config loglevel="notice"
> [1] npm WARN invalid config loglevel="notice"
> [0]
> [0] > daedalus@0.8.0 hot-server C:\Users\Sebas\Documents\Github\daedalus
> [0] > cross-env NODE_ENV=development node --preserve-symlinks -r babel-register webpack/server.js
> [0]
> [1]
> [1] > daedalus@0.8.0 start-hot C:\Users\Sebas\Documents\Github\daedalus
> [1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./electron/main.development
> [1]
> [1]
> [0] Happy[1]: Version: 4.0.0-beta.2. Threads: 3
> [0] Listening at http://localhost:4000
> [0] Happy[1]: All set; signaling webpack to proceed.
> [0] webpack building...
> [0] webpack: wait until bundle finished: /dist/bundle.js
> [0] webpack: wait until bundle finished: /dist/bundle.js

**Comment by zmeel** [comment]
As far as I can see this is not a bug. When you run `npm run dev` you actually invoke two commands: `npm run hot-server` and `npm run start-hot`. The `npm run hot-server` is the command to build the middleware and the `npm run start-hot` is the command to open the Daedalus frontend. As long as the middleware is not finished building, Daedalus frontend has to wait until middleware is build. By now, your middleware should be finished as it only takes a few minutes to build...

**Comment by SebastienGllmt** [comment]
Never managed to get this to work. Built it on Ubuntu instead.
