### ISSUE TITLE
Daedalus stuck at Syncing blocks 100.00%

### ISSUE THREAD

**Issue by pawelchojnacki** [input-output-hk/daedalus#646]
I built the latest `master`s of `cardano-sl` and `daedalus` on Ubuntu 17.10. I managed to build the former with the use of https://github.com/input-output-hk/cardano-sl/issues/2247 and started `./connect-to-mainnet`, which seems to work fine.

I started Daedalus with an option `export NODE_TLS_REJECT_UNAUTHORIZED=0` and `electron dist/main.js`, which brought up the application's window and started displaying sync status.

Right now it's been stuck at 100.00% for several hours and there seems to be no way to proceed.

Have I done anything wrong? Is it `cardano-sl`'s or `daedalus`'s problem? Can you suggest any way to view logs?

**Edit**: Looking into Daedalus' electron console yields:
`index.html#/:1 Uncaught SyntaxError: Unexpected end of JSON input`

**Comment by mkawalec** [comment]
I have the same thing and can add that `cardano-sl` keeps on logging

```
[node.worker.block:DEBUG:ThreadId 12735] [2018-01-05 10:21:11 CET] Chain quality for the last 'k' (2160) blocks is 0.989
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] After we took lock for genesis block creation, we noticed that we shouldn't create it
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] MemPool metrics release: modify time was 4790mcs size is 0
[node.worker.block:DEBUG:ThreadId 12735] [2018-01-05 10:21:11 CET] Overall chain quality is 1.000
[node.worker.block:DEBUG:ThreadId 12735] [2018-01-05 10:21:11 CET] Chain quality for last 3600s is 0.872
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] Our pk: pub:eec7a78e, our pkHash: 22ee637f
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] Current slot leader: 65904a89
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] Trimmed leaders: [(15039, 1deb8290), (15040, af2800c1), (15041, 65904a89), (15042, 6c9e1497), (15043, 1deb8290), (15044, 43011479), (15045, 6c9e1497), (15046, 5411c7bf), (15047, 1deb8290), (15048, 43011479), (15049, 65904a89), (15050, 5071d880), (15051, 6c9e1497), (15052, 5411c7bf), (15053, 6c9e1497), (15054, 1deb8290), (15055, 65904a89), (15056, 6c9e1497), (15057, 43011479), (15058, 5071d880), (15059, 5071d880)]
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] Available to use lightweight PSKs: []
[node.worker.block:DEBUG:ThreadId 12736] [2018-01-05 10:21:11 CET] End delegation psk for this slot: ProxySk { w = epoch #0, iPk = pub:0bdb1f5e, dPk = pub:5fddeeda }
[node.wallet.servant:INFO:ThreadId 12737] [2018-01-05 10:21:11 CET] 
GET
    :> api
    :> settings
    :> sync
    :> progress
   Status: OK 0.000476532s > progress=446969/446969 peers=0
```

Zero peers looks like an issue here :)

**Comment by mlb5000** [comment]
@pawelchojnacki make sure you start Daedalus before the block synchronization process starts on the SL node. That's the only way I've been able to avoid this issue.

**Comment by pawelchojnacki** [comment]
@mlb5000 thanks a lot!

What's interesting. If I start Daedalus first, in a moment after `cardano-sl` starts working I get an error saying I'm 0s behind the blockchain and I need to synchronize the system time.

In less than a minute, Daedalus starts working.

**Comment by zmeel** [comment]
@pawelchojnacki Do you see an error in Daedalus? You are probably using the wrong version of Daedalus. You should build revision `a267ae05daaf3947fe679eac56d1257a8775b27b` and not `master`. See this [issue](https://github.com/input-output-hk/cardano-sl/issues/2184)

**Comment by zmeel** [comment]
@pawelchojnacki: Did you succeed? If so, could you close the issue?

**Comment by domenkozar** [comment]
You should use daedalus `release/0.8.2` branch.

**Comment by pawelchojnacki** [comment]
@zmeel Succeeded, closing!
