### ISSUE TITLE
Daedalus on Linux with Btrfs

### ISSUE THREAD

**Issue by nohajc** [input-output-hk/daedalus#647]
I tried to run the wallet on linux and it looks like it doesn't play nice with btrfs.

Specifically, on the first run during the syncing process, I always run out of disk space after some time.
Well, the disk is actually not full - it still reports about 70 GB of free space which should be enough. The problem is with btrfs block group allocation.

Usually, the output of `btrfs fi df /` should look like this:
```
Data, single: total=102.72GiB, used=101.97GiB
System, single: total=4.00MiB, used=16.00KiB
Metadata, single: total=4.01GiB, used=1.95GiB
GlobalReserve, single: total=512.00MiB, used=0.00B
```

To quote from https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-filesystem#SUBCOMMAND

> total — sum of space reserved for all allocation profiles of the given type, ie. all Data/single. Note that it’s not total size of filesystem.
> used — sum of used space of the above, ie. file extents, metadata blocks

Ideally, the difference between `total` and `used` should be small. After trying to sync the blockchain multiple times, my `total` would increase to 100 % of fs capacity, while `used` is still about 70 GB lower.

This practically leads to _no space left on device_ kind of errors and can only be fixed by rebalancing (`btrfs balance start -d /`).

Obviously, this is not very practical. Could you try to reproduce?
Please, excuse me if this is the wrong place to report this. Maybe it should go to cardano-sl repository... I'm not sure.

**Comment by erikd** [comment]
This is almost certainly related to #576 .

**Comment by nikolaglumac** [comment]
Please post this question to https://github.com/input-output-hk/cardano-sl
