### ISSUE TITLE
Ada balance hasn't appeared in my Binance wallet for over 48 hours now - Sent from Daedalus wallet

### ISSUE THREAD

**Issue by silkyskills** [input-output-hk/daedalus#652]
It doesn't even show it pending in binance - works for other coins so it's defiantly a Ada network/wallet issue

**Comment by silkyskills** [comment]
Not sure what to do

**Comment by kingstenbanh** [comment]
Did you send it to the write Binance's Ada wallet address? Do you see an `Ada sent` transaction recorded in the `Summary` tab of the wallet?

**Comment by silkyskills** [comment]
All good now, seems Binance was at fault for the delay
