### ISSUE TITLE
Application not opening after install

### ISSUE THREAD

**Issue by marcodellovo** [input-output-hk/daedalus#656]
The application is not opening after the install. I checked the logs folder but it's completely empty.

I'm trying to run the application on a MacOS Yosemite (10.10.5).

**Comment by domenkozar** [comment]
Could you please add more information? What exact installer you used?

**Comment by nikolaglumac** [comment]
Please reinstall Daedalus following the instructions from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360011407033-Reinstallation-normal-method
