### ISSUE TITLE
[build-certificates-win64.bat] Fix OPENSSL_MD replacement

### ISSUE THREAD

**Issue by AmosHason** [input-output-hk/daedalus#664]
After DAYS of research of the https://github.com/input-output-hk/daedalus/issues/608 issue on Windows 7, getting no answers from the developers, and reading many people's suggestions over the net that this issue is not caused by the Daedalus wallet and should be fixed by the user, here I present to you:

[build-certificates.log]
OPENSSL_MD is an unsupported message digest type

This happens because the replacement in step 2 doesn't work as intended.

Workaround:

Manually change all occurrences of OPENSSL_MD to sha256 in ca.conf, client.conf and server.conf, and rerun the script.

Now launch Daedalus, and surprise - the endless "connecting to network" screen is now gone, and you can actually start using your wallet.

There are so many users affected by this issue, and it must be fixed ASAP. I have no idea why it has persisted up until now.

**Comment by AmosHason** [comment]
Suggestion: don't use PowerShell for this task. Some Windows users (like me) experience issues when trying to run PowerShell. Use another method for this replacement, or pre-define sha256 in the configuration files.

**Comment by deepfire** [comment]
Thank you for reporting this finding, @AmosHason!

It is indeed, disconcerting, that powershell availability on Windows isn't as uniform as we'd like.. : -/
