### ISSUE TITLE
Javascript error on launch. Win7 x64

### ISSUE THREAD

**Issue by T81** [input-output-hk/daedalus#665]
Installer: daedalus-win64-1.0.3769.0-installer.exe
Problem: Daedalus does not launch.
After installation, when running daedalus the following error occurs:
**

> A Javascript error occured in the main process
> Uncaught Exception:
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.join (path.js:466:7)
>     at exports.default (C:\Program Files\Daedalus\resources\app\dist\webpack:\electron\lib\getRuntimeFolderPath.js:9:19)
>     at Object.<anonymous>  (C:\Program Files\Daedalus\resources\app\dist\webpack:\electron\main.development.js:14:27)
>     at __webpack_require__  (C:\Program Files\Daedalus\resources\app\dist\webpack:\webpack\bootstrap 8e6fe361fd7dbf5e3e5b:19:1)
>    at object.<anonymous> (C:\Program Files\Daedalus\resources\app\dist\\main.js:50:19)
>    at __webpack_require__  (C:\Program Files\Daedalus\resources\app\dist\webpack:\webpack\bootstrap 8e6fe361fd7dbf5e3e5b:19:1)
> at C:\Program Files\Daedalus\resources\app\dist\webpack:\webpack\bootstrap 8e6fe361fd7dbf5e3e5b:39:1
>    at object.<anonymous> (C:\Program Files\Daedalus\resources\app\dist\\main.js:45:10)
>    at Module._compile (module.js:566:32)

**

**Comment by domenkozar** [comment]
@fersel

**Comment by T81** [comment]
Fixed on next release
