### ISSUE TITLE
Request: Instructions how to build Daedalus wallet on NixOS ("/setup: line 1044: 7660 Segmentation fault")

### ISSUE THREAD

**Issue by gwpl** [input-output-hk/daedalus#669]
* https://github.com/input-output-hk/cardano-sl/blob/199774af177f05a4ca8741db25dc67ab79d02bcf/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

instructions lack instructions how to build Daedalus wallet on NixOS.

In NixOS, I:
```
nix-shell -p git vim nodejs-8_x python2
git clone https://github.com/input-output-hk/daedalus.git
cd daedalus
npm install
# AND IT FAILS
```

Btw. which branch should I checkout? master? 'cardano-sl-1.0-grouping-policy' or 'cardano-sl-0.6' ?

P.S. So far I have build and seems running cardano-sl in NixOS as I [posted here](https://github.com/input-output-hk/cardano-sl/issues/2305#issuecomment-357654422) and (on user request) I [shared  VM appliance here](https://github.com/input-output-hk/cardano-sl/issues/2305#issuecomment-358301733) (so you can just try out on same VM appliance I am using)

**Comment by cleverca22** [comment]
```
git checkout devops-13
nix-env -f release.nix -iA daedalus
```
that is pretty much all you need to get it running, only thing missing is automated updates

**Comment by gwpl** [comment]
Command finished. Now how to run it? As [readme](https://github.com/input-output-hk/daedalus/blob/1a6357dbd7a5ae84ec38cae1785382633a4021ea/README.md) suggest `npm run dev` which does not work in nix environment you've proposed for compilation : `npm not found`. Sorry if it's trivial, but I am doing my first steps with Nix.

**Comment by gwpl** [comment]
> Insanity: doing the same thing over and over again and expecting different results.
> ([brainyquote](https://www.brainyquote.com/quotes/unknown_133991))

Let me confirm, that after running command again, I get the same result (just faster), i.e. same Segfault on line 1044 of "/setup" ... as visible on screenshot. (In first post links to NixOS version I used and packaged Virtual Machine Appliance)

**Comment by cleverca22** [comment]
and it still happens when not in a `nix-shell`?
what does `cat /proc/cpuinfo` say?

**Comment by gwpl** [comment]
without nix-shell I have no access to git.

**Comment by cleverca22** [comment]
how much ram did you give to virtualbox? try giving it 4096mb of ram and then re-run the nix-env command

**Comment by gwpl** [comment]
Good point!
With 4096 MB of RAM it compiled!
Thanks.

**Comment by MissingNoIOI** [comment]
Sry to necro this issue, but the nix script doesn't seem to work anymore. When I try to build daedalus I simply get the following error:
```
λ  daedalus devops-13 ✓ nix-env --show-trace -f release.nix -iA daedalus
error: while evaluating the file '/home/gerrit/Downloads/daedalus/linux.nix':
while evaluating anonymous function at /home/gerrit/Downloads/daedalus/fetchNixpkgs.nix:1:1, called from /home/gerrit/Downloads/daedalus/linux.nix:1:14:
while evaluating 'ifThenElse' at /home/gerrit/Downloads/daedalus/fetchNixpkgs.nix:7:16, called from /home/gerrit/Downloads/daedalus/fetchNixpkgs.nix:11:1:
store path mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs/archive/3eccd0b11d1.tar.gz'
```

**Comment by cleverca22** [comment]
@MissingNoIOI thats a bug with nix 2.0, nix 1.11 should work for that branch
