### ISSUE TITLE
Issues with "paste" in Windows verions when using the mouse

### ISSUE THREAD

**Issue by b3dk7** [input-output-hk/daedalus#671]
Cant paste addresses into the receiver text box under the "Send" tab using the mouse in Microsoft Windows 7. I am using daedalus version. 1.0.3769

**Comment by domenkozar** [comment]
@darko-mijic @nikolaglumac is that due to the fact we're running as admin?

**Comment by dmitrystas** [comment]
Have the same problem. The context menu by right click are calling, but there is no action for Copy or Paste. When I click to Copy or Paste - nothing happens. But Ctrl+C and Ctrl+V works perfectly

**Comment by DominikGuzei** [comment]
@darko-mijic im not sure if this is related to the rights issue (running as admin) we discovered for drag & drop. We need to further investigate (i couldn't find the issue a while ago)

**Comment by nikolaglumac** [comment]
This issue has been resolved in https://github.com/input-output-hk/daedalus/blob/develop/CHANGELOG.md#091
