### ISSUE TITLE
Ecectron Protocol Handler Vulnerability

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/daedalus#679]
Is it a know issue?

https://electronjs.org/blog/protocol-handler-fix

**Comment by csoroz** [comment]
Also appears in The Hacker News: https://thehackernews.com/2018/01/electron-js-hacking.html

**Comment by domenkozar** [comment]
Daedalus does not register any protocols, so it's not affected. Next release will ship patched Electron regardless.
