### ISSUE TITLE
Daedalus won't download

### ISSUE THREAD

**Issue by bobboington** [input-output-hk/daedalus#685]
Hey there, I can't down load Daedalus. It keeps saying 'download failed'. I've checked that PowerShell is installed (Windows 7 so it was anyway). I've tried turning off the anti virus and attempting download through Mozilla, Chrome and Brave. Any other ideas?

**Comment by Partikel** [comment]
I've got the same issue. Windows 10. Tried Chrome and Edge.

**Comment by domenkozar** [comment]
We've resolved this by moving storage from appveyor to our custom S3 bucket.
