### ISSUE TITLE
MacOS restart required for proper synchronization, receive funds

### ISSUE THREAD

**Issue by dash-** [input-output-hk/daedalus#693]
A very recently-downloaded version required restarting the operating system to perform a full sync, despite the fact that the UI indicated it was synchronized.  Prior to restarting, I had verified via the Block Explorer that funds had been successfully transferred to the wallet address.  Attempted to use GUI to force resynchronization: Top-right indicated icons said "Blocks synced 100%", clicking made no impact (not clickable?), tried View->Reload, no luck there.  Tried restarting the application.  No change.

Upon googling, I found online conversations suggesting restarting as a workaround.  I restarted my laptop and re-opened Daedalus.  After finishing syncing, funds immediately appeared.

Feature request: Manual forced synchronization.
Bug fix: "Blocks synced 100%" was not accurate.

**Comment by dash-** [comment]
https://github.com/input-output-hk/daedalus/blob/master/app/stores/NetworkStatusStore.js#L119-L125

**Comment by nikolaglumac** [comment]
This should no longer be an issue. Please update to latest Daedalus release: https://daedaluswallet.io/#download
