### ISSUE TITLE
Certificate issues connecting to SL

### ISSUE THREAD

**Issue by ml31415** [input-output-hk/daedalus#698]
I'm trying to get the wallet running on Linux. After quite some theater I'm able to launch SL and Daedalus now, but Daedalus hangs with the well known "Connecting to network" message, and I see the console flooded with messages like:

```
[10:11:52:0147] [error] AdaApi::syncProgress error: {
  "stack": "Error: self signed certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:188:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)",
  "message": "self signed certificate",
  "code": "DEPTH_ZERO_SELF_SIGNED_CERT"
}
[10:11:52:0166] [error] AdaApi::getLocalTimeDifference error: {
  "stack": "Error: self signed certificate\n    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:188:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)",
  "message": "self signed certificate",
  "code": "DEPTH_ZERO_SELF_SIGNED_CERT"
```
I'm using cardano-SL master ( https://github.com/input-output-hk/cardano-sl/commit/797dfa4704adfd566c425357ced6787f0a576268 ) and the recommended version for Daedalus ( ab6aab0c5203e9bad9af66d17ad65b460f61f226 ) which is supposed to get along with the timedifference issue. Though, I suppose the errors concerning some certificate have some other reason, and I didn't see any reports about that so far. I'm running node v6.12.3 on Ubuntu 16.04. Pls let me know if I can help with further debug data.

**Comment by omefire** [comment]
Facing the same issue. Did you figure it out ?

**Comment by ml31415** [comment]
Nope. Decided to further wait for a Linux client. Wasted enough time already with this dependency desaster of a codebase.

**Comment by zmeel** [comment]
I had the same issue. Solved it by setting `NODE_TLS_REJECT_UNAUTHORIZED=0` as environmental variable

**Comment by domenkozar** [comment]
We are working on Linux support to avoid packaging issues, please follow: https://github.com/input-output-hk/daedalus/issues/492

**Comment by CraniumDad** [comment]
I was also able to work around this by copying or symbolic linking the cardano-sl's nodes 'state-wallet-mainnet/tls/server.cert' to ~/tls/ca/ca.crt for Daedalus.
