### ISSUE TITLE
Ubuntu 17.10 install stuck on "Syncing blocks 100.00%"

### ISSUE THREAD

**Issue by coventry** [input-output-hk/daedalus#708]
I seem to have a full copy of the blockchain, and Daedalus is running (though I did have to set `NODE_TLS_REJECT_UNAUTHORIZED=0` as described in #698.) However, there are no usable UI elements in Daedalus.

This is with recently pulled master (commit d972b86101347d8e9244aaa4241ad542a28d79f8.)

![image](https://user-images.githubusercontent.com/70152/35759117-9d4e2e68-0845-11e8-8983-b171d3a45c81.png)

**Comment by zmeel** [comment]
Try building `release/0.8.2` of Daedalus.

**Comment by coventry** [comment]
Thanks for the suggestion. I get the same failure with `release/0.8.2`.

![daedalus2](https://user-images.githubusercontent.com/70152/35771904-6c0e6602-0902-11e8-9425-7888c9d37f8a.png)

I simply did `git checkout release/0.8.2; npm install`. Please LMK if the build system is fragile, and I should try a clean rebuild.

**Comment by coventry** [comment]
No, the terminal I start daedalus in is silent. (It's the top RH terminal in the image in my last response.)

Is there a debug mode?

**Comment by domenkozar** [comment]
We are working on Linux support to avoid packaging issues, please follow: https://github.com/input-output-hk/daedalus/issues/492
