### ISSUE TITLE
Offer to help Localize Daedalus

### ISSUE THREAD

**Issue by gdorta** [input-output-hk/daedalus#714]
Would like to offer help localizing Daedalus Daedalus on Github. Charles mentioned to email Jousha Miller but got an auto-reply. Let me know how I can help, more than happy to. Best Wallet UI on the planet!

**Comment by simon66** [comment]
This is an open-source project. Fork it, add your fixes and do a PR :)
I'm sure they wont reject good working code :+1:

You can see some locales stuff here
https://github.com/input-output-hk/daedalus/tree/master/app/i18n/locales

**Comment by darko-mijic** [comment]
Please wait with localization efforts @gdorta. We are putting a process in place. Until we have a solid process for managing opensounce contributions in this area, it will be a problem for us to handle these efforts. PRs with features and fixes cannot be merged currently if we have missing translations.

**Comment by simon66** [comment]
Hi @darko-mijic 
Thanks for the update. I did not know Deadalus did not accept community contribution. Do you have an ETA on when this will be possible? Not trying to rush but I would also like to contribute :)
Thanks

**Comment by darko-mijic** [comment]
@simon66 Daedalus is open to community contributions. We will announce the guidelines soon. Translations are a specific case since they need to be included in feature branches. If we decide to support new language we would need contributors for that language on a regular base. More information coming soon.

**Comment by vantuz-subhuman** [comment]
Would also like to contribute the Russian translation, but I can see the problem of incomplete localizations when new GUI elements with text are added. Core team would have to either update all translations by themselves, or to wait for new contributions.

**Comment by nikolaglumac** [comment]
Thank you for your contribution! Unfortunately, at this moment in time, we can not accept this translation as it would be hard to maintain it without internal translation/audit process.
