### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/daedalus#720]
Error: self signed certificate

![image](https://user-images.githubusercontent.com/2520028/36077259-8a228972-0f36-11e8-8e40-6d075ca2bb6e.png)

![image](https://user-images.githubusercontent.com/2520028/36077265-b18187f2-0f36-11e8-83e5-877253460250.png)

**Comment by zmeel** [comment]
Duplicate of [698](https://github.com/input-output-hk/daedalus/issues/698). Solved it by setting `NODE_TLS_REJECT_UNAUTHORIZED=0` as environmental variable

**Comment by domenkozar** [comment]
We are working on Linux support to avoid packaging issues, please follow: https://github.com/input-output-hk/daedalus/issues/492

**Comment by datlife** [comment]
As @zmeel suggested, this solution work.Export this before running your wallet `npm run start`.
```shell
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
