### ISSUE TITLE
Acceptance Test Window Blank

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/daedalus#736]
I sync'd to the latest version of develop and ran the acceptance tests after following the steps in features/README (except for the step asking you to do it off of master)

The steps fail because the wallet simply loads a blank screen with no UI (despite no error in `npm run hot-server` (finished with `webpack: Compiled successfully.`)

`npm run dev` still works as expected. 

Any idea how to debug this?

**Comment by SebastienGllmt** [comment]
![image](https://user-images.githubusercontent.com/2608559/36419850-fd55f958-15e7-11e8-8568-bd3c65120a5d.png)

This build is on Ubuntu-64bit if that changes anything

**Comment by darko-mijic** [comment]
Any errors in the Electron console @SebastienGllmt?

**Comment by SebastienGllmt** [comment]
I tried rerunning the steps and now looking at it, I didn't notice that step the following step in `features/README.md` failed

4. Link your backend build with the Daedalus frontend (assumed that you have build the backend previously):
> $ cd daedalus/node_modules/
> $ npm link daedalus-client-api

It fails with `404 Registry returned 404 for GET on https://registry.npmjs.org/daedalus-client-api`. 

I think this is because there was a missing step where I had to run `scripts/build-installer-unix.sh`

After running the build using `./scripts/build-installer-unix.sh 1.0.3769 develop` (not sure if the arguments are right but it worked)
I now get `npm ERR! enoent ENOENT: no such file or directory, open '/home/sebastien/Documents/git/daedalus/node_modules/daedalus-client-api/package.json'` (that is to saw the folder only contains `node_modules/daedalus-client-api/node_modules`

Any idea what is missing? Does this mean you can't run tests on changes that haven't been pushed to a branch on this repo?

**Comment by jontambi** [comment]
Hey @SebastienGllmt I have the same problem, Now I have soved.
Check this path: /home/(yourUSER)/.config/Electron if your user have access. I set chown -R yourUser:yourUser /home/(yourUSER)/.config ... after  I ran npm install && npm run build
Then: npm run start 
or
npm run dev
after that Daedalus appear well.
