### ISSUE TITLE
Closing Daedalus during sync does not close port - opening it again leaves it stuck in "Connecting to Network..." state

### ISSUE THREAD

**Issue by andsav** [input-output-hk/daedalus#760]
**Platform**: Mac OS High Sierra
**Release**: Daedalus 1.0.3619

**Bug**
After closing Daedalus during the initial block sync, there is still a process *cardano-n* listening to port 8090. When opening Daedalus again, it is stuck in the *Connecting to Network...* state forever. This is only solved by killing *cardano-n* manually.

**Expected behavior**
Close the application properly, or at least detect that cardano-n is blocking port 8090 and kill it at startup

**Comment by nikolaglumac** [comment]
This bug was fixed in Daedalus 0.12.0: https://github.com/input-output-hk/daedalus/tree/0.12.0

> **Improved process management**
> Process management has been completely re-engineered to give Daedalus greater control of the Cardano node process, especially when detecting issues with the Cardano node and recovering from them. This change also introduces a dynamic selection of ports, which eliminates issues with starting the Cardano node if the configured port is already taken. This feature also includes dynamic TLS certificate generation for two-way encryption in communication with the Cardano node for improved security. This change fixes some of the issues which were causing Daedalus to be stuck on the loading screen with a ‘Connecting to network’ message.
