### ISSUE TITLE
Daedalus loses sync with a wallet when sending from a different computer

### ISSUE THREAD

**Issue by andsav** [input-output-hk/daedalus#763]
**Platforms**: Mac OS High Sierra, Windows 10
**Release**: Daedalus 1.0.3619

**Bug**
If I have a wallet with the same seed on two different computers and I do a send transaction from one computer, the other one does not refresh the wallet balance before Daedalus is restarted. If the wallet receives funds subsequently, the first computer will not see them before the application is not restarted. Doing a "soft refresh" with Cmd+R does not solve the problem: Daedalus must be closed and started again.

This is not expected behavior as Daedalus says "Blocks synced 100%" in the top upper corner.

**Comment by greggdourgarian** [comment]
I noticed this as well on the old version (1.0.3619).   Still present on 1.1.0.408?

**Comment by nikolaglumac** [comment]
This should no longer be happening.
