### ISSUE TITLE
Error in $: key "groupingPolicy" not presentres

### ISSUE THREAD

**Issue by kenken64** [input-output-hk/daedalus#764]
I trying to get fee 

from /api/txs/fee/{from}/{to}/{amount}

getting the following error. Can someone show me all the input values to test this end point?

**Comment by nikolaglumac** [comment]
Please use the V1 API: https://cardanodocs.com/technical/wallet/api/v1/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions~1fees%2Fpost
