### ISSUE TITLE
npm install fails for node-gyp

### ISSUE THREAD

**Issue by McReinhardt** [input-output-hk/daedalus#774]
I try to install the wallet for Linux (Debian 9), but the suggested command from the docs fails with the following:

npm install   

> daedalus@0.8.0 preinstall /home/max/daedalus
> which electron || npm install electron@1.7.9

> electron@1.7.9 postinstall /home/max/daedalus/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN daedalus@0.8.0 No repository field.
npm WARN daedalus@0.8.0 No license field.

+ electron@1.7.9
added 155 packages in 13.348s
npm WARN deprecated babel-preset-es2015@6.24.0: 🙌ease read babeljs.io/env to update! 
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌ease read babeljs.io/env to update! 
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated babel-preset-latest@6.16.0: We're super 😸nstead of making more yearly presets 😭babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏e us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌ease read babeljs.io/env to update! 
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌ease read babeljs.io/env to update! 
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> v8-profiler@5.6.5 preinstall /home/max/daedalus/node_modules/electron-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'

> v8-debug@0.7.7 preinstall /home/max/daedalus/node_modules/electron-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

> scrypt@6.0.3 preinstall /home/max/daedalus/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: in `/home/max/daedalus/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

> electron-chromedriver@1.7.1 install /home/max/daedalus/node_modules/electron-chromedriver
> node ./download-chromedriver.js

> scrypt@6.0.3 install /home/max/daedalus/node_modules/scrypt
> node-gyp rebuild

make: Verzeichnis „/home/max/daedalus/node_modules/scrypt/build“ wird betreten
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
make: cc: Kommando nicht gefunden
scrypt_wrapper.target.mk:110: die Regel für Ziel „Release/obj.target/scrypt_wrapper/src/util/memlimit.o“ scheiterte
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Fehler 127
make: Verzeichnis „/home/max/daedalus/node_modules/scrypt/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/max/daedalus/node_modules/scrypt
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN daedalus@0.8.0 No repository field.
npm WARN daedalus@0.8.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2018-03-06T15_36_03_950Z-debug.log

Here is the debug-log:
[2018-03-06T15_36_03_950Z-debug.log](https://github.com/input-output-hk/daedalus/files/1785651/2018-03-06T15_36_03_950Z-debug.log)

**Comment by Furiacs** [comment]
> make: cc: Kommando nicht gefunden

You need to install c++ compiler. It will be used by node-gyp...

**Comment by McReinhardt** [comment]
But I have already installed gcc, g++ and clang:
cmake is also installed.
> 
Statusinformationen werden eingelesen.... Fertig
g++ ist schon die neueste Version (4:6.3.0-4).
gcc ist schon die neueste Version (4:6.3.0-4).
clang ist schon die neueste Version (1:3.8-36).
>

**Comment by Furiacs** [comment]
> Error: Error: Command failed: ./configure
> configure: error: in /home/max/daedalus/node_modules/scrypt/scrypt/scrypt-1.2.0': configure: error: no acceptable C compiler found in $PATH Seeconfig.log' for more details

So there is something wrong with your paths.

**Comment by reidblomquist** [comment]
What version of node are you using? I saw some similar errors when trying 8.X; downgraded to 6.X LTS and all seems fine. I think electron and some of its packaging tools have issues w/ newer versions of node and npm

**Comment by McReinhardt** [comment]
i've now downgraded to version 6.13.1 but unfortunately this doesn't change the error message much:
npm install                                                            

> daedalus@0.8.0 preinstall /home/max/daedalus
> which electron || npm install electron@1.7.9

/home/max/daedalus/node_modules/.bin/electron

> v8-profiler@5.6.5 preinstall /home/max/daedalus/node_modules/.staging/v8-profiler-e1097ed7
> node -e 'process.exit(0)'


> scrypt@6.0.3 preinstall /home/max/daedalus/node_modules/.staging/scrypt-0688ce32
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: in `/home/max/daedalus/node_modules/.staging/scrypt-0688ce32/scrypt/scrypt-1.2.0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details


> v8-profiler@5.6.5 install /home/max/daedalus/node_modules/electron-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/max/daedalus/node_modules/electron-inspector/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-x64/profiler.node" is installed via remote

> scrypt@6.0.3 install /home/max/daedalus/node_modules/scrypt
> node-gyp rebuild

make: Verzeichnis „/home/max/daedalus/node_modules/scrypt/build“ wird betreten
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
make: cc: Kommando nicht gefunden
scrypt_wrapper.target.mk:109: die Regel für Ziel „Release/obj.target/scrypt_wrapper/src/util/memlimit.o“ scheiterte
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Fehler 127
make: Verzeichnis „/home/max/daedalus/node_modules/scrypt/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/max/daedalus/node_modules/scrypt
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
biased-opener@0.2.8 node_modules/biased-opener -> node_modules/electron-inspector/node_modules/node-inspector/node_modules/biased-opener
strong-data-uri@1.0.5 node_modules/strong-data-uri -> node_modules/electron-inspector/node_modules/node-inspector/node_modules/strong-data-uri
options@0.0.6 node_modules/options -> node_modules/electron-inspector/node_modules/ws/node_modules/options
daedalus@0.8.0 /home/max/daedalus
└─┬ electron-inspector@0.1.4
  ├── node-inspector@0.12.8  (git+https://github.com/enlight/node-inspector.git#accd46758501d8187e55b32b54e3eff65c3fdaa3)
  └── v8-profiler@5.6.5  (git+https://github.com/enlight/v8-profiler.git#dc3a4e15f06dd6eaca705e69e235d21d5962eaf5)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN daedalus@0.8.0 No repository field.
npm WARN daedalus@0.8.0 No license field.
npm ERR! Linux 4.9.0-6-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/daedalus/npm-debug.log

**Comment by McReinhardt** [comment]
my path variables are: 
echo $PATH                                                         
/usr/local/bin:/usr/bin:/bin:/usr/games
Do I really have to include more? I'm not aware about manually changing $PATH from the original Debian configuration.

**Comment by McReinhardt** [comment]
Daedalus is working after using the new beta....
