### ISSUE TITLE
Please provide sha256 code.

### ISSUE THREAD

**Issue by jaohaohsuan** [input-output-hk/daedalus#776]
It's better to show sha256 code in every release.
Thanks

**Comment by archfan** [comment]
No signatures and no updates for Linux. You guys should set your priorities straight.

**Comment by nikolaglumac** [comment]
Both PGP signatures and SHA256 checksums are available for all Daedalus installers: https://daedaluswallet.io/#download

**Comment by goetzc** [comment]
@nikolaglumac it makes sense to include the SHA sums on the same locations as the download site, but not so with the PGP signatures. They should be also available on other locations, as for example on the repository on GitHub releases page, as it used to be back on the 0.11.0 release.
https://github.com/input-output-hk/daedalus/releases/tag/0.11.0

**Comment by goetzc** [comment]
Please see https://github.com/input-output-hk/daedalus/issues/1380.

**Comment by nikolaglumac** [comment]
@darko-mijic let's look into this!

**Comment by nikolaglumac** [comment]
@LaurenceIO can you please include PGP signature in the Daedalus release notes?
We used to do that [before](https://github.com/input-output-hk/daedalus/issues/776#issuecomment-619443591) and we should make this a part of our usual release process. Thanks 🙏

**Comment by nikolaglumac** [comment]
@goetzc we will be publishing the PGP signature within Daedalus release notes on GitHub from this point forward thanks to @LaurenceIO 🎉

**Comment by goetzc** [comment]
This is great news, thanks!

**Comment by nikolaglumac** [comment]
@goetzc we have the PGP signature in the latest release notes: https://github.com/input-output-hk/daedalus/releases/tag/3.3.0-FC1

Hope you like it 😄 

Many thanks to @LaurenceIO 🙏
