### ISSUE TITLE
Daedalus 1.1.4883 still has error with non-latin characters in APPDATA folder`s name

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/daedalus#780]
When I try to run I get error

> cardano-launcher.exe
> Couldn't pack log files, reasons: can't pack log file pub\node.pub because it doesn't exist or it's not a file

http://prntscr.com/iojuv9

**Comment by domenkozar** [comment]
on windows?

**Comment by dmitrystas** [comment]
yes, on windows 10

**Comment by domenkozar** [comment]
Sadly it's not trivial to fix - please monitor https://github.com/facebook/rocksdb/issues/3408

**Comment by SebastienGllmt** [comment]
To catch issues like this in the future, is it possible to have one of the CI run on a non-ASCII locale? @domenkozar

**Comment by dmitrystas** [comment]
For previous version of Daedalus 1.0.3769 I created symlink AnyLatinName to my real account NonLatinName and changed all %APPDATA% to C:\Users\AnyLatinName in the bat file, and all was fine. But is no bat file in last version, and I can run Daedalus only if I create another account with latin characters only

**Comment by domenkozar** [comment]
We are actively working on a fix - but don't expect this soon as we have to upstream fixes.

**Comment by Hugovdu** [comment]
at least im not the only one with the problem
howcome the update was automatically without warning upfront? would have been nicer so everyone can first make sure they have absolutely saved all keys and recovery logs

**Comment by Hugovdu** [comment]
eh i just fixed my issue (also had the pub\node.pub error)
i first installed the old wallet again (1.10 version or something) then i downloaded the new wallet from the cardano website, installed it & was able to open it without issue after a short sync
