### ISSUE TITLE
Daedalus Wallet stuck on "Reconnecting to network ..." seems in endless loop in logs

### ISSUE THREAD

**Issue by assal01** [input-output-hk/daedalus#788]
I have not opened my wallet in a few weeks. 
Now, I tried opening it and it was stuck in "Connecting to network ..."
I searched for an update and found current release 1.1 - downloaded and installed it.
Still, I get "Connecting to network ..." and after a few minutes "Network connection lost - reconnecting..." and it stays there.
After reading some FAQ I restarted my computer to get rid of any possible "hung" processes.
Again, no luck, and I checked - no hung processes and the ports 8080 and 8090 are not in use by any application.
Checked logs, it seems it is in an endless loop of "getChainDifficulty".
Logs attached.
[pub.zip](https://github.com/input-output-hk/daedalus/files/1800635/pub.zip)

**Comment by cleverca22** [comment]
`[node.worker.subscription:NOTICE:ThreadId 580] [2018-03-11 17:24:27.43 UTC] subscriptionWorker: lost connection to NodeId 13.229.193.102:3000:0 Exceptional (TransportError ConnectFailed "Network.Socket.recvBuf: resource vanished (Connection reset by peer)")`

does your firewall allow outgoing traffic on port 3000?

**Comment by assal01** [comment]
I will look into it, but I don't see why a Node that was fully sync'd once suddenly stops working because a port nobody touched... Thans @cleverca22

**Comment by assal01** [comment]
Nothing wrong on 3000...

The first error message I see in logs actually is in this block (although it doesn't tell me anything, other than, it was connected then lost connection for some reason):


`[94m[node.plugin.ntp-check:INFO:ThreadId 652] [0m[2018-03-11 20:07:02.31 UTC] Launched NTP client
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.50 UTC] Got packet NtpPacket {ntpParams = 28, ntpPoll = 3, ntpOriginTime = 1520798822318788mcs, ntpReceivedTime = 1520798822413024mcs, ntpTransmitTime = 1520798822413105mcs}
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.50 UTC] Received time delta 642 mcs
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.55 UTC] Got packet NtpPacket {ntpParams = 28, ntpPoll = 3, ntpOriginTime = 1520798822318723mcs, ntpReceivedTime = 1520798822448740mcs, ntpTransmitTime = 1520798822448754mcs}
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.56 UTC] Received time delta 9240 mcs
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.56 UTC] Got packet NtpPacket {ntpParams = 28, ntpPoll = 3, ntpOriginTime = 1520798822318819mcs, ntpReceivedTime = 1520798822447830mcs, ntpTransmitTime = 1520798822447862mcs}
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.56 UTC] Received time delta 5759 mcs
[92m[node.plugin.ntp-check:DEBUG:ThreadId 658] [0m[2018-03-11 20:07:02.56 UTC] Collecting responses
[94m[node.plugin.ntp-check:INFO:ThreadId 658] [0m[2018-03-11 20:07:02.56 UTC] Evaluated clock offset 5759 mcs for request at 1520798822318819 mcs
[94m[node.plugin.ntp-check:INFO:ThreadId 650] [0m[2018-03-11 20:07:02.56 UTC] NTP client is stopped
[92m[node.plugin.ntp-check:DEBUG:ThreadId 655] [0m[2018-03-11 20:07:02.56 UTC] **doReceive failed on socket<socket: 68>, reason: threadWait: invalid argument (Bad file descriptor), recreate socket in 5 sec**
[92m[node.plugin.ntp-check:DEBUG:ThreadId 656] [0m[2018-03-11 20:07:02.56 UTC] **doReceive failed on socket<socket: 69>, reason: threadWait: invalid argument (Bad file descriptor), recreate socket in 5 sec**
`

**Comment by cleverca22** [comment]
that looks like an ntp error, which is separate from the cardano network

**Comment by assal01** [comment]
NTP seems to be working fine. But your comment made me think of something: Last time I sync'd my node my country was in Daylight Savings (UTC-2), now we are back to Normal time (UTC-3) - so we went "back in time" - I wonder how the Wallet is (or isn't) ready to deal with this type of event...

**Comment by cleverca22** [comment]
internally, the computer and cardano completely ignore timezones and DST, it all operates on UTC

**Comment by assal01** [comment]
Still, reading the logs, Cardano seems to be trying to sync Time between nodes - and failing while doing that for some reason...

**Comment by assal01** [comment]
Could have been a bug of Mac OS X - got an update from Apple, after that update, Daedalus worked just fine.
