### ISSUE TITLE
Username with accent mark (Windows)

### ISSUE THREAD

**Issue by xSirk** [input-output-hk/daedalus#798]
I just installed Daedalus and I'm getting this error: "Couldn't pack log files, reason: can't pack log file pub\node.pub because it doesn't exist or it's not a file".

So I checked node.pub on "C:\Users\Sebastián\AppData\Roaming\Daedalus\Logs\pub" and one of the errors is:
[node:ERROR:ThreadId 3] [2018-03-17 00:57:55.69 UTC] UnsuccessfulOperation "c_rocksdb_open" "IO error: Failed to create dir: C:\Users\Sebasti\225n\AppData\Roaming\Daedalus\DB-1.0\blocks\index: No such file or directory"

This is my node.pub file, had to change extension to attach it.
[node.txt](https://github.com/input-output-hk/daedalus/files/1821174/node.txt)

**Comment by SebastienGllmt** [comment]
This is a known issue :(
See #780

**Comment by nikolaglumac** [comment]
> Up until this release, Windows users who had non-Latin characters in their Windows usernames were unable to use Daedalus. The first fix will ensure that these users will now be able to use Daedalus in Windows.

This issue has been resolved since Daedalus 0.11.1: https://github.com/input-output-hk/daedalus/tree/0.11.1
