### ISSUE TITLE
Caret problems in sum-input field in Daedalus 0.9.0 (1.1.0.408 MacOS)

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/daedalus#810]
Hi! I have three problems to report with the caret in the `Send` field in latest Daedalus. I think this problem is quite critical, since it easily may result in people sending a wrong amount of coins.

You can find videos and detailed descriptions here: https://imgur.com/a/i71Fb

Short description:
1. When some digits are put in, and then removed with backspace - leading zero becomes actual part of new input.
2. When a digit immediately following the order-comma is removed - caret jumps one digit back.
3. When the whole input is selected with `Cmd+A` (*Or mouse!*) and one new digit is typed in - caret is placed **before** this digit, so any next input is misplaced.

**Comment by SebastienGllmt** [comment]
Yikes.

**Comment by nikolaglumac** [comment]
@vantuz-subhuman this issue has been resolved.
