### ISSUE TITLE
Daedalus connect Error

### ISSUE THREAD

**Issue by gguoss** [input-output-hk/daedalus#813]
[2018-03-28 11:05:24:0420] [error] AdaApi::syncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8090",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8090
}

**Comment by cleverca22** [comment]
is `cardano-node` running?

**Comment by nitinsurana** [comment]
Getting the same error. 
@cleverca22  The readme talks about running `npm run dev` only; how to start `cardano-node` ?

**Comment by nitinsurana** [comment]
1. Cloned the cardano-sl repo - https://github.com/input-output-hk/cardano-sl
2. Built it from source
3. Entered the following commands to build connect-to-staging (macOS)
`bash`
`. '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'`
`nix-shell`
`nix-build -A cardano-sl-node-static --cores 0 --max-jobs 2 --no-build-output --out-link master`
4. Then built for staging using the steps mentioned here - https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/connect-to-cluster.md)
5. `./connect-to-staging`
6.  Started Daedalus using the following commands
`export NODE_TLS_REJECT_UNAUTHORIZED=0`
`npm run dev`

**Comment by nitinsurana** [comment]
Now, trying to create a newWallet and it keeps giving
```
[23:12:04.929] AdaApi::getWallets error: {
  "stack": "Error: SyntaxError: Unexpected end of JSON input\n    at IncomingMessage.eval (webpack-internal:///328:123:18)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)",
  "message": "SyntaxError: Unexpected end of JSON input"
}
```
Any idea what's going wrong ?

**Comment by nikolaglumac** [comment]
Please see updated instructions: https://github.com/input-output-hk/daedalus#development
