### ISSUE TITLE
Cardano  Android

### ISSUE THREAD

**Issue by yahova** [input-output-hk/daedalus#815]
Hello, please, add the Cardano Mobile for Android Mobile and Windows 32-bit
Android is especially important

**Comment by Syeikhleiman** [comment]
How i can get the wallet address plz?

**Comment by nikolaglumac** [comment]
Daedalus is a full-node client and as such cannot run on mobile devices.
Please check out Yoroi - a light client built by EMURGO: https://play.google.com/store/apps/details?id=com.emurgo
