### ISSUE TITLE
[serious-issue] Daedalus 0.9.0 does not display complete transaction history

### ISSUE THREAD

**Issue by gubatron** [input-output-hk/daedalus#819]
I've gone over manually adding up all the ADA received amounts in my wallet and my Summary total balance is considerably higher than the sum of all the transactions.

Is this a feature (are some transactions hidden on purpose) or a bug?

can't show screenshot for privacy reasons, can someone double check if they have the same issue?

Running

Daedalus 0.9.0
macOS build 1.1.0.408, with Cardano 1.1.0

**Comment by gubatron** [comment]
I see transfers going out of my exchange to my wallet, If I add everything up on the exchange side, it matches the balance shown by my wallet correctly, however, there are transactions missing in my wallet Transaction history.

The deposit addresses used in the exchange are correct and they show on the receive Tab in the list of addresses I've created, so it seems like there's a bug that doesn't display all the incoming transactions of the wallet.

**Comment by domenkozar** [comment]
This is an UI issue and will be addressed in the 1.1.1 hotfix.
