### ISSUE TITLE
Fail To Build With Build Script In Linux

### ISSUE THREAD

**Issue by prometx** [input-output-hk/daedalus#834]
Hi,

This would be *buntu 16.04.4. on cloning input-output-hk/daedalus, entering the "scripts" dir, and running, 

`sudo ./build-installer-unix.sh 0.8.2 master`

The build fails with:

`+ mv log-config-prod.yaml cardano-node cardano-launcher configuration.yaml mainnet-genesis-dryrun-with-stakeholders.json mainnet-genesis.json mainnet-staging-short-epoch-genesis.json ../../installers
mv: target '../../installers' is not a directory`

If anyone could provide any insight, that would be great. Thanks.

**Comment by prometx** [comment]
Incidentally, I attempted to edit the "installers" dir-path, within the script manually, successively, to:

`../installers
and
./installers`

Both of which yielded the same error with those respective directory locations.

**Comment by nikolaglumac** [comment]
Daedalus now uses nix setup which should resolve your issues: https://github.com/input-output-hk/daedalus#start-daedalus-using-demo-cluster
