### ISSUE TITLE
Stuck in connecting to network

### ISSUE THREAD

**Issue by bobbyharsono** [input-output-hk/daedalus#851]
OS Windows 10
Daedalus version 1.1.5813

I am stuck at connecting to network screen and sometimes it says reconnecting but that's it..
I have tried uninstall and do fresh installation again but it still the same..
I also keep refreshing (Ctrl + R) 
I even tried to let it keep connecting about half day but no progress..
Restarted my laptop few times also..

My laptop
clock is synced with internet and my ISP or my office's network admin seems like not blocking anything, if any, let me know all port or things that need to be whitelisted

[cardano-node.log](https://github.com/input-output-hk/daedalus/files/1897321/cardano-node.log)
[pub.zip](https://github.com/input-output-hk/daedalus/files/1897322/pub.zip)

**Comment by HirotoShioi** [comment]
This seems to be a firewall issue i.e your node cannot talk to other peers because firewall is blocking it. I'd suggest you change your ISP and see if you can connect to the network

**Comment by bobbyharsono** [comment]
Yesterday i went to several cafe and coffee shop and also tried using office internet in weekend and tried to sync, still not working...it was, however showed "syncing 0.00%"  before went back to "network lost -reconnecting"...

**Comment by dojo90** [comment]
Got the same problem. Any solution?
I setup a new PC and installed the new version (1.1.5813). I had no problems with the old one (1.0.3769.0).

**Comment by nikolaglumac** [comment]
Please follow the instructions from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360010522913--Cannot-Connect-to-Network-message

**Comment by laplasz** [comment]
with version 2.2.0 still has this annoying issue. I had a 100% synced node.. what I did is just restarted my Windows machine and It got stuck once I wanted to use the app after restart..
The solution was that restarted the machine again and wait for around 5 min..
