### ISSUE TITLE
what is the host of the public wallet api? 

### ISSUE THREAD

**Issue by locosoft1986** [input-output-hk/daedalus#858]
I have seen the public api at https://cardanodocs.com/technical/wallet/api/v1/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions%2Fget.
But in the "Getting started" session, it only refers to localhost:8089. I googled and check the Daedalus source code, find out that it uses cardano-sl client to access the api at "cardanoexplorer.com" which is very limited for us.
We want to use the documented API to fetch all the history transactions given an Address. So how can we get more data (history of transactions of a wallet)? What is the host of the beta version of the wallet api at https://cardanodocs.com/technical/wallet/api/v1/ ?

**Comment by nikolaglumac** [comment]
I order to use the Wallet API you should run your own Cardano node locally. This is why the docs mention `localhost`. There is no public API.
