### ISSUE TITLE
Unable to create new wallet - cannot read property push of null

### ISSUE THREAD

**Issue by nitinsurana** [input-output-hk/daedalus#879]
System : MacOS High Sierra
I followed the readme to start cardano and then executed `npm run dev`.
Clicking on `Confirm` in the final dialog of `create a new wallet` flow, throws the following error :
```
WalletStore.js?127b:65 Uncaught TypeError: Cannot read property 'push' of null
    at eval (WalletStore.js?127b:65)    //await this.walletsRequest.patch(result => { result.push(wallet); });
    at eval (Request.js?e35d:116)
    at executeAction (vendor.dll.js:8447)
    at res (vendor.dll.js:8438)
```

The console also has below error
```
renderer.js?407b:34 [01:43:50.888] AdaApi::getWallets error: {
  "stack": "Error: SyntaxError: Unexpected end of JSON input\n    at IncomingMessage.eval (webpack-internal:///328:123:18)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)",
  "message": "SyntaxError: Unexpected end of JSON input"
}
```

Any idea what's going wrong ? Where are the wallets stored - how can I reset them ?

[UPDATE]
Hitting `http://localhost:8090/api/v1/wallets` in the browser gives
`This server only accepts secure HTTPS connections.` 
Looks like this is the root-cause. There has to be some way to start cardano without https check.

**Comment by nikolaglumac** [comment]
Please use the latest Daedalus version and make sure to re-sync the blockchain data: https://iohk.zendesk.com/hc/en-us/articles/360009484874-Delete-and-re-sync-blockchain-data
