### ISSUE TITLE
Daedalus on Linux: Wallet Already Exists 

### ISSUE THREAD

**Issue by ralampay** [input-output-hk/daedalus#882]
After a fresh compile of Daedalus on Ubuntu 17.10 64-bit, I tried to restore my wallet using my passphrase. It seems to go in but it doesn't show. When I try to restore it again, it says:

Wallet already exists

Looking at the logs I find the following:

``
AdaApi::getWallets error: {
  "stack": "Error: SyntaxError: Unexpected end of JSON input\n    at IncomingMessage.eval (webpack-internal:///328:123:18)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)",
  "message": "SyntaxError: Unexpected end of JSON input"
}
``

Any fix for this?

**Comment by nikolaglumac** [comment]
Please use the latest Daedalus version and make sure to re-sync the blockchain data: https://iohk.zendesk.com/hc/en-us/articles/360009484874-Delete-and-re-sync-blockchain-data
