### ISSUE TITLE
daedalus-win64-1.1.5813.0-installer.exe | Install as non admin user | insufficient permission

### ISSUE THREAD

**Issue by dojo90** [input-output-hk/daedalus#902]
When installing the app as non admin, I get the following error:

![grafik](https://user-images.githubusercontent.com/17551597/39602503-a393239c-4f25-11e8-9aac-250c640ce599.png)

---

### Solution

Installer should ask to install as Admin or ask for admin privilegs.

**Comment by nikolaglumac** [comment]
@cleverca22 is this still an issue?

**Comment by cleverca22** [comment]
currently, the only supported way to run daedalus is to install and use it on a user that can gain admin via the UAC prompt, it is not supported to run on a non-admin account
