### ISSUE TITLE
daedalus-win64-1.1.5813.0-installer.exe | Install as non admin user | shortcut issue

### ISSUE THREAD

**Issue by dojo90** [input-output-hk/daedalus#903]
If installing the app as admin from an user (non admin privilegs) account:
---
- no shortcut is placed on the desktop on the user account

The installer should always ask for admin privilegs, see #902

**Comment by cleverca22** [comment]
currently, the only supported way to run daedalus is to install and use it on a user that can gain admin via the UAC prompt, it is not supported to run on a non-admin account
