### ISSUE TITLE
daedalus-win64-1.1.5813.0-installer.exe | Connecting to network stuck

### ISSUE THREAD

**Issue by dojo90** [input-output-hk/daedalus#904]
(I think) I made a mistake and started **C:\Program Files\Daedalus\Daedalus.exe**. So the problem is, that the app is *Connecting to network..* without success.

![grafik](https://user-images.githubusercontent.com/17551597/39603677-8f1eae32-4f29-11e8-9b8b-064dbcd2eb51.png)

---

Starting **C:\Program Files\Daedalus\cardano-launcher.exe** and everything works as expected..

![grafik](https://user-images.githubusercontent.com/17551597/39603754-da793118-4f29-11e8-95de-62f67286728b.png)

---

## Solution

Prevent starting **Daedalus.exe**. Maybe some Issues from other users depends on the same problem?!

**Comment by rbuckhoy** [comment]
I had same success with cardano-launcher.exe  file. Daedalus not working.

**Comment by cleverca22** [comment]
daedalus only works when ran with cardano-launcher

**Comment by nikolaglumac** [comment]
Please follow the instructions from the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360010522913--Cannot-Connect-to-Network-message
