### ISSUE TITLE
Do you have a way to get a record of the transaction by txid

### ISSUE THREAD

**Issue by XieWeiZM** [input-output-hk/daedalus#907]
Do you have a way to get a record of the transaction by txid

**Comment by XieWeiZM** [comment]
@vantuz-subhuman

**Comment by dojo90** [comment]
Have a look in the explorer

https://cardanoexplorer.com/

**Comment by XieWeiZM** [comment]
@dojo90  I want Cardano Wallet API  Because of the needs of my project

**Comment by XieWeiZM** [comment]
@dojo90 Can't find in this   https://cardanodocs.com/technical/wallet/api/v0/

**Comment by vantuz-subhuman** [comment]
https://cardanodocs.com/technical/explorer/api/

https://cardanoexplorer.com/api/txs/summary/edcdbb4852c1355319c2940e840ed889aa5a5b9b3d98ed34e3447946abd33fcf

**Comment by XieWeiZM** [comment]
@vantuz-subhuman {"Right":{"cabalVersion":"1.1.1","apiVersion":"v0","gitRevision":"aed0d925b06e0bd1278e26539c445274c52f4b67","softwareVersion":"cardano-sl:0"}}  my apiVersion  /api/txs/summary/  is   404
