### ISSUE TITLE
do we have separate repo for mobile?

### ISSUE THREAD

**Issue by BlueStalker** [input-output-hk/daedalus#908]
See if there is any chance to take a look and make some contributions, it is pretty important for the users.

**Comment by SebastienGllmt** [comment]
As in a mobile version of the Daedalus wallet? There isn't one. Light client support is a pre-req for such a feature (see roadmap for progress)

**Comment by BlueStalker** [comment]
cool Thanks very much for the reply. I just quickly go through the roadmap, it looks like the light client is trying to download the snapshot checkpoints instead of the whole chain. few quick questions:
1. how currently daedalus works? each desktop daedalus needs to download the whole chain, started the full node in locally?
2. I've noticed there is wallet api docs here: https://cardanodocs.com/technical/wallet/api/v1/#section/Getting-Started
Does it mean where there is a proxy of a current running nodes, which means if we have a running public node, the client can just sending the http(s) api to the node on any devices like desktop, or mobile.

Thanks in advance.

**Comment by SebastienGllmt** [comment]
When you install and run Daedalus you are actually installing both the Settlement Layer (SL) and the wallet. However, if you want to build from source yourself, you need to build/run both the SL and the wallet individually. The wallet simply connects to the SL so if you run the wallet without the SL (the node) it will just be waiting to connect forever. The SL is the one that is in charge of downloading the blockchain.

**Comment by BlueStalker** [comment]
I mean, technically, Does it work, if we want to build mobile wallet (client only), just run a SL somewhere, and the mobile app just use https://cardanodocs.com/technical/wallet/api/v1/#section/Getting-Started to connect to SL?

**Comment by alex-stout** [comment]
It looks like the API documentation sends requests to the localhost (running on that machine) SL. So the machine would need the SL to be running in order for the API to interface with it. To test it, run the SL on a remote machine and open the 8090 port on that machine. Then use the curl command to send a request to the API on the remote machine from another. That might work.

**Comment by nikolaglumac** [comment]
Daedalus is a full-node client and as such cannot run on mobile devices.
Please check out Yoroi - a light client built by EMURGO: https://play.google.com/store/apps/details?id=com.emurgo
