### ISSUE TITLE
java use keytool ca error,doesn't match common name of the certificate subject: localhost

### ISSUE THREAD

**Issue by XieWeiZM** [input-output-hk/daedalus#912]
Certificate for <192.168.11.105> doesn't match common name of the certificate subject: localhost
my service in 192.168.11.105  ,my client in 192.168.11.25  ，i want connect  to this

**Comment by deepfire** [comment]
@XieWeiZM, I'm sorry, it's not clear -- what are you trying to do?

**Comment by XieWeiZM** [comment]
@KtorZ  thanks,how to issue new certificates for my different (virtual) machines

**Comment by XieWeiZM** [comment]
@deepfire  my different (virtual) machines want to connect my 192.168.11.105‘node ，but  tls is error

**Comment by disassembler** [comment]
@XieWeiZM You have to generate your own CA with matching SANs. This will give you a general overview of doing this using openssl:
