### ISSUE TITLE
More than 27 wallet created ... daedalus crashed

### ISSUE THREAD

**Issue by kenken64** [input-output-hk/daedalus#926]
Hi ,

I used the rpc api to create 27 wallets then the Daedalus gui keep crashing

https://drive.google.com/file/d/1hUHPmi0rHGARbhUeNLVWfdream140f4u/view?usp=sharing

**Comment by amias-iohk** [comment]
Hi Ken,

Sorry to hear this isn't working for you and thanks for letting us know.

So we can recreate this issue please could you provide the following info :

Cardano version :
Daedalus version : 

It would also help if you could share the code you used to drive the api to create this scenario.

Thanks
Amias

**Comment by nikolaglumac** [comment]
Daedalus supports up to 20 Wallets. The UI enforces this limitation. Overriding this by using direct API calls can have unexpected results. Please delete extra wallets in order to continue using Daedalus.
