### ISSUE TITLE
unprivileged namespace use - how to disable again

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/daedalus#982]
I was shocked to see that there is no Linux wallet yet.

Your beta  
https://forum.cardano.org/t/iohk-statement-a-beta-release-for-daedalus-on-linux/10316  
when downloaded and started

needs these commands
```
sysctl -w kernel.unprivileged_userns_clone=1 ; echo kernel.unprivileged_userns_clone=1 > /etc/sysctl.d/nix-user-chroot.conf
```

2 questions:

* is there really no way around this? I have never seen that with any (over a hundred) cryptocurrency ...
* how can this be undone afterwards? what is the full command to reverse this decision?

Thanks!

**Comment by cleverca22** [comment]
that command can be reversed by setting it to `0` with `sysctl` and also removing the file `/etc/sysctl.d/nix-user-chroot.conf` that it creates

**Comment by drandreaskrueger** [comment]
> that command can be reversed

Thanks a lot.

So, like this:

```
sysctl -w kernel.unprivileged_userns_clone=0 ; rm /etc/sysctl.d/nix-user-chroot.conf
```

?

Then please add that to the instructions. 

But also ... isn't the second command too harsh? Removing the whole file?
Imagine some other tool has also written to the same file - then your suggestion would destroy that too

---

Secondly:

is there really no way around this? I have never seen that with any (over a hundred) cryptocurrency ...

**Comment by cleverca22** [comment]
the original `echo kernel.unprivileged_userns_clone=1 > /etc/sysctl.d/nix-user-chroot.conf` command would overwrite the entire file anyways, so no other tools should ever have contents in there
