### ISSUE TITLE
how to testnet with -1.1.0.960.bin

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/daedalus#994]
# how to testnet?

Starting with the [linux instructions](https://forum.cardano.org/t/iohk-statement-a-beta-release-for-daedalus-on-linux/10316) and `Daedalus-mainnet-installer-1.1.0.960.bin`, I have then tried 
```
export NETWORK=testnet; ~/bin/daedalus
```
(because [README](https://github.com/input-output-hk/daedalus#development---network-options))

but that seems to sync the mainnet too.

Not the testnet.

-->

_Perhaps in a next version of the installer also deliver a `~/bin/daedalus-testnet` which starts the same wallet but syncing the testnet chain?_

---

Until you give me access to the testnet, can anyone please send me a small amount of ADA, so that I can try out your software. Thanks. My address is:
```
DdzFFzCqrhsv2LMs2o45zjNihN3Saywq2cwV3aTzutuHJqX8y7pXZnkLyvbQNz5i8c8k8Ax8watkFNXiAatpBLhAwVjarnseKBoHi5dw
```

**Comment by drandreaskrueger** [comment]
on https://update-cardano-mainnet.iohk.io/ there is also no `Daedalus-testnet-installer-1.1.0.960.bin`

**Comment by drandreaskrueger** [comment]
> seems to sync the mainnet 

inferred from being at 100% immediately.

Why doesn't your wallet have an infopage? Name of chain, blocks synced, peers connected, etc. - TODO.

**Comment by drandreaskrueger** [comment]
found it? https://testnet.iohkdev.io

**Comment by nikolaglumac** [comment]
All Testnet related information can be found at: https://testnet.iohkdev.io/
